Repository kubernetes-sigs/kueue, pull requests merged in 2022-11, with the labels that each got.

#423 Adding junit.xml for unit/integration tests
  Makefile
Labels: kind/feature, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#430 Add requeue reason to log
  pkg/scheduler/scheduler.go
Labels: lgtm, tide/merge-method-squash, approved, kind/cleanup, size/XS, cncf-cla: yes

#437 Fix e2e test not load the right image
  Makefile
  hack/e2e-test.sh
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#414 Add webhook to Job controller
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/localqueue_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  apis/kueue/webhooks/workload_webhook.go
  config/components/webhook/manifests.yaml
  main.go
  pkg/controller/workload/job/job_webhook.go
  pkg/controller/workload/job/job_webhook_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/job/suite_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#440 dependabot addition to repo
  .github/dependabot.yml
Labels: kind/feature, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#442 add dependency-name to dependabot for go
  .github/dependabot.yml
Labels: kind/bug, lgtm, approved, needs-ok-to-test, size/XS, cncf-cla: yes

#441 configured e2e tests to run with existing cluster
  Makefile
  hack/e2e-test.sh
Labels: kind/feature, lgtm, tide/merge-method-squash, approved, ok-to-test, cncf-cla: yes, size/S

#439 Add a new field nodeSelector to resourceFlavor to replace original metadata.labels
  apis/kueue/v1alpha2/resourceflavor_types.go
  apis/kueue/v1alpha2/zz_generated.deepcopy.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook_test.go
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  docs/concepts/cluster_queue.md
  docs/tasks/administer_cluster_quotas.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/workload/job/job_controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#453 Fix race condition on admission error
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/framework/framework.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes
