Repository kubernetes-sigs/kueue, pull requests merged in 2022-12, with the labels that each got.

#454 Refactor: split out flavor assigment logic
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, size/XXL, approved, kind/cleanup, cncf-cla: yes

#433 Design for all-or-nothing semantics for workload resource assignment
  keps/349-all-or-nothing/README.md
  keps/349-all-or-nothing/kep.yaml
  keps/NNNN-template/README.md
Labels: kind/feature, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#455 Refactor flavorassigner for readability
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#464 Add default podSet name via webhook mutation
  apis/kueue/v1alpha2/workload_types.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#456 Make ClusterQueue.spec.queuingStrategy immutable
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
Labels: kind/feature, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#460 Add PodsReady condition if WaitForPodsReady is enabled
  apis/config/v1alpha2/configuration_types.go
  apis/config/v1alpha2/zz_generated.deepcopy.go
  apis/kueue/v1alpha2/workload_types.go
  config/components/manager/controller_manager_config.yaml
  main.go
  main_test.go
  pkg/controller/workload/job/job_controller.go
  pkg/controller/workload/job/job_controller_test.go
  test/integration/controller/job/job_controller_test.go
Labels: kind/feature, lgtm, tide/merge-method-squash, size/XL, approved, cncf-cla: yes

#476 Shorten name of objects in cohort in integration tests
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#474 Remove unnecessary function in kueue
  pkg/controller/core/workload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/workload/workload.go
  test/e2e/e2e_test.go
  test/integration/controller/core/workload_controller_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#462 Kueue performance tests
  test/performance/.env.example
  test/performance/.gitignore
  test/performance/README.md
  test/performance/config.yaml
  test/performance/job.yaml
  test/performance/local-queue.yaml
  test/performance/prerequisites/cluster-queue.template
  test/performance/prerequisites/resource-flavor.yaml
  test/performance/run-test.sh
Labels: size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#466 Validate using open API where possible
  apis/kueue/v1alpha2/clusterqueue_types.go
  apis/kueue/v1alpha2/resourceflavor_types.go
  apis/kueue/v1alpha2/workload_types.go
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook_test.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  test/integration/webhook/v1alpha2/clusterqueue_test.go
  test/integration/webhook/v1alpha2/resourceflavor_test.go
  test/integration/webhook/v1alpha2/workload_test.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#475 Prevent borrowing when preemption could help
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#473 Block admission until PodsReady for all admitted workloads if WaitForPodsReady is enabled
  main.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/scheduler/scheduler.go
  pkg/util/testing/wrappers.go
  test/integration/framework/framework.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/podsready/suite_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#483 test framework and e2e utilities usage
  test/e2e/e2e_test.go
  test/e2e/framework/constants.go
  test/e2e/framework/framework.go
  test/e2e/suite_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/v1alpha2/clusterqueue_test.go
  test/integration/webhook/v1alpha2/resourceflavor_test.go
  test/integration/webhook/v1alpha2/workload_test.go
  test/util/constants.go
  test/util/util.go
Labels: lgtm, size/XXL, approved, cncf-cla: yes

#484 Fix missing period in documentation
  docs/tasks/administer_cluster_quotas.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#491 Fix flaky integration tests for scheduling when WaitForPodsReady is enabled
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, approved, cncf-cla: yes, size/S

#489 Get ClusterQueues with a specific ResourceFlavor from the cache
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/resourceflavor_controller.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#496 Increase timeout for Kueue to be ready
  test/e2e/suite_test.go
Labels: kind/bug, lgtm, kind/flake, approved, size/XS, cncf-cla: yes

#415 Add condition field to ClusterQueueStatus
  apis/kueue/v1alpha2/clusterqueue_types.go
  apis/kueue/v1alpha2/zz_generated.deepcopy.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/core.go
  pkg/controller/core/resourceflavor_controller.go
  test/e2e/e2e_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/util/util.go
Labels: kind/feature, lgtm, size/XL, approved, kind/api-change, cncf-cla: yes

#492 Clean up webhook integration test
  pkg/util/testing/not_found_error_cmp.go
  test/integration/webhook/v1alpha2/clusterqueue_test.go
  test/integration/webhook/v1alpha2/suite_test.go
  test/integration/webhook/v1alpha2/workload_test.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes
