Repository kubernetes-sigs/kueue, pull requests merged in 2022-08, with the labels that each got.

#310 add validation to workload priority
  apis/kueue/v1alpha1/workload_webhook.go
  apis/kueue/v1alpha1/workload_webhook_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/v1alpha1/workload_test.go
Labels: kind/feature, lgtm, tide/merge-method-squash, approved, size/M, cncf-cla: yes

#304 Cleanup: scheduler tests independent of job controller
  pkg/util/testing/wrappers.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/suite_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
Labels: lgtm, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#296 Assigning the same flavor to codependent resources
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, size/XL, approved, cncf-cla: yes

#313 Migrate mutations/validations to new folder webhooks
  apis/kueue/v1alpha1/constants.go
  apis/kueue/v1alpha1/resourceflavor_webhook.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
  apis/kueue/webhooks/queue_webhook.go
  apis/kueue/webhooks/queue_webhook_test.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook_test.go
  apis/kueue/webhooks/webhooks.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  main.go
  pkg/controller/core/core.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/v1alpha1/suite_test.go
  test/integration/webhook/v1alpha1/workload_test.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#315 Add metrics for total number of admissions and wait time
  pkg/metrics/metrics.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#317 Default requests to limits in Workload
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#320 nominate kerthcet as kueue reviewer
  OWNERS
Labels: lgtm, approved, size/XS, cncf-cla: yes

#321 fix test in workload defaulter
  test/integration/webhook/v1alpha1/workload_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#318 Only set a podSet name if there is only one
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/S

#319 Update deps: k8s, ginkgo, gomega, logr
  Makefile
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/crd/bases/kueue.x-k8s.io_queues.yaml
  config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
  pkg/util/testing/equal_cmp.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/framework/framework.go
Labels: lgtm, size/XXL, approved, kind/cleanup, cncf-cla: yes

#325 Replace if-else with switch for readability
  pkg/controller/core/workload_controller.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#323 Update API docs with defaulting and validation
  apis/kueue/v1alpha1/clusterqueue_types.go
  apis/kueue/v1alpha1/resourceflavor_types.go
  apis/kueue/v1alpha1/workload_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#322 Avoid queueing workloads that don't match CQ namespaceSelector
  apis/config/v1alpha1/groupversion_info.go
  apis/kueue/v1alpha1/groupversion_info.go
  apis/kueue/webhooks/workload_webhook.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, size/XL, approved, cncf-cla: yes

#326 Validate codependent flavors in ClusterQueue
  apis/kueue/v1alpha1/clusterqueue_types.go
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#329 Add validation for API lists sizes
  apis/kueue/v1alpha1/clusterqueue_types.go
  apis/kueue/v1alpha1/resourceflavor_types.go
  apis/kueue/v1alpha1/workload_types.go
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
  apis/kueue/webhooks/common.go
  apis/kueue/webhooks/queue_webhook.go
  apis/kueue/webhooks/queue_webhook_test.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook_test.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#333 Use TooMany instead of Invalid on validation errors
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook_test.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#332 Use metav1.Condition and validate
  apis/kueue/v1alpha1/workload_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/webhooks/workload_webhook.go
  config/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/core/workload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/api/api.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#339 Set user agent with semantic version
  .dockerignore
  Dockerfile
  Makefile
  main.go
  pkg/constants/constants.go
  pkg/util/useragent/useragent.go
  pkg/util/useragent/useragent_test.go
  pkg/version/version.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#335 Add status label to pending_workloads metric
  pkg/controller/core/clusterqueue_controller.go
  pkg/metrics/metrics.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#338 Validate queueName is immutable when the workload is admitted
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/webhook/v1alpha1/workload_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#337 Use server-side-apply for admission
  apis/kueue/v1alpha1/workload_types.go
  config/crd/bases/kueue.x-k8s.io_workloads.yaml
  main.go
  pkg/constants/constants.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/controller/job/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#341 Renamed Queue to LocalQueue
  PROJECT
  apis/kueue/v1alpha1/localqueue_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/localqueue_webhook.go
  apis/kueue/webhooks/localqueue_webhook_test.go
  apis/kueue/webhooks/webhooks.go
  config/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_localqueues.yaml
  config/crd/patches/webhook_in_localqueues.yaml
  config/rbac/kustomization.yaml
  config/rbac/localqueue_editor_role.yaml
  config/rbac/localqueue_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/single-clusterqueue-setup.yaml
  config/webhook/manifests.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/core.go
  pkg/controller/core/localqueue_controller.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/local_queue.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/v1alpha1/localqueue_test.go
Labels: lgtm, size/XL, approved, kind/api-change, kind/cleanup, cncf-cla: yes

#342 Validate Workload admission
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  pkg/util/testing/wrappers.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#343 Add cluster_queue_status metric
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/metrics/metrics.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#345 Build prometheus-operator configuration yamls
  Makefile
  config/components/certmanager/certificate.yaml
  config/components/certmanager/kustomization.yaml
  config/components/certmanager/kustomizeconfig.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  config/components/crd/kustomization.yaml
  config/components/crd/kustomizeconfig.yaml
  config/components/crd/patches/cainjection_in_clusterqueues.yaml
  config/components/crd/patches/cainjection_in_localqueues.yaml
  config/components/crd/patches/cainjection_in_resourceflavors.yaml
  config/components/crd/patches/cainjection_in_workloads.yaml
  config/components/crd/patches/webhook_in_clusterqueues.yaml
  config/components/crd/patches/webhook_in_localqueues.yaml
  config/components/crd/patches/webhook_in_resourceflavors.yaml
  config/components/crd/patches/webhook_in_workloads.yaml
  config/components/internalcert/kustomization.yaml
  config/components/internalcert/secret.yaml
  config/components/manager/controller_manager_config.yaml
  config/components/manager/kustomization.yaml
  config/components/manager/manager.yaml
  config/components/prometheus/kustomization.yaml
  config/components/prometheus/monitor.yaml
  config/components/prometheus/role.yaml
  config/components/rbac/auth_proxy_client_clusterrole.yaml
  config/components/rbac/auth_proxy_role.yaml
  config/components/rbac/auth_proxy_role_binding.yaml
  config/components/rbac/auth_proxy_service.yaml
  config/components/rbac/batch_admin_role.yaml
  config/components/rbac/batch_user_role.yaml
  config/components/rbac/clusterqueue_editor_role.yaml
  config/components/rbac/clusterqueue_viewer_role.yaml
  config/components/rbac/job_editor_role.yaml
  config/components/rbac/job_viewer_role.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/leader_election_role.yaml
  config/components/rbac/leader_election_role_binding.yaml
  config/components/rbac/localqueue_editor_role.yaml
  config/components/rbac/localqueue_viewer_role.yaml
  config/components/rbac/resourceflavor_editor_role.yaml
  config/components/rbac/resourceflavor_viewer_role.yaml
  config/components/rbac/role.yaml
  config/components/rbac/role_binding.yaml
  config/components/rbac/service_account.yaml
  config/components/rbac/workload_editor_role.yaml
  config/components/rbac/workload_viewer_role.yaml
  config/components/webhook/kustomization.yaml
  config/components/webhook/kustomizeconfig.yaml
  config/components/webhook/manifests.yaml
  config/components/webhook/service.yaml
  config/default/kustomization.yaml
  config/prometheus/kustomization.yaml
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/v1alpha1/suite_test.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#347 Validate ClusterQueue cohort to be a valid object name
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
Labels: lgtm, approved, kind/api-change, kind/cleanup, cncf-cla: yes, size/S

#350 Fix prometheus rolebinding
  config/components/prometheus/role.yaml
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#346 Add docs to install and use metrics
  CHANGELOG/CHANGELOG-0.2.md
  docs/concepts/README.md
  docs/reference/README.m
  docs/reference/metrics.md
  docs/setup/README.md
  docs/setup/install.md
  pkg/metrics/metrics.go
Labels: lgtm, tide/merge-method-squash, approved, size/M, kind/documentation, cncf-cla: yes

#351 Enhance and update documentation
  CHANGELOG/CHANGELOG-0.2.md
  README.md
  docs/concepts/README.md
  docs/concepts/cluster_queue.md
  docs/concepts/local_queue.md
  docs/concepts/queue.md
  docs/concepts/workload.md
  docs/setup/install.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
Labels: size/L, lgtm, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes

#356 Recover updates to docs and release notes
  CHANGELOG/CHANGELOG-0.2.md
  README.md
  docs/concepts/cluster_queue.md
  docs/concepts/local_queue.md
  docs/setup/install.md
Labels: size/L, lgtm, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes

#357 Release 0.2 update
  Makefile
  README.md
  config/components/manager/kustomization.yaml
  docs/setup/install.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#358 Update docs to v0.2.1
  CHANGELOG/CHANGELOG-0.2.md
  README.md
  docs/setup/install.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#359 Update latest version
  README.md
  docs/setup/install.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#361 Change references of v1alpha1 to v1alpha2 in docs
  docs/concepts/cluster_queue.md
  docs/concepts/workload.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#364 Automated cherry pick of #361: Change references of v1alpha1 to v1alpha2 in docs
  docs/concepts/cluster_queue.md
  docs/concepts/workload.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
Labels: lgtm, approved, size/M, cncf-cla: yes
