Repository kubernetes-sigs/kueue, pull requests merged in 2022-04, with the labels that each got.

#160 Add event when failing to schedule a QW
  pkg/scheduler/scheduler.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/S

#173 Change queueingStrategy default to BestEffortFIFO
  api/v1alpha1/clusterqueue_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#174 Remove unused workload reference
  api/v1alpha1/queuedworkload_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
Labels: lgtm, approved, kind/api-change, size/M, kind/cleanup, cncf-cla: yes

#176 Add more details to the failure to admit event and condition message
  pkg/scheduler/scheduler.go
Labels: lgtm, tide/merge-method-squash, approved, size/M, kind/cleanup, cncf-cla: yes

#181 Ensure that Job owns the QueuedWorkload
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#182 Add integration test for admitting multiple workloads after they didn't fit
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#183 Skip requeueing workload if it was already admitted
  pkg/queue/manager.go
  pkg/queue/manager_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/S

#184 fix: incorrect anchor point for resource-flavor
  docs/concepts/README.md
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#175 Add details for managing cohorts
  docs/concepts/cluster_queue.md
  docs/tasks/administer_cluster_quotas.md
Labels: size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#180 Add concept for priority and queueing strategy
  docs/concepts/cluster_queue.md
  docs/concepts/queued_workload.md
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#185 Cleanup: variables renaming
  pkg/scheduler/scheduler.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#186 Docs: Add install doc pages
  docs/README.md
  docs/setup/README.md
  docs/setup/install.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
  docs/tasks/setup_rbac.md
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#188 Rename guaranteed to min and ceiling to max
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/samples/single-clusterqueue-setup.yaml
  docs/concepts/cluster_queue.md
  docs/tasks/administer_cluster_quotas.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, size/XL, approved, kind/api-change, kind/cleanup, cncf-cla: yes

#192 remove duplicate error message
  pkg/cache/cache.go
Labels: lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#193 fix: error jump link for setup_rbac.md
  docs/tasks/README.md
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#190 Add instructions for one-line installation
  Makefile
  README.md
  config/manager/kustomization.yaml
  docs/setup/install.md
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#198 Changes the project to support multiple api groups
  Dockerfile
  Makefile
  PROJECT
  apis/core/v1alpha1/clusterqueue_types.go
  apis/core/v1alpha1/groupversion_info.go
  apis/core/v1alpha1/queue_types.go
  apis/core/v1alpha1/resourceflavor_types.go
  apis/core/v1alpha1/workload_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  main.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/priority/priority.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#196 Add release process
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  .gitignore
  Makefile
  RELEASE.md
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#204 Renamed flavor.resourceFlavor to flavor.name
  apis/core/v1alpha1/clusterqueue_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  docs/concepts/cluster_queue.md
  docs/tasks/administer_cluster_quotas.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
Labels: size/L, lgtm, approved, kind/api-change, kind/cleanup, cncf-cla: yes

#205 Added an option to control processing jobs with no queue name set
  pkg/controller/workload/job/job_controller.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/suite_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#206 Renamed requestableResources to resources in clusterQueue
  apis/core/v1alpha1/clusterqueue_types.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/samples/single-clusterqueue-setup.yaml
  docs/concepts/cluster_queue.md
  docs/tasks/administer_cluster_quotas.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/api-change, kind/cleanup, cncf-cla: yes

#178 Distinguish workload type before requeue
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#211 Match release-0.1 tags in manifests
  Makefile
  config/manager/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/XS, cncf-cla: yes

#214 Fix install instructions for release
  docs/setup/install.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#215 Add installation instructions for a released version
  README.md
  docs/setup/install.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#216 Cleanup scheduler integration tests
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/suite_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#209 feat: sync workload condition when admitted
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
  test/integration/controller/core/workload_controller_test.go
Labels: kind/feature, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#218 Add learnings and examples from the last release
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes, size/S

#219 Rename apis/core package to apis/kueue
  PROJECT
  apis/kueue/v1alpha1/clusterqueue_types.go
  apis/kueue/v1alpha1/groupversion_info.go
  apis/kueue/v1alpha1/queue_types.go
  apis/kueue/v1alpha1/resourceflavor_types.go
  apis/kueue/v1alpha1/workload_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  main.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/priority/priority.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#202 introduce Heap package
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/queue.go
  pkg/util/heap/heap.go
  pkg/util/heap/heap_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#221 use struct `Resources` for `UsedResources` in tests
  pkg/cache/cache_test.go
Labels: lgtm, approved, size/M, kind/cleanup, needs-ok-to-test, cncf-cla: yes

#223 test: add testcases to cover ClusterQueueImpl methods
  pkg/queue/cluster_queue_impl_test.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#220 Add defaulting webhook for `Workload` resource
  PROJECT
  apis/kueue/v1alpha1/workload_types.go
  apis/kueue/v1alpha1/workload_webhook.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  main.go
  test/integration/framework/framework.go
  test/integration/webhook/v1alpha1/suite_test.go
  test/integration/webhook/v1alpha1/workload_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#191 feat: handle pod overhead
  config/rbac/role.yaml
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/workload_controller.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/framework/framework.go
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#233 Add metrics for admission attempts count and duration
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/role.yaml
  go.mod
  pkg/metrics/metrics.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#236 Fix import block in scheduler
  pkg/scheduler/scheduler.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#235 Add task list to enhancements template
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#238 Fix number of pending workloads in a BestEffortFIFO ClusterQueue
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes
