Repository kubernetes-sigs/kueue, pull requests merged in 2022-05, with the labels that each got.

#227 Change make cluster queue in wrappers to bestfifo
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#239 doc: note how to install cert-manager
  docs/setup/install.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#243 Fix format of error logging
  pkg/controller/core/workload_controller.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#246 Immediate requeue in BestEffortFIFO should put a workload for retry
  CHANGELOG/CHANGELOG-0.2.md
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
Labels: kind/bug, lgtm, kind/flake, approved, size/M, cncf-cla: yes

#237 Add metric for pending workloads, broken down by queue and cluster_queue
  go.mod
  go.sum
  main.go
  pkg/metrics/metrics.go
  pkg/queue/manager.go
  pkg/queue/queue.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#240 Add docs on how to change the configuration
  docs/setup/install.md
Labels: lgtm, tide/merge-method-squash, approved, size/M, kind/documentation, cncf-cla: yes

#224 feat: add detailed errors to assignFlavors
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#247 set default log timestamp format
  main.go
  test/integration/framework/framework.go
Labels: lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#225 Add validation for Workload via webhook
  apis/kueue/v1alpha1/workload_webhook.go
  apis/kueue/v1alpha1/workload_webhook_test.go
  pkg/util/testing/wrappers.go
  test/integration/webhook/v1alpha1/workload_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#179 Update tolerated flavors integration test
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#245 fix: update failure in requeue
  pkg/queue/manager.go
  pkg/queue/manager_test.go
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#253 Run integration tests with ginkgo
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#230 feat: clusterQueue add status field
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#255 Rename image to registry.k8s.io/kueue/kueue
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#252 add log filename and line number
  main.go
  test/integration/framework/framework.go
Labels: kind/feature, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#248 fix: forget to cleanup inadmissibleWorkloads when deleteFromQueue
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#228 test: add unit tests for the priority package
  pkg/util/priority/priority.go
  pkg/util/priority/priority_test.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#254 feat: filter inactive clusterQueues in scheduling
  main.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/status_checker.go
  pkg/scheduler/scheduler_test.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#260 Promoting denkensk to approver
  OWNERS
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#257 do workload.NewInfo when inserting and updating
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/manager.go
  pkg/queue/queue.go
  pkg/workload/workload.go
Labels: lgtm, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#262 Refactor TestCacheWorkloadOperations
  pkg/cache/cache_test.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes
