Repository kubernetes-sigs/kueue, pull requests merged in 2022-07, with the labels that each got.

#290 Refactor tests in scheduler
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, size/XXL, approved, kind/cleanup, cncf-cla: yes

#289 Refactor tests in clusterqueue controller
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#288 Fix: integration tests missed detail logs
  test/integration/framework/framework.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#263 manage a finalizer for resourceFlavor based on usage by cluster queues
  config/rbac/role.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/util/testing/not_found_error_cmp.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#292 Make a copy of workload when admitting to avoid cache corruption
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#294 Cleanup: remove no longer suitable tests in scheduler_test.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#293 Reduce cardinality of pending_workloads metric
  pkg/metrics/metrics.go
  pkg/queue/manager.go
  pkg/queue/queue.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#295 Track number of active running workloads per queue
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/core.go
  pkg/controller/core/queue_controller.go
  pkg/metrics/metrics.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/workload/workload.go
  test/integration/controller/core/queue_controller_test.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#291 Add metric for admitted active workloads
  pkg/cache/cache.go
  pkg/metrics/metrics.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#278 Feat: add support for replacing internal cert management
  apis/config/v1alpha1/configuration_types.go
  apis/config/v1alpha1/defaults.go
  apis/config/v1alpha1/groupversion_info.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  config/manager/controller_manager_config.yaml
  docs/setup/install.md
  main.go
  main_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#298 Cleanup: use BeNotFoundError for error validation
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/job/job_controller_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#300 Trigger re-queueing of workloads on namespace label update
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/clusterqueue_controller.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#303 Cleanup: rename ExpectedClusterQueueToBeDeleted
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#299 Add the finalizer via webhook when creating resourceFlavor
  apis/kueue/v1alpha1/resourceflavor_webhook.go
  apis/kueue/v1alpha1/resourceflavor_webhook_test.go
  config/webhook/manifests.yaml
  main.go
  pkg/controller/core/core.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/v1alpha1/resourceflavor_test.go
  test/integration/webhook/v1alpha1/suite_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#302 Add webhook defaulter to clusterQueue
  apis/kueue/v1alpha1/clusterqueue_webhook.go
  config/webhook/manifests.yaml
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  test/integration/webhook/v1alpha1/clusterqueue_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#306 Refactor: change the parameters' order
  apis/kueue/v1alpha1/workload_webhook_test.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#307 Add validations to workload
  apis/kueue/v1alpha1/workload_webhook.go
  apis/kueue/v1alpha1/workload_webhook_test.go
  test/integration/webhook/v1alpha1/workload_test.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#305 Cleanup: simplify tests in validating finalizer creating
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#264 feat: implement validation webhook for Queue
  PROJECT
  apis/kueue/v1alpha1/queue_webhook.go
  apis/kueue/v1alpha1/queue_webhook_test.go
  config/crd/kustomization.yaml
  config/webhook/manifests.yaml
  main.go
  pkg/controller/core/core.go
  pkg/util/testing/wrappers.go
  test/integration/webhook/v1alpha1/queue_test.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes
