Repository kubernetes-sigs/kueue, pull requests merged in 2022-03, with the labels that each got.

#73 Add support for affinity matching
  pkg/capacity/capacity.go
  pkg/capacity/snapshot.go
  pkg/capacity/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#76 cleanup: fix race condition
  Makefile
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#75 Add status report for kueue.Queue
  api/v1alpha1/queue_types.go
  config/crd/bases/kueue.x-k8s.io_queues.yaml
  main.go
  pkg/controller/core/queue_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#81 Add integration test for capacity controller
  api/v1alpha1/capacity_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/util/testing/equal_cmp.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/capacitycontroller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#89 Add ACK_GINKGO_DEPRECATIONS ack to clean test logs
  Makefile
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#93 Refactor scheduler integration tests
  test/integration/controller/core/capacitycontroller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/constants.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#95 Rename Capacity to ClusterQueue and Assignment to Admission
  PROJECT
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/queue_types.go
  api/v1alpha1/queuedworkload_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
  config/crd/bases/kueue.x-k8s.io_queues.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterqueues.yaml
  config/crd/patches/webhook_in_clusterqueues.yaml
  config/rbac/clusterqueue_editor_role.yaml
  config/rbac/clusterqueue_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/minimal.yaml
  main.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
Labels: lgtm, size/XXL, approved, kind/api-change, kind/cleanup, cncf-cla: yes

#98 Add integration tests for Queue controller
  api/v1alpha1/queue_types.go
  config/crd/bases/kueue.x-k8s.io_queues.yaml
  pkg/util/testing/wrappers.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/framework/framework.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#90 NamespaceSelector for ClusterQueue
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#100 fix typo in api
  api/v1alpha1/queuedworkload_types.go
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#99 Follow up on Capacity -> ClusterQueue
  pkg/cache/cache.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#106 Add github templates for diff purposes
  .github/BUG_REPORT.md
  .github/ENHANCEMENT.md
  .github/NEW_RELEASE.md
  .github/SUPPORT.md
  RELEASE.md
Labels: size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#109 Enable templates by creating ISSUE_TEMPLATE folder
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CLEANUP.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/S

#107 Migrate to GINKO/v2
  Makefile
  go.mod
  go.sum
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/suite_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#110 Rename AssignedWorkloads to AdmittedWorkloads
  api/v1alpha1/clusterqueue_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/controller/core/clusterqueue_controller.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#111 Remove Active condition from QueuedWorkload
  api/v1alpha1/queuedworkload_types.go
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#97 Have a single heap per ClusterQueue
  main.go
  pkg/cache/cache.go
  pkg/cache/snapshot.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/queue/queue_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#114 Enhance Kueue.Queue.Status test suite
  api/v1alpha1/queue_types.go
  config/crd/bases/kueue.x-k8s.io_queues.yaml
  pkg/controller/core/queue_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  test/integration/controller/core/queue_controller_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#115 Kueue.ClusterQueue.Status Add pendingWorkloads
  api/v1alpha1/clusterqueue_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/controller/core/clusterqueue_controller.go
  pkg/queue/manager.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: kind/feature, lgtm, approved, kind/api-change, size/M, cncf-cla: yes

#116 Fix image tag for postsubmit job
  Makefile
  cloudbuild.yaml
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#118 Fixing RBAC roles
  config/rbac/role.yaml
  pkg/controller/core/clusterqueue_controller.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/S

#121 Fix json tags
  api/v1alpha1/clusterqueue_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#120 Temporal solution for #101
  pkg/constants/constants.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queue_controller.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/S

#124 Update `go-get-tool` in Makefile
  Makefile
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#123 Rename ResourceFlavor to Flavor
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/queuedworkload_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/workload/job/job_controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/job/job_controller_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#104 Add PriorityClass in Workload api
  api/v1alpha1/queuedworkload_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
  pkg/constants/constants.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/queue.go
  pkg/queue/queue_test.go
  pkg/util/priority/priority.go
  pkg/util/routine/wrapper.go
  pkg/util/testing/wrappers.go
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#126 Use QueueStrategy in ClusterQueue construct
  pkg/queue/manager.go
  pkg/queue/queue.go
  pkg/queue/queue_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#127 Introduce the ResourceFlavor API
  PROJECT
  api/v1alpha1/resourceflavor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_resourceflavors.yaml
  config/crd/patches/webhook_in_resourceflavors.yaml
  config/rbac/resourceflavor_editor_role.yaml
  config/rbac/resourceflavor_viewer_role.yaml
  config/samples/kueue_v1alpha1_resourceflavor.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#128 Fix RBAC after adding Priority support
  config/rbac/role.yaml
  main.go
  pkg/controller/workload/job/job_controller.go
Labels: kind/bug, lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#129 Add imagePullPolicy to manager deployment
  config/manager/manager.yaml
  config/samples/minimal.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#130 Update README quick start section
  README.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#132 update RBAC for PriorityClass
  config/rbac/role.yaml
  pkg/controller/workload/job/job_controller.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#136 Remove go-get-tool helper
  Makefile
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#138 Fix kustomize installation
  Makefile
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#133 Implement ResourceFlavor API
  PROJECT
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/resourceflavor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/rbac/role.yaml
  config/samples/minimal.yaml
  main.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/job/job_controller_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#139 fix panic when flavor is not found
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#140 update readme and sample
  README.md
  config/samples/kueue_v1alpha1_resourceflavor.yaml
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#141 Add a concept page for each API resource
  README.md
  docs/concepts/README.md
  docs/concepts/cluster_queue.md
  docs/concepts/queue.md
  docs/concepts/queued_workload.md
Labels: size/L, lgtm, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes

#149 Fix a couple typos
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  docs/concepts/cluster_queue.md
  pkg/queue/manager_test.go
  pkg/queue/queue_test.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#150 Add pending condition to queuedworkloads
  main.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queue_controller_test.go
  test/integration/controller/core/queuedworkload_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#151 Fix typo in json field name
  api/v1alpha1/clusterqueue_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#142 Add task for single cluster queue setup
  README.md
  config/samples/single-clusterqueue-setup.yaml
  docs/README.md
  docs/concepts/README.md
  docs/tasks/README.md
  docs/tasks/administer_cluster_resources.md
Labels: size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#152 Make .quota.ceiling a pointer
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/samples/single-clusterqueue-setup.yaml
  docs/tasks/administer_cluster_resources.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/pointer/pointer.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, size/L, lgtm, tide/merge-method-squash, approved, kind/api-change, cncf-cla: yes

#153 Fix clusterqueue controller to update pending workloads
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  pkg/queue/manager.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/queuedworkload_controller_test.go
  test/integration/framework/framework.go
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#146 Abstract cluster queue interface
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#154 Do ClusterQueue updates after QW is updated in cache
  main.go
  pkg/constants/constants.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/bug, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#156 Add printer columns to Queue, ClusterQueue and QueuedWorkload
  api/v1alpha1/clusterqueue_types.go
  api/v1alpha1/queue_types.go
  api/v1alpha1/queuedworkload_types.go
  config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
  config/crd/bases/kueue.x-k8s.io_queues.yaml
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#159 Fix UpdateWorkloadStatus
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#157 Add task for run jobs
  config/samples/sample-job.yaml
  docs/tasks/README.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
Labels: size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#161 Increase logging during integration tests
  go.mod
  main.go
  pkg/scheduler/scheduler.go
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#163 Fix scheduler getting stuck when there are admission failures
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/queue_controller.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/scheduler/scheduler.go
Labels: kind/bug, size/L, lgtm, kind/failing-test, kind/flake, tide/merge-method-squash, approved, cncf-cla: yes

#165 Editorial review on user docs
  README.md
  docs/concepts/cluster_queue.md
  docs/concepts/queued_workload.md
  docs/tasks/README.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
Labels: size/L, lgtm, approved, kind/documentation, cncf-cla: yes
