Repository kubernetes-sigs/kueue, pull requests merged in 2022-10, with the labels that each got.

#409 Add Kind and GroupVersion to SSA object
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, kind/regression, approved, cncf-cla: yes, size/S

#408 ResourceFlavor labels require k8s 1.23
  docs/concepts/cluster_queue.md
  docs/setup/install.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#411 Automated cherry pick of #408: ResourceFlavor labels require k8s 1.23
  docs/concepts/cluster_queue.md
  docs/setup/install.md
Labels: lgtm, approved, size/XS, cncf-cla: yes

#413 leaderElectionID should be empty when leaderElection is disabled
  main.go
  main_test.go
Labels: kind/feature, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#416 Fix the image-local-build target
  Makefile
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#399 Consolidate defaulting for ControllerManagerConfigurationSpec
  apis/config/v1alpha2/defaults.go
  apis/config/v1alpha2/defaults_test.go
  main.go
  main_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#422 Add shortnames to kueue APIs
  apis/kueue/v1alpha2/clusterqueue_types.go
  apis/kueue/v1alpha2/resourceflavor_types.go
  apis/kueue/v1alpha2/workload_types.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/S
