Repository kubernetes-sigs/kueue, pull requests merged in 2022-02, with the labels that each got.

#1 Add more details and links related to the project
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#6 Add supported k8s version
  README.md
Labels: lgtm, approved, size/XS, cncf-cla: yes

#13 Add a simple Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/M, cncf-cla: yes

#12 group transfer to x-k8s.io
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_capacities.yaml
  config/crd/patches/cainjection_in_queuedworkloads.yaml
  config/crd/patches/cainjection_in_queues.yaml
  config/crd/patches/webhook_in_capacities.yaml
  config/crd/patches/webhook_in_queuedworkloads.yaml
  config/crd/patches/webhook_in_queues.yaml
  config/manager/controller_manager_config.yaml
  config/rbac/capacity_editor_role.yaml
  config/rbac/capacity_viewer_role.yaml
  config/rbac/queue_editor_role.yaml
  config/rbac/queue_viewer_role.yaml
  config/rbac/queuedworkload_editor_role.yaml
  config/rbac/queuedworkload_viewer_role.yaml
  config/rbac/role.yaml
  controllers/capacity_controller.go
  controllers/job_controller.go
  controllers/queue_controller.go
  controllers/queuedworkload_controller.go
  main.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#22 Make TotalRequests in workload.Info a list instead of map
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#31 Split integration tests into their own folder
  Makefile
  main.go
  pkg/constants/constants.go
  pkg/controller/core/capacity_controller.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  pkg/controller/workload/job/job_controller.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/suite_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#21 Add verify checks for go code
  Makefile
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#32 Issue/24
  Makefile
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/snapshot_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/queue.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#34 update annotation in sample
  config/samples/sample-job.yaml
Labels: lgtm, kind/failing-test, approved, size/XS, cncf-cla: yes

#35 Add the missing license header for source file
  Makefile
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#26 add event for queuedWorkload
  main.go
  pkg/constants/constants.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/S

#38 Verify manifests and code generation
  Makefile
Labels: lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#37 Consolidate re-queuing in a single place
  pkg/capacity/snapshot_test.go
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler.go
Labels: lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#42 refactor job suspension due to multiple or non-matching workloads in job-controller
  pkg/controller/workload/job/job_controller.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#48 RBAC add missing resource to kubebuilder set
  config/rbac/role.yaml
  pkg/controller/core/capacity_controller.go
  pkg/controller/core/queue_controller.go
  pkg/controller/core/queuedworkload_controller.go
  pkg/controller/workload/job/job_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#49 Refactor some variables collide with buildin func
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/snapshot.go
  pkg/capacity/snapshot_test.go
  pkg/controller/core/capacity_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#51 Makefile add arguments for img building and pushing
  Dockerfile
  Makefile
  README.md
Labels: lgtm, approved, size/M, cncf-cla: yes

#53 add ArangoGutierrez and denkensk as reviewers
  OWNERS
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#54 Fix deploy command in Makefile
  Makefile
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#36 Add queuedWorkload created event to batch/job
  main.go
  pkg/constants/constants.go
  pkg/controller/workload/job/job_controller.go
  pkg/util/testing/core.go
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#55 Keep parsed resource quantities in capacity cache
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/snapshot.go
  pkg/capacity/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#56 Update sample-job command
  config/samples/sample-job.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#46 Add support for tainted flavors
  go.mod
  go.sum
  pkg/capacity/capacity.go
  pkg/capacity/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#66 README fix usage guidelines for IMAGE_REGISTRY
  README.md
Labels: lgtm, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#60 Add go.mod verify checks
  .gitignore
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#69 Make kustomize directive noop
  Makefile
  config/manager/kustomization.yaml
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#71 Add integration test framework
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/suite_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/suite_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#57 Track usage in capacity status
  Makefile
  api/v1alpha1/capacity_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kueue.x-k8s.io_capacities.yaml
  main.go
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/snapshot.go
  pkg/controller/core/capacity_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/util/pointer/pointer.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, cncf-cla: yes
