Repository kubernetes-sigs/kueue, pull requests merged in 2022-09, with the labels that each got.

#366 reference readme misspelling
  docs/reference/README.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#368 Fix the broken links in the documents
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
  docs/tasks/setup_rbac.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#370 doc fix for admitted
  docs/concepts/cluster_queue.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#372 Automated cherry pick of #368: Fix broken links in the documents
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
  docs/tasks/setup_rbac.md
Labels: lgtm, approved, needs-ok-to-test, size/XS, cncf-cla: yes

#373 Give execute permission to cherry_pick_pull.sh
  hack/cherry_pick_pull.sh
Labels: lgtm, approved, kind/cleanup, needs-ok-to-test, size/XS, cncf-cla: yes

#374 Cherry Pick Into Release 0.2: doc fix for admitted section
  docs/concepts/cluster_queue.md
Labels: lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#378 Update the builder image
  cloudbuild.yaml
Labels: kind/feature, lgtm, approved, needs-ok-to-test, size/XS, cncf-cla: yes

#379 Fix the command for cloud build
  Makefile
  cloudbuild.yaml
  docs/setup/install.md
Labels: kind/bug, lgtm, tide/merge-method-squash, approved, ok-to-test, cncf-cla: yes, size/S

#362 Add options for internal cert management to component config
  CHANGELOG/CHANGELOG-0.3.md
  Makefile
  apis/config/v1alpha2/configuration_types.go
  apis/config/v1alpha2/defaults.go
  apis/config/v1alpha2/defaults_test.go
  apis/config/v1alpha2/groupversion_info.go
  apis/config/v1alpha2/zz_generated.deepcopy.go
  apis/kueue/webhooks/workload_webhook_test.go
  config/components/manager/controller_manager_config.yaml
  config/components/webhook/service.yaml
  docs/setup/install.md
  main.go
  main_test.go
  pkg/util/cert/cert.go
  pkg/util/pointer/pointer.go
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, ok-to-test, kind/documentation, cncf-cla: yes

#383 Fix make target for unit tests
  Makefile
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#384 Fix the broken links for admission
  docs/concepts/cluster_queue.md
  docs/concepts/workload.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#382 Add Admitted Workloads Field to LocalQueueStatus
  apis/kueue/v1alpha2/localqueue_types.go
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/localqueue_controller.go
  test/integration/controller/core/localqueue_controller_test.go
Labels: size/L, lgtm, approved, kind/api-change, ok-to-test, cncf-cla: yes

#386 Fix some typo comments for the pkg controller/workload/job
  pkg/controller/workload/job/job_controller.go
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#387 Regroup scheduler integration tests
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#389 Fix some wrong comments and messages
  pkg/controller/core/core.go
  pkg/queue/cluster_queue_interface.go
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#390 Stop using the deprecated library, github.com/go-logr/logr/testing
  pkg/scheduler/scheduler_test.go
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#393 Fix manager Role add jobs/finalizer resource
  CHANGELOG/CHANGELOG-0.3.md
  config/components/rbac/role.yaml
  pkg/controller/workload/job/job_controller.go
Labels: kind/bug, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#396 Add test for returning borrowed capacity
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#395 Install and Uninstall should use config/components/crd
  Makefile
Labels: kind/bug, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#398 Upgrade envtest k8s version to 1.24
  Makefile
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#397 Add scheduler integration tests for creating objects out of order
  test/integration/framework/framework.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#400 Add status of production readiness
  README.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#401 Add enhancements template and script for table of contents
  Makefile
  hack/.notableofcontents
  hack/update-toc.sh
  hack/verify-toc.sh
  keps/NNNN-template/README.md
  keps/NNNN-template/kep.yaml
Labels: size/L, lgtm, approved, kind/documentation, cncf-cla: yes
