Repository kubernetes-sigs/kueue, pull requests merged in 2023-04, with the labels that each got.

#673 add quotes for zsh terminal
  site/content/en/docs/installation/_index.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#668 Config option to select which job framework integrations should be enabled
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  config/components/manager/controller_manager_config.yaml
  config/components/webhook/manifests.yaml
  main.go
  main_test.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/noop/noop_webhook.go
Labels: kind/feature, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#654 603 admitted condition swap complexity
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/workload_controller.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/util/util.go
Labels: size/L, lgtm, tide/merge-method-squash, approved, ok-to-test, cncf-cla: yes

#676 Bump mpi-operator to v0.4.0
  go.mod
  go.sum
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#677 fixed flaky test
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#490 Update production readiness items
  README.md
  test/performance/README.md
Labels: lgtm, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#680 Set wait time precision in admission event to seconds
  pkg/scheduler/scheduler.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#681 Use resourceVersion when setting Admitted=False
  pkg/cache/cache.go
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/S

#682 Fix typos for the MPIJob
  pkg/controller/jobs/mpijob/mpijob_controller.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#685 Update docs to v0.3.0 in main branch
  README.md
  site/content/en/docs/installation/_index.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#684 Automated cherry pick of #682: Fix typos for the MPIJob
  pkg/controller/jobs/mpijob/mpijob_controller.go
Labels: lgtm, approved, size/XS, cncf-cla: yes

#675 Bump GO to 1.20
  Makefile
  go.mod
  go.sum
Labels: lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#698 Remove an unused function
  pkg/workload/workload.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#713 Update the queue name in workload only when the job is standalone
  CHANGELOG/CHANGELOG-0.4.md
  pkg/controller/jobframework/reconciler.go
  pkg/util/testingjobs/job/wrappers.go
  test/integration/controller/job/job_controller_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#705 Use FindStatusCondition in apimeta instead of workload.FindConditionIndex
  pkg/workload/workload.go
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#723 [CHANGELOG] Add LimitRange based validation before admission
  CHANGELOG/CHANGELOG-0.4.md
Labels: lgtm, kind/flake, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#717 Admission checking refactorization
  apis/kueue/webhooks/workload_webhook.go
  pkg/cache/cache.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/queue/manager.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  test/e2e/e2e_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
  test/integration/webhook/workload_test.go
  test/util/util.go
Labels: size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#689 [workload] WaitForPodsReady: Requeue at the back of the queue after timeout
  CHANGELOG/CHANGELOG-0.4.md
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/util/util.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, approved, ok-to-test, cncf-cla: yes

#733 Do not update allowedWorklodsPerQueue directly in AddClusterQueue
  pkg/cache/cache.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#734 Update the changelog for #711
  CHANGELOG/CHANGELOG-0.3.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#695 [jobframework] Integration Manager
  main.go
  main_test.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobs.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
Labels: lgtm, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#709 add example for borrowing limit
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, tide/merge-method-squash, approved, size/M, ok-to-test, cncf-cla: yes

#735 Pull-Request-Template: Add release-note block
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/XS, cncf-cla: yes

#736 Fix an integration test for the local-queue-controller
  test/integration/controller/core/localqueue_controller_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S
