Repository kubernetes-sigs/kueue, pull requests merged in 2023-05, with the labels that each got.

#732 Manage number of Pods as part of ClusterQueue quota
  CHANGELOG/CHANGELOG-0.4.md
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#739 Edit github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#727 Remove redundant checks in the cache
  pkg/cache/cache.go
  pkg/queue/manager.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#664 helm charts for kueue
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  .github/workflows/release.yaml
  Makefile
  charts/kueue/.helmignore
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/templates/_helpers.tpl
  charts/kueue/templates/certmanager/certificate.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  charts/kueue/templates/internalcert/secret.yaml
  charts/kueue/templates/manager/manager-config.yaml
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/templates/prometheus/monitor.yaml
  charts/kueue/templates/prometheus/role.yaml
  charts/kueue/templates/rbac/auth_proxy_client_clusterrole.yaml
  charts/kueue/templates/rbac/auth_proxy_role.yaml
  charts/kueue/templates/rbac/auth_proxy_role_binding.yaml
  charts/kueue/templates/rbac/auth_proxy_service.yaml
  charts/kueue/templates/rbac/batch_admin_role.yaml
  charts/kueue/templates/rbac/batch_user_role.yaml
  charts/kueue/templates/rbac/clusterqueue_editor_role.yaml
  charts/kueue/templates/rbac/clusterqueue_viewer_role.yaml
  charts/kueue/templates/rbac/job_editor_role.yaml
  charts/kueue/templates/rbac/job_viewer_role.yaml
  charts/kueue/templates/rbac/leader_election_role.yaml
  charts/kueue/templates/rbac/leader_election_role_binding.yaml
  charts/kueue/templates/rbac/localqueue_editor_role.yaml
  charts/kueue/templates/rbac/localqueue_viewer_role.yaml
  charts/kueue/templates/rbac/mpijob_editor_role.yaml
  charts/kueue/templates/rbac/mpijob_viewer_role.yaml
  charts/kueue/templates/rbac/resourceflavor_editor_role.yaml
  charts/kueue/templates/rbac/resourceflavor_viewer_role.yaml
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/rbac/role_binding.yaml
  charts/kueue/templates/rbac/service_account.yaml
  charts/kueue/templates/rbac/workload_editor_role.yaml
  charts/kueue/templates/rbac/workload_viewer_role.yaml
  charts/kueue/templates/webhook/service.yaml
  charts/kueue/templates/webhook/webhook.yaml
  charts/kueue/values.yaml
  hack/update-helm-crd.sh
Labels: kind/feature, lgtm, size/XXL, tide/merge-method-squash, approved, ok-to-test, cncf-cla: yes

#744 Remove workflow to release helm files
  .github/workflows/release.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#692 Keep evicted workloads in admitted while the associated jobs are still active
  CHANGELOG/CHANGELOG-0.4.md
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_interface.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/util/util.go
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#748 fixed resource flavor flaky test
  test/integration/controller/core/resourceflavor_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#751 update to use the latest logo
  site/assets/icons/logo.svg
  site/assets/scss/_styles_project.scss
  site/static/favicons/android-144x144.png
  site/static/favicons/android-192x192.png
  site/static/favicons/android-36x36.png
  site/static/favicons/android-48x48.png
  site/static/favicons/android-72x72.png
  site/static/favicons/android-96x96.png
  site/static/favicons/android-chrome-192x192.png
  site/static/favicons/android-chrome-512x512.png
  site/static/favicons/android-chrome-maskable-192x192.png
  site/static/favicons/android-chrome-maskable-512x512.png
  site/static/favicons/apple-touch-icon-180x180.png
  site/static/favicons/favicon-16x16.png
  site/static/favicons/favicon-32x32.png
  site/static/favicons/favicon.ico
  site/static/favicons/site.webmanifest
  site/static/images/logo.svg
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#731 [doc] Run A Flux Minicluster
  site/content/en/docs/tasks/run_flux_minicluster.md
Labels: lgtm, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#742 KEP-78: Dynamically reclaiming resources
  keps/78-dynamically-reclaiming-resources/README.md
  keps/78-dynamically-reclaiming-resources/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/api-change, kind/documentation, cncf-cla: yes

#759 Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/scheduler/preemption/preemption.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#708 Allow parallel admissions when using waitForPodsReady
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  main.go
  main_test.go
  pkg/cache/cache.go
  pkg/scheduler/scheduler.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/podsready/suite_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#760 [site] Mention Flux in the Tasks index.
  site/content/en/docs/tasks/_index.md
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#761 Automated cherry pick of #759: Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort
  CHANGELOG/CHANGELOG-0.3.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/scheduler/preemption/preemption.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#758 fix the suspend=true added to the job by the default job webhook has …
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#756 Dynamically reclaiming resources
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/cache/snapshot_test.go
  pkg/constants/constants.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#769 Add the unit test for the jobframework Defaulter
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/util/testingjobs/job/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#774 Update documentation to v0.3.1
  CHANGELOG/CHANGELOG-0.3.md
  README.md
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#775 Update steps of release process
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#779 Add logo & badges to README.md
  README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#784 Fix typos in integrationmanager
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#796 Regenerate a CRD for Workload with bumping k8s.io dependencies to v0.26.5
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
Labels: size/L, lgtm, tide/merge-method-squash, release-note-none, approved, kind/cleanup, cncf-cla: yes

#797 Add permission to update frameworkjob status
  config/components/rbac/role.yaml
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#787 Fix cluster queue validating webhook
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
Labels: kind/bug, release-note, lgtm, tide/merge-method-squash, approved, size/M, cncf-cla: yes

#785 Add interface compliance checks to framework jobs
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#788 Introduce feature gates
  go.mod
  go.sum
  main.go
  pkg/features/kube_features.go
  pkg/features/kube_features_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#799 Automated cherry pick of #787: fix panic in clusterqueue_webhook
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/clusterqueue_webhook_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#802 Use go.mod go version as a single source of truth of Ginkgo version
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#808 Add kerthcet as approver for deps, controllers, webhooks and utils
  OWNERS
  pkg/controller/OWNERS
  pkg/util/OWNERS
  pkg/webhooks/OWNERS
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#803 [makefile] Use the cached MPI module to get its CRDs for integration tests
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#763 KEP-420 Allow partial admission
  keps/420-partial-admission/README.md
  keps/420-partial-admission/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#778 add MPI example
  config/samples/sample-mpijob.yaml
  site/content/en/docs/tasks/run_mpi_jobs.md
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#813 update how to install helm-chart
  charts/kueue/README.md
Labels: lgtm, release-note-none, approved, needs-ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#815 Add trasc as reviewer
  OWNERS
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#805 Fix concurrent admission in cohort when borrowing
  pkg/cache/cache.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#819 Add ConfigMap to RayJob tutorial
  examples/ray-job-sample.yaml
  site/content/en/docs/tasks/run_rayjobs.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#822 Fix concurrent admission in cohort when borrowing (#805)
  pkg/cache/cache.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/preemption_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#823 Remove redundantly checks from Makefile
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#818 [test/integration] Reuse envtest
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/rayjob/rayjob_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#806 [preemption] Two step preemption.
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#824 Increase timeout for lint
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes
