Repository kubernetes-sigs/kueue, pull requests merged in 2023-03, with the labels that each got.

#589 Prefactor works of implementing job interface
  pkg/controller/workload/job/job_controller.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#596 support workload scheduler leader election
  main.go
  pkg/scheduler/scheduler.go
  pkg/util/cert/cert.go
  test/integration/controller/job/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: kind/bug, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#602 Upgrade controller-runtime
  go.mod
  go.sum
Labels: kind/bug, lgtm, kind/regression, approved, size/XS, cncf-cla: yes

#617 Remove v1alpha2 APIs
  apis/kueue/v1alpha2/clusterqueue_types.go
  apis/kueue/v1alpha2/constants.go
  apis/kueue/v1alpha2/groupversion_info.go
  apis/kueue/v1alpha2/localqueue_types.go
  apis/kueue/v1alpha2/resourceflavor_types.go
  apis/kueue/v1alpha2/workload_types.go
  apis/kueue/v1alpha2/zz_generated.deepcopy.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: lgtm, size/XXL, approved, kind/api-change, kind/cleanup, cncf-cla: yes

#616 Implement GenericJob interface on batchv1.Job (cherry-picked and resolved conflicts)
  pkg/controller/workload/job/job_controller.go
  pkg/controller/workload/job/job_controller_test.go
  pkg/controller/workload/job/job_webhook.go
  pkg/controller/workload/jobframework/helpers.go
  pkg/controller/workload/jobframework/interface.go
  test/integration/controller/job/job_controller_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#618 Add documentation for preemption
  apis/kueue/v1beta1/clusterqueue_types.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  site/content/en/docs/concepts/cluster_queue.md
Labels: size/L, lgtm, tide/merge-method-squash, approved, kind/documentation, cncf-cla: yes

#615 [pkg/workload] Use SSA patch to update status conditions.
  pkg/controller/core/workload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: kind/feature, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#619 Use the GenericJob interface by MPIJob
  pkg/controller/workload/job/job_controller.go
  pkg/controller/workload/jobframework/helpers.go
  pkg/controller/workload/jobframework/interface.go
  pkg/controller/workload/mpijob/mpijob_controller.go
  pkg/controller/workload/mpijob/mpijob_controller_test.go
  pkg/controller/workload/mpijob/mpijob_webhook.go
  test/integration/controller/mpijob/mpijob_controller_test.go
Labels: kind/feature, lgtm, size/XL, approved, cncf-cla: yes

#614 Allow borrowing while preemption is applied to assigned cluster queue
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, kind/feature, size/L, lgtm, approved, cncf-cla: yes

#627 Commonize reconciler code by generic Job reconciler
  main.go
  pkg/controller/workload/job/job_controller.go
  pkg/controller/workload/job/job_controller_test.go
  pkg/controller/workload/job/job_webhook.go
  pkg/controller/workload/jobframework/helpers.go
  pkg/controller/workload/jobframework/interface.go
  pkg/controller/workload/jobframework/reconciler.go
  pkg/controller/workload/jobframework/workload_names.go
  pkg/controller/workload/mpijob/mpijob_controller.go
  pkg/controller/workload/mpijob/mpijob_webhook.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/job/suite_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/mpijob/suite_test.go
Labels: kind/feature, lgtm, size/XXL, tide/merge-method-squash, approved, kind/cleanup, cncf-cla: yes

#631 Reorganize directory structure for jobs and the framework
  main.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/known_frameworks.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/workload_names.go
  pkg/controller/jobframework/workload_names_test.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  test/e2e/e2e_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/job/suite_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/mpijob/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#638 Upgrade the default K8s versions for local tests
  Makefile
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#633 Commonize webhooks and indexing
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/indexer.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobframework/workload_names.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
Labels: kind/feature, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#637 Fix a generic event handler for resourceFlavors in the clusterQueue controller
  pkg/controller/core/clusterqueue_controller.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#632 Documentation update for v1beta1 api
  config/samples/sample-job.yaml
  config/samples/single-clusterqueue-setup.yaml
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/local_queue.md
  site/content/en/docs/concepts/resource_flavor.md
  site/content/en/docs/tasks/administer_cluster_quotas.md
  site/content/en/docs/tasks/setup_sequential_admission.md
Labels: lgtm, size/XL, approved, kind/documentation, cncf-cla: yes

#623 Add a conditions field to LocalQueueStatus
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/localqueue_controller.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/webhook/localqueue_test.go
Labels: kind/feature, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#641 Graduate Configuration API version to v1beta1
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/groupversion_info.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  config/components/manager/controller_manager_config.yaml
  main.go
  main_test.go
  pkg/controller/core/core.go
  pkg/util/cert/cert.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/suite_test.go
  test/integration/controller/mpijob/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/suite_test.go
Labels: kind/feature, lgtm, approved, kind/api-change, size/M, cncf-cla: yes

#644 Remove a --arch=amd64 flag from envtest command
  Makefile
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#645 Update documentation for config.kueue.x-k8s.io v1beta1
  README.md
  site/content/en/docs/concepts/resource_flavor.md
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/run_jobs.md
Labels: lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#600 [workload] Get default resource values from LimitRanges
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  config/components/rbac/role.yaml
  pkg/controller/core/indexer/indexer.go
  pkg/controller/core/workload_controller.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/resource/resource.go
  pkg/util/resource/resource_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/core/workload_controller_test.go
Labels: kind/feature, lgtm, tide/merge-method-squash, size/XL, approved, ok-to-test, cncf-cla: yes

#651 Regenerate a CRD for the worklods when upgrading k8s.io dependencies to v0.26.3
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#657 Fix flaky integration test
  test/integration/webhook/localqueue_test.go
Labels: lgtm, kind/failing-test, approved, kind/cleanup, cncf-cla: yes, size/S

#656 Update release notes for 0.3
  CHANGELOG/CHANGELOG-0.3.md
  site/content/en/docs/tasks/run_jobs.md
  site/content/en/docs/tasks/setup_sequential_admission.md
Labels: lgtm, tide/merge-method-squash, approved, size/M, kind/documentation, cncf-cla: yes

#653 Keep adjusted workload resources in sync with limitRanges and runtimeClasses
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  apis/kueue/webhooks/workload_webhook.go
  apis/kueue/webhooks/workload_webhook_test.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/indexer/indexer.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
  test/util/util.go
Labels: kind/feature, lgtm, size/XXL, tide/merge-method-squash, approved, ok-to-test, cncf-cla: yes

#643 add diagrams of kueue
  site/assets/scss/_styles_project.scss
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/overview/_index.md
  site/content/en/docs/tasks/run_jobs.md
  site/static/images/cluster-queue.svg
  site/static/images/queueing-components.svg
  site/static/images/theory-of-operation.svg
Labels: lgtm, tide/merge-method-squash, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S
