Repository kubernetes-sigs/kueue, pull requests merged in 2023-11, with the labels that each got.

#1286 List features of Kueue in README and website/overview
  README.md
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#1305 correct some comments
  pkg/cache/cache.go
  pkg/controller/constants/constants.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/features/kube_features.go
  pkg/podset/podset.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/podset_reducer.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/util/heap/heap_test.go
  pkg/util/resource/resource.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#1316 [Helm] Error using default controllerManagerConfigYaml
  charts/kueue/templates/webhook/webhook.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#977 kep: issue 487 support for kubectl plugin
  keps/487-kubectl-plugin/README.md
  keps/487-kubectl-plugin/kep.yaml
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, ok-to-test, cncf-cla: yes

#1324 Add Mondoo as adopter
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1326 Add Google Cloud as adopter
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1328 Add adopters to top menu
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1314 specify FeatureGates in helm chart
  charts/kueue/templates/_helpers.tpl
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#1332 When preempting in a flavor, retry all flavors in the next iteration
  pkg/scheduler/scheduler.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#1300 KEP-168-2: Pending workloads visibility
  keps/168-2-pending-workloads-visibility/README.md
  keps/168-2-pending-workloads-visibility/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#1310 Commonize KubeflowJob Tests
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#1342 Perform finalize processes when job is deleting
  pkg/controller/jobframework/reconciler.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: release-note, lgtm, tide/merge-method-merge, approved, size/M, cncf-cla: yes

#1351 Retry provisioning request
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/util/testing/util.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1355 Retry for ProvisioningRequests KEP
  keps/1136-provisioning-request-support/README.md
Labels: kind/feature, lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1288 [KEP] A mechanism to stop a ClusterQueue
  keps/1284-cluster-queue-stop/README.md
  keps/1284-cluster-queue-stop/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1363 Use equality pkg instead of reflect pkg for the DeepEqual function
  pkg/config/config.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1319 Add support for pod groups
  pkg/controller/jobframework/errors.go
  pkg/controller/jobframework/indexer.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/util/testing/core.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1362 Extend visibility ClusterQueue PendingWorkloads endpoint
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  apis/visibility/v1alpha1/types.go
  client-go/applyconfiguration/visibility/v1alpha1/pendingworkload.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/visibility/api/rest/pending_workload_CQ.go
  pkg/visibility/api/rest/pending_workload_CQ_test.go
  test/e2e/e2e_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, kind/api-change, ok-to-test, cncf-cla: yes

#1366 Fix fungibility: Try next flavor if can't preempt on first
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, tide/merge-method-merge, approved, cncf-cla: yes

#1371 Fix JSON mapping in visibility types
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  apis/visibility/v1alpha1/types.go
  client-go/applyconfiguration/visibility/v1alpha1/clusterqueue.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1374 Prepare release for v0.5.1
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1375 Update latest version to v0.5.1
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1365 Add a visibility API endpoint for fetching pending workloads in a Local Queue
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  apis/visibility/v1alpha1/types.go
  apis/visibility/v1alpha1/zz_generated.deepcopy.go
  charts/kueue/templates/rbac/pending_workloads_cq_viewer_role.yaml
  charts/kueue/templates/rbac/pending_workloads_lq_viewer_role.yaml
  client-go/applyconfiguration/utils.go
  client-go/applyconfiguration/visibility/v1alpha1/localqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/fake/fake_localqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/fake/fake_visibility_client.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/localqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/visibility_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/visibility/v1alpha1/interface.go
  client-go/informers/externalversions/visibility/v1alpha1/localqueue.go
  client-go/listers/visibility/v1alpha1/expansion_generated.go
  client-go/listers/visibility/v1alpha1/localqueue.go
  config/components/rbac/kustomization.yaml
  config/components/rbac/pending_workloads_cq_viewer_role.yaml
  config/components/rbac/pending_workloads_lq_viewer_role.yaml
  pkg/queue/manager.go
  pkg/visibility/api/install.go
  pkg/visibility/api/rest/local_queue.go
  pkg/visibility/api/rest/pending_workloads_cq.go
  pkg/visibility/api/rest/pending_workloads_cq_test.go
  pkg/visibility/api/rest/pending_workloads_lq.go
  pkg/visibility/api/rest/pending_workloads_lq_test.go
  test/e2e/e2e_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, kind/api-change, ok-to-test, cncf-cla: yes

#1373 Improve pod/wl cleanup for pod groups
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/util/testingjobs/pod/wrappers.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1338 KEP update: Allow replacement pods in groups of pods
  keps/976-plain-pods/README.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1386 Remove metav1.TypeMeta field and implementation of runtime.Object interface from visibility.PendingWorkload,
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  apis/visibility/v1alpha1/types.go
  apis/visibility/v1alpha1/zz_generated.deepcopy.go
  client-go/applyconfiguration/visibility/v1alpha1/pendingworkload.go
Labels: release-note, lgtm, approved, kind/api-change, size/M, kind/cleanup, ok-to-test, cncf-cla: yes
