Repository kubernetes-sigs/kueue, pull requests merged in 2023-08, with the labels that each got.

#1028 Ignore .nix files from git
  .gitignore
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1014 check k8s version for synchronization of completions and parallelism
  config/components/webhook/manifests.yaml
  main.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/util/kubeversion/kubeversion.go
  pkg/util/kubeversion/kubeversion_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#1032 Add labels for workload parent
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testing/wrappers.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#1033 [jobframework] Check the potential failure of RunWithPodSetsInfo
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#991 KEP: Pending workloads visibility [expose in queue statuses]
  keps/168-pending-workloads-visibility/README.md
  keps/168-pending-workloads-visibility/kep.yaml
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, kind/api-change, cncf-cla: yes

#1040 [rayjob] Make the TestNodeSelectors test table driven.
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1042 Fix flaky tests that had problems cleaning up RFs
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/jobset/jobset_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/rayjob/rayjob_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, tide/merge-method-squash, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#1049 Remove an unused arg from setupScheduler()
  main.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1044 Checking server version in integration tests
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/job/suite_test.go
  test/integration/controller/jobset/jobset_controller_test.go
  test/integration/controller/jobset/jobset_webhook_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/mpijob/mpijob_webhook_test.go
  test/integration/controller/rayjob/rayjob_controller_test.go
  test/integration/controller/rayjob/rayjob_webhook_test.go
  test/integration/framework/framework.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1046 Ensure that the framework is available using RESTMapper instead of getting CRDs
  config/components/rbac/role.yaml
  go.mod
  main.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1055 remove pointer package and use k8s pointer
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  go.mod
  go.sum
  main_test.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/config/config_test.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/flavorassigner/podset_reducer.go
  pkg/scheduler/scheduler_test.go
  pkg/util/equality/podset.go
  pkg/util/pointer/pointer.go
  pkg/util/priority/priority.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/rayjob/wrappers.go
  pkg/webhooks/workload_webhook.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/jobset/jobset_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/rayjob/rayjob_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/workload_test.go
Labels: lgtm, tide/merge-method-squash, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#1016 Add document how to integrate a custom Job with Kueue
  site/content/en/docs/tasks/integrate_a_custom_job.md
Labels: lgtm, tide/merge-method-squash, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#1057 Update approvers and instructions in NEW_RELEASE template
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1059 Extend `make verify` to fully check `charts/kueue/templates`
  Makefile
  charts/kueue/templates/rbac/role.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1061 Remove Get prefix from function name
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1063 Use absolute paths for include
  site/layouts/shortcodes/include.html
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1048 Add docs for the PyTorchJob integration
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
  site/layouts/shortcodes/include.html
  site/static/examples/sample-pytorchjob.yaml
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#1039 [cohort] Multiple admissions in one scheduling cycle
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/maps/maps.go
  pkg/util/maps/maps_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1067 Fix typos
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1066 Add SIG scheduling contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1041 KEP: workload priority
  keps/973-workload-priority/README.md
  keps/973-workload-priority/kep.yaml
Labels: lgtm, tide/merge-method-squash, release-note-none, size/XL, approved, kind/api-change, ok-to-test, kind/documentation, cncf-cla: yes

#861 Workload finalizer
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/job/job_controller_test.go
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, release-note-none, approved, cncf-cla: yes

#1070 KubeflowJob: Commonize OrderedReplicaTypes and PriorityClass
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1077 Exit if fail to setup indexes
  main.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#1073 Add docs for the TFJob integration
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
  site/static/examples/sample-tfjob.yaml
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#994 KEP 993: Two Stage Admission Process
  keps/993-two-phase-admission/README.md
  keps/993-two-phase-admission/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1075 Change Admission semantics to better cover two stage admission.
  apis/kueue/v1beta1/workload_types.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/indexer/indexer.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/e2e/e2e_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
  test/integration/webhook/workload_test.go
  test/util/util.go
Labels: release-note, lgtm, tide/merge-method-squash, size/XL, approved, cncf-cla: yes

#1076 Add platform developer section to tasks index
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/integrate_a_custom_job.md
Labels: lgtm, tide/merge-method-squash, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes
