Repository kubernetes-sigs/kueue, pull requests merged in 2023-09, with the labels that each got.

#1088 Add a folder for experimental integrations
  Makefile
  cmd/experimental/README.md
  cmd/kueue/main.go
  cmd/kueue/main_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1097 Add to adopter
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1069 KEP 168: Visibility for cluster queue
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuependingworkload.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuependingworkloadsstatus.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuestatus.go
  client-go/applyconfiguration/utils.go
  cmd/kueue/main_test.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/core.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#810 KEP: Support for peremption based on flavor order
  keps/582-preempt-based-on-flavor-order/README.md
  keps/582-preempt-based-on-flavor-order/kep.yaml
Labels: kind/feature, size/L, lgtm, tide/merge-method-squash, release-note-none, approved, ok-to-test, cncf-cla: yes

#1104 Generate client-go library for AdmissionCheck
  apis/kueue/v1beta1/admissioncheck_types.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheck.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheckparametersreference.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheckspec.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/typed/kueue/v1beta1/admissioncheck.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_admissioncheck.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/generated_expansion.go
  client-go/clientset/versioned/typed/kueue/v1beta1/kueue_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/kueue/v1beta1/admissioncheck.go
  client-go/informers/externalversions/kueue/v1beta1/interface.go
  client-go/listers/kueue/v1beta1/admissioncheck.go
  client-go/listers/kueue/v1beta1/expansion_generated.go
Labels: release-note, lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#1105 Sync AmissionCheck API with KEP one
  apis/kueue/v1beta1/admissioncheck_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  test/integration/webhook/admissioncheck_test.go
  test/util/util.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#1109 Website release 0.5
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/metrics.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/enabling_pprof_endpoints.md
Labels: lgtm, tide/merge-method-merge, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1031 Add KEP for Pod support
  keps/976-plain-pods/README.md
  keps/976-plain-pods/kep.yaml
Labels: kind/feature, lgtm, tide/merge-method-merge, release-note-none, size/XL, approved, cncf-cla: yes

#1110 Two-Stage Admission KEP: Rename QuotaBookingMode to PreemptionPolicy
  keps/993-two-phase-admission/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1079 Add AdmissionCheckReconciler
  charts/kueue/templates/rbac/role.yaml
  config/components/crd/kustomization.yaml
  config/components/rbac/role.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/util/testing/not_found_error_cmp.go
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1115 Add viewer and editor roles for TFJob to rbac
  config/components/rbac/kustomization.yaml
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#1116 Remove duplicated constants in the integration tests
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1117 Merge changes for the next release into the main branch (2)
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
  site/static/examples/sample-pytorchjob.yaml
  site/static/examples/sample-tfjob.yaml
Labels: size/L, lgtm, tide/merge-method-merge, release-note-none, approved, kind/documentation, cncf-cla: yes

#1121 Do not export variables that are not externally used
  pkg/controller/core/clusterqueue_controller.go
  pkg/util/kubeversion/kubeversion.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1123 fix typo
  site/content/en/docs/tasks/setup_sequential_admission.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1114 Support kubeflow.org/xgboostjob
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/rbac/xgboostjob_editor_role.yaml
  charts/kueue/templates/rbac/xgboostjob_viewer_role.yaml
  charts/kueue/values.yaml
  cmd/kueue/main_test.go
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/role.yaml
  config/components/rbac/xgboostjob_editor_role.yaml
  config/components/rbac/xgboostjob_viewer_role.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/kubeflow/jobs/jobs.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook_test.go
  pkg/util/testingjobs/xgboostjob/wrappers.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1120 [DOC] Add tasks for XGBoostJob integration to site
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_xgboostjobs.md
  site/static/examples/sample-xgboostjob.yaml
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#1126 Pull and Load E2E Images
  hack/e2e-test.sh
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1124 release lock as soon as finish using
  pkg/queue/cluster_queue_impl.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1078 Deduplicate code samples
  README.md
  site/content/en/docs/tasks/administer_cluster_quotas.md
  site/content/en/docs/tasks/run_jobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
  site/content/en/docs/tasks/run_python_jobs.md
  site/content/en/docs/tasks/run_rayjobs.md
  site/static/examples/admin/single-clusterqueue-setup.yaml
  site/static/examples/jobs/ray-job-code-sample.yaml
  site/static/examples/jobs/ray-job-sample.yaml
  site/static/examples/jobs/sample-job-partial-admission.yaml
  site/static/examples/jobs/sample-job.yaml
  site/static/examples/jobs/sample-mpijob.yaml
Labels: size/L, lgtm, tide/merge-method-squash, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1133 Bump K8s dependencies to v1.28
  Makefile
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/informers/externalversions/factory.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/config/config.go
  pkg/config/config_test.go
  test/integration/framework/framework.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#1135 Trigger cq reconciliation on snapshot change
  pkg/controller/core/clusterqueue_controller.go
  pkg/queue/manager.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/suite_test.go
Labels: kind/bug, release-note, lgtm, kind/flake, approved, size/M, cncf-cla: yes

#1140 Ensure whether or not framework CRDs are installed by meta.IsNoMatchError()
  cmd/kueue/main.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1118 Added box and download icon for static files; modified the current md…
  site/content/en/docs/tasks/run_jobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_xgboostjobs.md
  site/content/en/docs/tasks/run_python_jobs.md
  site/content/en/docs/tasks/run_rayjobs.md
  site/layouts/shortcodes/include.html
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#1139 Adding featuregate for cluster queue visibility
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/core/workload_controller_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1144 Fix CmpNoOrder in case of duplicated items
  pkg/util/slices/slices.go
  pkg/util/slices/slices_test.go
Labels: kind/bug, lgtm, kind/failing-test, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#1142 Support kubeflow.org/paddlejob
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/rbac/paddlejob_editor_role.yaml
  charts/kueue/templates/rbac/paddlejob_viewer_role.yaml
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/values.yaml
  cmd/kueue/main_test.go
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/paddlejob_editor_role.yaml
  config/components/rbac/paddlejob_viewer_role.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/kubeflow/jobs/jobs.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook_test.go
  pkg/util/testingjobs/paddlejob/wrappers.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1158 [hack] Fix out of GOPATH client-go generation.
  hack/update-codegen.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1153 Bump go version
  Makefile
  go.mod
  go.sum
Labels: kind/feature, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#1127 [scheduler] Check the consistency of the workloads admission check list before fully admitting it.
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1165 [workload]Avoid unnecessary allocation in HasAllChecks
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1167 [slices] Avoid unnecessary allocation in CmpNoOrder
  pkg/util/slices/slices.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1072 Add support for single pods
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/webhook/webhook.yaml
  charts/kueue/values.yaml
  cmd/kueue/main.go
  cmd/kueue/main_test.go
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/role.yaml
  config/components/webhook/kustomization.yaml
  config/components/webhook/manifests.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobs.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#1166 Replace utils/maps::Clone function with std maps::Clone function after it was introduced in go 1.21
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/scheduler/scheduler.go
  pkg/util/maps/maps.go
  pkg/util/maps/maps_test.go
  pkg/workload/workload.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1148 Add a task for kubelow.org/paddlejob to docs
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_paddlejobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_xgboostjobs.md
  site/static/examples/jobs/sample-paddlejob.yaml
  site/static/examples/jobs/sample-pytorchjob.yaml
  site/static/examples/jobs/sample-tfjob.yaml
  site/static/examples/jobs/sample-xgboostjob.yaml
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#1168 [DOC] Queue visibility documentation
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/monitor_pending_workloads.md
Labels: release-note, size/L, lgtm, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1103 Add docs for pod integration
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_plain_pods.md
  site/static/examples/pods-kueue/kueue-pod.yaml
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes
