Repository kubernetes-sigs/kueue, pull requests merged in 2023-01, with the labels that each got.

#500 Upgrade apimachinery library to 0.26
  apis/kueue/webhooks/clusterqueue_webhook.go
  apis/kueue/webhooks/resourceflavor_webhook.go
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#502 Use generic Set for ClusterQueues in cohort
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#503 Use sets.KeySet to simplify cache tests
  pkg/cache/cache_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#504 Use klog.KRef when logging clusterQueue
  pkg/cache/cache.go
  pkg/scheduler/scheduler.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#501 Use human-readable logging format in manifest.yaml.
  Makefile
  config/dev/kustomization.yaml
  config/dev/manager_config_patch.yaml
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#507 fix broken link
  docs/setup/install.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#508 Explicitly set the number of controller workers in config and increase it to 3
  config/components/manager/controller_manager_config.yaml
Labels: kind/feature, lgtm, approved, size/XS, cncf-cla: yes

#509 Move version/commint logs after the logging is fully set up
  main.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#506 Define priority by value in testing wrappers
  apis/kueue/webhooks/workload_webhook_test.go
  pkg/util/priority/priority_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#512 Atomically release quota and queue inadmissible workloads
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, size/L, lgtm, approved, cncf-cla: yes

#513 Allow to set K8S client QPS and burst values and bump default settings to 50/100
  apis/config/v1alpha2/configuration_types.go
  apis/config/v1alpha2/defaults.go
  apis/config/v1alpha2/defaults_test.go
  apis/config/v1alpha2/zz_generated.deepcopy.go
  config/components/manager/controller_manager_config.yaml
  main.go
  main_test.go
Labels: kind/feature, size/L, lgtm, approved, cncf-cla: yes

#498 Enforce timeout for podsReady
  apis/config/v1alpha2/configuration_types.go
  apis/config/v1alpha2/defaults.go
  apis/config/v1alpha2/defaults_test.go
  apis/config/v1alpha2/zz_generated.deepcopy.go
  main.go
  main_test.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/suite_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/v1alpha2/suite_test.go
Labels: kind/feature, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#520 Configure timeouts for the ExpectWorkloadsToBeAdmitted as in other util functions
  test/util/util.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#519 One Preemption mode when assigning flavors
  keps/83-workload-preemption/README.md
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#515 Docs on enabling simple all-or-nothing scheduling in Kueue
  docs/setup/install.md
  docs/tasks/README.md
  docs/tasks/setup_sequential_admission.md
Labels: kind/feature, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#522 Do not update the PodsReady once True as long as the workload is admitted
  pkg/controller/workload/job/job_controller.go
  test/integration/controller/job/job_controller_test.go
Labels: kind/bug, lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#528 Set Job controller concurrency to 5 and drop other controllers to 1
  config/components/manager/controller_manager_config.yaml
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#530 Test cases for preemption mode with affinity and taints
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/util/testing/core.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#514 Preemption within ClusterQueue and cohort
  apis/kueue/v1alpha2/clusterqueue_types.go
  apis/kueue/v1alpha2/zz_generated.deepcopy.go
  apis/kueue/webhooks/clusterqueue_webhook.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/priority/priority.go
  pkg/util/routine/error_channel.go
  pkg/util/routine/error_channel_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/preemption_test.go
  test/integration/webhook/v1alpha2/clusterqueue_test.go
  test/integration/webhook/v1alpha2/suite_test.go
  test/util/util.go
Labels: kind/feature, lgtm, size/XXL, approved, kind/api-change, cncf-cla: yes

#539 Add tenzen-y to reviewers
  OWNERS
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes
