Repository kubernetes-sigs/kueue, pull requests merged in 2023-06, with the labels that each got.

#826 Bumping controller-gen to remove unneeded creationTimestamp
  Makefile
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#829 [api/workload] Optional PodSetAssignment.Count
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, kind/api-change, cncf-cla: yes

#832 [config/rbac] Add RayJob roles.
  config/components/rbac/rayjob_editor_role.yaml
  config/components/rbac/rayjob_viewer_role.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#833 Migrate away from google.com gcp project k8s-testimages
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#835 Ignore reconciling against unmanaged child jobs in the jobframework
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/known_frameworks.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/util/testing/client.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/job/job_webhook_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
  test/integration/controller/mpijob/suite_test.go
  test/integration/controller/rayjob/rayjob_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#841 [jobs] Add a common way to merge and clone node selectors
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/util/maps/maps.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#842 [jobframwork] Make `KnownWorkloadOwnerObject` part of integration Manager
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/known_frameworks.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#843 reverse condition for workloads admitted recently
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#845 Resolve conflicts after merging order of preempting workloads
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#848 Fix failing ResourceFlavor controller integration test.
  Makefile
  pkg/controller/core/resourceflavor_controller.go
  test/integration/controller/core/resourceflavor_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, release-note-none, approved, cncf-cla: yes, size/S

#847 [jobframework] Make `ReclaimablePods` optional
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#860 Makefile: Use 'GO_CMD' instead of 'go'
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#858 Don't embed source job types
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#789 Add client-go libraries
  Makefile
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/doc.go
  apis/kueue/v1beta1/groupversion_info.go
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/workload_types.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/doc.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/doc.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/doc.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/kueue/v1beta1/clusterqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/doc.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/doc.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_clusterqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_localqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_resourceflavor.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_workload.go
  client-go/clientset/versioned/typed/kueue/v1beta1/generated_expansion.go
  client-go/clientset/versioned/typed/kueue/v1beta1/kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/localqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/resourceflavor.go
  client-go/clientset/versioned/typed/kueue/v1beta1/workload.go
  client-go/informers/externalversions/factory.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/internalinterfaces/factory_interfaces.go
  client-go/informers/externalversions/kueue/interface.go
  client-go/informers/externalversions/kueue/v1beta1/clusterqueue.go
  client-go/informers/externalversions/kueue/v1beta1/interface.go
  client-go/informers/externalversions/kueue/v1beta1/localqueue.go
  client-go/informers/externalversions/kueue/v1beta1/resourceflavor.go
  client-go/informers/externalversions/kueue/v1beta1/workload.go
  client-go/listers/kueue/v1beta1/clusterqueue.go
  client-go/listers/kueue/v1beta1/expansion_generated.go
  client-go/listers/kueue/v1beta1/localqueue.go
  client-go/listers/kueue/v1beta1/resourceflavor.go
  client-go/listers/kueue/v1beta1/workload.go
  hack/update-codegen.sh
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#834 No annotation for PodSets Info backup
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/util/slices/slices.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  test/integration/controller/job/job_controller_test.go
  test/integration/controller/mpijob/mpijob_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#864 Replace 'IsOwnerManagebleByKueue' with 'IsOwnerManagedByKueue'
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobs/job/job_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#866 Add a link related to MPIJob to the tasks page
  site/content/en/docs/tasks/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#876 fix typo in workload.md
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#863 [Integration Test] Ensure that startTime is reset when jobs are stopped
  test/integration/controller/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#854 Add moficodes as approver for site
  site/OWNERS
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#885 Add integration test for job preemption and fungibility
  test/integration/controller/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#882 [client-go] Generate from outside GOPATH
  Makefile
  go.mod
  go.sum
  hack/internal/tools/pinversion.go
  hack/update-codegen.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#894 Store logs from controllers in E2E tests
  Makefile
  hack/e2e-test.sh
  hack/kind-cluster.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#883 Ignore jobs if integration is disabled
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/role.yaml
  go.mod
  main.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#890 Add E2E test for nodeSelector based on ResourceFlavor
  hack/kind-cluster.yaml
  pkg/scheduler/scheduler.go
  pkg/util/testingjobs/job/wrappers.go
  test/e2e/e2e_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#897 Cleanup created priority classes
  test/integration/controller/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#879 [makefile][e2e] Run e2e with multiple k8s versions.
  Makefile
  hack/e2e-test.sh
  test/e2e/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#889 Custom config loader
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  main.go
  main_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, size/XXL, tide/merge-method-squash, release-note-none, approved, kind/cleanup, cncf-cla: yes

#895 [tests] NodeSelector assignment when using quota only for pod count
  test/integration/controller/job/job_controller_test.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#865 Add validation for child jobs without ownerReference
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#856 [dep] Bump the default k8s version used to 1.27
  Makefile
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/internal/internal.go
  client-go/applyconfiguration/kueue/v1beta1/admission.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueue.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuepreemption.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuestatus.go
  client-go/applyconfiguration/kueue/v1beta1/flavorquotas.go
  client-go/applyconfiguration/kueue/v1beta1/flavorusage.go
  client-go/applyconfiguration/kueue/v1beta1/localqueue.go
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorusage.go
  client-go/applyconfiguration/kueue/v1beta1/localqueueresourceusage.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuespec.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuestatus.go
  client-go/applyconfiguration/kueue/v1beta1/podset.go
  client-go/applyconfiguration/kueue/v1beta1/podsetassignment.go
  client-go/applyconfiguration/kueue/v1beta1/reclaimablepod.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavor.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  client-go/applyconfiguration/kueue/v1beta1/resourcegroup.go
  client-go/applyconfiguration/kueue/v1beta1/resourcequota.go
  client-go/applyconfiguration/kueue/v1beta1/resourceusage.go
  client-go/applyconfiguration/kueue/v1beta1/workload.go
  client-go/applyconfiguration/kueue/v1beta1/workloadspec.go
  client-go/applyconfiguration/kueue/v1beta1/workloadstatus.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/doc.go
  client-go/clientset/versioned/typed/kueue/v1beta1/clusterqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_clusterqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_localqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_resourceflavor.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_workload.go
  client-go/clientset/versioned/typed/kueue/v1beta1/localqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/resourceflavor.go
  client-go/clientset/versioned/typed/kueue/v1beta1/workload.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/noop/noop_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/client.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/localqueue_webhook.go
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/workload_webhook.go
Labels: lgtm, size/XXL, kind/flake, release-note-none, approved, kind/cleanup, cncf-cla: yes

#905 Cherry-pick e2e run changers on release 0.3
  Makefile
  hack/e2e-test.sh
  hack/kind-cluster.yaml
  test/e2e/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#907 [Cache] Sort resourceUsages according to resourceName
  pkg/cache/cache.go
  pkg/cache/cache_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#908 Automated cherry pick of #907: Sort resourceUsages according to resourceName
  pkg/cache/cache.go
  pkg/cache/cache_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#910 [E2E] Improve logging
  hack/e2e-test.sh
Labels: lgtm, kind/flake, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#913 [jobframework] Limit the involvement in non-standalone job reconciliation
  pkg/controller/jobframework/reconciler.go
  test/integration/controller/job/job_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#914 [hack/e2e] Restore the image tag to `release-0.3`
  hack/e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#903 Continue E2E cleanup if apiserver is down
  hack/e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#904 E2E test for preemption and fungibility
  test/e2e/e2e_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#909 Clean up go module after generating codes
  hack/update-codegen.sh
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#916 [Cache] Use the same reciever name for ClusterQueue
  pkg/cache/cache.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#846 [jobframework] Move `EquivalentToWorkload` functionality into framework
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/util/equality/podset.go
  pkg/util/equality/podset_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#925 Added missing clusterrole rules for helm
  charts/kueue/templates/rbac/role.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#762 Support JobSet in Kueue
  Makefile
  apis/config/v1beta1/configuration_types.go
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  go.mod
  go.sum
  main_test.go
  pkg/controller/jobs/jobs.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/util/testingjobs/jobset/wrappers.go
  test/integration/controller/jobset/jobset_controller_test.go
  test/integration/controller/jobset/suite_test.go
  test/integration/framework/framework.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#923 [Makefile] Use $(PROJECT_DIR) instead of $(shell pwd)
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#919 [e2e] Make kind verbose
  hack/e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#930 Update workload manifest in doc
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#932 [Cache] Put the internal ClusterQueue on a separate file
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#896 Deleted env field in the helm chart as unused
  charts/kueue/templates/manager/manager.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#901 Jobset dynamic reclaim
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/util/testingjobs/jobset/wrappers.go
  test/integration/controller/jobset/jobset_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#918 [controlles/job] Don't set minCount when PartialAdmission is disabled
  pkg/controller/jobframework/reconciler.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S
