Repository kubernetes-sigs/kueue, pull requests merged in 2023-12, with the labels that each got.

#1252 Suspend a running Job without requeueing
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/workloadspec.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1384 Fix the equivalentToWorkload method for pod groups
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1383 Update wl/job handling for the case, when the job is finished
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testingjobs/mxjob/wrappers.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1331 KEP-1224: Lending Limit to the cohort
  keps/1224-lending-limit/README.md
  keps/1224-lending-limit/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1395 Suspend a running Job without requeueing - API doc update
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1361 corrected incorrect links
  site/content/en/docs/concepts/admission_check.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1391 Parametrize CGO_ENABLED argument for container build
  Dockerfile
  Makefile
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#1388 Remove the proposal of the single workload endpoint from KEP#168-2
  keps/168-2-pending-workloads-visibility/README.md
Labels: lgtm, release-note-none, approved, kind/api-change, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1400 [flaky][int/job] Fix flaky partial admission suspend check.
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1404 Fill the CreationTimestamp field in the visibility.PendingWorkload object
  pkg/visibility/api/rest/pending_workloads_cq_test.go
  pkg/visibility/api/rest/pending_workloads_lq_test.go
  pkg/visibility/api/rest/utils.go
  test/e2e/e2e_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1299 A mechanism to stop a ClusterQueue
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/controller/core/workload_controller.go
  pkg/metrics/metrics.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/clusterqueue_test.go
Labels: release-note, size/L, lgtm, approved, do-not-merge/hold, cncf-cla: yes

#1381 Add documentation for Kueue visibility on-demand
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/monitor_pending_workloads/_index.md
  site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_in_status.md
  site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_on_demand.md
Labels: release-note, size/L, lgtm, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1412 Fix RBAC to visibility into Local Queues
  charts/kueue/templates/rbac/pending_workloads_lq_viewer_role.yaml
  config/components/rbac/pending_workloads_lq_viewer_role.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#1414 Update README.md
  README.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1409 Clean up unit and integration test for kubeflow
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/util/testingjobs/mxjob/wrappers.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1390 Add retriable-in-group annotation handling for pod groups
  keps/976-plain-pods/README.md
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/util/util.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#1418 doc: fix link issue
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1415 Return 404 for non-existent queues for the visibility endpoints
  pkg/visibility/api/rest/pending_workloads_cq.go
  pkg/visibility/api/rest/pending_workloads_cq_test.go
  pkg/visibility/api/rest/pending_workloads_lq.go
  pkg/visibility/api/rest/pending_workloads_lq_test.go
  pkg/visibility/api/rest/test_utils.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#1417 Add e2e tests that test RBAC to the Visibility API
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#1431 Add RBAC for the flowcontrol.apiserver.k8s.io
  Makefile
  apis/visibility/v1alpha1/openapi/doc.go
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/visibility/server.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1354 Introduce util admissioncheck package and make ConfigHelper generic
  cmd/kueue/main.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler_test.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer.go
  pkg/controller/admissionchecks/provisioning/storehelper.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/admissioncheck/admissioncheck_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#1406 Add feature gate for priorities sorting in a cohort
  pkg/features/kube_features.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#1443 [site] Add documentation for resource flavor tolerations.
  site/content/en/docs/concepts/resource_flavor.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1433 Excess pods in group deletion
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testingjobs/pod/wrappers.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#1428 Add an event for when a ProvisioningRequest is created for a Workload
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/util/testing/client.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1360 Multi-cluster tests setups
  Makefile
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  hack/multikueue/manager-cluster.kind.yaml
  hack/multikueue/worker-cluster.kind.yaml
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/suite_test.go
  test/e2e/suite_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
  test/util/e2e.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#1436 Record events when QuotaReservation and Admition take place.
  pkg/constants/constants.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/client.go
Labels: kind/bug, release-note, size/L, lgtm, tide/merge-method-squash, approved, cncf-cla: yes

#1456 Reset PrioritySortingWithinCohort when test finishes
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1458 [release 0.5] Record events when QuotaReservation and Admition take place.
  pkg/constants/constants.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/client.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1457 Log setup of integrations
  cmd/kueue/main.go
Labels: kind/feature, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1464 Initial .openvex setup
  .openvex/templates/README.md
  .openvex/templates/main.openvex.json
Labels: lgtm, release-note-none, approved, size/M, sig/release, cncf-cla: yes

#1465 Generate openvex data on each release
  .github/workflows/openvex.yaml
Labels: lgtm, release-note-none, approved, sig/release, cncf-cla: yes, size/S

#1474 update documentation for Active field
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1480 Update jobset 0.3.0
  go.mod
  go.sum
  pkg/util/testingjobs/jobset/wrappers.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1358 Prebuilt workload suport
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/podset/podset.go
  pkg/podset/podset_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  test/e2e/singlecluster/e2e_test.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1468 Fix RBAC for the APF controller
  Makefile
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/visibility/server.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1453 call export logs for kind on e2e tests
  hack/e2e-common.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1486 Add required RBAC on integration finalizers sub-resources
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1475 Makes openvex action manual trigger only
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  .github/workflows/openvex.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, sig/release, cncf-cla: yes

#1487 Add patch permissions for flowcontrol
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/visibility/server.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1492 Increase log level in k8s components
  hack/kind-cluster.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1494 [e2e/multikueue] Check only the created workload spec.
  test/e2e/multikueue/e2e_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#1469 Added security insight
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  SECURITY-INSIGHTS.yaml
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, sig/release, cncf-cla: yes

#1495 Fix the flaky e2e test for pending workloads
  pkg/util/testingjobs/job/wrappers.go
  test/e2e/singlecluster/e2e_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1491 Increase startup timeout
  test/e2e/singlecluster/e2e_test.go
  test/util/constants.go
  test/util/e2e.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1497 Fix a genref's config
  site/genref/config.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1493 Fix provisioning request test
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1498 Simplify flavorassigner to only return bool if borrowing is required
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1500 fix invalid link for reserved resource name
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1508 Add required RBAC on integration finalizers sub-resources (#1486)
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1509 Fix webhooks serving in non-leading replicas
  go.mod
  go.sum
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#1511 Automated cherry pick of #1509: Fix webhooks serving in non-leading replicas
  go.mod
  go.sum
Labels: release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#1507 Remove charts/kueue/templates/visibility/kustomization.yaml
  charts/kueue/templates/visibility/kustomization.yaml
  hack/update-helm.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1521 cleanup for pod jobs
  cmd/experimental/podtaintstolerations/controller/pod_jobs.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1311 KEP-1282: Requeue Strategy
  keps/1282-pods-ready-requeue-strategy/README.md
  keps/1282-pods-ready-requeue-strategy/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1512 Update pod controller to reconcile not found pods
  pkg/controller/jobs/pod/pod_controller.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1524 Fix for JobWithSkip in case when job is not found
  pkg/controller/jobframework/reconciler.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1496 Add comments to explain special cases
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1529 Fix copyright in cache package
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1380 KEP-693: MultiKueue
  keps/693-multikueue/README.md
  keps/693-multikueue/arch.png
  keps/693-multikueue/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1525 Add validation and test for borrowingLimit when cohort is nil
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes
