Repository kubernetes-sigs/kueue, pull requests merged in 2023-10, with the labels that each got.

#1137 [workload] Finish with failure on admission check rejection.
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
  test/integration/controller/core/workload_controller_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#1179 Use apivalidation.ValidateImmutableField instead of field.Forbidden
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1177 Fix job finalization logic in generic reconciler
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#1152 KEP-1145: Additional labels, annotations, tolerations and node selector for AdmissionChecks
  keps/1145-additional-labels/README.md
  keps/1145-additional-labels/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1182 Fix typos for the QuoataReserved
  pkg/util/maps/maps.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1111 Pod taints & tolerations controller
  cmd/experimental/podtaintstolerations/.dockerignore
  cmd/experimental/podtaintstolerations/.gitignore
  cmd/experimental/podtaintstolerations/Dockerfile
  cmd/experimental/podtaintstolerations/Makefile
  cmd/experimental/podtaintstolerations/README.md
  cmd/experimental/podtaintstolerations/config/cluster-role-binding-manager.yaml
  cmd/experimental/podtaintstolerations/config/cluster-role-binding-pods.yaml
  cmd/experimental/podtaintstolerations/config/cluster-role-binding-proxy.yaml
  cmd/experimental/podtaintstolerations/config/cluster-role-pods.yaml
  cmd/experimental/podtaintstolerations/config/deployment.yaml
  cmd/experimental/podtaintstolerations/config/kustomization.yaml
  cmd/experimental/podtaintstolerations/config/role-binding-leaderelection.yaml
  cmd/experimental/podtaintstolerations/config/service-account.yaml
  cmd/experimental/podtaintstolerations/controller/pod_jobs.go
  cmd/experimental/podtaintstolerations/examples/pod-highpriority.yaml
  cmd/experimental/podtaintstolerations/examples/pod.yaml
  cmd/experimental/podtaintstolerations/examples/priorities.yaml
  cmd/experimental/podtaintstolerations/examples/queue.yaml
  cmd/experimental/podtaintstolerations/go.mod
  cmd/experimental/podtaintstolerations/go.sum
  cmd/experimental/podtaintstolerations/hack/e2e-test.sh
  cmd/experimental/podtaintstolerations/hack/kind-cluster.yaml
  cmd/experimental/podtaintstolerations/main.go
  cmd/experimental/podtaintstolerations/test/e2e/config/kustomization.yaml
  cmd/experimental/podtaintstolerations/test/e2e/e2e_test.go
  cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
  cmd/experimental/podtaintstolerations/test/util/pod.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#849 Enable preemption and borrowing based on flavor
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  client-go/applyconfiguration/kueue/v1beta1/flavorfungibility.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  keps/582-preempt-based-on-flavor-order/README.md
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/features/kube_features.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/workload/workload.go
  site/content/en/docs/installation/_index.md
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/clusterqueue_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#1156 Fix rayjob will not resume after preempted
  pkg/controller/jobs/rayjob/rayjob_controller.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1190 Automated cherry pick of #1156: Fix rayjob will not resume after preempted
  pkg/controller/jobs/rayjob/rayjob_controller.go
  test/integration/controller/rayjob/rayjob_controller_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#1184 Enable jobset integration by default when deploying the kueue using Helm
  charts/kueue/values.yaml
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#1193 [AdmissionCheck] Add Active condition to AdmissionCheck object
  apis/kueue/v1beta1/admissioncheck_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  client-go/applyconfiguration/kueue/v1beta1/admissioncheck.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheckstatus.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  pkg/cache/admissioncheck.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/util/testing/wrappers.go
  test/e2e/e2e_test.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1170 add docs for workloadPriority
  keps/973-workload-priority/README.md
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/concepts/workload_priority_class.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_job_with_workload_priority.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1197 Fix: Adjust resources when the LocalQueue is created after workloads
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/workload/resources.go
  test/integration/scheduler/workload_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1199 [cherry-pick] Fix: Adjust resources when the LocalQueue is created after workloads …
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/workload/resources.go
  test/integration/scheduler/workload_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1201 Update latest version to v0.4.2
  CHANGELOG/CHANGELOG-0.4.md
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1203 Add adopter for kueue
  site/content/en/docs/adopters/index.md
Labels: lgtm, tide/merge-method-merge, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1205 [KubeflowJobs] Use constants instead of raw strings
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1180 Propagate podsetupdates to jobs
  Makefile
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/jobframework/podsetinfo.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/util/maps/maps.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1207 Improve naming consistency for podSetsInfo
  cmd/experimental/podtaintstolerations/controller/pod_jobs.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1208 Use generic sets instead of deprecated sets
  pkg/controller/jobframework/reconciler.go
  pkg/webhooks/workload_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1186 Add document for the kubeflow.org/mxjob
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mxjobs.md
  site/static/examples/jobs/sample-mxjob.yaml
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#1221 Graduate Partial admission to Beta.
  pkg/controller/jobs/job/job_controller_test.go
  pkg/features/kube_features.go
  pkg/features/kube_features_test.go
  pkg/scheduler/scheduler_test.go
  site/content/en/docs/installation/_index.md
  test/e2e/e2e_test.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1222 Add FAR AI as an adopter to kueue
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1229 Update the chart versions for any release
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1231 feat: update ray-operator to v0.6.0
  go.mod
  go.sum
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#1206 Report Reserving queue metrics and stats.
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuestatus.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuestatus.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/localqueue_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1232 [webhook] Add admission check webhook
  config/components/webhook/manifests.yaml
  pkg/util/testing/wrappers.go
  pkg/webhooks/admissioncheck_webhook.go
  pkg/webhooks/admissioncheck_webhook_test.go
  pkg/webhooks/webhooks.go
  test/e2e/e2e_test.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/webhook/admissioncheck_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1244 fix config arg path to always match configmap mount path
  charts/kueue/templates/manager/manager.yaml
  config/default/manager_config_patch.yaml
  config/dev/manager_config_patch.yaml
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1191 Commonize KubeflowJob Tests
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/util/util.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1245 [doc] Dynamic Reclaim
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1242 [doc] Provisioning Admission Check Controller
  site/content/en/docs/admission-check-controllers/_index.md
  site/content/en/docs/admission-check-controllers/provisioning.md
  site/content/en/docs/installation/_index.md
  site/static/examples/provisioning/provisioning-setup.yaml
  site/static/examples/provisioning/sample-job.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1220 Validating admissionchecks
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1247 Update webhook template for pod integration
  charts/kueue/templates/webhook/webhook.yaml
Labels: kind/feature, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#1226 update document for FlavorFungibility
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#1248 Resource flavor tolerations
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/podsetinfo.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/podset/podset.go
  pkg/podset/podset_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/resourceflavor_webhook_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1250 Add information on pod webhook namespace selector
  site/content/en/docs/tasks/run_plain_pods.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#1254 [workload] Drop Quota Reservation on cluster queue deletion.
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/workload_controller.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/util/util.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1257 Do not generate files when running tests
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1259 Update production readiness status: testgrids and adopters
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1260 Add release notes and references for release-0.5
  CHANGELOG/CHANGELOG-0.5.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/values.yaml
  config/components/manager/kustomization.yaml
  hack/e2e-test.sh
Labels: lgtm, release-note-none, approved, size/M, do-not-merge/hold, kind/documentation, cncf-cla: yes

#1262 Update version references to v0.5.0
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1266 [test/integration/pod] Setup all indexes.
  test/integration/controller/jobs/pod/suite_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1273 Install kueue with server-side apply
  site/content/en/docs/installation/_index.md
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1225 Add UTs for AdjustResources
  pkg/util/testing/wrappers.go
  pkg/workload/resources.go
  pkg/workload/resources_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1275 [api] Fix Admission check state enum documentation.
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1278 [doc] Update preemption section
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1263 [docs] Generate API docs.
  Makefile
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/genref/config.yaml
  site/genref/markdown/members.tpl
  site/genref/markdown/pkg.tpl
  site/genref/markdown/type.tpl
Labels: lgtm, size/XXL, release-note-none, approved, kind/documentation, cncf-cla: yes

#1241 Add integration test for resuming a partially completed job
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1277 Allow decrease reclaimable pods to 0 for suspended job
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#1255 Avoid use of Consistently in integration tests
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1294 Fix client-go libraries bug
  apis/kueue/v1beta1/admissioncheck_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/workloadpriorityclass_types.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheck.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueue.go
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestconfig.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavor.go
  client-go/applyconfiguration/kueue/v1beta1/workloadpriorityclass.go
  client-go/clientset/versioned/typed/kueue/v1beta1/admissioncheck.go
  client-go/clientset/versioned/typed/kueue/v1beta1/clusterqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_admissioncheck.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_clusterqueue.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_provisioningrequestconfig.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_resourceflavor.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_workloadpriorityclass.go
  client-go/clientset/versioned/typed/kueue/v1beta1/kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/provisioningrequestconfig.go
  client-go/clientset/versioned/typed/kueue/v1beta1/resourceflavor.go
  client-go/clientset/versioned/typed/kueue/v1beta1/workloadpriorityclass.go
  client-go/informers/externalversions/kueue/v1beta1/admissioncheck.go
  client-go/informers/externalversions/kueue/v1beta1/clusterqueue.go
  client-go/informers/externalversions/kueue/v1beta1/interface.go
  client-go/informers/externalversions/kueue/v1beta1/provisioningrequestconfig.go
  client-go/informers/externalversions/kueue/v1beta1/resourceflavor.go
  client-go/informers/externalversions/kueue/v1beta1/workloadpriorityclass.go
  client-go/listers/kueue/v1beta1/admissioncheck.go
  client-go/listers/kueue/v1beta1/clusterqueue.go
  client-go/listers/kueue/v1beta1/expansion_generated.go
  client-go/listers/kueue/v1beta1/provisioningrequestconfig.go
  client-go/listers/kueue/v1beta1/resourceflavor.go
  client-go/listers/kueue/v1beta1/workloadpriorityclass.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1287 add shopee in adopters
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1285 Update reviewers and approvers
  OWNERS
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1295 Update `genref` version
  Makefile
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1223 Update workload when job changes before admission
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/webhook/workload_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes
