Repository kubernetes-sigs/kueue, pull requests merged in 2023-07, with the labels that each got.

#878 Allow specifiying pod and container security context
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#938 [dep] Use kuberay v0.5.2
  go.mod
  go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#945 [Integration test] Replace deprecated manager Options with new ones
  test/integration/framework/framework.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#944 Add adopters to the site
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#952 [test/integration] Fix scheduler reclaim flaky test
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#953 [e2e] Use kind 0.18
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#862 Added docs on how to integrate JobSet
  site/content/en/docs/tasks/run_jobsets.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#949 Simplify tests setup
  main.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/context.go
  pkg/util/testingjobs/job/wrappers.go
  test/e2e/e2e_test.go
  test/integration/controller/job/suite_test.go
  test/integration/controller/jobset/suite_test.go
  test/integration/controller/mpijob/suite_test.go
  test/integration/controller/rayjob/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#915 Changed logic of pods ready cond
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#950 add python examples folder
  examples/python/README.md
  examples/python/install-kueue-queues.py
  examples/python/requirements.txt
  examples/python/sample-job.py
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_python_jobs.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#934 Check job counts equal admission counts when unsuspended
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testing/client.go
Labels: size/L, lgtm, tide/merge-method-squash, release-note-none, approved, kind/cleanup, cncf-cla: yes

#954 [site] Document partial admission and feature gate usage.
  examples/sample-job-partial-admission.yaml
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/run_jobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#956 [artifacts] Add helm package
  Makefile
  charts/kueue/values.yaml
  config/components/manager/kustomization.yaml
Labels: kind/feature, lgtm, tide/merge-method-squash, release-note-none, approved, size/M, cncf-cla: yes

#958 Change `main` references to `release-0.4`
  Makefile
  README.md
  config/components/manager/kustomization.yaml
  hack/e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#959 Update for release 0.4
  examples/ray-job-sample.yaml
  examples/sample-job-partial-admission.yaml
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_jobs.md
  site/content/en/docs/tasks/run_jobsets.md
  site/content/en/docs/tasks/run_rayjobs.md
Labels: lgtm, release-note-none, size/XL, approved, kind/documentation, cncf-cla: yes

#960 Update docs to v0.4.0 in main branch
  README.md
  site/config.toml
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#964 [makefile] Use local yq and helm
  Makefile
  hack/update-helm.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#969 add include shortcode for adding file
  examples
  site/content/en/docs/tasks/run_python_jobs.md
  site/layouts/shortcodes/include.html
  site/static/examples/python/README.md
  site/static/examples/python/install-kueue-queues.py
  site/static/examples/python/requirements.txt
  site/static/examples/python/sample-job.py
  site/static/examples/ray-job-sample.yaml
  site/static/examples/sample-job-partial-admission.yaml
  site/static/examples/sample-job.yaml
  site/static/examples/sample-mpijob.yaml
  site/static/examples/single-clusterqueue-setup.yaml
Labels: size/L, lgtm, tide/merge-method-squash, release-note-none, approved, kind/documentation, cncf-cla: yes

#978 Added pprof endpoint
  apis/config/v1beta1/configuration_types.go
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#967 add simple queue control example to python docs
  site/content/en/docs/tasks/run_python_jobs.md
  site/static/examples/python/install-kueue-queues.py
  site/static/examples/python/sample-queue-control.py
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#981 Update administer_cluster_quotas.md
  site/content/en/docs/tasks/administer_cluster_quotas.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#986 feat: expose probe
  charts/kueue/README.md
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#996 [rbac] Add jobset roles
  charts/kueue/templates/rbac/jobset_editor_role.yaml
  charts/kueue/templates/rbac/jobset_viewer_role.yaml
  config/components/rbac/jobset_editor_role.yaml
  config/components/rbac/jobset_viewer_role.yaml
  config/components/rbac/kustomization.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#962 add flux operator python sdk example
  site/content/en/docs/tasks/run_flux_minicluster.md
  site/content/en/docs/tasks/run_python_jobs.md
  site/static/examples/python/sample-flux-operator-job.py
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1000 fix typo with reference to flux operator
  site/static/examples/python/sample-flux-operator-job.py
Labels: lgtm, release-note-none, approved, needs-ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#984 [site] Add cluster queue resource metrics
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/metrics.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#966 added WattIQ to adopters list
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#971 [batch/job] Partial admission - sync completions
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/util/testingjobs/job/wrappers.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1003 [site] Added pprof doc
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/enabling_pprof_endpoints.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#1006 Add helm installation instructions to website
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#1017 Changed helm installation link
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1008 add example MPI operator job
  site/content/en/docs/tasks/run_mpi_jobs.md
  site/content/en/docs/tasks/run_python_jobs.md
  site/static/examples/python/sample-mpijob.py
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1018 Fix flaky test issue
  test/integration/controller/core/localqueue_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1005 Always try to stop a job on eviction
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/util/testingjobs/job/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1024 Consider priority across ClusterQueues in a cohort
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#1025 Fix Flaky test: Kueue when Creating a Job With Queueing [It] Should unsuspend a job and set nodeSelectors
  test/e2e/e2e_test.go
  test/util/constants.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1023 Avoid changing snapshot in preemption
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes
