Repository kubernetes-sigs/kueue, pull requests merged in 2023-02, with the labels that each got.

#540 Updated workload Inadmissible message when LocalQueue does not exist
  pkg/controller/core/workload_controller.go
  test/integration/controller/core/workload_controller_test.go
Labels: lgtm, tide/merge-method-squash, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#547 Add default namespace to job in /samples
  config/samples/sample-job.yaml
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#551 Use errors.Is to check for a specific error
  pkg/queue/manager_test.go
  pkg/util/routine/error_channel_test.go
Labels: lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#552 Clean up unnecessary whitespace and convert
  apis/kueue/webhooks/workload_webhook.go
  pkg/cache/cache.go
  pkg/controller/core/workload_controller.go
  pkg/controller/workload/job/job_controller.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/manager.go
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#554 Makefile: set GO-VERSION as image version tag
  Makefile
Labels: lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#538 Refactor TestSnapshot
  pkg/cache/snapshot_test.go
Labels: lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#557 update netlify publish directory
  netlify.toml
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#549 Add integration tests for job controller
  test/integration/controller/job/job_controller_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#548 First pass - Documentation improvement
  config/samples/sample-job.yaml
  config/samples/single-clusterqueue-setup.yaml
  docs/concepts/README.md
  docs/concepts/cluster_queue.md
  docs/concepts/local_queue.md
  docs/concepts/resource_flavor.md
  docs/concepts/workload.md
  docs/tasks/README.md
  docs/tasks/administer_cluster_quotas.md
  docs/tasks/run_jobs.md
  docs/tasks/setup_rbac.md
  docs/tasks/setup_sequential_admission.md
Labels: size/L, lgtm, tide/merge-method-squash, approved, ok-to-test, kind/documentation, cncf-cla: yes

#565 Fix: add permission to watch RuntimeClass
  config/components/rbac/role.yaml
  pkg/controller/core/workload_controller.go
Labels: kind/bug, lgtm, approved, size/XS, cncf-cla: yes

#566 Increase and match requests and limits for manager
  config/components/manager/manager.yaml
Labels: lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#567 landing page updates
  site/assets/scss/_styles_project.scss
  site/config.toml
  site/content/en/_index.html
Labels: lgtm, tide/merge-method-squash, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#568 fix max width for only text content
  site/assets/scss/_styles_project.scss
Labels: kind/bug, lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#570 Validate queue-name annotation is a valid crd name
  pkg/controller/workload/job/job_webhook.go
  pkg/controller/workload/job/job_webhook_test.go
Labels: lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#572 remove list from concepts and tasks root page
  site/config.toml
  site/content/en/docs/_index.md
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/tasks/_index.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#438 Add roadmap to kueue
  README.md
Labels: lgtm, tide/merge-method-squash, approved, cncf-cla: yes, size/S

#537 [KEP]Add job interface for integration
  keps/369-job-interface/README.md
  keps/369-job-interface/kep.yaml
Labels: kind/feature, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#575 Update documentation links
  CHANGELOG/CHANGELOG-0.2.md
  README.md
Labels: lgtm, approved, size/M, kind/documentation, cncf-cla: yes

#581 Fix the broken link in the doc site
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/administer_cluster_quotas.md
  site/content/en/docs/tasks/task.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#583 Fix a typo on the website
  site/content/en/docs/installation/_index.md
Labels: lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#588 Add indexer to fakeCilent when bumping k8s.io deps to v0.26.1
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/constants/constants.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/indexer/indexer.go
  pkg/util/testing/client.go
  pkg/workload/workload_test.go
Labels: lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#592 Consolidate indexes in a single package
  main.go
  pkg/cache/cache.go
  pkg/controller/core/indexer/indexer.go
  pkg/queue/manager.go
  pkg/util/indexer/indexer.go
  pkg/util/testing/client.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/job/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/v1alpha2/suite_test.go
Labels: size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#594 fix url to run jobs
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_jobs.md
Labels: lgtm, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes
