Repository kubernetes-sigs/kueue, pull requests merged in 2024-06, with the labels that each got.

#2345 Log Kueue's feature gates at the start-up
  cmd/kueue/main.go
  pkg/features/kube_features.go
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#2279 document that enabling manageJobsWithoutQueueName can be risky
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#2343 Add myself as approver for `<kueue>/cmd`
  cmd/OWNERS
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2336 Update latest release to v0.7.0
  CHANGELOG/CHANGELOG-0.7.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2347 [multikueue] Remove remote objects synchronously when reachable.
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/util/maps/maps.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2318 Simplify the user-facing documentation for JobSet in MultiKueue
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/manage/setup_multikueue.md
  site/content/en/docs/tasks/run/jobsets.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2334 Declare the versions of tools allowing for updates by dependabot
  Makefile-deps.mk
  go.mod
  go.sum
  hack/internal/tools/pinversion.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2351 Self-nominate mimowo as top-level approver
  OWNERS
  hack/OWNERS
  pkg/OWNERS
  test/OWNERS
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2314 [kueuectl] Support autocompletion on kueue CLI commands
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/completion/completion.go
  cmd/kueuectl/app/completion/completion_test.go
  cmd/kueuectl/app/create/create_localqueue.go
  cmd/kueuectl/app/list/list_clusterqueue_test.go
  cmd/kueuectl/app/list/list_localqueue.go
  cmd/kueuectl/app/list/list_localqueue_test.go
  cmd/kueuectl/app/list/list_test.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/list/list_workload_test.go
  cmd/kueuectl/app/resume/resume_clusterqueue.go
  cmd/kueuectl/app/resume/resume_workload.go
  cmd/kueuectl/app/stop/stop_clusterqueue.go
  cmd/kueuectl/app/stop/stop_workload.go
  cmd/kueuectl/app/testing/fake.go
  cmd/kueuectl/app/util/client_getter.go
  site/content/en/docs/reference/kubectl-kueue/installation.md
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2352 🌱 docs: Add correct trademark disclaimer
  site/hugo.toml
  site/layouts/partials/footer.html
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2355 [multikueue] Ignore the `IsManaged` result during sync remote objects deletion.
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2354 Make test "should print workloads list with paging" less likely to fail
  test/integration/kueuectl/list_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2331 [multikueue] Use batch/Job `spec.managedBy` field.
  Makefile-test.mk
  hack/multikueue-e2e-test.sh
  hack/multikueue/manager-cluster.kind-1.30.0.yaml
  pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/features/kube_features.go
  pkg/util/testingjobs/job/wrappers.go
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/installation/_index.md
  test/e2e/config/manager_e2e_patch.yaml
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/framework/framework.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2366 Update dependabot to track package updates for internal tools.
  .github/dependabot.yml
  Makefile-deps.mk
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2368 [manual] Bump sigs.k8s.io/controller-tools from 0.14.0 to 0.15.0 in /hack/internal/tools
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2317 Setup the controller-runtime logger in e2e tests.
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/integration/framework/framework.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2369 MultiKueue skip garbage collection for disconnected clients.
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#2362 Wait for Requeue condition before push to heap.
  pkg/queue/cluster_queue.go
  pkg/queue/cluster_queue_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2372 Throw an error when config contains unknown fields
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2196 Provide support for ProvisioningRequest's CapacityRevoked condition
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/provisioning.go
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/kueuectl/resume_test.go
  test/integration/kueuectl/stop_test.go
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2375 [tools] Fix the name of the module from which the helm version comes.
  Makefile-deps.mk
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2378 Add myself as approver for `<kueue>/test`
  test/OWNERS
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2364 Use the fake time instead of real in tests
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/list/list.go
  cmd/kueuectl/app/list/list_clusterqueue.go
  cmd/kueuectl/app/list/list_clusterqueue_printer.go
  cmd/kueuectl/app/list/list_clusterqueue_test.go
  cmd/kueuectl/app/list/list_localqueue.go
  cmd/kueuectl/app/list/list_localqueue_printer.go
  cmd/kueuectl/app/list/list_localqueue_printer_test.go
  cmd/kueuectl/app/list/list_localqueue_test.go
  cmd/kueuectl/app/list/list_test.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/list/list_workload_printer.go
  cmd/kueuectl/app/list/list_workload_test.go
  test/integration/kueuectl/create_test.go
  test/integration/kueuectl/list_test.go
  test/integration/kueuectl/resume_test.go
  test/integration/kueuectl/stop_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2379 fix typo in comment
  charts/kueue/values.yaml
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2383 docs(site): Fix typo in sequential admission docs
  site/content/en/docs/tasks/manage/setup_sequential_admission.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2307 Kjobctl bootstrap
  Makefile
  cmd/experimental/kjobctl/.gitignore
  cmd/experimental/kjobctl/.golangci.yaml
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/PROJECT
  cmd/experimental/kjobctl/README.md
  cmd/experimental/kjobctl/apis/v1alpha1/doc.go
  cmd/experimental/kjobctl/apis/v1alpha1/groupversion_info.go
  cmd/experimental/kjobctl/apis/v1alpha1/volumebundle_types.go
  cmd/experimental/kjobctl/apis/v1alpha1/zz_generated.deepcopy.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/clientset.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/fake/clientset_generated.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/fake/doc.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/fake/register.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/scheme/doc.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/scheme/register.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/doc.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/fake/doc.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/fake/fake_apis_client.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/fake/fake_volumebundle.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/generated_expansion.go
  cmd/experimental/kjobctl/client-go/clientset/versioned/typed/apis/v1alpha1/volumebundle.go
  cmd/experimental/kjobctl/cmd/main.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  cmd/experimental/kjobctl/config/crd/kustomization.yaml
  cmd/experimental/kjobctl/config/default/kustomization.yaml
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/boilerplate.go.txt
  cmd/experimental/kjobctl/hack/tools/pinversion.go
  cmd/experimental/kjobctl/hack/update-codegen.sh
  cmd/experimental/kjobctl/pkg/cmd/cmd.go
  cmd/experimental/kjobctl/pkg/cmd/testing/fake.go
  cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
  cmd/experimental/kjobctl/pkg/cmd/util/dry_run.go
  cmd/experimental/kjobctl/pkg/cmd/util/helpers.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2173 Allow stoping admission from a specific LocalQueue.
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/constants.go
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/localqueuespec.go
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/localqueue_controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/core/workload_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#2392 Use clock instead time on workload controller.
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#2346 [kueuectl] Add version command
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/testing/fake.go
  cmd/kueuectl/app/version/version.go
  cmd/kueuectl/app/version/version_test.go
  site/content/en/docs/reference/kubectl-kueue/commands/version.md
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2380 [multikueue] Batch remote workload reconcile events.
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#2397 [kueuectl] Remove duplication of list commands.
  cmd/kueuectl/app/cmd.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2376 Add event for eviction on the workload.
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/workload/workload.go
Labels: kind/bug, size/L, lgtm, release-note-action-required, approved, cncf-cla: yes

#2395 [kueuectl] Fix "should print workloads list with paging" test
  test/integration/kueuectl/list_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2399 [kueuectl] Fix "Should print cluster queues list with paging" test.
  test/integration/kueuectl/list_test.go
Labels: lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#2238 [kueuectl] Add `for` filter to list workloads
  cmd/kueuectl/app/list/helpers.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/list/list_workload_test.go
  cmd/kueuectl/app/testing/fake.go
  cmd/kueuectl/app/util/client_getter.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2381 [multikueue] Add a no GC integration tests suite.
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#2363 Deactivate Workload if any of its AdmissionCheck get Rejected
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/scheduler.go
  pkg/util/testing/core.go
  pkg/workload/admissionchecks.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/workload_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2201 Add create clusterqueue command
  cmd/kueuectl/app/create/create.go
  cmd/kueuectl/app/create/create_clusterqueue.go
  cmd/kueuectl/app/create/create_clusterqueue_test.go
  keps/2076-kueuectl/README.md
  site/content/en/docs/reference/kubectl-kueue/commands/create.md
  test/integration/kueuectl/create_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#2406 Fix flaky jobset integration test
  test/integration/controller/jobs/jobset/jobset_controller_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2425 JobSet default managed by
  apis/kueue/v1alpha1/multikueue_types.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/queue/manager.go
  pkg/visibility/api/rest/pending_workloads_lq.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#2377 Add helm chart repository
  Makefile
  cloudbuild.yaml
  hack/push-chart.sh
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2412 [kjobctl] Added autocompletion.
  cmd/experimental/kjobctl/README.md
  cmd/experimental/kjobctl/pkg/cmd/cmd.go
  cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2430 [kueuectl] Move "List workload" test to Describe.
  test/integration/kueuectl/list_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2424 Initialise FairSharing option when building options for cache.
  cmd/kueue/main.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2433 [multikueue] Use the API controller name.
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
  pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
  pkg/controller/admissionchecks/multikueue/indexer.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  test/integration/multikueue/multikueue_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2435 Clean up provisioning integration tests
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2407 [fix] update assignedFlavorIdx at the beginning of loop
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#2373 [multikueue] Make the MultiKueue adapter part of the jobframework
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go
  pkg/util/api/api.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2442 [release-0.7] [MultiKueue] Do not reject JobSet when ClusterQueue does not exist
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/queue/manager.go
  pkg/visibility/api/rest/pending_workloads_lq.go
Labels: release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#2444 [kjobctl] Move dev dependencies to tools.
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/hack/tools/pinversion.go
  cmd/experimental/kjobctl/hack/update-codegen.sh
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2408 Improve AdmissionCheck documentation
  apis/kueue/v1beta1/admissioncheck_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  site/content/en/docs/concepts/admission_check.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2436 [multikueue] KEP add subcomponents and integration details.
  keps/693-multikueue/README.md
  keps/693-multikueue/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2439 Fix panic when not enough quota on FairSharing enabled.
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2450 Update dependabot to track package updates for kjobctl.
  .github/dependabot.yml
Labels: kind/feature, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2400 [kjobctl] Add volume API
  cmd/experimental/kjobctl/apis/v1alpha1/volumebundle_types.go
  cmd/experimental/kjobctl/apis/v1alpha1/zz_generated.deepcopy.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  cmd/experimental/kjobctl/go.mod
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2434 Create e2e test suite for fair sharing.
  test/e2e/config/controller_manager_config.yaml
  test/e2e/singlecluster/fair_sharing_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2455 [kueuectl] Clearing cluster queues after each creation on "Creating a ClusterQueue" tests.
  test/integration/kueuectl/create_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2461 Fix panic on update cluster queue status if cluster queue not found on queue manager.
  pkg/cache/cache.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/queue/manager.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2460 Fix race condition on delete workload from queue manager.
  pkg/queue/cluster_queue.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2457 Add link to ClusterAutoscaler ProvisioningRequest FAQ
  site/content/en/docs/admission-check-controllers/provisioning.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2448 Define FlavorResource, FlavorResourceQuantitiesFlat
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/resources/resource.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2456 Wait for jobset operator on starting e2e tests.
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#2443 Add sbom section to the security insights file
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  SECURITY-INSIGHTS.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2466 Automated cherry pick of #2456: Wait for jobset operator on starting e2e tests.
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2467 No need to wait for availability if controller manager restarts.
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2462 [cmd/kueue] Use a single rate limiter across all API types.
  cmd/kueue/main.go
Labels: kind/feature, lgtm, release-note-action-required, approved, size/XS, cncf-cla: yes

#2472 Set `AS` to uppercase in Dockerfile to avoid FromAsCasing warning.
  Dockerfile
  cmd/experimental/podtaintstolerations/Dockerfile
  cmd/importer/Dockerfile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2471 Fix race condition when setting MaxRetries on provisioning controller.
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/provisioning.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2394 [kjobctl] Add job builder.
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/builder_test.go
  cmd/experimental/kjobctl/pkg/builder/job_builder.go
  cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
  cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
  cmd/experimental/kjobctl/pkg/constants/constants.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2477 Remove dependency of apis/ on pkg/
  apis/visibility/v1alpha1/conversion_test.go
  apis/visibility/v1alpha1/defaults.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#2409 Add a new DeactivationTarget workload condition.
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/workload/workload.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2485 Fix lint issue reported by fatcontext
  .golangci.yaml
  pkg/controller/core/workload_controller.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2490 Fix flaky integration test for ProvisioningRequest
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2492 Fix nested context in loop
  pkg/controller/core/workload_controller.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2484 [kjobctl] Added create job command.
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/apis/v1alpha1/volumebundle_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  cmd/experimental/kjobctl/config/samples/application_profile.yaml
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/hack/tools/pinversion.go
  cmd/experimental/kjobctl/pkg/cmd/cmd.go
  cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/cmd/testing/fake.go
  cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/application_profile_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/container_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/supported_mode_wrappers.go
  cmd/experimental/kjobctl/test/framework/framework.go
  cmd/experimental/kjobctl/test/integration/kjobctl/create_test.go
  cmd/experimental/kjobctl/test/integration/kjobctl/suite_test.go
  cmd/experimental/kjobctl/test/integration/kjobctl/util.go
  cmd/experimental/kjobctl/test/util/util.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2478 Document RBAC augmentation for external frameworks
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#1791 fix build error in pod taints tolerations example
  cmd/experimental/podtaintstolerations/controller/pod_jobs.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#2410 Fix shellcheck not working
  .shellcheckrc
  hack/verify-shellcheck.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2488 [doc] typo fixes on keps
  keps/1432-admission-check-per-resource-flavor/README.md
  keps/1714-fair-sharing/README.md
  keps/2076-kueuectl/README.md
  keps/582-preempt-based-on-flavor-order/README.md
  keps/77-dynamically-sized-jobs/README.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#2495 Update golang version (1.22.3 -> 1.22.4)
  go.mod
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2494 Remove kjobctl verification from main Makefile.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2498 [PodSetInfo] Skip duplicate Tolerations during merge.
  pkg/podset/podset.go
  pkg/podset/podset_test.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2487 Refactor funcs to accept a Context as first parameter
  .golangci.yaml
  cmd/kueue/main.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/visibility/server.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/jobset/suite_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/mxjob/suite_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/framework/framework.go
  test/integration/importer/suite_test.go
  test/integration/kueuectl/suite_test.go
  test/integration/multikueue/suite_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2500 [importer] fix typo in log field name
  cmd/importer/pod/check.go
  cmd/importer/pod/import.go
Labels: release-note, lgtm, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes
