Repository kubernetes-sigs/kueue, pull requests merged in 2024-02, with the labels that each got.

#1675 Dependabot can update kubernetes dependencies as a group
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1640 [multikueue] Add Path kubeConfig location type
  apis/kueue/v1alpha1/multikueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  keps/693-multikueue/README.md
  pkg/controller/admissionchecks/multikueue/indexer_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/testdata/worker1KubeConfig
  pkg/util/testing/wrappers.go
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1678 [website] Updated RayJob Documentation
  site/content/en/docs/tasks/run_rayjobs.md
Labels: release-note, lgtm, approved, needs-ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1676 Fix Kueue startup by waiting for webhooks server using probes
  cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
  cmd/kueue/main.go
  hack/e2e-common.sh
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1682 Automated cherry pick of #1676: Wait for webhooks server using probes
  cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
  cmd/kueue/main.go
  hack/e2e-test.sh
  test/e2e/suite_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#1679 Remove deleted pending workloads from the cache so the visibility API results are correct
  pkg/controller/core/workload_controller.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#1667 Fix emitting events for pods preempted by Kueue [pod groups]
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testing/client.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1687 Automated cherry pick of #1679: Make sure pending workloads are removed from the cache
  pkg/controller/core/workload_controller.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#1683 Ensure all group members own the workload [pod groups]
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testing/wrappers.go
  test/e2e/singlecluster/pod_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, needs-rebase, cncf-cla: yes

#1691 Cleanup unit test for events
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testing/client.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1668 [multikueue] Job live status update
  pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/util/testingjobs/jobset/wrappers.go
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1694 Cleanup OwnerReference helper functions for tests
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/setup_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testing/wrappers.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1690 Emit event when excess pods are deleted by Kueue [pod groups]
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  test/e2e/singlecluster/pod_test.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1608 KEP: Add an exponential backoff mechanism to the requeueing strategy
  keps/1282-pods-ready-requeue-strategy/README.md
  keps/1282-pods-ready-requeue-strategy/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1689 [cache] Don't assign finished workloads to newly add CQs.
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1698 Remove .spec.volumes from role hash for pods
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#1688 [website] Custom Jobs integrations documentation cleanup
  site/content/en/docs/tasks/run_jobsets.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_mxjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_paddlejobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
  site/content/en/docs/tasks/run_kubeflow_jobs/run_xgboostjobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, kind/documentation, cncf-cla: yes

#1666 [Site] Update provisioning admission check controller public doc with supported CA version
  site/content/en/docs/admission-check-controllers/provisioning.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1701 Give more flexibility to requeueing parameters in the config api
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  cmd/kueue/main.go
  keps/1282-pods-ready-requeue-strategy/README.md
  pkg/config/config_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/scheduler/podsready/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, kind/api-change, cncf-cla: yes

#1671 [multikueue] Retry on remote wl creation failure
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1707 [kueue] Check certificates readiness before the webhook server.
  cmd/kueue/main.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1708 fix: typo in, "Why Kueue?"
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1684 Extend documentation on pod group support [pod groups]
  site/content/en/docs/tasks/run_plain_pods.md
  site/static/examples/pods-kueue/kueue-pod-group.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1706 Improve event message when workload creation fails [pod groups]
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1710 E2e extend startup interval
  hack/e2e-common.sh
  hack/multikueue/manager-cluster.kind.yaml
  hack/multikueue/worker-cluster.kind.yaml
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/constants.go
  test/util/e2e.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#1531 KEP-79: Hierarchical Cohorts
  keps/79-hierarchical-cohorts/README.md
  keps/79-hierarchical-cohorts/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, kind/api-change, cncf-cla: yes

#1712 Prepare for release v0.5.3
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1716 Update latest release v0.5.3
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1717 Update latest release v0.5.3
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1720 Manage controller-gen via go.mod
  Makefile
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  apis/visibility/v1alpha1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
  hack/internal/tools/pinversion.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1723 Avoid reconciles without any meaningful changes when the workload controller checks PodsReadyTimeout
  pkg/controller/core/workload_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1709 Implement backoff re-queuing mechanism
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  charts/kueue/templates/webhook/webhook.yaml
  client-go/applyconfiguration/kueue/v1beta1/requeuestate.go
  client-go/applyconfiguration/kueue/v1beta1/workloadstatus.go
  client-go/applyconfiguration/utils.go
  cmd/kueue/main.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  config/components/webhook/manifests.yaml
  keps/1282-pods-ready-requeue-strategy/README.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/constants/constants.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/webhook/workload_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, kind/api-change, cncf-cla: yes

#1728 Remove stubs from clusterQueueBase
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/manager_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1730 Add make rule to prepare branch for release
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
  charts/kueue/Chart.yaml
  charts/kueue/values.yaml
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1727 Doc: Add PodsReadyRequeueStrategy documentation
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/tasks/setup_sequential_admission.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1733 Prepare release notes and files for v0.6.0
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  config/components/manager/kustomization.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1734 Fix filename for openvex artifact
  .github/workflows/openvex.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1736 Update latest release to v0.6.0
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/config.toml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1705 [doc] MultiKueue
  site/content/en/docs/admission-check-controllers/multikueue.md
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/genref/config.yaml
  site/static/examples/multikueue/multikueue-setup.yaml
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1718 Refactor flavorassigner to reduce number of passed arguments
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1739 Bump go.etcd.io/etcd/v3@v3.5.10 to v3.5.11 to remove CVE
  go.mod
  go.sum
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1743 Use maps.Clone when snapshotting
  pkg/cache/snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1721 Test that pods are observed when there are error during the cleanup
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1744 Admisssion to Admission doc typo
  site/content/en/docs/admission-check-controllers/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1756 Typo fixes on all /site docs
  site/content/en/docs/admission-check-controllers/provisioning.md
  site/content/en/docs/adopters/index.md
  site/content/en/docs/concepts/admission_check.md
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_on_demand.md
  site/content/en/docs/tasks/run_rayclusters.md
  site/static/examples/python/README.md
Labels: lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#1748 Typo fixes on all docs and on 'AssignmentClusterQueueState' type
  .openvex/templates/README.md
  CHANGELOG/CHANGELOG-0.3.md
  CONTRIBUTING.md
  keps/168-2-pending-workloads-visibility/README.md
  keps/168-pending-workloads-visibility/README.md
  keps/487-kubectl-plugin/README.md
  keps/582-preempt-based-on-flavor-order/README.md
  keps/693-multikueue/README.md
  keps/78-dynamically-reclaiming-resources/README.md
  keps/79-hierarchical-cohorts/README.md
  keps/83-workload-preemption/README.md
  keps/976-plain-pods/README.md
  keps/993-two-phase-admission/README.md
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1747 Drop `kueue.x-k8s.io/parent-workload` in favor of a object ownership based approach.
  pkg/controller/constants/constants.go
  pkg/controller/core/indexer/indexer.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobframework/workload_names.go
  pkg/controller/jobframework/workload_names_test.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/util/testing/client.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
Labels: release-note, lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#1751 [Doc]Add documents for feature LendingLimit
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1758 Exclude labels, image, preemptionPolicy from pod role hash calculation
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1760 Automated cherry pick of #1723: Exclude labels, image, preemptionPolicy from pod role hash calculation
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#1746 Don't deploy visibility by default
  charts/kueue/templates/_helpers.tpl
  charts/kueue/templates/visibility/apiservice.yaml
  charts/kueue/templates/visibility/role_binding.yaml
  charts/kueue/templates/visibility/service.yaml
  config/alpha-enabled/kustomization.yaml
  config/default/kustomization.yaml
  config/visibility/kustomization.yaml
  hack/update-helm.sh
  test/e2e/config/kustomization.yaml
  test/e2e/config_1_26/kustomization.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1732 [jobframework] Use the jobs uid in workload's name hash.
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/workload_names.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/multikueue/multikueue_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#1763 [AC] Update description for "Retry" and "Rejected" states.
  apis/kueue/v1beta1/admissioncheck_types.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1761 Parallelize integration tests
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1767 chore: typo in RegisterIntegration comment
  pkg/controller/jobframework/integrationmanager.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1765 Remove check for CapacityAvailable ProvReq condition
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1774 Fix duplicated imports reported by gocritic linter
  .golangci.yaml
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  test/e2e/singlecluster/pod_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1778 Remove unnecessary nil check
  pkg/cache/cache.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1779 [e2e/multikue] Use a custom service account and role
  hack/create-multikueue-kubeconfig.sh
  hack/multikueue-e2e-test.sh
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1780 Simplify tests by using T.TempDir
  cmd/kueue/main_test.go
  pkg/config/config_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S
