Repository kubernetes-sigs/kueue, pull requests merged in 2024-11, with the labels that each got.

#3411 Fix "Should admit a JobSet via TAS" test.
  test/e2e/singlecluster/tas_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3408 [release-0.8][KubeRay] Support NumOfHosts when calculating PodSet assignments (#3386)
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/util/testingjobs/raycluster/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3412 Remove WithName("mxjob-webhook") on BaseWebhook.
  pkg/controller/jobframework/base_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3417 [kjobctl] Update run_slurm.md docs.
  cmd/experimental/kjobctl/docs/run_slurm.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3410 TAS: Add integration tests for JobSet.
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/jobset/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3416 [kjobctl] Add short flag -J for --job-name on slurm mode.
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3398 Replace direct modification of cohort resources in flavorassigner_test
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#3420 Optimize pod managerSetup.
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3308 [doc] Maximum execution time
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/reference/labels-and-annotations.md
Labels: release-note, lgtm, approved, kind/documentation, cncf-cla: yes, size/S

#3409 TAS: Enable for Pod integration.
  apis/kueue/v1alpha1/tas_types.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/e2e/singlecluster/tas_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3431 Bump sigs.k8s.io/controller-tools from 0.16.4 to 0.16.5 in /cmd/experimental/kjobctl/hack/tools
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_jobtemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayclustertemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayjobtemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3418 [kjobctl] Add validation for priority required field.
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/builder_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#3433 Prepare release v0.8.2
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3434 Update latest version to v0.8.2
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3403 TAS: Support MPIJob.
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3436 Add IBM Research to Kueue adoptors page
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3440 fix typo in FromPodSet comment
  pkg/podset/podset.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3442 Prepare v0.8.3
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3432 TAS: Add documentation page for concepts
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/topology_aware_scheduling.md
  site/static/examples/tas/sample-job-preferred.yaml
  site/static/examples/tas/sample-queues.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3443 Updat artifact publishing step in the Release steps
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3438 Use testGenericJob on BaseWebhook tests.
  pkg/controller/jobframework/base_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3446 Doc: Mention about the ProvisioningRequest on the kueue.x-k8s.io/managed label
  site/content/en/docs/reference/labels-and-annotations.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3447 Fix "Should requeue a workload which exceeded the timeout to reach PodsReady=True" test.
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3444 Update latest version to v0.8.3
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3452 Add missed defer cancel().
  pkg/cache/cache_test.go
  pkg/queue/manager_test.go
  pkg/util/wait/backoff_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3445 TAS: Improve messages why workload cannot fit
  pkg/cache/cache_test.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/tas/resource_flavor.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3451 [kjobctl] Use t.Cleanup to remove test script file.
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3414 TAS: Support Kubeflow.
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/util/testingjobs/mxjob/wrappers.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/mxjob/suite_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/webhook/jobs/mxjob_webhook_test.go
  test/integration/webhook/jobs/paddlejob_webhook_test.go
  test/integration/webhook/jobs/pytorchjob_webhook_test.go
  test/integration/webhook/jobs/suite_test.go
  test/integration/webhook/jobs/tfjob_webhook_test.go
  test/integration/webhook/jobs/xgboostjob_webhook_test.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#3375 Introduce RetryStrategy API to ProvisioningRequestConfig
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestconfigspec.go
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestretrystrategy.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  keps/1136-provisioning-request-support/README.md
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/features/kube_features.go
  pkg/queue/cluster_queue.go
  pkg/workload/workload.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/static/examples/provisioning/provisioning-setup.yaml
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#3449 Update Job-integrated features table.
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3458 Prepare release v0.9.0
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  config/components/manager/kustomization.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3456 Self-nominate pbundyra as a Kueue reviewer
  OWNERS
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3462 Fix readme repo and tag for manager image
  charts/kueue/README.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3460 Rename JobWithValidation to JobWithCustomValidation.
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3465 [kjobctl] Bump Kueue version.
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3457 Make error matcher more verbosity.
  pkg/util/testing/error_matchers.go
  test/integration/webhook/core/admissioncheck_test.go
  test/integration/webhook/core/clusterqueue_test.go
  test/integration/webhook/core/cohort_test.go
  test/integration/webhook/core/localqueue_test.go
  test/integration/webhook/core/resourceflavor_test.go
  test/integration/webhook/core/workload_test.go
  test/integration/webhook/jobs/job_webhook_test.go
  test/integration/webhook/jobs/jobset_webhook_test.go
  test/integration/webhook/jobs/mpijob_webhook_test.go
  test/integration/webhook/jobs/raycluster_webhook_test.go
  test/integration/webhook/jobs/rayjob_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3461 Update latest kueue v0.9.0
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3467 update multikueue setup examples to v1beta1 api
  site/static/examples/multikueue/multikueue-setup.yaml
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3459 TAS: Use redundand specs flag for kubeflow integrations.
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/framework/framework.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3421 [fix]: refactor code to replace time.Now() with Now() in clock package in pkg/scheduler(#3380)
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3470 Delete redundant retry logic in MultiKueue controller.
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3479 Fix MK integration test helper function
  test/integration/multikueue/multikueue_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3477 Reduce number of API requests in the Provisioning Controller
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3483 Remove duplication of Named() function.
  pkg/controller/jobs/pod/pod_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3478 [cleanup]: refactor code to show the use of fakeClock explicitly in pkg/queue(#3380)
  pkg/queue/cluster_queue_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3454 [MultiKueue] Document batch/Job managedBy field usage
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/run/multikueue/job.md
  site/content/en/docs/tasks/run/multikueue/jobsets.md
  site/content/en/docs/tasks/run/multikueue/kubeflow.md
  site/content/en/docs/tasks/run/multikueue/mpijob.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3484 Revert "[cleanup]: refactor code to show the use of fakeClock explicitly in pkg/queue(#3380)"
  pkg/queue/cluster_queue_test.go
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#3509 Use TopologyReference instead of string.
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/tas/resource_flavor.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3507 Update MultiKueue feature state.
  site/content/en/docs/concepts/multikueue.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3498 Replace time.Now() with clock.Now() in pkg/workload
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/core/workload_controller.go
  pkg/scheduler/preemption/preemption.go
  pkg/workload/admissionchecks.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3499 Remove v1alpha1 visibility API
  apis/visibility/openapi/zz_generated.openapi.go
  apis/visibility/v1alpha1/conversion_test.go
  apis/visibility/v1alpha1/defaults.go
  apis/visibility/v1alpha1/doc.go
  apis/visibility/v1alpha1/groupversion_info.go
  apis/visibility/v1alpha1/types.go
  apis/visibility/v1alpha1/zz_generated.conversion.go
  apis/visibility/v1alpha1/zz_generated.deepcopy.go
  apis/visibility/v1alpha1/zz_generated.defaults.go
  charts/kueue/templates/visibility/apiservice_v1alpha1.yaml
  client-go/applyconfiguration/utils.go
  client-go/applyconfiguration/visibility/v1alpha1/clusterqueue.go
  client-go/applyconfiguration/visibility/v1alpha1/localqueue.go
  client-go/applyconfiguration/visibility/v1alpha1/pendingworkload.go
  client-go/applyconfiguration/visibility/v1alpha1/pendingworkloadssummary.go
  client-go/clientset/versioned/clientset.go
  client-go/clientset/versioned/fake/clientset_generated.go
  client-go/clientset/versioned/fake/register.go
  client-go/clientset/versioned/scheme/register.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/clusterqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/doc.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/fake/doc.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/fake/fake_clusterqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/fake/fake_localqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/fake/fake_visibility_client.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/localqueue.go
  client-go/clientset/versioned/typed/visibility/v1alpha1/visibility_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/visibility/interface.go
  client-go/informers/externalversions/visibility/v1alpha1/clusterqueue.go
  client-go/informers/externalversions/visibility/v1alpha1/interface.go
  client-go/informers/externalversions/visibility/v1alpha1/localqueue.go
  client-go/listers/visibility/v1alpha1/clusterqueue.go
  client-go/listers/visibility/v1alpha1/expansion_generated.go
  client-go/listers/visibility/v1alpha1/localqueue.go
  config/components/visibility/apiservice_v1alpha1.yaml
  config/components/visibility/kustomization.yaml
  hack/update-helm.sh
  pkg/visibility/api/install.go
  pkg/visibility/api/v1alpha1/cluster_queue.go
  pkg/visibility/api/v1alpha1/local_queue.go
  pkg/visibility/api/v1alpha1/pending_workloads_cq.go
  pkg/visibility/api/v1alpha1/pending_workloads_cq_test.go
  pkg/visibility/api/v1alpha1/pending_workloads_lq.go
  pkg/visibility/api/v1alpha1/pending_workloads_lq_test.go
  pkg/visibility/api/v1alpha1/storage.go
  pkg/visibility/api/v1alpha1/test_utils.go
  pkg/visibility/api/v1alpha1/utils.go
  pkg/visibility/server.go
Labels: lgtm, size/XXL, release-note-action-required, approved, kind/cleanup, cncf-cla: yes

#3508 Update release-notes with upgrading steps to 0.9.x
  CHANGELOG/CHANGELOG-0.9.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3490 TAS: fix accounting for usage from TAS workloads using multiple resources
  pkg/cache/clusterqueue.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3475 [kjobctl] Slurm delete e2e test.
  cmd/experimental/kjobctl/test/e2e/slurm_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3455 [kjobctl] Skip kueue labels on child objects.
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder.go
  cmd/experimental/kjobctl/pkg/builder/job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3488 fix: nodelabels in tas's sample
  site/static/examples/tas/sample-queues.yaml
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3517 Add example using helm repo to helm installation guide
  Makefile
  charts/kueue/README.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3514 TAS: fix computing assignment when multiple PodSets
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3524 Automated cherry pick of #3514: TAS: fix computing assignment when multiple PodSets
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#3518 Automated cherry pick of #3350: reset admission check after deactivation
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/workload_controller_test.go
Labels: release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#3525 [kjobctl] refactor to use utilmaps.SortedKeys
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
  cmd/experimental/kjobctl/pkg/cmd/describe/helpers.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#3529 Use nginx image on StatefulSet example.
  site/static/examples/serving-workloads/sample-deployment.yaml
  site/static/examples/serving-workloads/sample-statefulset.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3247 Remove kubernetes 1.27 from supported versions
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/util/kubeversion/kubeversion.go
  test/e2e/singlecluster/pod_test.go
  test/integration/webhook/jobs/job_webhook_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#3536 Refactor FlavorAssigner
  pkg/resources/requests.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#3538 Remove run-test-tas-e2e from test-e2e
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3487 Allow StatefulSet scaling down to zero and scale up from zero.
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/webhook/webhook.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/statefulset/statefulset_controller.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3544 Remove kubebuilder:docs-gen marker from tests.
  cmd/experimental/podtaintstolerations/test/e2e/e2e_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/tas/util.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3542 Move expectJobWithSuspendedAndNodeSelectors to test and remove util.go
  test/e2e/tas/tas_test.go
  test/e2e/tas/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3532 TAS: cleanup TopologyUngater to prepare for ranks support
  pkg/controller/tas/topology_ungater.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3547 Prioritize Workload which fits in its CQ's Nominal Capacity
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3551 Cherry pick #3536 and #3547 to 0.8
  pkg/cache/clusterqueue_snapshot.go
  pkg/resources/requests.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#3548 Fix StatefulSet created should allow to scale up after scale down to zero test
  test/e2e/singlecluster/statefulset_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3559 TAS: fix scenario when parallelism < completions
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  test/e2e/tas/tas_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3541 Add unit test for CQ validation for unsupported configurations of TAS
  pkg/cache/clusterqueue_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#3557 Remove unnecessary manageJobsWithoutQueueName field on deployment webhook.
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3558 Use QueueNameForObject in Deployment Webhook.
  pkg/controller/jobs/deployment/deployment_webhook.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3545 Point MK Manager Cluster CRDs installation to dedicated pages
  site/content/en/docs/tasks/manage/setup_multikueue.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3561 Automated cherry pick of #3559: TAS: fix scenario when parallelism < completions
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#3553 Add Deployment e2e test.
  pkg/util/testingjobs/deployment/wrappers.go
  test/e2e/config/common/controller_manager_config.yaml
  test/e2e/singlecluster/deployment_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3556 Optimize and extend deployment unit tests.
  pkg/controller/jobs/deployment/deployment_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3562 Remove WithValues("deployment", klog.KObj(deployment))
  pkg/controller/jobs/deployment/deployment_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3566 Prepare v0.8.4
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3567 Prepare release 0.9.1
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3537 [kjobctl] Add --time flag to other modes.
  cmd/experimental/kjobctl/apis/v1alpha1/application_profile_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_interactive.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_job.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_raycluster.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_rayjob.md
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder.go
  cmd/experimental/kjobctl/pkg/builder/job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3572 Update changelog for 0.8.4
  CHANGELOG/CHANGELOG-0.8.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3555 Add validation for Deployment queue-name to fail fast
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/pod/pod_webhook.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3554 Optimize and extend deployment integration tests.
  test/integration/webhook/jobs/deployment_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3539 TAS: assign pods based on ranks for Job
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3575 Add validation for StatefulSet queue-name to fail fast.
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3586 Added info to 0.9.1 about Rank Ordering being deferred to the next release
  CHANGELOG/CHANGELOG-0.9.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3590 Bump sigs.k8s.io/jobset from 0.7.0 to 0.7.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3584 TAS: add e2e tests for rank ordering for Job
  test/e2e/tas/tas_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3587 [kjobctl] Remove the unused skip-priority-workload flag.
  cmd/experimental/kjobctl/apis/v1alpha1/application_profile_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3596 Automated cherry pick of #3573: Update latest version to v0.9.1
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3594 TAS: cleanup Job e2e tests
  test/e2e/tas/job_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3591 TAS: support rank-based ordering for JobSet
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/util/testingjobs/jobset/wrappers.go
  test/e2e/tas/jobset_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3592 TAS: Clean up TAS flavor snapshot
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3607 Use g.Expect instead of gomega.Expect on gomega.Eventually.
  test/e2e/tas/jobset_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3606 Selective installation of frameworks for e2e tests and install Kubeflow for TAS
  Makefile-test.mk
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  test/e2e/tas/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3593 Rename InactiveWorkload to Deactivated.
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/metrics/metrics.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/content/en/docs/concepts/admission_check.md
  site/content/en/docs/reference/metrics.md
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-action-required, approved, cncf-cla: yes

#3604 TAS: support rank-ordering for Kubeflow
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pytorch_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3612 TAS: fix dropping of reconcile events for non-leading replica
  pkg/controller/tas/resource_flavor.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#3619 Replace bytes.NewReader with strings.NewReader
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
  cmd/experimental/kjobctl/pkg/parser/slurm.go
  cmd/kueuectl/app/list/list_pods_test.go
  cmd/kueuectl/app/list/list_workload_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#3618 Simplify functions by removing strings.Compare
  .golangci.yaml
  cmd/experimental/kjobctl/cmd/kjobctl-docs/generators/doc.go
  cmd/kueuectl-docs/generators/doc.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/tas/topology_ungater.go
  pkg/util/testing/client.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3611 Use ResourceFlavorReference for ResourceFlavor names
  cmd/importer/pod/check.go
  cmd/importer/util/util.go
  cmd/kueuectl/app/create/create_clusterqueue.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/tas/resource_flavor.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3617 Make e2e scripts compatible with older versions of bash
  hack/e2e-common.sh
  hack/e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3528 Allow mutating queue name in Deployment Webhook.
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/util/testingjobs/deployment/wrappers.go
  test/e2e/singlecluster/deployment_test.go
  test/integration/webhook/jobs/deployment_webhook_test.go
Labels: kind/feature, release-note, size/L, lgtm, needs-kind, approved, cncf-cla: yes

#3603 [MultiKueue] fix using MultiKueue when some integrations are disabled
  cmd/kueue/main.go
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/jobframework/integrationmanager.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#3631 Automated cherry pick of #3603: [MultiKueue] fix using MultiKueue when some integrations are disabled
  cmd/kueue/main.go
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/jobframework/integrationmanager.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3632 TAS: fix panic in e2e test when parallelism < completions
  test/e2e/tas/job_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3634 Fix should admit workloads after change queue-name if AvailableReplicas = 0 test.
  test/e2e/singlecluster/deployment_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3635 Update run_slurm.md.
  cmd/experimental/kjobctl/docs/run_slurm.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3638 [kjobctl] Install CRDs guide.
  cmd/experimental/kjobctl/docs/installation.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3642 Use gomega Matcher in the visibility E2E testings
  test/e2e/singlecluster/visibility_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3641 Make topology levels immutable.
  apis/kueue/v1alpha1/tas_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
Labels: kind/bug, release-note, lgtm, needs-kind, approved, size/XS, cncf-cla: yes

#3643 Sync KEP and actual APIs for Hierarchical Cohort
  keps/79-hierarchical-cohorts/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3647 Use g.Expect instead of gomega.Expect on gomega.Eventually.
  test/e2e/tas/job_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3615 TAS: Update cache on delete Topology.
  pkg/cache/tas_flavor.go
  pkg/controller/tas/indexer/indexer.go
  pkg/controller/tas/resource_flavor.go
  test/integration/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3655 Automated cherry pick of #3509: Use TopologyReference instead of string. #3615: TAS: Update cache on delete Topology.
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/tas/indexer/indexer.go
  pkg/controller/tas/resource_flavor.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/tas/tas_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#3656 Reuse the core API hostname node label
  pkg/cache/cache_test.go
  pkg/cache/tas_cache_test.go
  pkg/scheduler/scheduler_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pytorch_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3616 Promote ConfigurableResourceTransformations and WorkloadResourceRequestsSummary to Beta
  keps/2937-resource-transformer/kep.yaml
  pkg/features/kube_features.go
  pkg/scheduler/scheduler_test.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/manage/administer_cluster_quotas.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3659 use automatically aligned Int64
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#3665 Fix multikueue e2e test failure due to empty strings
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3657 Implement Topology CRD validations testing
  test/integration/tas/tas_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3669 Remove redundant inflight object informations from webhook loggings
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/cohort_webhook.go
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/workload_webhook.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3672 TAS: Move sorting domains lexicographically from TopologyUngater to TAS Snapshot
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3649 TAS: Rank-ordering support for Pod groups
  apis/kueue/v1alpha1/tas_types.go
  keps/976-plain-pods/README.md
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/util/testingjobs/pod/wrappers.go
  site/content/en/docs/reference/labels-and-annotations.md
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3676 TAS: introduce addNode function to prepare for taints support
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3682 Doc: Fix an incorrect reference formating
  site/content/en/docs/reference/labels-and-annotations.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3681 Update KEP to re-evaluate the support for topologies without hostname
  keps/2724-topology-aware-scheduling/README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3687 TAS: TopologyUngater clean up for Pod groups
  pkg/controller/tas/topology_ungater.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3595 KEP 3589: Uniformly filter manageJobsWithoutQueueNames by namespace
  keps/3589-manage-jobs-selectively/README.md
  keps/3589-manage-jobs-selectively/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes
