Repository kubernetes-sigs/kueue, pull requests merged in 2024-07, with the labels that each got.

#2504 Enhance scheduler and preemption logging
  pkg/cache/snapshot.go
  pkg/scheduler/logging.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2510 cherry-pick #2504 to 0.7
  pkg/cache/snapshot.go
  pkg/scheduler/logging.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#2505 Clean all jobsets on delete namespace.
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2515 [kjobctl] Import authentication plugins.
  cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
Labels: kind/feature, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2486 Use Kueue API types in FlavorAssignerTest
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/util/testing/wrappers.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2514 [kueuectl] Generate krew plugin configuration.
  .gitignore
  hack/generate_krew.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2513 [kueuectl] Build kubectl-kueue tar.gz archives to artifact directory.
  hack/multiplatform-build.sh
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#2521 Do not omit weightedShare when zero
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2518 [kueuectl] Add resourceflavor to pass-through commands.
  apis/kueue/v1beta1/resourceflavor_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  cmd/kueuectl/app/passthrough/passthrough.go
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  keps/2076-kueuectl/README.md
  site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
  test/integration/kueuectl/passthrough_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2520 Fix preemption when requesting 0 of a resource at nominal quota
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2524 Automated cherry pick of #2520: Fix preemption when requesting 0 of a resource at nominal
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#2507 Add documentation for restricting job creation without queue name
  site/content/en/docs/tasks/manage/setup_job_admission_policy.md
  site/static/examples/sample-validating-policy-binding.yaml
  site/static/examples/sample-validating-policy.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2530 [e2e/pod] Extend the waiting for node assignment of an ungated pod.
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2479 Fix race condition on run garbage collection in multikueuecluster reconciler.
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/util/maps/maps.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#2526 [test/multikueue] Move kubecofig generation in the go code.
  hack/create-multikueue-kubeconfig.sh
  hack/multikueue-e2e-test.sh
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2528 Remove the unused structure PendingWorkloadsSummaryList
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  apis/visibility/v1alpha1/types.go
  apis/visibility/v1alpha1/zz_generated.deepcopy.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2509 Fix race condition on requeueAndUpdate.
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#2468 Runs the race detector on integration tests.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2506 Remove deprecated Hugo template
  site/layouts/partials/head.html
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2533 Fixed prefixes on comments.
  apis/kueue/v1alpha1/multikueue_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
  pkg/metrics/metrics.go
  pkg/resources/resource.go
  pkg/util/heap/heap.go
  pkg/util/maps/maps.go
  pkg/util/testingjobs/pod/wrappers.go
  pkg/visibility/api/rest/cluster_queue.go
  pkg/visibility/api/rest/local_queue.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/util/constants.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2482 Add test case for TryNextFlavor but flavor is full
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2539 Delete Unused IsBorrowing
  pkg/cache/clusterqueue.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2519 Define ClusterQueueSnapshot and CohortSnapshot types
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/resource.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/resources/resource.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#2463 Increase waiting time to verify workload completion.
  test/e2e/singlecluster/pod_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2501 Use Patch instead of Update on jobframework.
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
  pkg/util/client/client.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2547 Unexport cache ClusterQueue and Cohort
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2543 Prepare release v0.7.1
  CHANGELOG/CHANGELOG-0.7.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2550 Move Requests from workload to resources package
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/resources/requests.go
  pkg/resources/resource.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler.go
  pkg/webhooks/workload_webhook.go
  pkg/workload/resources_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2551 Flatten several usages of FlavorResourceQuantities
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/preemption/preemption.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2525 [kueuectl] Add list resourceflavor command.
  cmd/kueuectl/app/list/list.go
  cmd/kueuectl/app/list/list_resourceflavor.go
  cmd/kueuectl/app/list/list_resourceflavor_printer.go
  cmd/kueuectl/app/list/list_resourceflavor_printer_test.go
  cmd/kueuectl/app/list/list_resourceflavor_test.go
  keps/2076-kueuectl/README.md
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/podset/podset_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/resourceflavor_webhook_test.go
  site/content/en/docs/reference/kubectl-kueue/commands/list.md
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/pod_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/kueuectl/list_test.go
  test/integration/kueuectl/passthrough_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/resourceflavor_test.go
  test/performance/scheduler/runner/generator/generator.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2555 Update latest version to v0.7.1
  CHANGELOG/CHANGELOG-0.7.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2556 Automated cherry pick of #2555: Update latest version to v0.7.1
  CHANGELOG/CHANGELOG-0.7.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2517 [kueuectl] Add create resourceflavor command.
  cmd/kueuectl/app/create/create.go
  cmd/kueuectl/app/create/create_resourceflavor.go
  cmd/kueuectl/app/create/create_resourceflavor_test.go
  keps/2076-kueuectl/README.md
  site/content/en/docs/reference/kubectl-kueue/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/create.md
  test/integration/kueuectl/create_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2557 [kueuectl] Added Node Labels column on resource flavor list.
  cmd/kueuectl/app/list/list_resourceflavor_printer.go
  cmd/kueuectl/app/list/list_resourceflavor_printer_test.go
  cmd/kueuectl/app/list/list_resourceflavor_test.go
  site/static/examples/admin/single-clusterqueue-setup.yaml
  test/integration/kueuectl/list_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2562 Delete ClusterQueueSnapshot.Lendable
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2342 Add reusable feature-state component
  site/assets/scss/_styles_project.scss
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/dev/enabling_pprof_endpoints.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  site/content/en/docs/tasks/manage/setup_wait_for_pods_ready.md
  site/layouts/shortcodes/feature-state.html
Labels: kind/feature, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2549 [test/integration] Add API logging
  Makefile-test.mk
  test/integration/framework/framework.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2559 [kueuectl] Add Node Labels column on List ResourceFlavors.
  keps/2076-kueuectl/README.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2563 Delete ClusterQueue.Lendable
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2565 Revert "Use Patch instead of Update on jobframework."
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
  pkg/util/client/client.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2568 Fix license.
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/errors.go
  pkg/controller/jobframework/events.go
  pkg/controller/jobframework/indexer.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/podset/podset.go
  pkg/util/routine/error_channel.go
  pkg/util/routine/error_channel_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2558 Mention label copying in the docs
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2445 Provide support for ProvisioningRequest's BookingExpired condition
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2413 [kjobctl] Add list job
  cmd/experimental/kjobctl/pkg/cmd/cmd.go
  cmd/experimental/kjobctl/pkg/cmd/list/helpers.go
  cmd/experimental/kjobctl/pkg/cmd/list/list.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job_test.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
  cmd/experimental/kjobctl/pkg/cmd/util/helpers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
  cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#2411 Distinguish between Preemption due to reclamation and fair sharing
  pkg/scheduler/logging.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  test/integration/scheduler/preemption_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2567 Retry to reset start time and restore info after error on stop job.
  pkg/controller/jobs/job/job_controller.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#2580 [kjobctl] Use RunE instead Run in list job command.
  cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2575 [kueuectl] Removed [flags] suffix in use line on version command.
  cmd/kueuectl/app/version/version.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2577 Add the prow labels to the dependabot
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2579 Add generic delete functions in `test/util`
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/kueuectl_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/visibility_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/importer/importer_test.go
  test/integration/kueuectl/create_test.go
  test/integration/kueuectl/list_test.go
  test/integration/kueuectl/resume_test.go
  test/integration/kueuectl/stop_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
  test/integration/webhook/admissioncheck_test.go
  test/integration/webhook/clusterqueue_test.go
  test/integration/webhook/resourceflavor_test.go
  test/util/util.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#2587 Upgrade the minimum required kubernetes version in docs
  README.md
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2578 [kueuectl] Use RunE instead Run in commands.
  cmd/kueuectl/app/create/create_clusterqueue.go
  cmd/kueuectl/app/create/create_localqueue.go
  cmd/kueuectl/app/list/list_clusterqueue.go
  cmd/kueuectl/app/list/list_localqueue.go
  cmd/kueuectl/app/list/list_resourceflavor.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/passthrough/passthrough.go
  cmd/kueuectl/app/resume/resume_clusterqueue.go
  cmd/kueuectl/app/resume/resume_localqueue.go
  cmd/kueuectl/app/resume/resume_workload.go
  cmd/kueuectl/app/stop/stop_clusterqueue.go
  cmd/kueuectl/app/stop/stop_localqueue.go
  cmd/kueuectl/app/stop/stop_workload.go
  cmd/kueuectl/app/version/version.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2583 Refactor DominantResourceShare tests; Increase Coverage
  pkg/cache/clusterqueue_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#2553 Use patch instead of update on jobframework.
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/util/client/client.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#2591 Remove unused parameters.
  cmd/experimental/podtaintstolerations/controller/pod_jobs.go
  cmd/kueuectl/app/list/list_localqueue.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/resume/resume_clusterqueue.go
  cmd/kueuectl/app/resume/resume_localqueue.go
  cmd/kueuectl/app/stop/stop_clusterqueue.go
  cmd/kueuectl/app/stop/stop_localqueue.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/noop/noop_webhook.go
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/visibility/api/rest/pending_workloads_cq.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/workload_webhook.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2493 [jobframework] Only check if the owner is managed for enabled integrations.
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobframework/setup_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2598 Remove non-necessary conditions.
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2602 [kueuectl] Import auth plugins for K8s
  cmd/kueuectl/app/util/client_getter.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2604 docs: fix typo, beta -> Beta
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2540 Added kueuectl-docs generator.
  Makefile
  Makefile-deps.mk
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  hack/internal/tools/kueuectl-docs/generators/doc.go
  hack/internal/tools/kueuectl-docs/main.go
  hack/internal/tools/kueuectl-docs/templates/main.html
  hack/internal/tools/kueuectl-docs/templates/options.html
  site/content/en/docs/reference/kubectl-kueue/commands/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/create.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_version/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/list.md
  site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
  site/content/en/docs/reference/kubectl-kueue/commands/resume.md
  site/content/en/docs/reference/kubectl-kueue/commands/stop.md
  site/content/en/docs/reference/kubectl-kueue/commands/version.md
Labels: release-note, lgtm, size/XXL, approved, kind/documentation, cncf-cla: yes

#2607 Automated cherry pick of #2602: Import auth plugins for K8s
  cmd/kueuectl/app/util/client_getter.go
Labels: release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2610 Stop manually setting ClusterQueueSnapshot.Usage in scheduler_test
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2608 Fixed "There are pending workloads due to capacity maxed by the admitted job" e2e test.
  test/e2e/singlecluster/visibility_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2611 Revert "Added kueuectl-docs generator."
  Makefile
  Makefile-deps.mk
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  hack/internal/tools/kueuectl-docs/generators/doc.go
  hack/internal/tools/kueuectl-docs/main.go
  hack/internal/tools/kueuectl-docs/templates/main.html
  hack/internal/tools/kueuectl-docs/templates/options.html
  site/content/en/docs/reference/kubectl-kueue/commands/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/create.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_version/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/list.md
  site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
  site/content/en/docs/reference/kubectl-kueue/commands/resume.md
  site/content/en/docs/reference/kubectl-kueue/commands/stop.md
  site/content/en/docs/reference/kubectl-kueue/commands/version.md
Labels: kind/bug, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2600 Wait for removing "spot-untainted" ResourceFlavor on Job controller interacting with scheduler test.
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2601 Change example Job Admission Policy to use matchLabels
  site/content/en/docs/tasks/manage/setup_job_admission_policy.md
  site/static/examples/sample-validating-policy-binding.yaml
  site/static/examples/sample-validating-policy.yaml
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#2616 [website] fix broken link
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2615 feat: Add a column to workload indicating if it is finished
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2618 Add raycluster roles to manifests.yaml
  config/components/rbac/kustomization.yaml
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2623 Force remove workloads before removing ClusterQueues in AfterEach e2e tests.
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/jobset_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2622 Simplify scheduler.cohortsUsage; Cleanup FlavorResourceQuantities
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2624 Automated cherry pick of #2623: Force remove workloads before removing ClusterQueues in
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/jobset_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2627 Automated cherry pick of #2608: Fixed "There are pending workloads due to capacity maxed by
  test/e2e/singlecluster/visibility_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2629 Fix detailed preemption reason bug
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  test/integration/scheduler/preemption_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#2632 Add redundant-import-alias check on .golangci.yaml.
  .golangci.yaml
  cmd/experimental/kjobctl/.golangci.yaml
  cmd/experimental/kjobctl/apis/v1alpha1/job_template_types.go
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/kueuectl/app/version/version.go
  cmd/kueuectl/app/version/version_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/util/priority/priority_test.go
  pkg/visibility/api/install.go
  pkg/visibility/api/rest/pending_workloads_cq_test.go
  pkg/visibility/api/rest/pending_workloads_lq_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2633 Refactor update(Flavor|Cohort)Usage to take FlavorResourceQuantitiesFlat
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/resources/resource.go
  pkg/resources/resource_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2636 Do not start Kueue when the visibility server cannot be started
  pkg/visibility/server.go
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#2538 Add a metric that tracks the number of preemptions issued by a ClusterQueue
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/scheduler/preemption/preemption.go
  test/integration/scheduler/preemption_test.go
  test/util/util.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#2639 [performance] Relax ClusterQueueClassesMinUsage.
  test/performance/scheduler/checker/checker_test.go
  test/performance/scheduler/default_rangespec.yaml
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2637 Remove unnecessary wrappers for goroutines.
  cmd/kueue/main.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2613 Added kueuectl-docs generator.
  Makefile
  Makefile-deps.mk
  cloudbuild.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  hack/internal/tools/kueuectl-docs/generators/doc.go
  hack/internal/tools/kueuectl-docs/main.go
  hack/internal/tools/kueuectl-docs/templates/main.html
  hack/internal/tools/kueuectl-docs/templates/options.html
  site/content/en/docs/reference/kubectl-kueue/commands/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/create.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_resume/kueuectl_resume_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_stop/kueuectl_stop_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_version/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/list.md
  site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
  site/content/en/docs/reference/kubectl-kueue/commands/resume.md
  site/content/en/docs/reference/kubectl-kueue/commands/stop.md
  site/content/en/docs/reference/kubectl-kueue/commands/version.md
Labels: release-note, lgtm, size/XXL, approved, kind/documentation, cncf-cla: yes

#2643 Fixed deleted unschedulable pods are finalized unit test.
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/workload/admissionchecks_test.go
  pkg/workload/workload_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2646 Revert check in hasCommonFlavorResources
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, kind/regression, release-note-none, approved, size/M, cncf-cla: yes

#2648 Create []FlavorResource more efficiently
  pkg/cache/clusterqueue.go
  pkg/cache/resource.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2641 Enable Multiple Preemptions within Cohort in a single Scheduling Cycle
  pkg/cache/clusterqueue_snapshot.go
  pkg/features/kube_features.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  site/content/en/docs/installation/_index.md
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2649 Prepare release v0.8.0
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  config/components/manager/kustomization.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2651 Update latest kueue v0.8.0
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2644 [kjobctl] Add docs generator.
  Makefile
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/README.md
  cmd/experimental/kjobctl/docs/_index.md
  cmd/experimental/kjobctl/docs/commands/kjobctl.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/_index.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_list/_index.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_list/kjobctl_list_job.md
  cmd/experimental/kjobctl/docs/installation.md
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/hack/tools/kjobctl-docs/generators/doc.go
  cmd/experimental/kjobctl/hack/tools/kjobctl-docs/main.go
  cmd/experimental/kjobctl/hack/tools/kjobctl-docs/templates/main.md
  cmd/experimental/kjobctl/hack/tools/kjobctl-docs/templates/options.html
Labels: lgtm, size/XXL, release-note-none, approved, kind/documentation, cncf-cla: yes

#2588 Add an enabling the feturegate note to the setup a job admission policy docs
  site/content/en/docs/tasks/manage/setup_job_admission_policy.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2653 Add makezero linter.
  .golangci.yaml
  pkg/controller/jobframework/setup_test.go
  pkg/webhooks/workload_webhook.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2664 [kjobctl] Bump sigs.k8s.io/kueue from 0.7.0 to 0.8.0
  cmd/experimental/kjobctl/README.md
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2645 [website] Using docsy instead GitHub style Note.
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/resource_flavor.md
  site/content/en/docs/tasks/manage/setup_wait_for_pods_ready.md
  site/content/en/docs/tasks/run/jobs.md
  site/content/en/docs/tasks/run/plain_pods.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2670 [performance] Bump scalability workload classes large ms.
  test/performance/scheduler/default_rangespec.yaml
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2666 [website] Adds installing kubectl-kueue plugin via Krew guide.
  site/content/en/docs/reference/kubectl-kueue/installation.md
Labels: release-note, lgtm, approved, size/XS, kind/documentation, cncf-cla: yes

#2676 Cleanup typo faPreemtionTargets -> faPreemptionTargets
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2673 [kjobctl] Update release version on installation guide.
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  cmd/experimental/kjobctl/docs/installation.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2476 Publish images to new staging registry
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
  Makefile-test.mk
  charts/kueue/README.md
  charts/kueue/values.yaml
  cloudbuild.yaml
  cmd/importer/README.md
  cmd/importer/run-in-cluster/kustomization.yaml
  config/components/manager/kustomization.yaml
  hack/dump_cache.sh
  hack/push-chart.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2679 [kjobctl] Remove k8s dependency
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2680 Fix Helm chart repository name
  Makefile
  Makefile-test.mk
  hack/push-chart.sh
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#2597 [kjobctl] Build additional environment variables.
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/builder_test.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/cmd.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/constants/constants.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/application_profile_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/container_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/pod_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/pod_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/volume_bundle_wrappers.go
  cmd/experimental/kjobctl/test/integration/kjobctl/create_test.go
  cmd/experimental/kjobctl/test/integration/kjobctl/suite_test.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2685 Add a note about the need to restart the kueue pod
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/mxjobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2683 Fix unclosed action error.
  charts/kueue/templates/manager/manager.yaml
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2655 fix: Refactor FitInCohort tests
  pkg/cache/clusterqueue_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2690 Doc: Update the outdated production readiness statues section
  README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2696 Cleanup to use FlavorResourceQuantities.Add in cache
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2693 [Hierarchical Cohorts] Define Cohort API
  PROJECT
  apis/kueue/v1alpha1/cohort_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
Labels: kind/feature, release-note, lgtm, size/XL, approved, kind/api-change, cncf-cla: yes

#2603 feat: Add integration test for jobset preemption
  test/integration/controller/jobs/jobset/jobset_controller_test.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2654 [krew] Add krew release bot.
  .github/workflows/krew-release.yml
  .krew.yaml
  hack/generate_krew.sh
  hack/multiplatform-build.sh
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2702 [kjobctl] Split test to test-unit and test-integration commands.
  cmd/experimental/kjobctl/Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2703 [kueuectl] Fix resource flavor name pattern on create cq
  cmd/kueuectl/app/create/create_clusterqueue.go
  cmd/kueuectl/app/create/create_clusterqueue_test.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2684 Add update-security-insights directive
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
Labels: kind/feature, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2516 [Feature] Enable prometheus metrics for local queues
  keps/1833-metrics-for-local-queue/README.md
  keps/1833-metrics-for-local-queue/kep.yaml
Labels: kind/feature, release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#2719 Remove duplicate of rayv1.AddToScheme on SetupClient.
  test/integration/framework/framework.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2721 Finish flattening of FlavorResourceQuantities
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/resource.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/resources/resource.go
  pkg/resources/resource_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2722 Add ResourceFlavor section to Job troubleshooting guide
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2626 Support TFJob(kubeflow) in Multikueue
  Makefile-test.mk
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  pkg/controller/admissionchecks/multikueue/indexer_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
  pkg/util/testingjobs/tfjob/wrappers_tfjob.go
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/manage/setup_multikueue.md
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
  test/util/e2e.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, ok-to-test, cncf-cla: yes

#2726 Support for new ProvisioningRequest annotations
  pkg/controller/admissionchecks/provisioning/constants.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2733 Fix "Failed Pod can be replaced in group" flaky test.
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S
