Repository kubernetes-sigs/kueue, pull requests merged in 2024-04, with the labels that each got.

#1446 [site] add example of cronjob
  site/content/en/docs/tasks/run/jobs.md
  site/content/en/docs/tasks/run/run_cronjobs.md
  site/static/examples/jobs/sample-cronjob.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1932 fix for importer readme
  cmd/importer/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1920 [makefile] Support for sed on Darwin
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1802 Upgrade RayJob API to v1
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobframework/setup_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/util/testingjobs/rayjob/wrappers.go
  site/static/examples/jobs/ray-job-sample.yaml
  test/integration/controller/jobs/raycluster/raycluster_webhook_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/framework/framework.go
Labels: size/L, lgtm, release-note-action-required, approved, cncf-cla: yes

#1940 Revert "[jobframework] Return all errors when updating workload status"
  .golangci.yaml
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#1936 Count inflight workload as pending
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  test/integration/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#1938 Replace webhooks with CEL validation rules for LocalQueue
  apis/kueue/v1beta1/localqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  charts/kueue/templates/webhook/webhook.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  config/components/webhook/manifests.yaml
  pkg/util/testing/error_matchers.go
  pkg/util/testing/not_found_error_cmp.go
  pkg/webhooks/localqueue_webhook.go
  pkg/webhooks/localqueue_webhook_test.go
  pkg/webhooks/webhooks.go
  test/integration/webhook/localqueue_test.go
Labels: size/L, lgtm, release-note-action-required, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1777 Fair share during admission
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#1945 Remove duplicated word reported by dupword
  .golangci.yaml
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1934 Make requeuing Strategy mutable
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/queue/cluster_queue.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/cluster_queue_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, kind/api-change, cncf-cla: yes

#1949 fix some issue about lendingLimit docs
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1935 KEP-1432: AdmissionCheck per ResourceFlavor
  keps/1432-admission-check-per-resource-flavor/README.md
  keps/1432-admission-check-per-resource-flavor/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1933 allow configuration of ipFamilyPolicy
  charts/kueue/templates/webhook/service.yaml
  charts/kueue/values.yaml
  hack/update-helm.sh
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#1951 [test/int] Wait for workload admission change in rayjob preemption test.
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1941 Remove redundant RayCluster logic from Pod controller
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1952 Index PodGroupName
  pkg/controller/jobs/pod/indexer.go
  pkg/controller/jobs/pod/pod_controller.go
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#1965 Prepare release v0.6.2
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1967 Update the default testing k8s versions
  Makefile
  test/integration/controller/jobs/job/job_webhook_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1969 Update latest version to v0.6.2
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1942 Distinguish preemption reasons
  apis/kueue/v1beta1/workload_types.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/scheduler/preemption_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1966 [importer] Extend README.md
  cmd/importer/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1968 Graduate Admission Check Controller to beta
  pkg/features/kube_features.go
  site/content/en/docs/admission-check-controllers/provisioning.md
  site/content/en/docs/installation/_index.md
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#1958 Add CEL rules to ResourceFlavor
  apis/kueue/v1beta1/resourceflavor_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/resourceflavor_webhook_test.go
  test/integration/webhook/resourceflavor_test.go
Labels: size/L, lgtm, release-note-action-required, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1946 Remove unneeded loop variable copying
  .golangci.yaml
  Makefile
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/util/priority/priority.go
  pkg/util/priority/priority_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1956 Added support for s390x and ppc64le for multi-arch image build
  Makefile
Labels: kind/feature, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1978 Add a lock to ClusterQueueFromLocalQueue
  pkg/queue/manager.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1979 Fix preemption algorithm to reduce the number of preemptions
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1973 Pod Integration Performance
  test/performance/jobs/.env.example
  test/performance/jobs/.gitignore
  test/performance/jobs/README.md
  test/performance/jobs/config.yaml
  test/performance/jobs/job.yaml
  test/performance/jobs/local-queue.yaml
  test/performance/jobs/prerequisites/cluster-queue.template
  test/performance/jobs/prerequisites/resource-flavor.yaml
  test/performance/jobs/run-test.sh
  test/performance/podgroups/.gitignore
  test/performance/podgroups/README.md
  test/performance/podgroups/manifest.diff
  test/performance/podgroups/run-test.sh
  test/performance/podgroups/templates/cluster-queue.yaml
  test/performance/podgroups/templates/local-queue.yaml
  test/performance/podgroups/templates/pod.yaml
  test/performance/podgroups/templates/resource-flavor.yaml
  test/performance/podgroups/test-config.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#1975 Add CEL rules to AdmissionCheck
  apis/kueue/v1beta1/admissioncheck_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/webhook/webhook.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/webhook/manifests.yaml
  pkg/webhooks/admissioncheck_webhook.go
  pkg/webhooks/admissioncheck_webhook_test.go
  pkg/webhooks/webhooks.go
  test/integration/webhook/admissioncheck_test.go
Labels: lgtm, size/XL, release-note-action-required, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1980 Automated cherry pick of #1979: Fix preemption algorithm to reduce the number of
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1981 Remove unnecessary parameter for minimalPreemptions
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1939 Set ObservedGeneration in conditions
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/localqueue_controller_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/rayjob/wrappers.go
  pkg/workload/admissionchecks.go
  pkg/workload/admissionchecks_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/jobset_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/scheduler/scheduler_test.go
  test/util/constants.go
Labels: release-note, lgtm, size/XXL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1984 [dep] Use jobset v0.5.0
  go.mod
  go.sum
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1972 Add CEL rules to ClusterQueue
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  test/integration/webhook/clusterqueue_test.go
Labels: lgtm, size/XL, release-note-action-required, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1870 MultiKueue JobSet managedBy
  hack/multikueue-e2e-test.sh
  pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/util/testingjobs/jobset/wrappers.go
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/run/jobsets.md
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1960 Introduce AdmissionCheckStrategy API, change assigning AdmissionCheck…
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/admissionchecksstrategy.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheckstrategyrule.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/maps/maps.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/static/examples/provisioning/provisioning-setup.yaml
  test/integration/scheduler/workload_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1990 Fix typos in unexported variable names
  cmd/importer/pod/check_test.go
  cmd/importer/pod/import_test.go
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/podset/podset_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1947 Improve e2e execution time
  test/e2e/singlecluster/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1995 Fair sharing KEP rule typo fix
  keps/1714-fair-sharing/README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1931 Scalability tests
  Makefile
  pkg/util/testing/kubeconfig.go
  pkg/util/testing/wrappers.go
  test/integration/multikueue/suite_test.go
  test/scalability/README.md
  test/scalability/checker/checker_test.go
  test/scalability/default_generator_config.yaml
  test/scalability/default_rangespec.yaml
  test/scalability/minimalkueue/main.go
  test/scalability/runner/controller/controller.go
  test/scalability/runner/generator/generator.go
  test/scalability/runner/generator/generator_test.go
  test/scalability/runner/main.go
  test/scalability/runner/recorder/recorder.go
  test/scalability/runner/stats/stats.go
Labels: release-note, lgtm, size/XXL, approved, cncf-cla: yes

#1988 Preemption algorithm described
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1948 Fair preemptions in a cohort, rule S2-a
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#1999 Fix sublists in KEP #1714
  keps/1714-fair-sharing/README.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1993 Make ClusterQueue's AdmissionCheckStrategy a pointer, avoid type casting
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  pkg/workload/workload.go
  test/integration/scheduler/workload_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1991 Non-admitted workloads with QuotaReserved condition are shown as Admitted by kubectl
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  site/content/en/docs/tasks/run/jobs.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: release-note, lgtm, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2001 docs: add troubleshooting resource requests
  site/content/en/docs/admission-check-controllers/provisioning.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#2013 site: fix kubectl command of tasks example
  site/content/en/docs/tasks/run/plain_pods.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2014 Automated cherry pick of #1991: * Rename "Admitted by" to "Reserving in" printed column *
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  site/content/en/docs/tasks/run_jobs.md
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#1976 Fix deprecated comment for constants.QueueAnnotation
  .golangci.yaml
  pkg/controller/constants/constants.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2011 doc: website jobset url
  site/content/en/docs/tasks/run/jobsets.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1989 CVE fixes - Upgrade mpi-operator
  go.mod
  go.sum
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1992 Update kubeflow sample pytorchjob to pytorch 2.x and cuda 12.x (#1910)
  site/static/examples/jobs/sample-pytorchjob.yaml
Labels: kind/feature, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1987 [test] Scalability runner metrics
  Makefile
  test/scalability/checker/checker_test.go
  test/scalability/default_rangespec.yaml
  test/scalability/runner/controller/controller.go
  test/scalability/runner/main.go
  test/scalability/runner/recorder/recorder.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2024 docs: add troubleshooting resource requests (cherry pick of #2001)
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1944 [jobframework] Fix logging of error message
  .golangci.yaml
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2002 Rule s2-b for flat fair preemption
  pkg/queue/cluster_queue.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/util/heap/heap.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2025 Make the defaults for PodsReadyTimeout backoff more practical
  apis/config/v1beta1/configuration_types.go
  keps/1282-pods-ready-requeue-strategy/README.md
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  test/integration/scheduler/podsready/suite_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#2034 Fix generation of API reference
  Makefile
  hack/genref/config.yaml
  hack/genref/markdown/members.tpl
  hack/genref/markdown/pkg.tpl
  hack/genref/markdown/type.tpl
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/bug, size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1971 Allow run test-multikueue-e2e for mac os
  hack/multikueue-e2e-test.sh
  hack/multikueue/worker-cluster.kind.yaml
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1977 [metrics] Add quota_reserved_wait_time_seconds
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  site/content/en/docs/reference/metrics.md
  test/integration/controller/core/workload_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: kind/bug, kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2007 Propagate provisioning status of a ProvReq into the Workload status
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2037 Make dominant resource share flavor aware
  keps/1714-fair-sharing/README.md
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2046 Fix number of pod reconcilers in default chart values
  charts/kueue/values.yaml
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2044 Tighten asserts for PodsReady requeueAt by using a fake clock and jitter=0
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2030 add: custom annotations on service and deployment
  charts/kueue/templates/manager/auth_proxy_service.yaml
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2049 [multikueue] Fix e2e test timeout issue
  test/e2e/multikueue/e2e_test.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2018 Scalability scrape
  Makefile
  test/scalability/README.md
  test/scalability/minimalkueue/main.go
  test/scalability/runner/main.go
  test/scalability/runner/scraper/scraper.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2055 docs: web url
  site/content/en/docs/tasks/run/jobsets.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2053 Add a note on PodsReady timeout requeuing
  site/content/en/docs/tasks/manage/setup_sequential_admission.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2060 cleanup useless comments, and fix receiver names are different
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/jobframework/reconciler.go
  pkg/queue/cluster_queue.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/mxjob/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  pkg/util/testingjobs/raycluster/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2043 Adapt scalability range spec to the CI results
  test/scalability/default_rangespec.yaml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2058 Cleanup CQ and cohort resource stats
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#1996 Add AdmissionCheckStrategy documentation
  site/content/en/docs/concepts/admission_check.md
  site/content/en/docs/concepts/cluster_queue.md
  site/static/examples/admin/minimal-cq.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2052 Add the ProvisioningRequest's classname annotation
  pkg/controller/admissionchecks/provisioning/constants.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2047 Validate admission check applies to all flavors
  apis/kueue/v1beta1/admissioncheck_types.go
  pkg/cache/admissioncheck.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
  pkg/util/testing/wrappers.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#2062 Improve logging of workload status
  pkg/controller/core/workload_controller.go
Labels: release-note, lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#2069 Deterministic import order linter
  .golangci.yaml
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#2071 Conditions creation code cleanup
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2061 Fix handling of eviction in StrictFIFO to ensure the evicted workload is in the head
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
Labels: kind/bug, release-note, lgtm, kind/flake, approved, kind/cleanup, cncf-cla: yes, size/S

#2078 [makefile] Drop old `test-scalability` make target.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2026 Include a Failed condition in Workloads
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/jobset_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2067 [sclability] Relax the expectations.
  test/performance/scheduler/checker/checker_test.go
  test/performance/scheduler/default_rangespec.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2074 Using patch/apply on update pods.
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/client/client.go
Labels: kind/bug, kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#2008 Add CEL rules to Workload
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/webhooks/common.go
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/resourceflavor_webhook_test.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/webhook/workload_test.go
Labels: lgtm, size/XXL, release-note-action-required, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2087 fix(helm): wrong secret name in certificate
  charts/kueue/templates/certmanager/certificate.yaml
  charts/kueue/templates/internalcert/secret.yaml
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2079 [scalability] Changed binary directory of scalability runner and minimalkueue.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2089 Automated cherry pick of #2074: Using patch/apply on update pods.
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/client/client.go
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes
