Repository kubernetes-sigs/kueue, pull requests merged in 2024-09, with the labels that each got.

#2961 Bump github.com/ray-project/kuberay/ray-operator from 1.1.1 to 1.2.1 in /cmd/experimental/kjobctl.
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayjobtemplates.yaml
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2938 [flaky] Wrap Update with Eventually to avoid flakiness
  test/integration/controller/jobs/job/job_controller_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2785 fix docs: workload_priority_class.md
  site/content/en/docs/concepts/workload_priority_class.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2934 [kjobctl] Add describe rayjob command.
  cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2940 [kjobctl] Describe only kjobctl owned objects.
  cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
Labels: kind/feature, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2939 Support Cohorts with Resources in cache/hierarchy packages
  .golangci.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/cohort.go
  pkg/cache/resource.go
  pkg/cache/resource_node.go
  pkg/cache/snapshot_test.go
  pkg/hierarchy/cohort.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/util/testing/wrappers.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#2945 Allow an empty PodIntegrationOptions
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/deployment/deployment_webhook_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2946 Remove the kubebuilder PROJECT file
  PROJECT
  cmd/experimental/kjobctl/PROJECT
  cmd/experimental/kjobctl/test/framework/framework.go
  cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
  cmd/kueue/main.go
  test/e2e/singlecluster/suite_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/jobs/deployment/suite_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/jobset/suite_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/framework/framework.go
  test/integration/importer/suite_test.go
  test/integration/kueuectl/suite_test.go
  test/integration/multikueue/suite_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2968 drop mentions of 1.27 in kueue and makefile testing
  Makefile-test.mk
  README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2974 Resolve InvalidDefaultArgInFrom build check warnings.
  Dockerfile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2977 [kueuectl] Add EXEC TIME column on list workload command.
  cmd/kueuectl/app/list/list_test.go
  cmd/kueuectl/app/list/list_workload_printer.go
  cmd/kueuectl/app/list/list_workload_test.go
  test/integration/kueuectl/list_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2989 Update Snapshoting to use hierarchy.Manager
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2986 Update the release issue template with new admin, Michal
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2991 Automated cherry pick of #2574: Start Controller and Webhook on new CRDs availability
  cmd/kueue/main.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobframework/setup_test.go
Labels: release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2980 [kjobctl] Fix create interactive command.
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/container_wrappers.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2995 [config] Add cohorts CRD in the kustomization
  config/components/crd/kustomization.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2966 [kjobctl] Add describe raycluster command.
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_spec_wrapper.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/worker_group_spec_wrapper.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2997 Prepare release v0.8.1
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2999 Increase the timeout for waiting for zero pending workloads.
  test/e2e/singlecluster/visibility_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2988 import deployment package in jobs.go to register the deployment webhook
  charts/kueue/templates/webhook/webhook.yaml
  cmd/kueuectl/app/list/list_pods.go
  config/components/webhook/manifests.yaml
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobs/deployment/deployment_controller.go
  pkg/controller/jobs/jobs.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#3000 Support Hierarchical Cohorts in hierarchy.Manager
  pkg/cache/cache.go
  pkg/cache/snapshot.go
  pkg/hierarchy/cohort.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3002 Cleanup hierarchy.Manager
  pkg/hierarchy/manager.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3007 Update latest version to v0.8.1
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  cmd/experimental/kjobctl/docs/installation.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3004 Update the new release steps
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#3009 Automated cherry pick of #3007: Update latest version to v0.8.1
  CHANGELOG/CHANGELOG-0.8.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3010 Use Note instead Warning on the LendingLimit is enabled by default info.
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3022 Bump sigs.k8s.io/kueue from 0.8.0 to 0.8.1 in /cmd/experimental/kjobctl.
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3021 Bump github.com/prometheus/client_golang from 1.20.2 to 1.20.3.
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/modules.txt
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3023 Use current version instead of $VERSION.
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3020 [test][scalability] Retry performance test on failure
  Makefile-test.mk
  hack/performance-retry.sh
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2880 [Feature] Support Kubeflow MPIJob in MultiKueue
  Makefile-deps.mk
  Makefile-test.mk
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/setup_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/config/multikueue/manager/kustomization.yaml
  test/e2e/config/multikueue/manager/patch_crds.yaml
  test/e2e/config/multikueue/worker/kustomization.yaml
  test/e2e/config/multikueue/worker/patch_crds.yaml
  test/e2e/config/multikueue/worker/patch_deployment.yaml
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/suite_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/framework/framework.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
  test/util/e2e.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#3027 Fix Warning: 'commonLabels' is deprecated.
  test/e2e/config/multikueue/manager/kustomization.yaml
  test/e2e/config/multikueue/worker/kustomization.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3030 Clean roles and secrets after e2e multikueue test.
  test/e2e/multikueue/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3031 [kjobctl] Fix installation guide.
  Makefile
  cmd/experimental/kjobctl/docs/installation.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3029 Fix Should run a MPIJob on worker if admitted flaky test.
  test/e2e/multikueue/e2e_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3033 Remove unnecessary IgnoreConditionTimestampsAndObservedGeneration for ReplicaStatus object.
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3036 drop jobset from taints tolerations
  cmd/experimental/podtaintstolerations/go.mod
  cmd/experimental/podtaintstolerations/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2994 Update the notes about the need to restart the kueue pod
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/mxjobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
Labels: lgtm, release-note-none, approved, needs-rebase, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#3005 Create resource_test Suite
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/resource_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3034 update jobset to 0.6.0
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  site/content/en/docs/tasks/manage/setup_multikueue.md
  vendor/modules.txt
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/openapi_generated.go
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/jobset/pkg/constants/constants.go
  vendor/sigs.k8s.io/jobset/pkg/util/collections/collections.go
  vendor/sigs.k8s.io/jobset/pkg/util/testing/wrappers.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2971 Implement Cohort Reconciler
  charts/kueue/templates/rbac/role.yaml
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/role.yaml
  keps/79-hierarchical-cohorts/README.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/cohort_controller_test.go
  pkg/controller/core/core.go
  pkg/queue/manager.go
  pkg/util/testing/client.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#3035 [tests] Add ginkgo tests time analysis
  Makefile-test.mk
  hack/e2e-test.sh
  hack/internal/tools/ginkgo-top/ginkgo-top.go
  hack/multikueue-e2e-test.sh
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3040 Implement Cohort cycle detection in hierarchy.Manager
  pkg/cache/snapshot_test.go
  pkg/hierarchy/cycle.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3032 Update "KEP-168-2: Pending-workloads-visibility" before graduation to Beta
  keps/168-2-pending-workloads-visibility/README.md
  keps/168-2-pending-workloads-visibility/kep.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3041 Rename rest package to v1alpha1.
  pkg/visibility/api/install.go
  pkg/visibility/api/v1alpha1/cluster_queue.go
  pkg/visibility/api/v1alpha1/local_queue.go
  pkg/visibility/api/v1alpha1/pending_workloads_cq.go
  pkg/visibility/api/v1alpha1/pending_workloads_cq_test.go
  pkg/visibility/api/v1alpha1/pending_workloads_lq.go
  pkg/visibility/api/v1alpha1/pending_workloads_lq_test.go
  pkg/visibility/api/v1alpha1/test_utils.go
  pkg/visibility/api/v1alpha1/utils.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3042 [integration][framework]Put bootstrapping in it's own By.
  test/integration/framework/framework.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2969 [doc] Develop ACC task.
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/dev/develop-acc.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3048 Reformat tables.
  site/content/en/docs/adopters/index.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/metrics.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3047 Fix "Should allow fetching information about pending workloads in LocalQueue" e2e test.
  test/e2e/singlecluster/visibility_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3053 Automated cherry pick of #3048: Reformat tables.
  site/content/en/docs/adopters/index.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/metrics.md
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3055 Automated cherry pick of #2857: Bump github.com/golangci/golangci-lint from 1.59.1 to 1.60.1 in /hack/internal/tools
  cmd/kueuectl/app/list/list_clusterqueue.go
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  pkg/util/testing/client.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2967 Lint:ignore U1000 for hierarchy.Cohort struct.
  .golangci.yaml
  pkg/hierarchy/cohort.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2962 [kjobctl] Add describe slurm
  cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
  cmd/experimental/kjobctl/pkg/cmd/describe/helpers.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3050 Use WithKueueClientset and WithK8sClientset methods on TestClientGetter.
  cmd/experimental/kjobctl/pkg/cmd/testing/fake.go
  cmd/kueuectl/app/completion/completion_test.go
  cmd/kueuectl/app/create/create_resourceflavor_test.go
  cmd/kueuectl/app/list/list_clusterqueue_test.go
  cmd/kueuectl/app/list/list_localqueue_test.go
  cmd/kueuectl/app/list/list_pods_test.go
  cmd/kueuectl/app/list/list_resourceflavor_test.go
  cmd/kueuectl/app/list/list_test.go
  cmd/kueuectl/app/list/list_workload_test.go
  cmd/kueuectl/app/testing/fake.go
  cmd/kueuectl/app/util/client_getter.go
  cmd/kueuectl/app/version/version_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2700 Add e2e test for JobSet fix on suspend
  test/e2e/singlecluster/jobset_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3067 Bump sigs.k8s.io/controller-tools to 0.16.3
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_jobtemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayclustertemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayjobtemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3068 Bump github.com/kubeflow/training-operator to 1.8.1
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  vendor/modules.txt
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3006 Support Hierarchical Cohorts in Cache/Snapshot
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/cohort.go
  pkg/cache/resource_node.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/cohort_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3065 Bump github.com/golangci/golangci-lint from 1.60.3 to 1.61.0 in /hack/internal/tools.
  .golangci.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3078 [scheduler] Avoid unnecessary calls
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3073 [kjobctl] Fix fetching VolumeBundles in builder.
  cmd/experimental/kjobctl/pkg/builder/builder.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#3077 Use protobuf encoding for core K8s APIs in kueue
  cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
  cmd/kueuectl/app/util/client_getter.go
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#3083 Move openapi to visibility directory.
  apis/visibility/openapi/doc.go
  apis/visibility/openapi/zz_generated.openapi.go
  hack/update-codegen.sh
  pkg/visibility/server.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3088 Fix current version of visibility API.
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3091 Fix commonLabels deprecated warning.
  config/default/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/visibility/kustomization.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3092 Clean manager image tag in helm after create artifacts.
  Makefile
  charts/kueue/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3093 When the leader election is enabled, set true in leaderElectionReleaseOnCancel
  pkg/config/config.go
  pkg/config/config_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3070 Requeue all inadmissible workloads in Cohort Tree
  pkg/queue/cohort.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3102 Add a BaseWebhook that replaces all kubeflow webhooks
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
Labels: release-note, lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#3100 [kueuectl] Add passthrough integration tests for ClusterQueue and LocalQueue
  test/integration/kueuectl/passthrough_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3105 [kueuectl] Move exec.LookPath("kubectl") to RunE function.
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/passthrough/passthrough.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3107 Update Cohort Documentation; Delete Unused Variable
  apis/kueue/v1alpha1/cohort_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
Labels: lgtm, release-note-none, approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/S

#3043 Add opt-in P&F configs for Visibility API and reference from documentation
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/visibility-apf/flowschema.yaml
  charts/kueue/templates/visibility-apf/prioritylevelconfigurations.yaml
  charts/kueue/values.yaml
  config/components/visibility-apf/flowschema.yaml
  config/components/visibility-apf/kustomization.yaml
  config/components/visibility-apf/prioritylevelconfigurations.yaml
  config/visibility-apf/1_28/kustomization.yaml
  config/visibility-apf/default/kustomization.yaml
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  hack/update-helm.sh
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  test/e2e/config/1_28/kustomization.yaml
  test/e2e/config/common/controller_manager_config.yaml
  test/e2e/config/common/kustomization.yaml
  test/e2e/config/common/manager_e2e_patch.yaml
  test/e2e/config/default/kustomization.yaml
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3104 [kueuectl] Add short description for first level pass-through commands.
  cmd/kueuectl/app/passthrough/passthrough.go
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_clusterqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_localqueue.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3111 Change background color for deprecated feature.
  site/assets/scss/_styles_project.scss
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#3101 Update KEP-2076: Kueuectl.
  keps/2076-kueuectl/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2826 [PartialAdmission] Fix preemption while partially admitting.
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2992 [kueuectl] Delete the corresponding Job when deleting a Workload.
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/completion/completion.go
  cmd/kueuectl/app/completion/completion_test.go
  cmd/kueuectl/app/delete/delete_workload.go
  cmd/kueuectl/app/delete/delete_workload_test.go
  cmd/kueuectl/app/delete/helpers.go
  cmd/kueuectl/app/list/helpers.go
  cmd/kueuectl/app/list/list_localqueue.go
  cmd/kueuectl/app/list/list_pods.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/passthrough/passthrough.go
  cmd/kueuectl/app/testing/fake.go
  cmd/kueuectl/app/util/client_getter.go
  cmd/kueuectl/app/util/helpers.go
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_workload.md
  test/integration/kueuectl/passthrough_test.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3120 RayJob: update Finished() to account for JobDeploymentStatus
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3124 Fix TestUpdateClusterQueue.
  pkg/queue/manager_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3123 [test][integration][ray] Fix cleanup for flavors and priority-class
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#3112 Update "KEP-168-pending-workload-visibility" before deprecation.
  keps/168-pending-workloads-visibility/README.md
  keps/168-pending-workloads-visibility/kep.yaml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3130 [kjobctl] Ignore kubectl.kubernetes.io/last-applied-configuration on copying annotations from template.
  cmd/experimental/kjobctl/pkg/builder/interactive_builder.go
  cmd/experimental/kjobctl/pkg/builder/job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/pod_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_template_wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3110 Deprecate QueueVisibility feature and corresponding API.
  apis/config/v1beta1/configuration_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
Labels: kind/feature, lgtm, release-note-action-required, approved, size/M, cncf-cla: yes

#3054 Integration restart manager
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/deployment/suite_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/job/job_webhook_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/jobset/suite_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/mxjob/suite_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/framework/framework.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/webhook/core/admissioncheck_test.go
  test/integration/webhook/core/clusterqueue_test.go
  test/integration/webhook/core/cohort_test.go
  test/integration/webhook/core/localqueue_test.go
  test/integration/webhook/core/resourceflavor_test.go
  test/integration/webhook/core/suite_test.go
  test/integration/webhook/core/workload_test.go
  test/integration/webhook/jobs/deployment_webhook_test.go
  test/integration/webhook/jobs/job_webhook_test.go
  test/integration/webhook/jobs/jobset_webhook_test.go
  test/integration/webhook/jobs/mpijob_webhook_test.go
  test/integration/webhook/jobs/pod_webhook_test.go
  test/integration/webhook/jobs/raycluster_webhook_test.go
  test/integration/webhook/jobs/rayjob_webhook_test.go
  test/integration/webhook/jobs/suite_test.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#3127 [cache] Add more details in the clusterQueues inactive message.
  apis/kueue/v1beta1/clusterqueue_types.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/util/maps/maps.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: kind/feature, size/L, lgtm, release-note-action-required, approved, cncf-cla: yes

#3129 [kjobctl] Add ownerReference for additional Slurm objects.
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/builder_test.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/job_builder.go
  cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/configmap_wrappers.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#3146 [test][int][multikueue] Ignore error on config namespace multiple creation.
  test/integration/multikueue/suite_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3132 Drop remove operations from webhook patches
  go.mod
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/noop_webhook.go
  pkg/controller/jobframework/webhook/builder.go
  pkg/controller/jobframework/webhook/defaulter.go
  pkg/controller/jobframework/webhook/defaulter_test.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3155 Rename DefaultWebhookFactory to BaseWebhookFactory
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3159 Reformat all imports using gci linter.
  .golangci.yaml
  cmd/experimental/kjobctl/.golangci.yaml
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/completion/completion_test.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_interactive.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_interactive_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_ray_cluster.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_ray_cluster_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_ray_job.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_ray_job_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_slurm.go
  cmd/experimental/kjobctl/pkg/cmd/testing/fake.go
  cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
  cmd/experimental/kjobctl/pkg/cmd/util/helpers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/configmap_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/pod_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go
  cmd/experimental/kjobctl/test/integration/kjobctl/create_test.go
  cmd/kueue/main.go
  cmd/kueuectl/app/list/list_pods_test.go
  cmd/kueuectl/app/stop/stop.go
  cmd/kueuectl/app/util/client_getter.go
  pkg/config/config_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/webhook/builder.go
  pkg/controller/jobframework/webhook/defaulter.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_multikueue_adapter.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/util/kubeversion/kubeversion_test.go
  pkg/visibility/server.go
  test/e2e/multikueue/e2e_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/multikueue/multikueue_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3145 [test][integration] Relax `CheckLatestEvent` to `CheckEventRecordedFor`.
  pkg/util/testing/core.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#3139 [workload] Make better use of container generics
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3152 [batch/job] Allow unsuspending a job with a parallelism equal or less then minimum.
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  test/integration/webhook/jobs/job_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3153 [batch/job] Fix parallelism restoration after partial admission.
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  test/integration/webhook/jobs/job_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#3080 [kjobctl] Split samples.
  cmd/experimental/kjobctl/config/samples/interactive-sample.yaml
  cmd/experimental/kjobctl/config/samples/job-sample.yaml
  cmd/experimental/kjobctl/config/samples/ray-cluster-sample.yaml
  cmd/experimental/kjobctl/config/samples/ray-job-sample.yaml
  cmd/experimental/kjobctl/config/samples/ray_job_volume_bundle.yaml
  cmd/experimental/kjobctl/config/samples/slurm/script.sh
  cmd/experimental/kjobctl/config/samples/slurm/slurm-sample.yaml
  cmd/experimental/kjobctl/config/samples/slurm_volume_bundle.yaml
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#3148 Fix "Failed Pod can be replaced in group" e2e test.
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3156 Add mbobrovskyi to the top level reviewer
  OWNERS
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3166 Fix "SchedulerWithWaitForPodsReady Long PodsReady timeout Should block admission of one new workload if two are considered in the same scheduling cycle" test.
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3013 KEP 2937: Configurable Resource Transformers
  keps/2937-resource-transformer/README.md
  keps/2937-resource-transformer/kep.yaml
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, ok-to-test, kind/documentation, cncf-cla: yes

#3167 Fix description of RBAC directives for external integrations
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes
