Repository kubernetes-sigs/kueue, pull requests merged in 2024-08, with the labels that each got.

#2739 Bump github.com/google/docsy from v0.9.1 to v0.10.0.
  site/go.mod
  site/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2741 [multikueue][e2e] Update job's distributions across workers
  test/e2e/multikueue/e2e_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#2694 Add a step to create a presubmits jobs for the next patch release in the New Release flow
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2743 [kueuectl] Add tabs on installation guide.
  site/content/en/docs/reference/kubectl-kueue/installation.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2754 Add dependabot configuration for the site directory
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2744 Provide Kubeflow PaddleJob support for MultiKueue
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
  pkg/util/testingjobs/paddlejob/wrappers.go
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2758 Relax the CPU threshhold for the perftest
  test/performance/scheduler/default_rangespec.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2759 Add dependabot npm configuration for the site directory.
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2735 Provide Kubeflow PyTorchJob support for MultiKueue
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2736 [kjobctl] Add a localqueue filter to the list job command.
  cmd/experimental/kjobctl/docs/commands/kjobctl_list/kjobctl_list_job.md
  cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_job_test.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
  cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2761 Fail verify test on shellcheck error.
  hack/e2e-common.sh
  hack/multiplatform-build.sh
  hack/verify-shellcheck.sh
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2762 [fixed] Bump github.com/onsi/gomega from 1.34.0 to 1.34.1
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/golang.org/x/crypto/cryptobyte/asn1/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/hkdf/hkdf.go
  vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go
  vendor/golang.org/x/crypto/salsa20/salsa/hsalsa20.go
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/text/message/message.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/golang.org/x/tools/internal/versions/types_go122.go
  vendor/modules.txt
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2763 Enable shellcheck errors.
  .shellcheckrc
  cmd/experimental/kjobctl/hack/update-codegen.sh
  cmd/experimental/podtaintstolerations/hack/e2e-test.sh
  hack/dump_cache.sh
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  hack/multiplatform-build.sh
  hack/push-chart.sh
  hack/update-codegen.sh
  hack/update-helm.sh
  hack/verify-shellcheck.sh
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/performance/e2e/jobs/run-test.sh
  test/performance/e2e/podgroups/run-test.sh
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2765 Fail update-helm.sh on first error.
  hack/update-helm.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2766 Fail push-chart.sh on first error.
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2764 Bump shellcheck version v0.9.0 -> v0.10.0.
  hack/verify-shellcheck.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2746 Provide Kubeflow XGBoostJob support for MultiKueue
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
  pkg/util/testingjobs/xgboostjob/wrappers.go
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2698 Document how to use Kueue for Deployments
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run/deployment.md
  site/static/examples/deployment-kueue/kueue-deployment.yaml
Labels: release-note, size/L, lgtm, approved, kind/documentation, cncf-cla: yes

#2777 [kjobctl] Verify embeded manifest.
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2642 [kjobctl] Build kjobctl executables
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/hack/multiplatform-build.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2780 [kjobctl] Fix shell-lint errors
  cmd/experimental/kjobctl/hack/multiplatform-build.sh
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2781 fix docs: typo on concepts page
  site/content/en/docs/concepts/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2786 [multikueue-e2e]Fix junit reporting
  hack/multikueue-e2e-test.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2787 Set primary instead note color on Note block.
  site/content/en/docs/tasks/manage/setup_multikueue.md
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/mxjobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2779 Update ray examples.
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
  site/static/examples/jobs/ray-cluster-sample.yaml
  site/static/examples/jobs/ray-job-code-sample.yaml
  site/static/examples/jobs/ray-job-sample.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, kind/documentation, cncf-cla: yes

#2793 Add command to wait for Kueue to be fully available on installation guide.
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2792 [kueuectl] Fix examples for create clusterqueue command.
  cmd/kueuectl/app/create/create_clusterqueue.go
  hack/internal/tools/kueuectl-docs/templates/main.html
  keps/2076-kueuectl/README.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_clusterqueue.md
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2704 [site] Update classic preemption candidates selection description.
  site/content/en/docs/concepts/preemption.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2768 [jobframework] Add integration's framework dependencies.
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/setup.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2773 [kjobctl] Add describe interactive command
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
  cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2800 Cleanup preemption.go
  pkg/scheduler/preemption/preemption.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2809 [Partial Admission] Check Mode before attempting Preemption
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2810 [hack] Add compare performance script
  hack/compare-performance.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2805 [kjobctl] Copy labels and annotations from template on builder.
  cmd/experimental/kjobctl/apis/v1alpha1/ray_cluster_template_types.go
  cmd/experimental/kjobctl/apis/v1alpha1/zz_generated.deepcopy.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayclustertemplates.yaml
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/builder_test.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/job_builder.go
  cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/pod_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/pod_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_template_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2814 Move declaration of the Preempted reasons to API pkg
  apis/kueue/v1beta1/workload_types.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  test/integration/scheduler/preemption_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2812 [kjobctl] Make kubectl-kjob binaries statically linked.
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/hack/multiplatform-build.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2803 [kjobctl] Add raycluster flag for RayJob mode.
  cmd/experimental/kjobctl/apis/v1alpha1/application_profile_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_rayjob.md
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_ray_job_printer.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_ray_job_test.go
  cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go
  cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2819 [kjobctl] Add LICENSE file.
  cmd/experimental/kjobctl/LICENSE
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2828 Increase the timeout for waiting for pods to be running.
  test/e2e/singlecluster/visibility_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2811 Prefer Reclamation over Priority Based Preemption
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#2807 Fix using PrioritySortingWithinCohort=false and borrowWithinCohort
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/scheduler/preemption_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#2831 Cherry-pick of #2807 to 0.8
  apis/kueue/v1beta1/workload_types.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/scheduler/preemption_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#2832 Automated cherry pick of #2476: Publish images to new staging registry
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  Makefile
  Makefile-test.mk
  charts/kueue/README.md
  charts/kueue/values.yaml
  cloudbuild.yaml
  cmd/importer/README.md
  cmd/importer/run-in-cluster/kustomization.yaml
  config/components/manager/kustomization.yaml
  hack/dump_cache.sh
  hack/push-chart.sh
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2824 Define hierarchy.Manager
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/hierarchy/wired_clusterqueue.go
  pkg/hierarchy/wired_cohort.go
  pkg/queue/cluster_queue.go
  pkg/queue/cohort.go
  pkg/queue/dumper.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#2836 Allow to bump mdtoc version with dependabot.
  Makefile
  Makefile-deps.mk
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  hack/internal/tools/pinversion.go
  hack/update-toc.sh
  hack/verify-toc.sh
  keps/78-dynamically-reclaiming-resources/README.md
  keps/973-workload-priority/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2842 Add kueue.x-k8s.io_cohorts.yaml helm template.
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2843 Verifying that new generated files are added to git.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2795 attempt to commonize Kubeflow jobs Multikueue support methods
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_multikueue_adapter.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2841 [kjobctl] Delete RayJobs and RayClusters on delete namespace.
  cmd/experimental/kjobctl/test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2860 [kjobctl] Cover completion with tests.
  cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
  cmd/experimental/kjobctl/pkg/cmd/completion/completion_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2864 Graduate MultiplePreemptions to Beta
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
Labels: kind/feature, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2866 Fix hierarchy between flavors and resources in documentation
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2870 Update signature of resetFlavorsAndResources
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2861 Skip flaky e2e MultiKueue test for XGBoost
  test/e2e/multikueue/e2e_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2875 [kueuectl] Use integration manager to get PodLabelSelector.
  cmd/kueuectl/app/list/list_pods.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2877 Add the `kueue.x-k8s.io/managed` label to PodTemplates created by Kueue
  cmd/experimental/podtaintstolerations/test/util/pod.go
  pkg/constants/constants.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/util/testingjobs/pod/wrappers.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_webhook_test.go
  test/integration/importer/importer_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#2873 Fix overadmission after deleting resource from borrowing CQ.
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#2879 Automated cherry pick of #2873: Fixed overadmission after deleting resource from
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot_test.go
  test/integration/scheduler/scheduler_test.go
Labels: release-note, lgtm, size/XL, approved, cncf-cla: yes

#2872 Rename Cohort to Parent
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/hierarchy/wired_clusterqueue.go
  pkg/queue/manager.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2882 Doc: Update outdated PartialAdmission feature state
  site/content/en/docs/tasks/run/jobs.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2574 Start JobFramework controller and webhook on new CRDs availability
  cmd/kueue/main.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobframework/setup_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2857 Bump github.com/golangci/golangci-lint from 1.59.1 to 1.60.1 in /hack/internal/tools
  cmd/kueuectl/app/list/list_clusterqueue.go
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  pkg/util/testing/client.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2890 Remove unnecessary PodLabelSelector integration callback.
  pkg/controller/jobframework/integrationmanager.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2900 Add Copywrites
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/resource.go
  pkg/controller/jobs/pod/event_handlers.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/hierarchy/wired_clusterqueue.go
  pkg/hierarchy/wired_cohort.go
  pkg/queue/cohort.go
  pkg/scheduler/flavorassigner/podset_reducer_test.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/util/kubeversion/kubeversion.go
  pkg/util/kubeversion/kubeversion_test.go
  pkg/webhooks/common.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2886 [kueuectl] Add explanation of --for=pod/foo option.
  cmd/kueuectl/app/list/helpers.go
  cmd/kueuectl/app/list/list_pods.go
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_pods.md
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2887 Increase timeout for pod failing after pod deletion on e2e test.
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2840 Requeue without error if handleJobWithNoWorkload finds a Workload
  pkg/controller/jobframework/reconciler.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2888 Use clock instead time for Preemptor.
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#2859 Upgrade Go version to v1.22.6
  cloudbuild.yaml
  cmd/experimental/kjobctl/README.md
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/hack/tools/go.mod
  go.mod
  hack/internal/tools/go.mod
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2884 Add release notes to the body of the pull request on create cherry-pick.
  hack/cherry_pick_pull.sh
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2908 Rename/Refactor Hierarchy Package
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/hierarchy/clusterqueue.go
  pkg/hierarchy/cohort.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/queue/cluster_queue.go
  pkg/queue/cohort.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2906 Grouping codepending directory for the gomod dependabot configuration
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2903 Deep clone ResourceGroups instead shallow copy on snapshot clusterQueue.
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2904 Fix typos for the Poset with PodSet
  pkg/webhooks/workload_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2909 Graduate LendingLimit to Beta
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot_test.go
  pkg/features/kube_features.go
  pkg/metrics/metrics_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/webhooks/clusterqueue_webhook_test.go
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/scheduler_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2922 Increase the timeout for waiting for pods to be running.
  test/e2e/singlecluster/visibility_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2921 Add a guide for deleting cluster queues.
  site/content/en/docs/tasks/troubleshooting/troubleshooting_delete_clusterqueue.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2925 Fix ResourceFlavorReconciler.AddUpdateWatcher
  pkg/controller/core/resourceflavor_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2928 Remove test nodeLabels from example.
  site/static/examples/admin/single-clusterqueue-setup.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2881 Update ClusterQueue and Cohort Resource Accounting for Hierarchical Cohorts
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/resource.go
  pkg/cache/resource_node.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/hierarchy/cohort.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#2919 Add gauge for skipped preemptions within a cycle
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2935 Update High-level Kueue operation diagram
  site/static/images/theory-of-operation.svg
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2813 [jobframework] Deployment integration
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobframework/noop_controller.go
  pkg/controller/jobframework/noop_webhook.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobs/deployment/deployment_controller.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/util/testingjobs/deployment/wrappers.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/controller/jobs/deployment/deployment_webhook_test.go
  test/integration/controller/jobs/deployment/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2942 Automated cherry pick of #2919: Add gauge for skipped preemptions within a cycle
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2926 Add Job-Integrated Features table
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S
