Repository kubernetes-sigs/kueue, pull requests merged in 2024-10, with the labels that each got.

#3085 [test][integration] Add spec labels support
  Makefile-test.mk
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/framework/framework.go
  test/integration/multikueue/multikueue_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3157 Docs: how to develop a webhook for a job integration
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3135 Move jobsets multikueue run details to separte multikueue subfolder
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/multikueue/_index.md
  site/content/en/docs/tasks/run/multikueue/jobsets.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3039 [test][integration] Start the multikueue test clusters in parallel.
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/framework/framework.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3172 Fix date format in front matter block of docs/concepts/admission_check.md
  site/content/en/docs/concepts/admission_check.md
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#3170 Fix "Should set the condition rejected when the provision fails" test.
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3165 [webhooks] Add namespace selectors for deployment webhooks.
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/kustomization.yaml
  hack/update-helm.sh
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3136 [kjobctl] Use init container to initialise env on Slurm mode.
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#3176 Time sleep optimization on tests.
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3177 [kjobctl] Add local queue validation
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_interactive.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_job.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_raycluster.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_rayjob.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/test/integration/kjobctl/create_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3179 [test][integration] Drop `fwk.RunManager` in favor of `SetupClient` and `StartManager`
  test/integration/framework/framework.go
  test/integration/kueuectl/suite_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/core/suite_test.go
  test/integration/webhook/jobs/pod_webhook_test.go
  test/integration/webhook/jobs/raycluster_webhook_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3171 [kjobctl] Add --priority flag to Slurm mode
  cmd/experimental/kjobctl/apis/v1alpha1/application_profile_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3182 [kjobctl] Add --chdir flag to Slurm mode
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: kind/feature, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#3160 Add steps how to access VisibilityOnDemand via curl
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  site/static/examples/visibility/cluster-role-and-binding.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3190 Add RBAC permissions for ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding resources.
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/util/cert/cert.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#3185 [kjobctl] Fix --mem-per-cpu flag
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3187 [kjobctl] Fix --mem-per-gpu flag
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3193 [kjobctl] Support $SLURM_JOB_NODELIST in Slurm mode.
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/service_wrappers.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3188 [kjobctl] Fix output Slurm variables
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3056 Record an event when provisioning request fails
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3203 Update "KEP-993: Two Stage Admission Process".
  keps/993-two-phase-admission/README.md
  keps/993-two-phase-admission/kep.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3202 Fix `has malformed LC_DYSYMTAB` warning on darwin platform.
  Makefile-test.mk
  cmd/experimental/kjobctl/Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3204 Align the retryDelayMinutes deprecation notice with the standard form
  apis/kueue/v1beta1/admissioncheck_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3207 Automated cherry pick of #3152: [batch/job] Allow unsuspending a job with a parallelism equal or less then minimum.
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  test/integration/controller/jobs/job/job_webhook_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#3208 Automated cherry pick of #3153: [batch/job] Fix parallelism restoration after partial admission.
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  test/integration/controller/jobs/job/job_webhook_test.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#3214 Truncate message when provisioning request creation fails
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: kind/feature, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3201 Add Labels and Annotations to the documentation page.
  site/content/en/docs/reference/labels-and-annotations.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3209 Add integration tests for detecting CRD installed after Kueue started.
  test/integration/controller/jobframework/setup/setup_controllers_test.go
  test/integration/controller/jobframework/setup/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3216 Update Job-integrated features table.
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3221 Bump sigs.k8s.io/controller-tools from 0.16.3 to 0.16.4 in /cmd/experimental/kjobctl/hack/tools.
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_jobtemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayclustertemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_rayjobtemplates.yaml
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_volumebundles.yaml
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3226 Bump sigs.k8s.io/controller-tools from 0.16.3 to 0.16.4 in /hack/internal/tools
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3225 Upgrade Go version to 1.23
  Dockerfile
  cmd/experimental/kjobctl/README.md
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/hack/tools/go.mod
  go.mod
  hack/internal/tools/go.mod
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3227 Update KEP-349 to reflect actual state of the `WaitForPodsReady` API
  keps/349-all-or-nothing/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3181 KEP-3122: Expose Flavors in LocalQueue Status.
  keps/3122-expose-flavors-in-localqueue-status/README.md
  keps/3122-expose-flavors-in-localqueue-status/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3012 [kjobctl] Add documentation for Slurm mode
  cmd/experimental/kjobctl/docs/run_slurm.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3228 PodSet label and Workload annotation for PodTemplates
  apis/kueue/v1alpha1/tas_types.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#3236 use constant for podUUID
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3240 Use E2eTestSleepImage constant on e2e tests.
  test/e2e/singlecluster/jobset_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3242 Add deployment integration framework on manifests.
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3238 [kjobctl] Use busybox init image.
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3241 Add `kueue.x-k8s.io/pod-group-fast-admission` annotation on docs.
  site/content/en/docs/reference/labels-and-annotations.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3237 TAS: KEP update for API
  keps/2724-topology-aware-schedling/README.md
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3248 Fix "Scheduler with WaitForPodsReady Suite"
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3251 Update TAS KEP after API discussions
  keps/2724-topology-aware-schedling/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#3126 Add JobManagedBy feature docs for Kubeflow
  site/content/en/docs/tasks/run/multikueue/_index.md
  site/content/en/docs/tasks/run/multikueue/jobsets.md
  site/content/en/docs/tasks/run/multikueue/kubeflow.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3244 [test][MK][e2e] Change the way JobManagedBy feature gate is enabled.
  hack/multikueue-e2e-test.sh
  hack/multikueue/manager-cluster.kind-1.30.0.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3026 Implementation of Configurable Resource Transformers
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podsetrequest.go
  client-go/applyconfiguration/kueue/v1beta1/workloadstatus.go
  client-go/applyconfiguration/utils.go
  cmd/kueue/main.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  keps/2937-resource-transformer/README.md
  keps/2937-resource-transformer/kep.yaml
  pkg/cache/cache.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/features/kube_features.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/scheduler/suite_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#3260 test cleanup: replace equality.DeepEqual by gomega.BeComparableTo
  test/integration/scheduler/workload_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#3264 Change the insufficient resource event type from Normal to Warning
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, release-note-action-required, approved, ok-to-test, size/XS, cncf-cla: yes

#3143 Expose available ResourceFlavors from the ClusterQueue in the LocalQueue status.
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuestatus.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  keps/3122-expose-flavors-in-localqueue-status/README.md
  pkg/cache/cache.go
  pkg/controller/core/localqueue_controller.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/core/localqueue_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#3262 TAS: Add scheduling gate to Pods admitted by TAS
  pkg/podset/podset.go
  pkg/podset/podset_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3268 Add example transformation parameters to the controllerConfig
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3213 [Kjobctl] Extend priority flag to other modes
  cmd/experimental/kjobctl/apis/v1alpha1/application_profile_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_interactive.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_job.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_raycluster.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_rayjob.md
  cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#3270 TAS: move expecatations store to utils to share with TopologyUngater
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/expectations/store.go
  pkg/util/expectations/store_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3255 Wait for the prebuild workload.
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  site/content/en/docs/reference/labels-and-annotations.md
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#3252 [test][util] Add 'ExpectClusterQueuesToBeActive'
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/kueuectl/list_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3272 Await for pods to be running before delete all pods.
  test/e2e/singlecluster/e2e_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3277 Use -ldflags=-linkmode=internal to fix malformed LC_DYSYMTAB issue.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3271 TAS: introduce dedicated TAS label
  apis/kueue/v1alpha1/tas_types.go
  keps/2724-topology-aware-schedling/README.md
  pkg/podset/podset.go
  pkg/podset/podset_test.go
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3267 [kjobctl] Fix crash issue in Slurm mode when ntasks > 1
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3175 Add user documentation for KEP-2937 to website
  site/content/en/docs/tasks/manage/administer_cluster_quotas.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#3266 TAS: TopologyUngater
  cmd/kueue/main.go
  go.mod
  pkg/controller/tas/constants.go
  pkg/controller/tas/controllers.go
  pkg/controller/tas/indexer.go
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/util/tas/tas.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#3281 [kjobctl] Use -ldflags=-linkmode=internal to fix malformed LC_DYSYMTAB issue.
  cmd/experimental/kjobctl/Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3180 [kjobctl] Move unmask_filename to go.
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3283 Set deprecated PreRelease for QueueVisibility feature.
  pkg/features/kube_features.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3256 TAS: Compute the topology assignments
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/cache/tas_cache.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/core/cohort_controller_test.go
  pkg/controller/jobframework/tas.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/tas/constants.go
  pkg/controller/tas/controllers.go
  pkg/controller/tas/resource_flavor.go
  pkg/debugger/debugger.go
  pkg/resources/requests.go
  pkg/resources/requests_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  test/e2e/config/common/manager_e2e_patch.yaml
  test/integration/tas/suite_test.go
  test/integration/tas/tas_job_test.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#3278 [KEP] Add retry strategy to the ProvisionigRequestConfig API
  keps/1136-provisioning-request-support/README.md
  keps/1136-provisioning-request-support/kep.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3280 [kjobctl] Move SBATCH_ variables to entrypoint script.
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3253 [kjobctl] Init e2e tests
  cmd/experimental/kjobctl/Makefile
  cmd/experimental/kjobctl/hack/e2e-test.sh
  cmd/experimental/kjobctl/hack/tools/go.mod
  cmd/experimental/kjobctl/hack/tools/go.sum
  cmd/experimental/kjobctl/hack/tools/pinversion.go
  cmd/experimental/kjobctl/test/e2e/e2e_test.go
  cmd/experimental/kjobctl/test/e2e/suite_test.go
  cmd/experimental/kjobctl/test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3254 [MultiKueue] Introduce Admission Check Validation feature gate
  apis/kueue/v1beta1/clusterqueue_types.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/multikueue/multikueue_test.go
Labels: size/L, lgtm, release-note-action-required, approved, ok-to-test, cncf-cla: yes

#3282 Add topology spread constraints to manager deployment
  charts/kueue/templates/manager/manager-pdb.yaml
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#3287 Add more clarify on how reclaimWithinCohort interacts with fair sharing
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#3133 [KEP] Maximum Execution Time
  keps/3125-maximum-execution-time/README.md
  keps/3125-maximum-execution-time/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3291 TAS: cleanups after merging main PRs
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/tas/topology_ungater.go
  test/integration/tas/tas_job_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3001 StatefulSet integration
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/webhook/webhook.yaml
  config/components/manager/controller_manager_config.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/jobs.go
  pkg/controller/jobs/statefulset/statefulset_controller.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/statefulset/wrappers.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/static/examples/deployment-kueue/kueue-statefulset.yaml
  test/e2e/config/common/controller_manager_config.yaml
  test/e2e/singlecluster/statefulset_test.go
  test/integration/webhook/jobs/statefulset_webhook_test.go
Labels: release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#3288 [kjobctl] Skip removing ConfigMap on delete Slurm.
  cmd/experimental/kjobctl/pkg/cmd/delete/delete_slurm.go
  cmd/experimental/kjobctl/pkg/cmd/delete/delete_slurm_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3294 Add more clarify on how reclaimWithinCohort interacts with fair shari…
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#3297 [MultiKueue] Fix a typo in cluster queue type constant
  apis/kueue/v1beta1/clusterqueue_types.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#3298 [doc] fix typos on website
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
  site/content/en/docs/tasks/run/multikueue/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#3284 TAS: introduce sanity e2e test
  test/e2e/singlecluster/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3184 [workload] Add maximum execution time.
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/workloadspec.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/core/workload_controller_test.go
  test/integration/webhook/core/workload_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3292 TAS: include usage from non-TAS Pods
  pkg/cache/snapshot.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3303 Fix "Stateful set integration when Single CQ should admit group that fits" test.
  test/e2e/singlecluster/statefulset_test.go
  test/util/util.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3304 Remove statefulSetUID parameter from GetWorkloadName.
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  test/e2e/singlecluster/statefulset_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3305 TAS: Remeve unused status subresource
  apis/kueue/v1alpha1/tas_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  client-go/applyconfiguration/kueue/v1alpha1/topology.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/fake/fake_topology.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/topology.go
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3309 Propagate gomega.Gomega on multikueue tests.
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3289 Support MPIJob managedBy feature for the MultiKueue
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#3311 HierarchicalCohort: Remove unused status field
  apis/kueue/v1alpha1/cohort_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3191 [jobs]Add max execution time
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3318 Use IsNegativeErrorMsg in the apimachnery lib instead of self deined one
  pkg/config/validation.go
  pkg/constants/constants.go
  pkg/webhooks/clusterqueue_webhook.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3200 [workload] Accumulate past admitted time.
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/workloadstatus.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/scheduler/scheduler.go
  pkg/util/testing/wrappers.go
  pkg/workload/admissionchecks.go
  pkg/workload/admissionchecks_test.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/core/workload_controller_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/performance/scheduler/runner/controller/controller.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3324 [nit] Remove redundant "that" in workload.md
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#3325 Add gomega status condition matcher.
  pkg/util/testing/condition_matchers.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3296 Remove alculquicondor from OWNERS
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  OWNERS
  SECURITY_CONTACTS
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3301 TAS: validate the preferred and required annotations for Job and JobSet
  pkg/controller/jobframework/tas_validation.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3326 Propagate gomega.Gomega on integration/webhook tests.
  pkg/util/testing/error_matchers.go
  test/integration/webhook/core/admissioncheck_test.go
  test/integration/webhook/core/clusterqueue_test.go
  test/integration/webhook/core/localqueue_test.go
  test/integration/webhook/core/workload_test.go
  test/integration/webhook/jobs/job_webhook_test.go
  test/integration/webhook/jobs/pod_webhook_test.go
  test/integration/webhook/jobs/raycluster_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3327 Propagate gomega.Gomega on integration/controller/core tests.
  test/integration/controller/core/admissioncheck_controller_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/resourceflavor_controller_test.go
  test/integration/controller/core/workload_controller_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#3328 Propagate gomega.Gomega on integration/controller/jobs tests.
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3329 Propagate gomega.Gomega on integration/scheduler tests.
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#3330 Propagate gomega.Gomega on integration tests.
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/framework/framework.go
  test/integration/kueuectl/passthrough_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3342 Bump sigs.k8s.io/controller-tools from 0.16.4 to 0.16.5 in /hack/internal/tools
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3341 Bump sigs.k8s.io/jobset from 0.6.0 to 0.7.0.
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/openapi_generated.go
  vendor/sigs.k8s.io/jobset/pkg/constants/constants.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3323 Reset all Ready and Ready AdmissionChecks on Eviction as Pending
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
  test/e2e/singlecluster/e2e_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3340 TAS: surface errors when building snapshot
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller_test.go
  pkg/debugger/debugger.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3348 Use HaveConditionStatusTrue instead of IsStatusConditionTrue.
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3320 TAS: validation for CQs using TAS
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  pkg/cache/clusterqueue.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler_test.go
  pkg/controller/admissionchecks/provisioning/constants.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer.go
  pkg/controller/admissionchecks/provisioning/indexer_test.go
  test/e2e/singlecluster/tas_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/tas/tas_job_test.go
  test/integration/tas/tas_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3316 [MultiKueue] Document MPI Operator managedBy field
  site/content/en/docs/tasks/run/multikueue/kubeflow.md
  site/content/en/docs/tasks/run/multikueue/mpijob.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#3356 Fix "Should requeue the workload with a delay when the connection to …
  test/integration/multikueue/multikueue_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3355 Automated cherry pick of #3102: Add a BaseWebhook that replaces all kubeflow webhooks
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
Labels: release-note, lgtm, size/XXL, approved, cncf-cla: yes

#3354 Force status field ownership by core Kueue to fix the MultiKueue integration
  pkg/workload/workload.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3358 Automated cherry pick of #3132: Drop remove operations from webhook patches
  go.mod
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/webhook/builder.go
  pkg/controller/jobframework/webhook/defaulter.go
  pkg/controller/jobframework/webhook/defaulter_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#3347 Propagate gomega.Gomega.
  test/e2e/singlecluster/pod_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3364 Use previously created context instead of the background
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/localqueue_controller_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#3369 Fix "Pod groups when Single CQ should admit group that fits" test.
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3312 Stateful set integration docs
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run/deployment.md
  site/content/en/docs/tasks/run/statefulset.md
  site/static/examples/serving-workloads/sample-deployment.yaml
  site/static/examples/serving-workloads/sample-statefulset.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3367 Fix "Short PodsReady timeout Should requeue a workload which exceeded…
  test/integration/scheduler/podsready/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3374 Fix "Workload controller when the workload has a maximum execution ti…
  test/integration/controller/core/workload_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3376 TAS: Extend job TestPodSet.
  pkg/controller/jobs/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3378 TAS: Add jobset TestPodSet.
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/util/testingjobs/jobset/wrappers.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3379 TAS: Support RayJob.
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3361 TAS: introduce scheduler-level tests
  pkg/cache/clusterqueue.go
  pkg/cache/tas_cache_test.go
  pkg/controller/tas/resource_flavor.go
  pkg/scheduler/scheduler_test.go
  pkg/util/tas/tas.go
  pkg/util/testing/wrappers.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#3373 TAS: Skip RFs which don't match PodSet TAS requirements
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3383 Skip further checks after NotFound error on ExpectPodsFinalizedOrGone() and ExpectWorkloadsFinalizedOrGone() functions.
  test/util/util.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3321 [kjobctl] Add --time flag on Slurm mode.
  cmd/experimental/kjobctl/apis/v1alpha1/application_profile_types.go
  cmd/experimental/kjobctl/config/crd/bases/kjobctl.x-k8s.io_applicationprofiles.yaml
  cmd/experimental/kjobctl/docs/run_slurm.md
  cmd/experimental/kjobctl/go.mod
  cmd/experimental/kjobctl/go.sum
  cmd/experimental/kjobctl/pkg/builder/builder.go
  cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
  cmd/experimental/kjobctl/pkg/cmd/create/create.go
  cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
  cmd/experimental/kjobctl/pkg/cmd/printcrds/embed/manifest.gz
  cmd/experimental/kjobctl/pkg/parser/slurm.go
  cmd/experimental/kjobctl/pkg/parser/slurm_test.go
  cmd/experimental/kjobctl/pkg/parser/time_limit.go
  cmd/experimental/kjobctl/pkg/parser/time_limit_test.go
  cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#3389 Cleanup debug log in provisioning integration tests
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3391 TAS: Cleanup flavor assigner check
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3394 TAS: Merge tas_test.go and tas_job_test.go together.
  test/integration/tas/tas_job_test.go
  test/integration/tas/tas_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3390 TAS: update KEP based on the recent discussions
  keps/2724-topology-aware-scheduling/README.md
  keps/2724-topology-aware-scheduling/kep.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/S

#3395 Cherry-pick of Reset all Ready and Ready AdmissionChecks on Eviction as Pending (#3323)
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
  test/e2e/singlecluster/e2e_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3397 TAS: Add sanity e2e test for JobSet.
  test/e2e/singlecluster/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3402 TAS: Support Pod.
  pkg/constants/constants.go
  pkg/controller/jobframework/tas.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3386 TAS: Support RayCluster.
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3392 TAS: Add integration tests for job.
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/job/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3399 TAS: skip flavor checks which don't have requested level
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3384 [KubeRay] Support NumOfHosts when calculating PodSet assignments
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/util/testingjobs/raycluster/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes
