Repository kubernetes-sigs/kueue, pull requests merged in 2024-05, with the labels that each got.

#2106 Fix UTs for preemption with borrowing, missing CQ
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2110 Reduce preemptions within ClusterQueue when preemption with borrowing is enabled
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2111 Automated cherry pick of #2110: Reduce preemptions within ClusterQueue when preemption with
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#2093 KEP 2076: Kueuectl
  keps/2076-kueuectl/README.md
  keps/2076-kueuectl/kep.yaml
  keps/487-kubectl-plugin/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2027 [kueuectl] Create Local Queue
  Makefile
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/create/create.go
  cmd/kueuectl/app/create/create_localqueue.go
  cmd/kueuectl/app/create/create_localqueue_test.go
  cmd/kueuectl/app/util/dry_run.go
  cmd/kueuectl/app/util/helpers.go
  cmd/kueuectl/main.go
  go.mod
  go.sum
  hack/multiplatform-build.sh
  site/content/en/docs/reference/kubectl-kueue.md
  test/e2e/singlecluster/kueuectl_test.go
  test/e2e/singlecluster/suite_test.go
  test/integration/kueuectl/create_test.go
  test/integration/kueuectl/suite_test.go
  test/integration/kueuectl/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#2107 Stable API to encapsulate Job validation for webhooks
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2063 Fix transitions of Requeued condition
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/workload/workload.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/job/suite_test.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2123 Add troubleshooting note for pending admission checks
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2120 Doc for troubleshooting queues
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_queues.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2142 Relax the threshold for the "Average wait for admission" scalability test
  test/performance/scheduler/default_rangespec.yaml
Labels: lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2143 Сlear RequeuAt on workload backoff finished
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2131 Move the eviction by inactivation mechanism from the jobframework reconciler to the workload controller
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#1442 Add examples for namespaceSelector via matchLabels and matchExpressions.
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#2152 [doc] Fix sample manifests path
  site/content/en/docs/admission-check-controllers/provisioning.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#2099 Add sidecar containers to resource requests computation
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/testing/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#2151 Fixing a bug when provisioned condition is missing
  pkg/controller/admissionchecks/provisioning/controller.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#2098 Automated cherry pick of #2087: fix(helm): wrong secret name in certificate
  charts/kueue/templates/certmanager/certificate.yaml
  charts/kueue/templates/internalcert/secret.yaml
Labels: release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#2159 Automated cherry pick of #2099: Add sidecar containers to resource requests computation
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/testing/wrappers.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#2158 Fix "should requeued after job status ready" test.
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#2128 fix(helm): ensure Manager Deployment is restarted when config changes
  charts/kueue/templates/manager/manager.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2042 [KEP] Support new ProvisioningRequest's conditions
  keps/1136-provisioning-request-support/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2070 Add APIs for configuring fair sharing
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/values.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  client-go/applyconfiguration/kueue/v1beta1/fairsharing.go
  client-go/applyconfiguration/utils.go
  cmd/kueue/main.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/manager/controller_manager_config.yaml
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/clusterqueue_webhook.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/integration/webhook/clusterqueue_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#2130 Reorganize validations for the frameworks and the externalFrameworks
  cmd/kueue/main.go
  cmd/kueue/main_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobframework/setup_test.go
Labels: size/L, lgtm, release-note-none, approved, needs-rebase, kind/cleanup, cncf-cla: yes

#2083 [scalability] Collect extra information by default (metrics and logs)
  Makefile
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2122 [kueuectl] Added validation for ClusterQueue on creating LocalQueue.
  cmd/kueuectl/app/create/create_localqueue.go
  site/content/en/docs/reference/kubectl-kueue.md
  test/e2e/singlecluster/kueuectl_test.go
  test/integration/kueuectl/create_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#2166 Enforce the pre null pointer check for the Integrations when performing WithEnabledFrameworks()
  cmd/kueue/main.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/setup_test.go
Labels: release-note, lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#2150 Change the Admitted condition reason while using admission checks.
  pkg/workload/admissionchecks.go
  pkg/workload/admissionchecks_test.go
  test/integration/controller/core/workload_controller_test.go
Labels: lgtm, release-note-action-required, approved, kind/cleanup, cncf-cla: yes, size/S

#2165 [multikueue] Reconcile the relevant ACs on cluster create.
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#1955 add a metric for eviction number in cluster queue
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/queue/manager.go
  pkg/scheduler/preemption/preemption.go
  pkg/util/testing/metrics/metrics.go
  pkg/util/testing/metrics/metrics_test.go
  site/content/en/docs/reference/metrics.md
  test/integration/controller/core/workload_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: release-note, size/L, lgtm, approved, needs-rebase, ok-to-test, cncf-cla: yes

#2164 [e2e/pod] Wait independently for pods and workload deletion.
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2161 Disabled scheduler on "should requeued after job status ready" test.
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/job/suite_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2170 Set Subsystem for the evicted_workloads_total metric
  pkg/metrics/metrics.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2171 Fixed panic on report evicted workloads.
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#2048 [MultiKueue] Default managedBy for ClusterQueues configured to use MultiKueue AC
  cmd/kueue/main.go
  pkg/cache/cache.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/visibility/api/rest/pending_workloads_lq.go
  site/content/en/docs/tasks/run/jobsets.md
  test/e2e/singlecluster/jobset_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2172 Should update Evicted condition only when the Workload have not already got Eviction
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1963 [multikueue] Add file system kubeconfig watch.
  go.mod
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/fswatch.go
  pkg/controller/admissionchecks/multikueue/fswatch_test.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#2116 Split Makefile to test, debug, external-crds, tools
  Makefile
  Makefile-deps.mk
  Makefile-test.mk
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2147 Expose Provisioning Request status as events for Pods/Jobs
  pkg/controller/jobframework/events.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2177 Update and improve the visibility API documentation
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2176 Remove default namespace
  config/default/kustomization.yaml
  config/visibility/kustomization.yaml
  config/visibility/role_binding_visibility_transformer.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2134 [kueuectl] Add stop/resume workload commands
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/options/update_workload_activation_options.go
  cmd/kueuectl/app/resume/resume.go
  cmd/kueuectl/app/resume/resume_workload.go
  cmd/kueuectl/app/stop/stop.go
  cmd/kueuectl/app/stop/stop_workload.go
  site/content/en/docs/reference/kubectl-kueue/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/create.md
  site/content/en/docs/reference/kubectl-kueue/commands/resume.md
  site/content/en/docs/reference/kubectl-kueue/commands/stop.md
  site/content/en/docs/reference/kubectl-kueue/installation.md
  test/integration/kueuectl/resume_test.go
  test/integration/kueuectl/stop_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2189 Cleanup the TODO in the integration test
  test/integration/scheduler/podsready/scheduler_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#2187 [jobs] refactor GenericJob.Finished implementation
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, needs-ok-to-test, cncf-cla: yes

#2190 Split "should requeued after job status ready" test.
  test/integration/controller/jobs/job/job_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#2160 Propagate the reason for Eviction into the pod TerminationTarget condition
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2186 Restructure integration page and add content on external integrations
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#2156 [kueuectl] List cluster queues
  cmd/kueuectl/app/list/helpers.go
  cmd/kueuectl/app/list/list.go
  cmd/kueuectl/app/list/list_clusterqueue.go
  cmd/kueuectl/app/list/list_clusterqueue_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kubectl-kueue/_index.md
  site/content/en/docs/reference/kubectl-kueue/commands/list.md
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2000 Fix lint issues reported by gocritic
  .golangci.yaml
  cmd/importer/pod/check.go
  cmd/importer/pod/import.go
  pkg/config/validation.go
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/pod/expectations.go
  pkg/queue/manager_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler_test.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/resource/resource.go
  pkg/util/testing/client.go
  pkg/util/testing/wrappers.go
  pkg/visibility/api/rest/pending_workloads_cq_test.go
  pkg/visibility/api/rest/pending_workloads_lq_test.go
  pkg/workload/workload.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2184 Remove gci linter because it breaks import comments
  .golangci.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#2197 Fix ms function implementation
  .golangci.yaml
  pkg/util/wait/backoff_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#2185 Enhance troubleshooting for pending jobs
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2202 Refactor variable names according to Go style guide
  .golangci.yaml
  apis/config/v1beta1/defaults.go
  apis/visibility/v1alpha1/defaults.go
  cmd/importer/pod/import.go
  pkg/controller/admissionchecks/multikueue/fswatch.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler_test.go
  pkg/util/resource/resource_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/performance/scheduler/runner/main.go
  test/performance/scheduler/runner/recorder/recorder.go
  test/performance/scheduler/runner/scraper/scraper.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2203 Automated cherry pick of #2185: Enhance troubleshooting for pending jobs
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2211 Skip invalid fswatch tests on Mac OS.
  pkg/controller/admissionchecks/multikueue/fswatch_test.go
Labels: lgtm, kind/failing-test, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#2199 Refactor to use filepath.Join instead of path.Join for consistency
  cmd/importer/util/util_test.go
  pkg/controller/admissionchecks/multikueue/fswatch_test.go
  test/integration/multikueue/multikueue_test.go
  test/performance/scheduler/runner/generator/generator_test.go
  test/performance/scheduler/runner/main.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2214 configAPI: Implement waitForPodsReady validations
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#2210 Add default parameters in the waitForPodsReady configuration
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2212 [pods] Consider deleted pods without `spec.nodeName` inactive.
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#2224 [release-0.6] WaitForPodsReady: Load the backoffLimitCount regardless of the requeueingStrategy.timestamp
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#2181 [kueuectl] Pass-through commands.
  Makefile-test.mk
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/localqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  cmd/kueuectl/app/cmd.go
  cmd/kueuectl/app/passthrough/passthrough.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  keps/2076-kueuectl/README.md
  site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
  test/integration/kueuectl/passthrough_test.go
  test/integration/kueuectl/suite_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#2229 Automated cherry pick of #2131: Move the eviction by inactivation mechanism from the
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#2241 Automated cherry pick of #2189: Cleanup the TODO in the integration test
  test/integration/scheduler/podsready/scheduler_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2236 Flaky test: Pod groups when Single CQ should admit group that fits.
  test/e2e/singlecluster/pod_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#2249 Automated cherry pick of #2236: Fixed "Pod groups when Single CQ should admit group that
  test/e2e/singlecluster/pod_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2248 Relax the the constraints for the average CPU usage during performance scheduler tests.
  test/performance/scheduler/default_rangespec.yaml
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2250 [test/int/kueuectl] Delete the used CQ at the end of stop/resume tests.
  test/integration/kueuectl/resume_test.go
  test/integration/kueuectl/stop_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2230 Added "should evict workload due workload deactivated on pods ready timeout" test.
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/suite_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2253 Automated cherry pick of #2230: Added "should evict workload due workload deactivated on pods
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_webhook_test.go
  test/integration/controller/jobs/pod/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#2251 Set DefaultRequeuingBackoffBaseSeconds to 60s.
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  keps/1282-pods-ready-requeue-strategy/README.md
  pkg/controller/core/workload_controller.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/tasks/manage/setup_sequential_admission.md
Labels: lgtm, release-note-action-required, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#2254 [preemption] Use strict patching when issuing evictions.
  pkg/scheduler/preemption/preemption.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2162 servicemonitorCRD is need before install prometheus.yaml
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2252 Pod controller: "when Using pod group Should keep the running pod group with the queue name if workload is evicted" flakes
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/util/util.go
Labels: lgtm, kind/failing-test, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#2262 Automated cherry pick of #2239: Plain Pod gets deleted once admitted via ProvisioningRequest
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/equality/podset.go
  pkg/util/equality/podset_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#2261 Follow-up of #2239
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/equality/podset_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#2264 Add limit to the retry period for re-queing workloads
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#2274 [release-0.6]Update golangci-lint to 1.55.2
  Makefile
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#2273 Cherry pick of #1819 to release-0.6
  go.mod
  go.sum
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/client.go
  pkg/workload/workload_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#2265 [workload] Allow specifying PodSetUpdates for a subset of PodSets
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/webhook/workload_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#2281 Automated cherry pick of #2265: [workload] Allow specifying PodSetUpdates for a subset of PodSets
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#2219 WaitForPodsReady: Reset .status.requeueState.count once the workload is deactivated
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#2276 Show fair share of a CQ in status and a metric
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuestatus.go
  client-go/applyconfiguration/kueue/v1beta1/fairsharingstatus.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/metrics/metrics.go
  site/content/en/docs/reference/kueue.v1beta1.md
  site/content/en/docs/reference/metrics.md
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#2220 [release-0.6] WaitForPodsReady: Reset .status.requeueState once the workload is deactivated
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#2195 [kueuectl] Added list workloads command.
  cmd/kueuectl/app/list/helpers.go
  cmd/kueuectl/app/list/list.go
  cmd/kueuectl/app/list/list_clusterqueue.go
  cmd/kueuectl/app/list/list_localqueue_test.go
  cmd/kueuectl/app/list/list_test.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/list/list_workload_printer.go
  cmd/kueuectl/app/list/list_workload_test.go
  cmd/kueuectl/app/testing/fake.go
  cmd/kueuectl/app/util/client_getter.go
  cmd/kueuectl/app/util/helpers.go
  keps/2076-kueuectl/README.md
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kubectl-kueue/commands/list.md
  test/integration/kueuectl/list_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#2289 Chore: Remove HasRequeueState helper function
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2290 [scalability] Adjust the threshold for small workloads
  test/performance/scheduler/default_rangespec.yaml
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#2292 Prepare release v0.6.3
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2286 [provisionong-AC] Check the limits for used resources.
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/workload/resources.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#2294 Add additional fix to v0.6.3
  CHANGELOG/CHANGELOG-0.6.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2296 Dependabot actions
  .github/dependabot.yml
  .github/workflows/openvex.yaml
  .github/workflows/sbom.yaml
Labels: kind/bug, lgtm, release-note-none, approved, kind/cleanup, do-not-merge/hold, cncf-cla: yes, size/S

#2301 Fix SBOM filename to latest openssf convention
  .github/workflows/sbom.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2303 Use a bigger machine for cloudbuild
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2306 [kueuectl] Include kubectl-kueue binary on release artifacts
  Makefile
Labels: kind/feature, release-note, lgtm, approved, size/XS, cncf-cla: yes

#2304 Update latest version to v0.6.3
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2309 ConfigAPI: Implement the non negative validation for the queueVisibility.clusterQueues.maxCount
  pkg/config/validation.go
  pkg/config/validation_test.go
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#2310 Add the default parameters in the waitForPodsReady.requeuingStrategy.backoffMaxSeconds
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#2268 Allow podSet count to be 0
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/scheduler/flavorassigner/podset_reducer_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/workload_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#2312 Use root Go version in gh-actions
  .github/workflows/sbom.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2005 Use k8s 1.30 API and testing infra.
  Makefile-test.mk
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
Labels: release-note, lgtm, size/XXL, approved, kind/cleanup, cncf-cla: yes

#2319 [test-integration] Don't panic after `Framework.Init` failure.
  test/integration/framework/framework.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2323 Fix indentation of commented out configurations
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#2315 improve debuggability in jobset controller tests
  test/integration/controller/jobs/jobset/jobset_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#2326 Enhance documentation for admissionChecksStrategy
  site/content/en/docs/admission-check-controllers/provisioning.md
  site/content/en/docs/concepts/admission_check.md
  site/content/en/docs/concepts/cluster_queue.md
  site/static/examples/provisioning/provisioning-setup.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2333 [kueuectl] Build binaries to artifact directory
  Makefile
  hack/multiplatform-build.sh
  site/content/en/docs/reference/kubectl-kueue/installation.md
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#2328 Add documentation for the excludeResourcePrefixes
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  site/content/en/docs/tasks/manage/administer_cluster_quotas.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2327 WaitForPodsReady: Add documentation for the backoffMaxSeconds
  site/content/en/docs/tasks/manage/setup_sequential_admission.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#2322 Add documentation for fair sharing
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/installation/_index.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2332 Prepare release-0.7 branch
  CHANGELOG/CHANGELOG-0.7.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  config/components/manager/kustomization.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#2338 Move checkout action to the top
  .github/workflows/sbom.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#2337 Use latest patch version for golang
  go.mod
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes
