Repository kubernetes-sigs/kueue, pull requests merged in 2024-01, with the labels that each got.

#1528 Verbose logging of cache and queues
  cmd/kueue/main.go
  pkg/cache/snapshot.go
  pkg/debugger/debugger.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/dumper.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/logging.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1467 Generate SBOM on each release
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  .github/workflows/sbom.yaml
Labels: lgtm, release-note-none, approved, size/M, sig/release, cncf-cla: yes

#1541 Debug image and cache dump script
  Makefile
  cloudbuild.yaml
  hack/debugpod/Dockerfile
  hack/dump_cache.sh
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#1544 Fix flaky test: hold CQ until all workloads are observed
  test/integration/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#1397 Support Preemption while borrowing
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/borrowwithincohort.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuepreemption.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/scheduler/preemption_test.go
  test/integration/webhook/clusterqueue_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1549 Split visibility tests into their own file
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/visibility_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1547 Fix flaky test: add a dedicated finalizer to verify the pod's status after the workload is evicted
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, size/L, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes

#1561 Fix preemption within cohort when there is no borrowingLimit
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#1563 Align all kubebuilder markers with leading space
  apis/config/v1beta1/configuration_types.go
  apis/kueue/v1beta1/admissioncheck_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/workloadpriorityclass_types.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/util/cert/cert.go
  pkg/visibility/server.go
  test/e2e/singlecluster/suite_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/jobset/suite_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/multikueue/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, needs-ok-to-test, cncf-cla: yes

#1564 Automated cherry pick of #1561: Fix the borrowing while preemption when no borrowingLimit
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#1556 UT for replacement in pod group with different phases
  pkg/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1502 Pod group concurrent reconciles
  pkg/controller/jobframework/indexer.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/workload_names.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/util/testing/wrappers.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#1567 Helm: Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob and JobSet
  charts/kueue/templates/webhook/webhook.yaml
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#1569 [integration/multikueue] Check only the created workload spec.
  test/integration/multikueue/multikueue_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#1523 Fix: remove workload finalizer if workload is finished
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1572 Skip recreating a workload for a finished job
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testingjobs/mxjob/wrappers.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#1562 Trigger the workloads eviction on admission check rejection.
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/workload/workload.go
  test/integration/controller/core/workload_controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1573 Finalize deleted gated Pods from groups without a Workload
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1576 Add unit test for preemption while borrowing when multiple jobs in a cycle
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1579 Use constant gvk for pod owner index
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, kind/regression, release-note-none, approved, cncf-cla: yes, size/S

#1583 [release-0.5] Fix: remove workload finalizer if workload is finished
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1581 Fix the flake preemption while borrowing unit test
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#1584 Upgrade version of sleep image for consistency
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  site/content/en/docs/tasks/run_python_jobs.md
  site/static/examples/jobs/sample-job-partial-admission.yaml
  site/static/examples/jobs/sample-job.yaml
  site/static/examples/provisioning/sample-job.yaml
  site/static/examples/python/sample-job.py
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/visibility_test.go
  test/performance/job.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#1577 E2E tests partial pod groups and replacements
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/pod_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1304 Adding toleration to the job doesn't trigger workload change
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/util/equality/podset.go
  pkg/util/equality/podset_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#1585 Fix syncing of the second provisioning request
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: kind/bug, release-note, size/L, lgtm, kind/flake, approved, cncf-cla: yes

#1588 Use constants in the supportedPrebuildWlJobGVKs
  pkg/controller/jobframework/validation.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1504 update kind to 0.20.0
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1594 Use log level 3 in E2E tests
  test/e2e/config/kustomization.yaml
  test/e2e/config_1_26/kustomization.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1592 Wrapping errors when cleaning up pods
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1586 Replace the no need Eventf() with Event()
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1595 Automated cherry pick of #1351: Support retry for provisioning requests
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/util/testing/util.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Labels: release-note, lgtm, size/XL, approved, cncf-cla: yes

#1589 Increase reconcilers for Pod
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  test/e2e/config/controller_manager_config.yaml
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#1604 Event for pod admission once per pod
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1597 Add documentation about PrioritySortingWithinCohort feature
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1542 Make ordering timestamp configurable when Workload evicted due to Pods-ready
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  cmd/kueue/main.go
  pkg/config/config_test.go
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_best_effort_fifo_test.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_interface.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/cluster_queue_strict_fifo_test.go
  pkg/queue/manager.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/podsready/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, kind/api-change, ok-to-test, cncf-cla: yes

#1598 Set default leader election configuration
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/groupversion_info.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/config/v1beta1/zz_generated.defaults.go
  pkg/config/config_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1610 Prepare release for v0.5.2
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1611 Arguments for ginkgo in E2E tests
  Makefile
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1614 Update an issue template for the new release
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1613 Update latest version to v0.5.2
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1609 Simplify generic job reconciler factory
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1616 Automated cherry pick of #1613: Update latest version to v0.5.2
  CHANGELOG/CHANGELOG-0.5.md
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1617 Do not (re)create ProvReq is the state of admission check is Ready
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#1621 Explicit non-goal for distributing Jobs across multiple worker clusters
  keps/693-multikueue/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#1632 Parallelize operations in groups of pods
  pkg/controller/jobs/pod/pod_controller.go
  pkg/util/parallelize/parallelize.go
  pkg/util/parallelize/parallelize_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1623 Do not cleanup excess pods when awaiting to observe previous clean ups
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/pod/expectations.go
  pkg/controller/jobs/pod/expectations_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1620 Automated cherry pick of #1617: Do not (re)create ProvReq is the state of admission check is
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#1637 Add the integrationOptions to jobframework.Options
  cmd/kueue/main.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1639 add jobset to tasks
  site/content/en/docs/tasks/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1644 Fix kueue crashing when clearing outdated assignment on log level 6
  pkg/scheduler/flavorassigner/flavorassigner.go
Labels: kind/bug, release-note, lgtm, kind/regression, approved, do-not-merge/hold, size/XS, cncf-cla: yes

#1554 Add HA support for the visibility API
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/controller/core/leader_aware_reconciler.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  test/e2e/config/kustomization.yaml
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#1653 Pod groups: add a note about not recreating pods deleted by kueue
  keps/976-plain-pods/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#1650 Use a native slices library
  pkg/config/validation.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1638 Pod groups: e2e tests for diverse pods and preemption
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/pod_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1560 [Helm]Add script to sync webhookConfigurations to helm charts automatically
  charts/kueue/templates/webhook/service.yaml
  charts/kueue/templates/webhook/webhook.yaml
  hack/update-helm.sh
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1652 Use leader election defaulting to set up controllers HA
  pkg/controller/core/leader_aware_reconciler.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/jobset/suite_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/mxjob/suite_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/framework/framework.go
  test/integration/multikueue/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/webhook/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1672 Improve links in KEP #1136
  keps/1136-provisioning-request-support/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1670 Prevent cluster queue webhook from panicking for existing resources
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#1633 k8s 1.29 bump
  apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/informers/externalversions/factory.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  go.mod
  go.sum
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/webhooks/resourceflavor_webhook_test.go
  pkg/webhooks/workload_webhook_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes
