Repository kubernetes-sigs/kueue, pull requests merged in 2024-12, with the labels that each got.

#3689 Add NodeWrapper for testing
  pkg/cache/tas_cache_test.go
  pkg/util/testingjobs/node/wrappers.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3701 Use NodeWrapper in test files
  pkg/scheduler/scheduler_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#3697 Fix pod-group tas tests
  test/e2e/tas/pod_group_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#3691 Fix preemption.findCandidates for Hierarchical Cohorts
  pkg/cache/cohort_snapshot.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3707 Add release checklist to add new periodic for patch release
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3704 TAS: Extend `PodSetTopologyRequest` API by index labels
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podsettopologyrequest.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  keps/2724-topology-aware-scheduling/README.md
  pkg/controller/jobframework/tas.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3715 Fix Kueue crashing when a node is deleted
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3708 TAS: Sort domains by the level values, change leaves' ids to hostname
  pkg/cache/tas_flavor_snapshot.go
  pkg/util/slices/slices.go
  pkg/util/slices/slices_test.go
  pkg/util/testing/wrappers.go
  test/integration/tas/tas_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3714 TAS: validate that kubernetes.io/hostname can only be at the lowest level
  apis/kueue/v1alpha1/tas_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  test/integration/tas/tas_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#3722 Fix assigning ResourceFlavor tolerations during assignment
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3652 KEP-2936: LocalQueue defaulting
  keps/2936-local-queue-defaulting/README.md
  keps/2936-local-queue-defaulting/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3717 Use ReadUIntFromLabelWithMax to get and validate pod index.
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/pod/pod.go
  pkg/util/pod/pod_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3725 fix table indenting
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3685 Fix live-updates for kubernetes Job getting stuck occasionally
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
Labels: kind/bug, release-note, lgtm, kind/flake, approved, cncf-cla: yes, size/S

#3732 Remove node.kubernetes.io/not-ready taint if status active after creation.
  pkg/controller/tas/indexer/indexer.go
  pkg/util/slices/slices.go
  pkg/util/tas/tas.go
  pkg/util/testingjobs/node/wrappers.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3684 Fix rolling update for StatefulSet integration
  hack/e2e-common.sh
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/pod/wrappers.go
  pkg/util/testingjobs/statefulset/wrappers.go
  site/content/en/docs/reference/labels-and-annotations.md
  test/e2e/singlecluster/statefulset_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/util/e2e.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3692 Add Serving Workload section on KEP-976.
  keps/976-plain-pods/README.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3736 Check resource deletion in tas e2e tests
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/pod_group_test.go
Labels: lgtm, kind/flake, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#3739 Step down kerthcet as approvers
  OWNERS
  pkg/controller/OWNERS
  pkg/util/OWNERS
  pkg/webhooks/OWNERS
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3712 Implementation of KEP-3589: uniformly filter manageJobsWithoutQueueNames by namespace
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  cmd/kueue/main.go
  config/components/manager/controller_manager_config.yaml
  keps/3589-manage-jobs-selectively/kep.yaml
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/webhook/jobs/job_webhook_test.go
  test/integration/webhook/jobs/pod_webhook_test.go
  test/integration/webhook/jobs/raycluster_webhook_test.go
  test/util/util.go
Labels: release-note, lgtm, size/XXL, approved, cncf-cla: yes

#3727 kueue-viz: Dashboard for kueue: Initial commit
  cmd/experimental/kueue-viz/.gitignore
  cmd/experimental/kueue-viz/CONTRIBUTING.md
  cmd/experimental/kueue-viz/LICENSE
  cmd/experimental/kueue-viz/README.md
  cmd/experimental/kueue-viz/backend/.gitignore
  cmd/experimental/kueue-viz/backend/CONTRIBUTING.md
  cmd/experimental/kueue-viz/backend/Dockerfile
  cmd/experimental/kueue-viz/backend/Makefile
  cmd/experimental/kueue-viz/backend/README.md
  cmd/experimental/kueue-viz/backend/go.mod
  cmd/experimental/kueue-viz/backend/go.sum
  cmd/experimental/kueue-viz/backend/handlers/cluster_queues.go
  cmd/experimental/kueue-viz/backend/handlers/cohorts.go
  cmd/experimental/kueue-viz/backend/handlers/gvr.go
  cmd/experimental/kueue-viz/backend/handlers/handlers.go
  cmd/experimental/kueue-viz/backend/handlers/local_queue_workloads.go
  cmd/experimental/kueue-viz/backend/handlers/local_queues.go
  cmd/experimental/kueue-viz/backend/handlers/resource_flavors.go
  cmd/experimental/kueue-viz/backend/handlers/websocket_handler.go
  cmd/experimental/kueue-viz/backend/handlers/workloads.go
  cmd/experimental/kueue-viz/backend/handlers/workloads_dashboard.go
  cmd/experimental/kueue-viz/backend/kubernetes_client.go
  cmd/experimental/kueue-viz/backend/main.go
  cmd/experimental/kueue-viz/examples/00-resource-flavor.yaml
  cmd/experimental/kueue-viz/examples/01-cluster-queues.yaml
  cmd/experimental/kueue-viz/examples/02-local-queues.yaml
  cmd/experimental/kueue-viz/examples/03-agi-job.yaml
  cmd/experimental/kueue-viz/examples/04-llm-job.yaml
  cmd/experimental/kueue-viz/examples/05-cancer-cure-research.yaml
  cmd/experimental/kueue-viz/examples/07-workload-priority-classes.yaml
  cmd/experimental/kueue-viz/frontend/.env
  cmd/experimental/kueue-viz/frontend/.gitignore
  cmd/experimental/kueue-viz/frontend/CONTRIBUTING.md
  cmd/experimental/kueue-viz/frontend/Dockerfile
  cmd/experimental/kueue-viz/frontend/Makefile
  cmd/experimental/kueue-viz/frontend/package.json
  cmd/experimental/kueue-viz/frontend/public/env.js
  cmd/experimental/kueue-viz/frontend/public/favicon.ico
  cmd/experimental/kueue-viz/frontend/public/index.html
  cmd/experimental/kueue-viz/frontend/public/kueue-viz.png
  cmd/experimental/kueue-viz/frontend/react-inject-env.config.js
  cmd/experimental/kueue-viz/frontend/src/App.css
  cmd/experimental/kueue-viz/frontend/src/App.js
  cmd/experimental/kueue-viz/frontend/src/ClusterQueueDetail.js
  cmd/experimental/kueue-viz/frontend/src/ClusterQueues.js
  cmd/experimental/kueue-viz/frontend/src/CohortDetail.js
  cmd/experimental/kueue-viz/frontend/src/Cohorts.js
  cmd/experimental/kueue-viz/frontend/src/Dashboard.js
  cmd/experimental/kueue-viz/frontend/src/FlavorTable.js
  cmd/experimental/kueue-viz/frontend/src/LocalQueueDetail.js
  cmd/experimental/kueue-viz/frontend/src/LocalQueues.js
  cmd/experimental/kueue-viz/frontend/src/Navbar.js
  cmd/experimental/kueue-viz/frontend/src/ResourceFlavorDetail.js
  cmd/experimental/kueue-viz/frontend/src/ResourceFlavors.js
  cmd/experimental/kueue-viz/frontend/src/WorkloadDetail.js
  cmd/experimental/kueue-viz/frontend/src/Workloads.js
  cmd/experimental/kueue-viz/frontend/src/WorkloadsList.js
  cmd/experimental/kueue-viz/frontend/src/env.js
  cmd/experimental/kueue-viz/frontend/src/index.js
  cmd/experimental/kueue-viz/frontend/src/useWebSocket.js
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#3738 TAS: Make ResourceFlavorSpec that defines `topologyName` immutable
  apis/kueue/v1beta1/resourceflavor_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  test/integration/tas/tas_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#3745 Automated cherry pick of #3244: [test][MK][e2e] Change the way JobManagedBy feature gate is enabled.
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  hack/multikueue/manager-cluster.kind-1.30.0.yaml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3673 Implement Prometheus metrics for LocalQueue
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/controller/core/core.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/workload_controller.go
  pkg/features/kube_features.go
  pkg/metrics/metrics.go
  pkg/queue/local_queue.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  test/integration/controller/core/clusterqueue_controller_test.go
  test/integration/controller/core/localqueue_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, kind/api-change, ok-to-test, cncf-cla: yes

#3747 Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.
  charts/kueue/README.md
  charts/kueue/values.yaml
  cmd/experimental/podtaintstolerations/config/deployment.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#3750 Automated cherry pick of #3747: Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.
  charts/kueue/README.md
  charts/kueue/values.yaml
  cmd/experimental/podtaintstolerations/config/deployment.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: release-note, lgtm, approved, size/XS, cncf-cla: yes

#3744 Use variadic function to set levels in TopologyWrapper
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#3752 Use QueueNameForObject in StatefulSet Webhook.
  pkg/controller/jobs/statefulset/statefulset_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3751 TAS: Support rank-based ordering for StatefulSet.
  apis/kueue/v1alpha1/tas_types.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/statefulset/wrappers.go
  site/content/en/docs/reference/labels-and-annotations.md
  test/e2e/tas/statefulset_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3753 Sort labels and annotations.
  site/content/en/docs/reference/labels-and-annotations.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3748 document manageJobsNamespaceSelector
  site/content/en/docs/tasks/manage/enforce_job_management/_index.md
  site/content/en/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md
  site/content/en/docs/tasks/manage/enforce_job_management/setup_job_admission_policy.md
  site/static/examples/sample-validating-policy.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3766 optimize pod web hook by avoiding deep copy when no updates were made
  pkg/controller/jobs/pod/pod_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3765 managedJobsNamespaceSelector for Deployment, StatefulSets, and Pods
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/defaults_test.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3771 Remove Denkensk from Kueue reviewers
  OWNERS
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3773 Replace time.Now() with clock.Now() in pkg/core
  pkg/controller/core/clusterqueue_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#3610 Implement default LocalQueue
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/features/kube_features.go
  pkg/queue/local_queue.go
  pkg/queue/manager.go
  site/content/en/docs/installation/_index.md
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3734 [Flaky] Integration tests - Using cohorts for sharing unused resources
  test/integration/scheduler/scheduler_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#3763 Refresh Kueue roadmap on the main page for 2025
  README.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3777 use node 22 instead of node 16
  cmd/experimental/kueue-viz/frontend/Dockerfile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3781 README.md: Fix some minor typos
  README.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3780 Configure Dependabot for kueue-viz.
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3793 Bump babel/plugin-proposal-private-property-in-object from 7.18.6 to 7.21.11
  cmd/experimental/kueue-viz/frontend/package.json
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3800 [website] Add Innovatrics adopter
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, needs-ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3806 Update resource group example
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3795 Do not default the queue-name for jobs with kueue managed owners
  pkg/controller/jobframework/defaults.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3769 Add default topologies for tests
  pkg/cache/cache_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/defaults.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/statefulset_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#3805 add configuration for setting feature gates
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  cmd/kueue/main.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#3810 generate should generate kueuectl and apiref rather than verify
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3811 Bump kube rbac proxy
  charts/kueue/values.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3803 fix default suspension of Deployment/StatefulSet with Kueue-managed owners
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/webhook/webhook.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3770 Deactivate ClusterQueue if there is no Topology
  apis/kueue/v1beta1/clusterqueue_types.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/controller/tas/resource_flavor.go
  pkg/queue/manager.go
  test/integration/tas/tas_test.go
Labels: kind/bug, kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#3814 Use lock when accessing IsIntegrationEnabled
  pkg/controller/jobframework/integrationmanager.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3816 Add kueue.x-k8s.io/pod-suspending-parent to the documentation page.
  site/content/en/docs/reference/labels-and-annotations.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3815 Use annotation rather than label for serving workloads
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/deployment/wrappers.go
  pkg/util/testingjobs/statefulset/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3823 Automated cherry pick of #3719: Use TopologyWrapper and ResourceFlavorWrapper in tests #3744: Use variadic function to set levels in TopologyWrapper #3769: Add default topologies for tests
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/defaults.go
  pkg/util/testing/wrappers.go
  test/e2e/singlecluster/tas_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#3783 Documentation for LocalQueueDefaulting
  site/content/en/docs/reference/labels-and-annotations.md
  site/content/en/docs/tasks/manage/enforce_job_management/setup_default_local_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3817 avoid hardcoding framework names in pod wehook
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobs/pod/pod_webhook.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3828 update Pod integration docs to prefer managedJobsNamespaceSelector
  site/content/en/docs/tasks/run/deployment.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/run/statefulset.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3826 add section to metrics with (alpha) LQ metrics
  site/content/en/docs/reference/metrics.md
Labels: lgtm, release-note-none, approved, size/M, needs-ok-to-test, kind/documentation, cncf-cla: yes

#3605 Added Log output for LocalQueue and ClusterQueue
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/visibility/api/v1beta1/pending_workloads_cq_test.go
  pkg/visibility/api/v1beta1/pending_workloads_lq_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#3825 update golang crypto to 0.31.0
  cmd/experimental/kueue-viz/backend/go.mod
  cmd/experimental/kueue-viz/backend/go.sum
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.s
  vendor/golang.org/x/sys/cpu/asm_darwin_x86_gc.s
  vendor/golang.org/x/sys/cpu/cpu_darwin_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.s
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/syscall_darwin_x86_gc.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: kind/bug, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#3832 [release-0.9] [Manual cherry-pick] 1Added Log output for LocalQueue and ClusterQueue
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/visibility/api/v1alpha1/pending_workloads_cq_test.go
  pkg/visibility/api/v1alpha1/pending_workloads_lq_test.go
  pkg/visibility/api/v1beta1/pending_workloads_cq_test.go
  pkg/visibility/api/v1beta1/pending_workloads_lq_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3819 Automated cherry pick of #3770: Deactivate ClusterQueue if there is no Topology
  apis/kueue/v1beta1/clusterqueue_types.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/core.go
  pkg/controller/tas/resource_flavor.go
  pkg/queue/manager.go
  test/integration/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3833 [release-0.9]: upgrade crypto to 0.31
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.s
  vendor/golang.org/x/sys/cpu/asm_darwin_x86_gc.s
  vendor/golang.org/x/sys/cpu/cpu_darwin_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.s
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/syscall_darwin_x86_gc.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: kind/bug, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#3834 drop pod taints toleration from kueue repo
  cmd/experimental/podtaintstolerations/.dockerignore
  cmd/experimental/podtaintstolerations/.gitignore
  cmd/experimental/podtaintstolerations/Dockerfile
  cmd/experimental/podtaintstolerations/Makefile
  cmd/experimental/podtaintstolerations/README.md
  cmd/experimental/podtaintstolerations/config/cluster-role-binding-manager.yaml
  cmd/experimental/podtaintstolerations/config/cluster-role-binding-pods.yaml
  cmd/experimental/podtaintstolerations/config/cluster-role-binding-proxy.yaml
  cmd/experimental/podtaintstolerations/config/cluster-role-pods.yaml
  cmd/experimental/podtaintstolerations/config/deployment.yaml
  cmd/experimental/podtaintstolerations/config/kustomization.yaml
  cmd/experimental/podtaintstolerations/config/role-binding-leaderelection.yaml
  cmd/experimental/podtaintstolerations/config/service-account.yaml
  cmd/experimental/podtaintstolerations/controller/pod_jobs.go
  cmd/experimental/podtaintstolerations/examples/pod-highpriority.yaml
  cmd/experimental/podtaintstolerations/examples/pod.yaml
  cmd/experimental/podtaintstolerations/examples/priorities.yaml
  cmd/experimental/podtaintstolerations/examples/queue.yaml
  cmd/experimental/podtaintstolerations/go.mod
  cmd/experimental/podtaintstolerations/go.sum
  cmd/experimental/podtaintstolerations/hack/e2e-test.sh
  cmd/experimental/podtaintstolerations/hack/kind-cluster.yaml
  cmd/experimental/podtaintstolerations/main.go
  cmd/experimental/podtaintstolerations/test/e2e/config/kustomization.yaml
  cmd/experimental/podtaintstolerations/test/e2e/e2e_test.go
  cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
  cmd/experimental/podtaintstolerations/test/util/pod.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3838 Check if unexpected errors did not occur in queue unit testings
  pkg/queue/manager_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3835 Fix memory leak due to workload entries left in MultiKueue cache
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3843 Automated cherry pick of #3835: Fix memory leak due to workload entries left in MultiKueue cache
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3836 Distinguish errors for non-existing LocalQueue and ClusterQueue in the workload-controller
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3824 Use kueue.x-k8s.io/resource-in-use finalizer for Topology.
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/tas/constants.go
  pkg/controller/tas/controllers.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  test/e2e/singlecluster/tas_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3729 Add RayJob submitter job into PodSets
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/webhook/jobs/raycluster_webhook_test.go
Labels: kind/bug, size/L, lgtm, release-note-action-required, approved, cncf-cla: yes

#3847 Automated cherry pick of #3725: fix table indenting
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3862 Prepare release v0.9.2
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3864 Automated cherry pick of #3863: Update latest kueue v0.10.0
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3865 Add changelog v0.9.2
  CHANGELOG/CHANGELOG-0.9.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3869 Bump braces from 3.0.2 to 3.0.3 in /site
  site/package-lock.json
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3871 Remove unused kueue-viz frontend dependencies
  cmd/experimental/kueue-viz/frontend/package.json
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3848 Move topologyHandler logic to topology controller.
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#3876 fix logging of manager configuration
  cmd/kueue/main.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#3849 Adds build and push of kueue-viz images
  Makefile
  cloudbuild.yaml
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#3882 Add section about Workload's requeueState field to KEP#349
  keps/349-all-or-nothing/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#3883 Build for only one platform on kueue-viz-image target.
  Makefile
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3879 Refresh Kueue features overview page
  README.md
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#3885 Talks and presentations page for Kueue
  README.md
  site/content/en/docs/contribution guidelines/_index.md
  site/content/en/docs/talks_and_presentations/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3891 Wait for finalizer added to the topology on integration test.
  test/integration/tas/tas_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3895 address non-linear parsing of case-insensitive content
  cmd/experimental/kueue-viz/backend/go.mod
  cmd/experimental/kueue-viz/backend/go.sum
  go.mod
  go.sum
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/modules.txt
Labels: kind/bug, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#3910 Fix: kueue-manager-role can not update topologies
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/tas/topology_controller.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#3870 Replace `time.Now()` with `clock.Clock.Now()` in pkg/workload/workload.go
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/performance/scheduler/runner/controller/controller.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3908 [Fix] Remove the requirement for VAP
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/util/cert/cert.go
  pkg/visibility/server.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S
