Repository kubernetes-sigs/kueue, pull requests merged in 2024-03, with the labels that each got.

#1782 Fix run make target: update path to main.go
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1781 Fix test lint issues reported by ginkgolinter
  .golangci.yaml
  cmd/experimental/podtaintstolerations/test/e2e/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/visibility_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/scheduler_test.go
  test/integration/webhook/workload_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#1740 Update autoscaler dependency to fix CVE
  go.mod
  go.sum
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1796 Revert "Update autoscaler dependency to fix CVE (#1740)"
  go.mod
  go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1799 Upgrade golangci-lint to `v1.56.2`
  Makefile
Labels: lgtm, kind/failing-test, release-note-none, approved, ok-to-test, size/XS, priority/critical-urgent, cncf-cla: yes

#1766 [pods] Finalize the replaced pods
  keps/976-plain-pods/README.md
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/slices/slices.go
  pkg/util/slices/slices_test.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/pod_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: release-note, lgtm, size/XL, approved, cncf-cla: yes

#1801 [release-0.6][pods] Finalize the replaced pods
  keps/976-plain-pods/README.md
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/slices/slices.go
  pkg/util/slices/slices_test.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/pod_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1793 KEP #1788: Passing parameters to ProvisioningRequest
  keps/1788-pass-parameters-to-ProvReq/README.md
  keps/1788-pass-parameters-to-ProvReq/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#1805 Discard the alpha infix in the ProvReq annotation name
  keps/1788-pass-parameters-to-ProvReq/README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#1804 Fix "Update autoscaler dependency to fix CVE (#1740)"
  go.mod
  go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1803 Fixes typos in variables, comments, and tests
  .golangci.yaml
  apis/visibility/v1alpha1/conversion_test.go
  pkg/cache/cache_test.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/validation.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/util/maps/maps_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/e2e/multikueue/e2e_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, kind/documentation, cncf-cla: yes

#1806 [multikueue] Cluster connection monitoring and reconnect.
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  test/e2e/multikueue/e2e_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#1681 [multikueue] Manage worker cluster unavailability
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  cmd/kueue/main.go
  cmd/kueue/main_test.go
  pkg/config/config_test.go
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1797 Simplify code by removing unnecessary conversions
  .golangci.yaml
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/controller/jobs/rayjob/rayjob_controller_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1811 [performance test] Fix cluster-queue template and update api version
  test/performance/local-queue.yaml
  test/performance/prerequisites/cluster-queue.template
  test/performance/prerequisites/resource-flavor.yaml
  test/performance/run-test.sh
Labels: lgtm, kind/failing-test, release-note-none, approved, size/M, kind/cleanup, needs-ok-to-test, cncf-cla: yes

#1808 Improve readability of job controller unit tests
  pkg/controller/jobs/job/job_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1815 Generalize heap implementation
  pkg/queue/cluster_queue_best_effort_fifo.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/cluster_queue_strict_fifo.go
  pkg/queue/local_queue.go
  pkg/util/heap/heap.go
  pkg/util/heap/heap_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1552 Add shellcheck for verifying shell scripts
  Makefile
  cmd/experimental/podtaintstolerations/hack/e2e-test.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  hack/update-helm.sh
  hack/verify-shellcheck.sh
  test/performance/run-test.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#1819 Bump sigs.k8s.io/controller-runtime to v0.17.2
  go.mod
  go.sum
  pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/client.go
  pkg/workload/workload_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1817 Revert "Bump github.com/ray-project/kuberay/ray-operator (#1786)"
  go.mod
  go.sum
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1770 Fix incorrect snapshot usage when lendingLimit enabled
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#1822 Avoid requeue on ClusterQueue status update
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/workload_controller.go
  pkg/metrics/metrics.go
  pkg/queue/cluster_queue_impl.go
  pkg/queue/cluster_queue_impl_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  test/integration/scheduler/scheduler_test.go
  test/util/util.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#1823 [multikueue] Decrease the number logged errors
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1827 [multikueue] Don't use reconnecting clients in WL reconnecting.
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1831 [e2e] Fix visibility tests.
  config/visibility/kustomization.yaml
Labels: kind/bug, lgtm, kind/failing-test, release-note-none, approved, size/XS, cncf-cla: yes

#1810 Enable govet linter; disable vet in make verify
  .golangci.yaml
  Makefile
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1830 [e2e] Restore the manager's image from the bash scripts.
  Makefile
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1835 Fix number of reconcilers for Pod integration
  config/components/manager/controller_manager_config.yaml
  pkg/controller/jobs/pod/pod_controller.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#1839 Clean up test utils
  pkg/util/testing/client.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1836 [release-0.6] [e2e] Restore the manager's image from the bash scripts. (Cherry pick #1830)
  Makefile
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#1838 WaitForPodsReady: Reset the requeueState while reconciling
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/core/workload_controller.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/webhook/workload_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#1843 Automated cherry pick of #1838: WaitForPodsReady: Reset the requeueState while reconciling
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/core/workload_controller.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/webhook/workload_test.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#1820 Do not make API calls when the workload already has condition Admitted=false
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#1845 Automated cherry pick of #1820: Do not make API calls when the workload already has condition
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#1847 Prepare release v0.6.1
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1848 Update latest version to v0.6.1
  CHANGELOG/CHANGELOG-0.6.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  site/config.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#1846 Do not default to suspending a job whose parent is already managed by Kueue
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  test/integration/controller/jobs/raycluster/raycluster_webhook_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1853 Flaky integration test "RayCluster Job controller interacting with scheduler"
  test/integration/controller/jobs/raycluster/raycluster_controller_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1857 [doc] fix website broken links
  site/content/en/docs/admission-check-controllers/provisioning.md
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/contribution guidelines/_index.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run_python_jobs.md
  site/content/en/docs/tasks/setup_sequential_admission.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#1856 [doc] fix typo in 'GitHub'
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  site/content/en/_index.html
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1855 Fix typo in resource_flavor.md
  site/content/en/docs/concepts/resource_flavor.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1861 [doc] Catch up the recent changes in kubernetes-template-project
  CONTRIBUTING.md
  SECURITY.md
Labels: lgtm, release-note-none, approved, needs-ok-to-test, kind/documentation, cncf-cla: yes, size/S

#1773 KEP-1714: Fair Sharing
  keps/1714-fair-sharing/README.md
  keps/1714-fair-sharing/kep.yaml
  keps/1714-fair-sharing/lca.png
Labels: kind/feature, size/L, lgtm, release-note-none, approved, kind/api-change, cncf-cla: yes

#1863 update verify shellcheck to reduce the time to less than 15min
  hack/verify-shellcheck.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1866 Fix preemption blocked by earlier pending Workload
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/scheduler/preemption_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1825 Add pod importer
  cmd/importer/README.md
  cmd/importer/main.go
  cmd/importer/pod/check.go
  cmd/importer/pod/check_test.go
  cmd/importer/pod/import.go
  cmd/importer/pod/import_test.go
  cmd/importer/util/util.go
  go.mod
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  test/integration/framework/framework.go
  test/integration/importer/importer_test.go
  test/integration/importer/suite_test.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#1878 [importer] Extend mapping capabilities.
  cmd/importer/README.md
  cmd/importer/main.go
  cmd/importer/pod/check.go
  cmd/importer/pod/check_test.go
  cmd/importer/pod/import.go
  cmd/importer/pod/import_test.go
  cmd/importer/util/util.go
  cmd/importer/util/util_test.go
  go.mod
  test/integration/importer/importer_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#1875 Avoid unnecessary preemptions when candidates have the same timestamp
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/util/testing/wrappers.go
  test/integration/scheduler/preemption_test.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#1881 [importer] Add missing header in test file.
  cmd/importer/util/util_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1883 Use the setup-evnvtest version compatible with go 1.21
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#1879 Troubleshooting: checking whether job is admitted or preempted
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/troubleshooting/_index.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1884 Upgrade to Hugo Modules
  Makefile
  netlify.toml
  site/archetypes/default.md
  site/assets/scss/_styles_project.scss
  site/assets/scss/_variables_project.scss
  site/content/en/_index.html
  site/go.mod
  site/go.sum
  site/hugo.toml
  site/layouts/partials/feedback.html
  site/package-lock.json
  site/package.json
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1882 [importer] Run in cluster
  Makefile
  cloudbuild.yaml
  cmd/importer/Dockerfile
  cmd/importer/README.md
  cmd/importer/run-in-cluster/deps.yaml
  cmd/importer/run-in-cluster/importer.yaml
  cmd/importer/run-in-cluster/kustomization.yaml
  cmd/importer/run-in-cluster/mapping.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#1890 test: use utilruntime package wrap panic method
  pkg/controller/admissionchecks/multikueue/indexer_test.go
  pkg/controller/admissionchecks/provisioning/indexer_test.go
  pkg/util/admissioncheck/admissioncheck_test.go
  pkg/util/testing/client.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1887 drop special config for 126
  hack/e2e-common.sh
  test/e2e/config_1_26/kustomization.yaml
  test/e2e/config_1_26/manager_e2e_patch.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1891 [cloudbuild] Build all images in a single step.
  Makefile
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1895 bump to golang 1.22
  go.mod
Labels: kind/feature, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#1888 Organize tasks into folders
  README.md
  cmd/experimental/README.md
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/concepts/workload.md
  site/content/en/docs/concepts/workload_priority_class.md
  site/content/en/docs/overview/_index.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/dev/_index.md
  site/content/en/docs/tasks/dev/enabling_pprof_endpoints.md
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
  site/content/en/docs/tasks/manage/_index.md
  site/content/en/docs/tasks/manage/administer_cluster_quotas.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/_index.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  site/content/en/docs/tasks/manage/rbac.md
  site/content/en/docs/tasks/manage/run_job_with_workload_priority.md
  site/content/en/docs/tasks/manage/setup_multikueue.md
  site/content/en/docs/tasks/manage/setup_sequential_admission.md
  site/content/en/docs/tasks/monitor_pending_workloads/_index.md
  site/content/en/docs/tasks/run/_index.md
  site/content/en/docs/tasks/run/flux_miniclusters.md
  site/content/en/docs/tasks/run/jobs.md
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/kubeflow/_index.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/mxjobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/run/python_jobs.md
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
  site/static/_redirects
  site/static/examples/python/README.md
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1900 [doc] typo fixes on site
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/content/en/docs/tasks/manage/setup_sequential_admission.md
  site/layouts/shortcodes/include.html
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1862 [doc] typo fixes on keps
  keps/1136-provisioning-request-support/README.md
  keps/693-multikueue/README.md
  keps/78-dynamically-reclaiming-resources/kep.yaml
  keps/976-plain-pods/README.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#1889 Troubleshooting pods
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#1872 Introduce the ClusterAutoscaler APIs module
  Makefile
  cmd/kueue/main.go
  go.mod
  go.sum
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer.go
  pkg/controller/admissionchecks/provisioning/indexer_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1905 Fix Pod finalizers for succeeded groups
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#1869 Passing parameters to ProvisioningRequest from annotations
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/constants/constants.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/mxjob/wrappers.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#1897 Dereference StopPolicy before equality check
  pkg/controller/core/workload_controller.go
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#1915 Automated cherry pick of #1872: Introduce the ClusterAutoscaler APIs module
  Makefile
  cmd/kueue/main.go
  go.mod
  go.sum
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer.go
  pkg/controller/admissionchecks/provisioning/indexer_test.go
  test/integration/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/controller/admissionchecks/provisioning/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#1919 Adjust base timeouts for integration and E2E tests
  test/e2e/singlecluster/pod_test.go
  test/util/constants.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#1902 add e2e test for single cluster jobset
  Makefile
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  test/e2e/singlecluster/jobset_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#1923 docs: Fix broken link in Kubernetes Jobs guide
  site/content/en/docs/tasks/run/flux_miniclusters.md
  site/content/en/docs/tasks/run/jobs.md
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/mxjobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/run/python_jobs.md
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
  site/static/_redirects
Labels: lgtm, release-note-none, approved, size/M, needs-ok-to-test, kind/documentation, cncf-cla: yes

#1921 e2e speedup
  Makefile
  test/e2e/multikueue/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#1927 Fix README formatting
  cmd/importer/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#1840 Load shellcheck configuration from the .shellcheckrc
  .shellcheckrc
  hack/verify-shellcheck.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#1907 [jobframework] Return all errors when updating workload status
  .golangci.yaml
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#1929 Mention published importer image tag
  cmd/importer/README.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#1930 Cleanup resources created by the preemption integration test
  test/integration/scheduler/preemption_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes
