Repository kubernetes-sigs/kueue, pull requests merged in 2025-10, with the labels that each got.

#7075 Follow-up: Refactor reconcile_test to use AfterEach for default namespace cleanup
  test/e2e/customconfigs/reconcile_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#7094 Bump the all group in /cmd/kueueviz/frontend with 3 updates
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#7097 Update KEP-77 calling out additional Beta graduation criteria.
  keps/77-dynamically-sized-jobs/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#7109 Add JobWithSkip interface compliance check for *Pod.
  pkg/controller/jobs/pod/pod_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#7115 [Cleanup] Use clock in WorkloadSlicing funcs
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/scheduler.go
  pkg/util/testing/wrappers.go
  pkg/workloadslicing/workloadslicing.go
  pkg/workloadslicing/workloadslicing_test.go
  test/integration/multikueue/jobs_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#7131 Automated cherry pick of #7122: Use clock to get time.Now() in CandidatesOrdering.
  pkg/scheduler/preemption/fairsharing/ordering.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#7118 Replace scheduler stub with interceptor function in TestSchedule.
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#7053 [Doc] Add WorkloadRequestUseMergePatch documentation
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/concepts/workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#7132 [Fix] Synchronise access to RuntimeInfo to avoid data race
  pkg/controller/jobs/trainjob/trainjob_controller.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#7140 Replace scheduler stub with interceptor function in TestLastSchedulingContext.
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6736 Avoid explicit Pod integration enablement for pod-dependent frameworks
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobs/deployment/deployment_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/statefulset/statefulset_controller.go
  test/e2e/customconfigs/podintegrationautoenablement_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#7149 Automated cherry pick of #7115: [Cleanup] Use clock in WorkloadSlicing funcs
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/scheduler.go
  pkg/util/testing/wrappers.go
  pkg/workloadslicing/workloadslicing.go
  pkg/workloadslicing/workloadslicing_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#7148 Automated cherry pick of #7118: Replace scheduler stub with interceptor function in TestSchedule.
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#7151 Automated cherry pick of #6701: [#5743] Cleanup deleteWorkloads from the TestLastSchedulingContext unit test. #7141: [release-0.14] Replace scheduler stub with interceptor function in TestLastSchedulingContext.
  pkg/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#7135 Refactor: Add context parameter to job interface methods
  internal/mocks/controller/jobframework/interface.go
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/appwrapper/appwrapper_controller_test.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/jaxjob/jaxjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/trainjob/trainjob_controller.go
  pkg/controller/jobs/trainjob/trainjob_controller_test.go
  pkg/controller/jobs/trainjob/trainjob_webhook_test.go
  pkg/util/client/client_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#7158 Revert pinversion.go.
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  hack/internal/tools/pinversion.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#7162 Automated cherry pick of #7153: Remove patchAdmission stub from scheduler.
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_tas_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#7010 Integration test for preemption from AC flavors.
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#7169 Reorganize `shouldTryNextFlavor` to make the logic more clear.
  pkg/scheduler/flavorassigner/flavorassigner.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#7183 Fix typos in `RayJob` and `RayCluster` head group metadata paths
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#7157 [BestEffortFIFO] Implement Sticky ClusterQueue Head Policy
  pkg/cache/queue/cluster_queue.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/util/util_scheduling.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#7196 add admin and user roles for trainjob to kueue rbac
  charts/kueue/templates/rbac/trainjob_editor_role.yaml
  charts/kueue/templates/rbac/trainjob_viewer_role.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/trainjob_editor_role.yaml
  config/components/rbac/trainjob_viewer_role.yaml
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#7202 [release-0.13] Cherry-pick #7157, #7201
  pkg/queue/cluster_queue.go
  pkg/queue/cluster_queue_test.go
  pkg/queue/manager.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/util/util_scheduling.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#7204 Prepare release v0.14.1
  CHANGELOG/CHANGELOG-0.14.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#7205 Update main with the latest v0.14.1
  CHANGELOG/CHANGELOG-0.14.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#7208 update CHANGELOG with 0.13.6
  CHANGELOG/CHANGELOG-0.13.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S
