Repository kubernetes-sigs/kueue, pull requests merged in 2025-06, with the labels that each got.

#5431 Kueue should provide RBAC permissions for cohorts OOTB
  charts/kueue/templates/rbac/cohort_editor_role.yaml
  charts/kueue/templates/rbac/cohort_viewer_role.yaml
  config/components/rbac/cohort_editor_role.yaml
  config/components/rbac/cohort_viewer_role.yaml
  config/components/rbac/kustomization.yaml
Labels: release-note, lgtm, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#5423 [Cleanup] Flaky tas test preemption cleanup
  test/integration/singlecluster/tas/tas_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5451 Prevent removal of queue-name label in namespaces with default localqueue
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobframework/validation_test.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5462 Automated cherry pick of #5426: TAS: Fix using reservation is the second flavor is Provisioning
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/snapshot.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5464 TAS: Keep level ordering even when algorithm is LeastFreeCapacityAlgorithm
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#5467 TAS: Simplify TAS profile selection utils
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5486 Add v0.11.6 changelog
  CHANGELOG/CHANGELOG-0.11.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5432 Respect configured webhook.certDir in cert-manager rotator
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  pkg/config/config_test.go
  pkg/util/cert/cert.go
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#5492 Doc: Fix a HC typo
  site/content/en/docs/concepts/cohort.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5411 Commonize the Helm chart artifact generation process.
  Makefile
  hack/helm-chart-package.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5445 Cleanup and extend docs on podSetMergePolicy
  site/content/en/docs/admission-check-controllers/provisioning.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5506 Doc: Add missing FGs to installation guide
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5400 Align the Helm configuration for the image of KueueViz with the main controller
  Makefile
  charts/kueue/templates/kueueviz/backend-deployment.yaml
  charts/kueue/templates/kueueviz/frontend-deployment.yaml
  charts/kueue/values.yaml
  hack/helm-chart-package.sh
  hack/processing-plan.yaml
Labels: kind/bug, lgtm, release-note-action-required, approved, size/M, cncf-cla: yes

#5271 docs: add object retention page
  site/content/en/docs/tasks/manage/setup_object_retention_policy.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#5512 Simplify Kueue Config defaultings by cmp.Or()
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5500 Exclude go.work from git management
  .dockerignore
  .gitignore
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5461 [Flaky] TAS tests unique cq names
  test/integration/singlecluster/tas/tas_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#5476 [AFS] Add documentation to Kueue website
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/admission_fair_sharing.md
  site/content/en/docs/concepts/fair_sharing.md
  site/content/en/docs/installation/_index.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#5522 Rename EXTRA_TAG to IMAGE_EXTRA_TAG.
  Makefile
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5526 Automated cherry pick of #5521: Remove redundant EXTRA_TAG variable from helm-chart-package.sh.
  Makefile
  hack/helm-chart-package.sh
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5530 Automated cherry pick of #5522: Rename EXTRA_TAG to IMAGE_EXTRA_TAG.
  Makefile
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5525 Change repo only for promoted images in helm chart package.
  hack/helm-chart-package.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5539 Remove IMAGE_NAME variables from Makefile.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5543 Remove IMAGE_EXTRA_TAG and use branch name instead.
  Makefile
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5532 Update charts/kueue README.md.
  charts/kueue/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5549 Automated cherry pick of #5543: Remove IMAGE_EXTRA_TAG and use branch name instead.
  Makefile
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5554 Remove redundant CYPRESS_IMAGE_NAME variable.
  Makefile-test.mk
  hack/e2e-kueueviz-local.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5556 Fix Makefile test-e2e-kueueviz-local target.
  hack/e2e-common.sh
  hack/e2e-kueueviz-local.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5552 Automated cherry pick of #5386: Cleanup Makefiles.
  Makefile-deps.mk
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5553 Automated cherry pick of #5386: Cleanup Makefiles.
  Makefile-deps.mk
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5551 Automated cherry pick of #5537: Cleanup Makefile.
  Makefile
  cloudbuild.yaml
  hack/helm-chart-package.sh
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5569 Optimize Makefiles.
  Makefile
  Makefile-deps.mk
  Makefile-test.mk
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5579 Automated cherry pick of #5569: Optimize Makefiles.
  Makefile
  Makefile-deps.mk
  Makefile-test.mk
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#5574 chore: Move utilnode to utiltas
  pkg/controller/tas/node_failure_controller.go
  pkg/util/node/node.go
  pkg/util/tas/tas.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5576 [Deflake] TAS integration test "should evict workload when multiple assigned nodes are deleted"
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5585 Fix the NeedsSecondPass check
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5584 Install genref using go tool.
  Makefile-deps.mk
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5587 Fix second pass entries outliving the workload delete
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/second_pass_queue.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, kind/flake, approved, cncf-cla: yes

#5596 Add PodSet Slice API
  apis/kueue/v1alpha1/topology_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podsettopologyrequest.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5603 Automated cherry pick of #5597: Generate Cohort client-go
  apis/kueue/v1alpha1/cohort_types.go
  client-go/applyconfiguration/kueue/v1alpha1/cohort.go
  client-go/applyconfiguration/kueue/v1alpha1/cohortspec.go
  client-go/applyconfiguration/kueue/v1alpha1/cohortstatus.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/cohort.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/fake/fake_cohort.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/fake/fake_kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/kueue_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/kueue/v1alpha1/cohort.go
  client-go/informers/externalversions/kueue/v1alpha1/interface.go
  client-go/listers/kueue/v1alpha1/cohort.go
  client-go/listers/kueue/v1alpha1/expansion_generated.go
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
Labels: release-note, lgtm, size/XL, approved, cncf-cla: yes

#5605 Automated cherry pick of #5587: Fix second pass entries outliving the workload delete
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/second_pass_queue.go
  test/integration/singlecluster/tas/tas_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#5582 Validate slice annotations
  pkg/controller/jobframework/tas_validation.go
  pkg/controller/jobs/job/job_webhook_test.go
Labels: release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5619 Automated cherry pick of #5378: Remove CronJob in AfterEach instead of DeferCleanup.
  test/e2e/singlecluster/e2e_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5630 Automated cherry pick of #5625: Don’t add the Workload to the Queues Manager if it is deactivated.
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/util/constants.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#5353 Two level TAS scheduling / PodSet chunk topology
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/jobframework/tas.go
  pkg/controller/jobframework/tas_validation.go
  test/e2e/tas/jobset_test.go
Labels: release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#5631 Allow setting the controller-manager PriorityClassName in helm
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/tests/manager_test.yaml
  charts/kueue/values.yaml
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#5645 Update Chart version on prepare release branch.
  Makefile
  charts/kueue/Chart.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5641 Use helm-docs to generate README.md for Helm.
  Makefile
  Makefile-deps.mk
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  charts/kueue/values.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#5627 Fix Dockerfile to work when not using Makefile
  Dockerfile
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5649 Automated cherry pick of #5631: Allow setting the controller-manager PriorityClassName in helm
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/tests/manager_test.yaml
  charts/kueue/values.yaml
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#5650 Automated cherry pick of #5631: Allow setting the controller-manager PriorityClassName in helm
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
Labels: release-note, lgtm, approved, size/XS, cncf-cla: yes

#5653 [KueueViz] Install node_modules on running test-e2e-kueueviz-local target.
  hack/e2e-kueueviz-local.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5655 [KueueViz] Remove the redundant headless flag.
  hack/e2e-kueueviz-local.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5621 Documentation describing the TAS failed node replacement
  site/content/en/docs/concepts/topology_aware_scheduling.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5660 Two-level scheduling follow up / Improve readability
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#5633 Add Pending Workloads in Grafana page.
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_grafana.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  site/static/examples/jobs/sample-job.yaml
  site/static/examples/visibility/README.md
  site/static/examples/visibility/grafana-cluster-queue-reader.yaml
  site/static/examples/visibility/grafana-local-queue-reader.yaml
  site/static/examples/visibility/pending-workloads-for-cluster-queue-visibility-dashboard.json
  site/static/examples/visibility/pending-workloads-for-local-queue-visibility-dashboard.json
  site/static/images/pending-workloads-for-cluster-queue-visibility-dashboard.png
  site/static/images/pending-workloads-for-local-queue-visibility-dashboard.png
Labels: lgtm, release-note-none, size/XL, approved, kind/documentation, cncf-cla: yes

#5665 kueueviz: Update INSTALL.md
  cmd/kueueviz/INSTALL.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5671 Fix "Should admit workloads with admission checks" test.
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5672 Automated cherry pick of #5671: Fix "Should admit workloads with admission checks" test.
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5674 refactor: only log warning when job has multiple workloads
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#5670 Add a recommended installation note to the Productionization page.
  site/content/en/docs/tasks/manage/productization/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5682 Simplify scheduler.netUsage
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5685 Fix customconfigs WaitForPodsReady E2E Tests.
  test/e2e/customconfigs/waitforpodsready_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, size/XL, approved, cncf-cla: yes

#5662 Propagate error from TAS request builder
  pkg/controller/jobframework/tas.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#5647 Allow user opt-in namespace for running e2e testsuite
  hack/e2e-common.sh
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-local.sh
  test/e2e/certmanager/metrics_test.go
  test/e2e/certmanager/suite_test.go
  test/e2e/customconfigs/suite_test.go
  test/e2e/customconfigs/waitforpodsready_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/suite_test.go
  test/e2e/singlecluster/visibility_test.go
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5698 FlavorAssigner - Use Preemption Simulation Results in More Cases
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#5701 Rename pkg preemption/preemptioncommon to preemption/common
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/common/types.go
  pkg/scheduler/preemption/preemption_oracle.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5703 Doc: Fix MultiKueue supporting Jobs listing level
  site/content/en/docs/concepts/multikueue.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5595 Promote Cohort API to v1beta1
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/cohort_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/webhook/manifests.yaml
  client-go/applyconfiguration/kueue/v1beta1/cohort.go
  client-go/applyconfiguration/kueue/v1beta1/cohortspec.go
  client-go/applyconfiguration/kueue/v1beta1/cohortstatus.go
  client-go/applyconfiguration/utils.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/fake/fake_cohort.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/fake/fake_kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/generated_expansion.go
  client-go/clientset/versioned/typed/kueue/v1alpha1/kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/cohort.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_cohort.go
  client-go/clientset/versioned/typed/kueue/v1beta1/fake/fake_kueue_client.go
  client-go/clientset/versioned/typed/kueue/v1beta1/generated_expansion.go
  client-go/clientset/versioned/typed/kueue/v1beta1/kueue_client.go
  client-go/informers/externalversions/generic.go
  client-go/informers/externalversions/kueue/v1alpha1/interface.go
  client-go/informers/externalversions/kueue/v1beta1/cohort.go
  client-go/informers/externalversions/kueue/v1beta1/interface.go
  client-go/listers/kueue/v1alpha1/expansion_generated.go
  client-go/listers/kueue/v1beta1/cohort.go
  client-go/listers/kueue/v1beta1/expansion_generated.go
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/webhook/manifests.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/cohort.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/cohort_controller_test.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/cohort_webhook.go
  pkg/webhooks/cohort_webhook_test.go
  site/content/en/docs/concepts/cohort.md
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: lgtm, size/XXL, release-note-action-required, approved, kind/api-change, kind/deprecation, cncf-cla: yes

#5615 Ensure Job status is updated after remote completion
  pkg/controller/jobs/job/job_multikueue_adapter.go
  test/integration/multikueue/jobs_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#5710 Fix the links for GoReport to point to the latest release
  README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#5726 Make panic more infoamable
  pkg/scheduler/flavorassigner/flavorassigner.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5725 Remove duplication of findBestFitDomain function
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#5727 Clean up wrappers
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/jaxjob/wrappers.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/paddlejob/wrappers.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/tfjob/wrappers_tfjob.go
  pkg/util/testingjobs/xgboostjob/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5731 Doc: Use the same primary color for Note
  site/content/en/docs/tasks/run/multikueue/kubeflow.md
  site/content/en/docs/tasks/run/multikueue/kuberay.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5735 Add unit tests for the improved accuracy of flavor assigner
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5740 Automated cherry pick of #5698: Improve accuracy of flavor assignment using preemption simulation in more cases
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5733 Doc: Single Truth of MultiKueue supported Jobs documentations
  site/content/en/docs/concepts/multikueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5752 Update CHANGELOG after v0.11.7
  CHANGELOG/CHANGELOG-0.11.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5750 Update main branch with the latest v0.12.3
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5745 AppWrapper also supports MultiKueue
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/run/multikueue/appwrapper.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5760 Fix KueueViz frontend version.
  Makefile
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5766 Confugure Dependabot for cypress dependencies.
  .github/dependabot.yml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5149 [KEP-2941]: Supporting Dynamic Resource Allocations in Kueue
  keps/2941-DRA/README.md
  keps/2941-DRA/kep.yaml
Labels: lgtm, release-note-none, size/XL, approved, ok-to-test, kind/documentation, cncf-cla: yes

#5775 Bump KueueViz frontend dependencies.
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5785 Automated cherry pick of #5063: Mutating webhook with reinvocation policy
  charts/kueue/README.md
  charts/kueue/templates/webhook/webhook.yaml
  charts/kueue/values.yaml
  hack/update-helm.sh
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#5786 fix: ignore not-found errors when updating ResourceFlavor finalizers
  pkg/controller/core/resourceflavor_controller.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#5788 chore: Fix redundant workloads initializations in queue manager
  pkg/queue/manager.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5797 refactor(internationalization): remove outdated language guide and enhance language selector
  site/add-language.md
  site/hugo.toml
  site/i18n.md
  site/layouts/partials/navbar-lang-selector.html
Labels: lgtm, release-note-none, size/XL, approved, ok-to-test, kind/documentation, cncf-cla: yes

#5803 Fix TAS LeastFreeCapacityFit for fit where nodes that are not the smallest one can accommodate Workload
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#5811 Bump the mui-packages group in /cmd/kueueviz/frontend with 2 updates
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes
