Repository kubernetes-sigs/kueue, pull requests merged in 2025-04, with the labels that each got.

#4846 docs: fix typo in error message
  pkg/workload/resources.go
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#4852 Bump lws from 0.5.1 to 0.6.0
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/lws/api/leaderworkerset/scheme/scheme.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/groupversion_info.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/leaderworkerset_types.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/zz_generated.deepcopy.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4858 add rbac for topologies
  charts/kueue/templates/rbac/topology_editor_role.yaml
  charts/kueue/templates/rbac/topology_viewer_role.yaml
  config/alpha-enabled/kustomization.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/topology_editor_role.yaml
  config/components/rbac/topology_viewer_role.yaml
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#4796 [Cleanup] Do not load images onto control-plane nodes
  hack/e2e-common.sh
  hack/multikueue/manager-cluster.kind.yaml
  hack/multikueue/worker-cluster.kind.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#4863 Move update kueue configuration logic to separate function.
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/customconfigs/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4794 add Open Cluster Management MultiKueue solution link to the doc
  site/content/en/docs/tasks/manage/setup_multikueue.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#4855 [Cleanup] Split MultiKueue integration tests into smaller files
  test/integration/multikueue/enabled_integration_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/no_gc_test.go
  test/integration/multikueue/setup_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4866 Fix topology API version.
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go
  client-go/applyconfiguration/kueue/v1beta1/topologyinfo.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  keps/3122-expose-flavors-in-localqueue-status/README.md
  pkg/cache/cache.go
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4842 [Cleanup] Fix the kubeflow/training-operator image version reference
  hack/e2e-common.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4875 Cleanup MultiKueue naming letter case.
  test/integration/multikueue/enabled_integration_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/no_gc_test.go
  test/integration/multikueue/setup_test.go
  test/integration/multikueue/suite_test.go
  test/integration/singlecluster/controller/core/clusterqueue_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4874 Automated cherry pick of #4855: [Cleanup] Split MultiKueue integration tests into smaller files
  test/integration/multikueue/enabled_integration_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/no_gc_test.go
  test/integration/multikueue/setup_test.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#4879 Prepare for v0.11.3
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4885 Fix artifact generation due to wrong alpha-enabled manifests
  config/alpha-enabled/kustomization.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4891 Update main after v0.11.3
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4893 Add sanity tests for deployment suspend by parent logic.
  pkg/util/testingjobs/deployment/wrappers.go
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/singlecluster/appwrapper_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4904 Automated cherry pick of #4894: Use ns.Name instead of ns.Namespace on client.InNamespace()
  test/e2e/singlecluster/deployment_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4870 add feature gate to control cohort controller
  pkg/controller/core/core.go
  pkg/features/kube_features.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#4898 Use the same receiver name.
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/resources/requests.go
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/workload/workload.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4889 [Cleanup] Change image tag search pattern
  hack/e2e-common.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4909 Automated cherry pick of #4854: Pod groups MultiKueue adapter
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/jobs/pod/pod_multikueue_adapter.go
  pkg/controller/jobs/pod/pod_multikueue_adapter_test.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/jobs_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#4910 Bump sigs.k8s.io/controller-tools from 0.17.2 to 0.17.3 in /hack/internal/tools
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4473 Differentiate error message for cohort and cluster queue
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  pkg/webhooks/cohort_webhook.go
  pkg/webhooks/cohort_webhook_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#4913 Manual cherry pick of #4870 add feature gate to control cohort controller
  pkg/controller/core/core.go
  pkg/features/kube_features.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#4896 Add AppWrapper with Deployment example.
  site/content/en/docs/tasks/run/appwrappers.md
  site/content/en/docs/tasks/run/external_workloads/wrapped_custom_workload.md
  site/static/examples/appwrapper/deployment-sample.yaml
  site/static/examples/appwrapper/leaderworkerset-sample.yaml
  site/static/examples/appwrapper/pytorch-sample.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4635 Assert Snapshot Unmodified in Preemption Tests
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#4824 Fix getAncestorWorkload if integration disabled.
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4924 Automated cherry pick of #4824: Fix getAncestorWorkload if integration disabled.
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
Labels: release-note, lgtm, size/XL, approved, cncf-cla: yes

#4788 add helm verify step to confirm charts render correctly
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4916 Add sync-hugo-version target to sync HUGO_VERSION.
  Makefile
  netlify.toml
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#4931 Use SimulateUsageAddition in FairSharingIterator
  pkg/scheduler/fair_sharing_iterator.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4930 Unexport ResourceNode; Cleanup Preemption Test
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/cohort.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/resource_node.go
  pkg/cache/snapshot_test.go
  pkg/scheduler/preemption/preemption_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4808 Fix LeaderWorkerSet with manageJobsWithoutQueueName.
  Makefile-test.mk
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/defaults_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_controller.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_controller.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/deployment/wrappers.go
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/suite_test.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4937 Use MustCreate for all Success object creation.
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/integration/singlecluster/controller/jobs/kubeflow/kubeflowjob.go
  test/util/e2e.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4936 Automated cherry pick of #4808: Fix LeaderWorkerSet with manageJobsWithoutQueueName.
  Makefile-test.mk
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/defaults_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_controller.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_controller.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/deployment/wrappers.go
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/suite_test.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4938 bump AppWrapper version from v1.1.1 to v1.1.2
  go.mod
  go.sum
  vendor/github.com/project-codeflare/appwrapper/api/v1beta2/appwrapper_types.go
  vendor/modules.txt
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4944 update helm to v3.17.3
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4943 [release-0.11]: Fix helm verify release 0 11
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4945 Add appwrappers permissions to multikueue service account example.
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#4941 Include sched links in talks/presentation page
  site/content/en/docs/talks_and_presentations/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4800 certmanager: add test to curl metrics data using certs
  charts/kueue/templates/certmanager/certificatemetrics.yaml
  config/components/certmanager/certificate-metrics.yaml
  config/default/kustomization.yaml
  test/e2e/certmanager/certmanager_test.go
  test/e2e/certmanager/metrics_test.go
  test/e2e/certmanager/suite_test.go
  test/e2e/config/certmanager/cert_metrics_manager_patch.yaml
  test/e2e/config/certmanager/controller_manager_config.yaml
  test/e2e/config/certmanager/kustomization.yaml
  test/e2e/config/certmanager/mutating_webhookcainjection_patch.yaml
  test/e2e/config/certmanager/validating_webhookcainjection_patch.yaml
Labels: kind/feature, release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#4801 make iterable function for traversing to root
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/cohort.go
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/preemption/fairsharing/least_common_ancestor.go
  pkg/scheduler/preemption/fairsharing/ordering.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#4955 Fix message in LQ's status
  pkg/controller/core/localqueue_controller.go
  test/integration/singlecluster/controller/core/localqueue_controller_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: release-note, lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#4933 Create public type for LQ in cache
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/localqueue.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4963 Reconcile Cohort when FairSharing Weight Updated
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/cohort_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#4964 Document waitForPodsReady.recoveryTimeout
  site/content/en/docs/tasks/manage/setup_wait_for_pods_ready.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4950 Set the E2E_KIND_VERSION mk variable based on the E2E_K8S_VERSION
  Makefile-test.mk
  site/content/en/docs/contribution_guidelines/testing.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4976 Automated cherry pick of #4973: Handle request value with zero in CountIn
  pkg/resources/requests.go
  pkg/resources/requests_test.go
  pkg/scheduler/scheduler_test.go
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#4978 Automated cherry pick of #4950: Set the E2E_KIND_VERSION mk variable based on the E2E_K8S_VERSION
  Makefile-test.mk
  site/content/en/docs/contribution_guidelines/testing.md
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4979 Automated cherry pick of #4950: Set the E2E_KIND_VERSION mk variable based on the E2E_K8S_VERSION
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4962 Protect GuaranteedQuota When FairSharing Weight=0
  apis/kueue/v1beta1/fairsharing_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  pkg/cache/fair_sharing.go
  pkg/cache/fair_sharing_test.go
  pkg/metrics/metrics.go
  pkg/scheduler/preemption/preemption_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4918 Delete LeaderWorkerSets before cleanup StatefulSets and Pods.
  test/e2e/tas/leaderworkerset_test.go
  test/util/util.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#4929 Helm: ensure Chart version matches version in registry
  hack/push-chart.sh
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#4985 Fix HierarchicalCohorts feature gate
  pkg/controller/core/core.go
  pkg/features/kube_features.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4987 [release-0.10] Helm: ensure Chart version matches version in registry
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4988 [release-0.11] Helm: ensure Chart version matches version in registry
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4991 Update HierarchicalCohorts FG version
  pkg/features/kube_features.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4992 address https://github.com/advisories/GHSA-hcg3-q754-cr77 in kueue-viz
  cmd/kueueviz/backend/go.mod
  cmd/kueueviz/backend/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5001 Fix assignment verification in the LeaderWorkerSet test.
  test/e2e/tas/leaderworkerset_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#5008 Fair Sharing Preemption - Small Cleanup
  pkg/scheduler/preemption/fairsharing/least_common_ancestor.go
  pkg/scheduler/preemption/fairsharing/target.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5010 Drop test-e2e-all Makefile target
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5011 Remove IsManagingObjectsOwner from IntegrationCallbacks.
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/deployment/deployment_controller.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/statefulset/statefulset_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5012 Automated cherry pick of #4985: Fix HierarchicalCohorts feature gate
  pkg/controller/core/core.go
  pkg/features/kube_features.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5014 Rename tas_types.go to topology_types.go.
  apis/kueue/v1alpha1/topology_types.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4790 Add LeaderWorkerSet as owner of Workload.
  go.mod
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/pod/pod_controller.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4981 [Docs] Update MultiKueue documentation for pod groups
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/run/multikueue/plain_pods.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5013 Add validation for spec field in Topology.
  apis/kueue/v1alpha1/topology_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#5019 Fix tiny typo in docs
  site/content/en/docs/tasks/run/external_workloads/argo_workflow.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#5024 [Doc][Ray] Replace links to deprecated KubeRay GitHub pages with links to the Ray docs
  site/content/en/docs/tasks/run/rayclusters.md
  site/content/en/docs/tasks/run/rayjobs.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#5029 Use AppendOwnerReference.
  pkg/util/testingjobs/appwrapper/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/pod/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5025 Wait for LeaderWorkerSet in E2E customconfigs tests.
  test/e2e/certmanager/suite_test.go
  test/e2e/customconfigs/suite_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/e2e/tas/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5028 [chore][log] Remove `fmt.Sprintf` from `log.info`
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#4594 test: add WaitForPodsReady e2e test
  pkg/util/testingjobs/job/wrappers.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/e2e/customconfigs/suite_test.go
  test/e2e/customconfigs/waitforpodsready_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#5036 Remove unused FlavorIndependentAdmissionCheck constant.
  apis/kueue/v1beta1/admissioncheck_types.go
  pkg/cache/admissioncheck.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4911 Use AdmissionCheckReference to improve static code analysis
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/admissioncheckstate.go
  client-go/applyconfiguration/kueue/v1beta1/admissioncheckstrategyrule.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer.go
  pkg/controller/admissionchecks/provisioning/provisioning.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/admissioncheck/admissioncheck_test.go
  pkg/util/maps/maps.go
  pkg/util/strings/strings.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/metrics_test.go
  test/integration/multikueue/enabled_integration_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/no_gc_test.go
  test/integration/multikueue/setup_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/core/admissioncheck_controller_test.go
  test/integration/singlecluster/controller/core/clusterqueue_controller_test.go
  test/integration/singlecluster/controller/core/localqueue_controller_test.go
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/scheduler/workload_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
  test/util/util.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#5030 Drop KeepQuotaForProvReqRetry feature gate.
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: release-note, lgtm, size/XL, approved, kind/cleanup, cncf-cla: yes

#5043 Merge the FlowSchema and PriorityLevelConfiguration v1 manifests into the installation manifests
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/visibility/flowschema.yaml
  charts/kueue/templates/visibility/prioritylevelconfigurations.yaml
  charts/kueue/values.yaml
  config/components/visibility-apf/kustomization.yaml
  config/components/visibility/flowschema.yaml
  config/components/visibility/kustomization.yaml
  config/components/visibility/prioritylevelconfigurations.yaml
  config/visibility-apf/kustomization.yaml
  hack/update-helm.sh
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  test/e2e/config/default/kustomization.yaml
Labels: kind/feature, lgtm, release-note-action-required, approved, size/M, cncf-cla: yes

#5050 Drop deprecated WorkloadEvictedByDeactivation reason.
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/workload/workload.go
Labels: release-note, lgtm, approved, kind/cleanup, cncf-cla: yes, size/S

#4902 Add KubeConEU'25 presentations
  site/content/en/docs/talks_and_presentations/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5069 Remove kueuectl from test-multikueue-integration.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5070 Update Production Readiness status.
  README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5075 Add a KubeCon talk to the Kueue docs
  site/content/en/docs/talks_and_presentations/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5066 [Failing test] Workload controller with scheduler when the queue has …
  test/integration/singlecluster/scheduler/workload_controller_test.go
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4806 Reclaim/preemption for hierarchical cohorts
  pkg/cache/cohort_snapshot.go
  pkg/cache/resource_node.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/classical/candidate_generator.go
  pkg/scheduler/preemption/classical/hierarchical_preemption.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
Labels: kind/bug, release-note, lgtm, size/XXL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4935 fix: invalid SSA patch due to field manager
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#4989 Add support for node selectors based filtering in TAS
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#4252 KEP-4136: Admission Fair Sharing
  keps/4136-admission-fair-sharing/README.md
  keps/4136-admission-fair-sharing/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, kind/api-change, cncf-cla: yes

#5068 Split integration tests into baseline and extended targets.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5077 Fix flaky perf scheduling test
  test/performance/scheduler/checker/checker_test.go
  test/performance/scheduler/default_rangespec.yaml
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#5081 Automated cherry pick of #5068: Split integration tests into baseline and extended targets.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5086 Automated cherry pick of #4935: fix: invalid SSA patch due to field manager
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#5088 Automated cherry pick of #4935: fix: invalid SSA patch due to field manager
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#5087 Automated cherry pick of #4989: Add support for node selectors based filtering in TAS
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  test/integration/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5035 Add git hub action to automatically bump hugo version on dependabot commit
  .github/workflows/sync-dependabot.yaml
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#5093 Update 0.10.5 release-note for preparation
  CHANGELOG/CHANGELOG-0.10.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5094 Update v0.11.4 release-note for preparation
  CHANGELOG/CHANGELOG-0.11.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5095 Remove duplicated release note for v0.11.4
  CHANGELOG/CHANGELOG-0.11.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5099 Automated cherry pick of #5097: Fix script to push helm chart
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5098 Automated cherry pick of #5097: Fix script to push helm chart
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5100 Use locally built kind images for kueue-viz e2e tests
  Makefile-test.mk
  hack/e2e-common.sh
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-local.sh
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5105 Use EXTRA_TAG for Helm App version if it is semantic versioning
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5108 Automated cherry pick of #5105: Use EXTRA_TAG for Helm App version if it is semantic versioning
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5111 Update CHANGELOG after v0.10.5
  CHANGELOG/CHANGELOG-0.10.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5112 Update the latest version with v0.11.4
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5115 Bump go version in Dockerfile
  Dockerfile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5120 Fix topologies rbac to specify resource in plural form
  charts/kueue/templates/rbac/topology_editor_role.yaml
  charts/kueue/templates/rbac/topology_viewer_role.yaml
  config/components/rbac/topology_editor_role.yaml
  config/components/rbac/topology_viewer_role.yaml
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#5117 Upgrade golangci-lint version to v2.
  .golangci.yaml
  Makefile-deps.mk
  cmd/kueuectl/app/create/create_resourceflavor_test.go
  cmd/kueuectl/app/list/helpers.go
  cmd/kueuectl/app/list/list_pods.go
  cmd/kueuectl/app/list/list_workload.go
  cmd/kueuectl/app/list/list_workload_printer.go
  cmd/kueuectl/app/util/dry_run.go
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  hack/internal/tools/pinversion.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/config/validation.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/tas/resource_flavor.go
  pkg/scheduler/preemption/classical/hierarchical_preemption.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/util/testing/client.go
  pkg/util/testing/error_matchers.go
  pkg/util/testing/metrics_matchers.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/appwrapper/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/paddlejob/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  pkg/util/testingjobs/tfjob/wrappers_tfjob.go
  pkg/util/testingjobs/xgboostjob/wrappers.go
  pkg/visibility/server.go
  test/integration/singlecluster/scheduler/fairsharing/suite_test.go
  test/integration/singlecluster/scheduler/workload_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5125 Remove FORCE target.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5126 Use setup-e2e-env target for all e2e tests.
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5110 fix: PropagateResourceRequests map equality check
  pkg/workload/workload.go
  pkg/workload/workload_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5137 [Cleanup] Change E2E_RUN_ONLY_ENV read argument to -p
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5143 Use condition matcher with reason.
  pkg/util/testing/condition_matchers.go
  pkg/util/testing/condition_matchers_test.go
  test/e2e/customconfigs/waitforpodsready_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/tas/leaderworkerset_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes
