Repository kubernetes-sigs/kueue, pull requests merged in 2025-07, with the labels that each got.

#5819 Fix a bug for tas_node_failure_controller name
  pkg/controller/tas/node_failure_controller.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#5796 refactor: improve error handling with client.IgnoreNotFound in controllers
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/workload_controller.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#5799 [zh-cn] sync installation and overview
  site/content/zh-CN/docs/installation/_index.md
  site/content/zh-CN/docs/overview/_index.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#5818 Fix a bug for the non propagated controller concurrency
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/tas/node_failure_controller.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/controller/tas/topology_ungater.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#5829 [zh-cn] Localize adopters
  site/content/zh-CN/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5836 [Docs] Clean up concepts/multikueue.md
  site/content/en/docs/concepts/multikueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#5833 TAS: fix Kueue crashing when quota-based preemption is targeting a workload using deleted Node
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#5843 Automated cherry pick of #5833: TAS: fix Kueue crashing when quota-based preemption is targeting a workload using deleted Node
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#5838 fix: use sed in e2e-common.sh build and deploy
  hack/e2e-common.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5816 [AFS] Describe entry penalty in KEP
  keps/4136-admission-fair-sharing/README.md
  keps/4136-admission-fair-sharing/kep.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5781 refactor(scheduler): extract workload admission metrics recording into separate methods
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#5832 Fix unexpected issues caused by IgnoreNotFound-related changes
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go
  pkg/controller/core/workload_controller.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#5848 TAS: Support the LeaderElection for NodeFailure controller
  pkg/controller/tas/node_failure_controller.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#5849 TAS: Specify and adjust logging levels
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5839 [Docs][zh-CN] Localize local_queue.md
  site/content/zh-CN/docs/concepts/local_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5852 [Docs][zh] Localize fair_sharing
  site/content/zh-CN/docs/concepts/fair_sharing.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S, area/localization, language/zh

#5820 helm: support for specifying nodeSelector and tolerations for all Kueue components
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/kueueviz/backend-deployment.yaml
  charts/kueue/templates/kueueviz/frontend-deployment.yaml
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/tests/manager_test.yaml
  charts/kueue/values.yaml
  hack/processing-plan.yaml
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#5780 fix: use agnhost images preloaded to the containerd in tests
  hack/e2e-common.sh
  test/e2e/certmanager/metrics_test.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/e2e/customconfigs/objectretentionpolicies_test.go
  test/e2e/customconfigs/waitforpodsready_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/appwrapper_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jaxjob_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/pytorchjob_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/e2e/tas/appwrapper_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/leaderworkerset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/statefulset_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/util/e2e.go
Labels: size/L, lgtm, kind/failing-test, kind/flake, release-note-none, approved, cncf-cla: yes

#5867 Add missing cleanups to preemption integration tests
  test/integration/singlecluster/scheduler/preemption_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5874 Automated cherry pick of #5780: fix: use agnhost images preloaded to the containerd in tests
  hack/e2e-common.sh
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/appwrapper_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/e2e/tas/appwrapper_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/leaderworkerset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/statefulset_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#5869 Automated cherry pick of #5820: helm: support for specifying nodeSelector and tolerations for all Kueue components
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/kueueviz/backend-deployment.yaml
  charts/kueue/templates/kueueviz/frontend-deployment.yaml
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/tests/manager_test.yaml
  charts/kueue/values.yaml
  hack/processing-plan.yaml
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#5632 [AFS] Support preemption based on historical LQ's usage
  cmd/kueue/main.go
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/snapshot.go
  pkg/queue/cluster_queue.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/util/admissionfairsharing/admission_fair_sharing.go
  pkg/workload/workload.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/fairsharing/suite_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#5879 [Docs][zh]Localize run_job_with_workload_priority.md
  site/content/zh-CN/docs/tasks/manage/run_job_with_workload_priority.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5868 [Docs][zh]sync enabling_pprof_endpoints
  site/content/zh-CN/docs/tasks/dev/enabling_pprof_endpoints.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5870 [Docs][zh]Localize develop-acc.md
  site/content/zh-CN/docs/tasks/dev/develop-acc.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5821 Add npm-depcheck Makefile target.
  .github/dependabot.yml
  Makefile
  hack/depcheck/Dockerfile
  hack/depcheck/verify.sh
  test/e2e/kueueviz/.dockerignore
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5894 [Docs][zh]Localize manage_jobs_without_queue_name
  site/content/zh-CN/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5678 KEP: Reconcile jobs only in opt-in namespaces
  keps/3589-manage-jobs-selectively/README.md
  keps/3589-manage-jobs-selectively/kep.yaml
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#5900 [Docs][zh]Localize cert_manager.md
  site/content/zh-CN/docs/tasks/manage/productization/cert_manager.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5912 Prepare v0.11.8 release
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5911 Prepare v0.12.4
  CHANGELOG/CHANGELOG-0.12.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5918 Update main after v0.12.4
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5913 Add v0.11.8 changelog
  CHANGELOG/CHANGELOG-0.11.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5919 Update CHANGELOG after v0.12.4
  CHANGELOG/CHANGELOG-0.12.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5905 Fix slice-only TAS
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/jobframework/tas.go
  test/e2e/tas/jobset_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#5910 [flaky test] AFS integration test makes Kueue panic / crash
  pkg/workload/workload.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5932 Fix passing IMAGE_BUILD_EXTRA_OPTS in Makefile when it contains spaces
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5934 Allow modification of TEST_LOG_LEVEL for Unit Tests
  pkg/util/testing/context.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5947 Automated cherry pick of #5942: Fix Topology Aware Scheduling when Delete Topology when ResourceFlavor exists should not allow to delete topology test.
  test/integration/singlecluster/tas/tas_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5914 chore: update golangci-lint to v2.2.1
  .golangci.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#5945 Use ShortInterval with Consistently.
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/e2e/customconfigs/objectretentionpolicies_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/integration/singlecluster/scheduler/workload_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
  test/integration/singlecluster/webhook/jobs/job_webhook_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5944 Remove support for Kubernetes 1.30.
  Makefile-test.mk
  README.md
  hack/multikueue-e2e-test.sh
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/no_gc_test.go
  test/integration/multikueue/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5949 Restore managers image after deploy Kueue.
  hack/e2e-common.sh
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-local.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5950 Automated cherry pick of #5949: Restore managers image after deploy Kueue.
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#5952 Use trap to restore managers image in kueue_deploy.
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5951 Automated cherry pick of #5949: Restore managers image after deploy Kueue.
  hack/e2e-common.sh
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-local.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#5930 [YAML Processor] Remove comments from the generated chart templates.
  charts/kueue/templates/prometheus/monitor.yaml
  charts/kueue/templates/rbac/batch_admin_role.yaml
  charts/kueue/templates/rbac/batch_user_role.yaml
  charts/kueue/templates/rbac/clusterqueue_editor_role.yaml
  charts/kueue/templates/rbac/clusterqueue_viewer_role.yaml
  charts/kueue/templates/rbac/cohort_editor_role.yaml
  charts/kueue/templates/rbac/cohort_viewer_role.yaml
  charts/kueue/templates/rbac/jaxjob_editor_role.yaml
  charts/kueue/templates/rbac/jaxjob_viewer_role.yaml
  charts/kueue/templates/rbac/job_editor_role.yaml
  charts/kueue/templates/rbac/job_viewer_role.yaml
  charts/kueue/templates/rbac/jobset_editor_role.yaml
  charts/kueue/templates/rbac/jobset_viewer_role.yaml
  charts/kueue/templates/rbac/leader_election_role.yaml
  charts/kueue/templates/rbac/localqueue_editor_role.yaml
  charts/kueue/templates/rbac/localqueue_viewer_role.yaml
  charts/kueue/templates/rbac/mpijob_editor_role.yaml
  charts/kueue/templates/rbac/mpijob_viewer_role.yaml
  charts/kueue/templates/rbac/paddlejob_editor_role.yaml
  charts/kueue/templates/rbac/paddlejob_viewer_role.yaml
  charts/kueue/templates/rbac/pending_workloads_cq_viewer_role.yaml
  charts/kueue/templates/rbac/pending_workloads_lq_viewer_role.yaml
  charts/kueue/templates/rbac/pytorchjob_editor_role.yaml
  charts/kueue/templates/rbac/pytorchjob_viewer_role.yaml
  charts/kueue/templates/rbac/raycluster_editor_role.yaml
  charts/kueue/templates/rbac/raycluster_viewer_role.yaml
  charts/kueue/templates/rbac/rayjob_editor_role.yaml
  charts/kueue/templates/rbac/rayjob_viewer_role.yaml
  charts/kueue/templates/rbac/resourceflavor_editor_role.yaml
  charts/kueue/templates/rbac/resourceflavor_viewer_role.yaml
  charts/kueue/templates/rbac/tfjob_editor_role.yaml
  charts/kueue/templates/rbac/tfjob_viewer_role.yaml
  charts/kueue/templates/rbac/topology_editor_role.yaml
  charts/kueue/templates/rbac/workload_editor_role.yaml
  charts/kueue/templates/rbac/workload_viewer_role.yaml
  charts/kueue/templates/rbac/xgboostjob_editor_role.yaml
  charts/kueue/templates/rbac/xgboostjob_viewer_role.yaml
  hack/internal/tools/yaml-processor/yamlproc/processor.go
  hack/internal/tools/yaml-processor/yamlproc/yaml.go
  hack/processing-plan.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5954 Change package name from maps to ptr for consistency
  pkg/util/ptr/ptrs.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#4444 Update autoscaling provision request API to v1
  cmd/kueue/main.go
  go.mod
  go.sum
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer.go
  pkg/controller/admissionchecks/provisioning/indexer_test.go
  pkg/controller/admissionchecks/provisioning/provisioning.go
  site/content/en/docs/admission-check-controllers/provisioning.md
  test/integration/framework/framework.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/tas/tas_test.go
  vendor/github.com/fxamacker/cbor/v2/README.md
  vendor/github.com/fxamacker/cbor/v2/bytestring.go
  vendor/github.com/fxamacker/cbor/v2/cache.go
  vendor/github.com/fxamacker/cbor/v2/decode.go
  vendor/github.com/fxamacker/cbor/v2/doc.go
  vendor/github.com/fxamacker/cbor/v2/encode.go
  vendor/github.com/fxamacker/cbor/v2/encode_map.go
  vendor/github.com/fxamacker/cbor/v2/encode_map_go117.go
  vendor/github.com/fxamacker/cbor/v2/omitzero_go124.go
  vendor/github.com/fxamacker/cbor/v2/omitzero_pre_go124.go
  vendor/github.com/fxamacker/cbor/v2/simplevalue.go
  vendor/github.com/fxamacker/cbor/v2/stream.go
  vendor/github.com/fxamacker/cbor/v2/structfields.go
  vendor/github.com/fxamacker/cbor/v2/tag.go
  vendor/github.com/modern-go/reflect2/safe_type.go
  vendor/k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1/doc.go
  vendor/k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1/register.go
  vendor/k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1/types.go
  vendor/k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1/zz_generated.defaults.go
  vendor/k8s.io/gengo/v2/codetags/extractor.go
  vendor/k8s.io/gengo/v2/codetags/parser.go
  vendor/k8s.io/gengo/v2/codetags/scanner.go
  vendor/k8s.io/gengo/v2/codetags/types.go
  vendor/k8s.io/gengo/v2/comments.go
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
Labels: lgtm, size/XXL, release-note-action-required, approved, kind/cleanup, cncf-cla: yes

#5975 use group version kind instead of hard coded strings
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5953 [Docs][zh]Localize pending_workloads_in_status
  site/content/zh-CN/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5982 [Flake] Update node resources with eventually
  test/e2e/tas/suite_test.go
Labels: lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#5984 Emit the Workload event indicating eviction when LocalQueue is stopped
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#5923 add metric for duration between workload podsReady and preemption
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/workload/workload.go
  test/integration/singlecluster/scheduler/podsready/scheduler_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5987 graduate managedJobNamespaceSelector to GA
  apis/config/v1beta1/defaults.go
  cmd/kueue/main.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/defaults_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/features/kube_features.go
  site/content/en/docs/installation/_index.md
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#6001 Cleanup after graduation ManagedJobsNamespaceSelector feature.
  pkg/controller/jobs/pod/pod_webhook_test.go
  site/content/en/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
  site/content/zh-CN/docs/installation/_index.md
  site/content/zh-CN/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md
  site/content/zh-CN/docs/tasks/run/plain_pods.md
  site/content/zh-CN/docs/tasks/troubleshooting/troubleshooting_pods.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#6005 Cleanup MultiplePreemptions and WorkloadResourceRequestsSummary feature gates.
  site/content/zh-CN/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5895 [KEP-2724] Add cross-podset TAS scheduling documentation
  keps/2724-topology-aware-scheduling/README.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#6011 address GHSA-557j-xg8c-q2mm via upgrading to helm 3.17.4
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6019 Fix "Shouldn't admit deactivated Workload after manager restart" test.
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#6003 [zh] Sync site/content/zh-CN/docs/concepts/workload_priority_class.md to Chinese
  site/content/zh-CN/docs/concepts/workload_priority_class.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, area/localization, language/zh

#5985 Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/resource_node.go
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#5878 Group PodSets together for finding common flavor
  apis/kueue/v1alpha1/topology_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podsettopologyrequest.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/jobframework/tas.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/flavorassigner/podset_groups.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#6027 Automated cherry pick of #5985: Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/resource_node.go
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#6054 [Docs][zh]Localize argo_workflow.md
  site/content/zh-CN/docs/tasks/run/external_workloads/argo_workflow.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6055 Simplify Pod configuration options.
  pkg/controller/jobs/pod/pod_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#6032 clean up silenced errors
  pkg/cache/clusterqueue.go
  pkg/cache/cohort.go
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#6056 [zh] Sync docs/tasks/run/jobs.md to Chinese.
  site/content/zh-CN/docs/tasks/run/jobs.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6034 bug fix: ServiceMonitor tlsConfig field
  charts/kueue/templates/prometheus/monitor.yaml
  hack/processing-plan.yaml
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#6114 Move UpdateKueueConfiguration() to utils.
  test/e2e/certmanager/suite_test.go
  test/e2e/customconfigs/managejobswithoutqueuename_test.go
  test/e2e/customconfigs/objectretentionpolicies_test.go
  test/e2e/customconfigs/reconcile_test.go
  test/e2e/customconfigs/suite_test.go
  test/e2e/customconfigs/waitforpodsready_test.go
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6138 chore: wrapper objects should be built by Obj() function
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6053 [Docs][zh-cn] command kueuectl_version
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_version/_index.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6142 [Docs][zh]Localize wrapped_custom_workload.md
  site/content/zh-CN/docs/tasks/run/external_workloads/wrapped_custom_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6145 [Docs][zh]Localize flux_miniclusters.md
  site/content/zh-CN/docs/tasks/run/external_workloads/flux_miniclusters.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6159 Cleanup patch handling by commonizing the code
  pkg/util/client/client.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6151 Eliminate code duplication for indexing Workloads
  pkg/controller/core/indexer/indexer.go
  pkg/controller/jobframework/indexer.go
  pkg/workloadslicing/workloadslicing.go
  pkg/workloadslicing/workloadslicing_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6163 Refactor client.go Patch
  pkg/util/client/client.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6133 [KEP] Update KEP of the flavor fungibility feature
  keps/582-preempt-based-on-flavor-order/README.md
  keps/582-preempt-based-on-flavor-order/kep.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#6132 Flavor Fungibility Prefers Fit over NoBorrow
  pkg/features/kube_features.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_oracle.go
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#6169 [Docs][zh]Localize pytorchjobs.md
  site/content/zh-CN/docs/tasks/run/kubeflow/pytorchjobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6156 [Docs][zh]Localize external_workloads/_index
  site/content/zh-CN/docs/tasks/run/external_workloads/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S, area/localization, language/zh

#6170 [Docs][zh]Localize kubeflow/tfjobs.md
  site/content/zh-CN/docs/tasks/run/kubeflow/tfjobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#5933 Add entrance penalty for admitted Workloads
  cmd/kueue/main.go
  pkg/cache/snapshot.go
  pkg/controller/core/core.go
  pkg/controller/core/localqueue_controller.go
  pkg/queue/afs_entry_penalties.go
  pkg/queue/cluster_queue.go
  pkg/queue/cluster_queue_test.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/util/admissionfairsharing/admission_fair_sharing.go
  pkg/util/queue/local_queue.go
  pkg/workload/workload.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/fairsharing/suite_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#6189 [AFS] Follow up - Add entrance penalty
  pkg/cache/snapshot.go
  pkg/queue/cluster_queue.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  test/integration/singlecluster/scheduler/fairsharing/suite_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6190 manually carry 6164 to release-0.11
  test/e2e/singlecluster/statefulset_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#6173 [Docs][zh]Localize rayjobs.md
  site/content/zh-CN/docs/tasks/run/rayjobs.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6172 [Docs][zh]Localize rayclusters.md
  site/content/zh-CN/docs/tasks/run/rayclusters.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6178 [Docs][zh]Localize kubeflow/jaxjobs.md
  site/content/zh-CN/docs/tasks/run/kubeflow/jaxjobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6191 [Docs][zh]Localize kubeflow/xgboostjobs.md
  site/content/zh-CN/docs/tasks/run/kubeflow/xgboostjobs.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6203 Fix workload slices when creation timestamps collide
  pkg/scheduler/scheduler.go
  pkg/workloadslicing/workloadslicing.go
  pkg/workloadslicing/workloadslicing_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#6215 Update main with the latest v0.13.0
  CHANGELOG/CHANGELOG-0.13.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6229 docs: add until section to the object retention policies alpha
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#6144 [Docs][zh]Localize tektoncd.md
  site/content/zh-CN/docs/tasks/run/external_workloads/tektoncd.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6220 [zh] sync docs/task/manage/enable_kubeviz.md to Chinese.
  site/content/zh-CN/docs/tasks/manage/enable_kubeviz.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6221 Address workload-slice regression which may result in incorrect workload slice to job assignment.
  pkg/workloadslicing/workloadslicing.go
  pkg/workloadslicing/workloadslicing_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#6225 [Docs][zh]Localize kueuectl_describe/_index.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6226 [Docs][zh]Localize kueuectl_describe/kueuectl_describe_clusterqueue.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6259 AFS: Add explanation of entry penalty to documentation
  site/content/en/docs/concepts/admission_fair_sharing.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#6262 [Docs][zh]Localize kueuectl_describe/kueuectl_describe_resourceflavor.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6263 [Docs][zh]Localize kueuectl_describe/kueuectl_describe_workload.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6287 Rename ClusterQueue functions to hide heap implementation details
  pkg/controller/core/localqueue_controller.go
  pkg/queue/cluster_queue.go
  pkg/queue/manager.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6283 Fix evicting workloads due to AdmissionCheck retry
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/workload/workload.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/metrics_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/util/e2e.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#6301 Automated cherry pick of #6298: [release-0.12] Fix evicting workloads due to AdmissionCheck retry
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/workload/workload.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/metrics_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/util/e2e.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#6289 [Docs][zh]Localize kueuectl_edit/kueuectl_edit_localqueue.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6290 [Docs][zh]Localize kueuectl_edit/kueuectl_edit_resourceflavor.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6295 [Docs][zh]Localize kueuectl_edit/kueuectl_edit_workload.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6306 Automated cherry pick of #6300: Support disabling the client-side rate limiting
  apis/config/v1beta1/configuration_types.go
  cmd/kueue/main.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#6312 [Cleanup] Tests to use resource consts
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/tas_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/kueuectl/create_test.go
  test/integration/singlecluster/webhook/core/clusterqueue_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6322 [ProvReq] Fix ProvReq not recreating after second failed attempt
  pkg/controller/admissionchecks/provisioning/controller.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6315 Doc: Add kueue.x-k8s.io/podset-unconstrained-topology descriptions
  site/content/en/docs/concepts/topology_aware_scheduling.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#6321 [Cleanup] Unify function that checks no objects are left in the worker clusters
  test/e2e/multikueue/e2e_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes
