Repository kubernetes-sigs/kueue, pull requests merged in 2025-01, with the labels that each got.

#3900 Replace `time.Now()` with `clock.Clock.Now()` in pkg/workload/admissionchecks
  cmd/importer/pod/import.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/admissionchecks.go
  pkg/workload/admissionchecks_test.go
  pkg/workload/workload.go
  test/e2e/singlecluster/e2e_test.go
  test/integration/controller/core/workload_controller_test.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/scheduler/fairsharing/fair_sharing_test.go
  test/integration/scheduler/podsready/scheduler_test.go
  test/integration/scheduler/workload_controller_test.go
  test/integration/webhook/core/workload_test.go
  test/performance/scheduler/runner/controller/controller.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#3917 Revert "Add section about Workload's requeueState field to KEP#349"
  keps/349-all-or-nothing/README.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#3923 [Follow-up] Remove unnecessary admission plugins from visibility server
  pkg/visibility/server.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/admission.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/OWNERS
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/doc.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/install/install.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/register.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/types.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/defaults.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/doc.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/register.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/types.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/zz_generated.conversion.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1/zz_generated.defaults.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/defaults.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/doc.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/register.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/types.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1alpha1/zz_generated.defaults.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/defaults.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/doc.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/register.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/types.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/validation/validation.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/apis/resourcequota/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/config.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/doc.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/resource_access.go
  vendor/k8s.io/apiserver/pkg/quota/v1/generic/OWNERS
  vendor/k8s.io/apiserver/pkg/quota/v1/generic/configuration.go
  vendor/k8s.io/apiserver/pkg/quota/v1/generic/evaluator.go
  vendor/k8s.io/apiserver/pkg/quota/v1/generic/registry.go
  vendor/modules.txt
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3932 [Website] Add Red Hat adopter
  site/content/en/docs/adopters/index.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3921 Fix "should allow to preempt the lower priority group" test.
  test/e2e/singlecluster/pod_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#3942 Publish the debug:main image
  Makefile
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#3947 improve instructions for disabling VisibilityOnDemand feature
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3963 Doc: Fix an incorrect reference
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
Labels: lgtm, release-note-none, approved, needs-ok-to-test, size/XS, cncf-cla: yes

#3964 Remove trasc from reviewers and approvers lists.
  OWNERS
  cmd/OWNERS
  test/OWNERS
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3954 rename usage variabale to be more clear
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3968 Self-nominate gabesaba@ as a reviewer
  OWNERS
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#3937 Fix: TAS assignment error
  pkg/cache/tas_flavor_snapshot.go
  pkg/resources/requests.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#3972 [release-0.9] Fix: TAS assignment error
  pkg/cache/tas_flavor_snapshot.go
  pkg/resources/requests.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3955 Do not add finalizer to the topology after removal
  pkg/controller/tas/topology_controller.go
  test/integration/tas/tas_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#3938 MultiKueue: add tests to show worker workloads are deleted when MK AC is rejected
  test/integration/multikueue/multikueue_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#3982 Fix link to examples directory in README
  README.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#3988 Register local queue resource metrics
  pkg/controller/core/localqueue_controller.go
  test/integration/controller/core/localqueue_controller_test.go
  test/util/util.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#3978 document using AppWrappers to run wrapped custom Jobs
  site/content/en/docs/tasks/dev/integrate_a_custom_job.md
  site/content/en/docs/tasks/run/wrapped_custom_workload.md
  site/static/examples/jobs/appwrapper-leaderworkerset-sample.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3939 Update metrics docs.
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/metrics.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#3892 [Feature] Kuberay RayJob MultiKueue adapter
  Makefile-deps.mk
  Makefile-test.mk
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
  pkg/util/testingjobs/rayjob/wrappers.go
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/webhook/jobs/suite_test.go
  test/util/e2e.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#3991 [StatefulSet] Allow to change replicas without queue-name.
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/statefulset/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#3999 Automated cherry pick of #3991: [StatefulSet] Allow to change replicas without queue-name.
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/statefulset/wrappers.go
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#3515 LeaderWorkerSet integration
  Makefile-deps.mk
  Makefile-test.mk
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/webhook/webhook.yaml
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  go.mod
  go.sum
  hack/e2e-common.sh
  hack/e2e-test.sh
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/jobs.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/pod/pod.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/static/examples/serving-workloads/sample-leaderworkerset.yaml
  test/e2e/config/common/controller_manager_config.yaml
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
  test/util/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/lws/LICENSE
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/doc.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/groupversion_info.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/leaderworkerset_types.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/types.go
  vendor/sigs.k8s.io/lws/api/leaderworkerset/v1/zz_generated.deepcopy.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#3977 Cherry-pick #3908: Fix the requirement for VAP
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/util/cert/cert.go
  pkg/visibility/server.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#3995 doc: add admissionCheck example link
  site/content/en/docs/concepts/admission_check.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#4011 Prepare release v0.10.1
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4010 Prepare release v0.9.3
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4019 Improvements to the release instructions identified during 0.10.1
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4018 Update latest version to v0.10.1
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4020 Update v0.9 release changelog
  CHANGELOG/CHANGELOG-0.9.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4005 Revert "MultiKueue: add tests to show worker workloads are deleted when MK AC is rejected"
  test/integration/multikueue/multikueue_test.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4025 Rename leaderworkerset integration to leaderworkerset.x-k8s.io/leaderworkerset.
  apis/config/v1beta1/configuration_types.go
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/e2e/config/common/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4026 Add AppWrapper to the lists of integrations consistently
  apis/config/v1beta1/configuration_types.go
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/tasks/run/wrapped_custom_workload.md
  test/e2e/config/common/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4029 Fix integration tests fail after upgrade to 1.32.
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/bug, size/L, lgtm, kind/failing-test, release-note-none, approved, cncf-cla: yes

#4006 fix: propagate priority-class label for leaderworkerset
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4035 cherry-pick for 0.10: fix: propagate priority-class label for deploy and statefulset
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#4036 cherry-pick for 0.9: fix: propagate priority-class label for deploy and statefulset
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#4034 [MultiKueue] Add Pod MK adapter
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_multikueue_adapter.go
  pkg/controller/jobs/pod/pod_multikueue_adapter_test.go
  site/static/examples/multikueue/create-multikueue-kubeconfig.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/multikueue/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, ok-to-test, cncf-cla: yes

#4054 [Cleanup] Use PROJECT_DIR for crd path instead of indirect path
  Makefile-test.mk
  test/integration/controller/admissionchecks/provisioning/suite_test.go
  test/integration/controller/core/suite_test.go
  test/integration/controller/jobframework/setup/setup_controllers_test.go
  test/integration/controller/jobframework/setup/suite_test.go
  test/integration/controller/jobs/appwrapper/suite_test.go
  test/integration/controller/jobs/job/suite_test.go
  test/integration/controller/jobs/jobset/suite_test.go
  test/integration/controller/jobs/mpijob/suite_test.go
  test/integration/controller/jobs/mxjob/suite_test.go
  test/integration/controller/jobs/paddlejob/suite_test.go
  test/integration/controller/jobs/pod/suite_test.go
  test/integration/controller/jobs/pytorchjob/suite_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/controller/jobs/tfjob/suite_test.go
  test/integration/controller/jobs/xgboostjob/suite_test.go
  test/integration/framework/framework.go
  test/integration/importer/suite_test.go
  test/integration/kueuectl/suite_test.go
  test/integration/multikueue/suite_test.go
  test/integration/scheduler/fairsharing/suite_test.go
  test/integration/scheduler/podsready/suite_test.go
  test/integration/scheduler/suite_test.go
  test/integration/tas/suite_test.go
  test/integration/webhook/core/suite_test.go
  test/integration/webhook/jobs/suite_test.go
  test/util/constants.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4031 Document current behavior of workload deletion if AC is rejected
  test/integration/multikueue/multikueue_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4065 Link Kueue's logos in README
  README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4058 Remove comment for #3841
  pkg/controller/admissionchecks/multikueue/workload.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4069 Ignore the workload is controlled by another object.
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#3983 Stop supporting FlowSchema and PriorityLevelConfiguration v1beta3.
  Makefile
  charts/kueue/templates/visibility-apf/flowschema.yaml
  charts/kueue/templates/visibility-apf/prioritylevelconfigurations.yaml
  config/visibility-apf/1_28/kustomization.yaml
  config/visibility-apf/kustomization.yaml
  hack/e2e-common.sh
  hack/update-helm.sh
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  test/e2e/config/1_28/kustomization.yaml
  test/e2e/config/common/kustomization.yaml
  test/e2e/config/default/controller_manager_config.yaml
  test/e2e/config/default/kustomization.yaml
  test/e2e/config/default/manager_e2e_patch.yaml
Labels: release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#3952 [StatefulSet] Disallow changes to PodSpec fields other than the image field
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/statefulset/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4080 [Cleanup] Make test-integration to call only singlecluster tests
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3959 [Feature] Multikueue adapter of RayCluster
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go
  pkg/util/testingjobs/raycluster/wrappers.go
  site/content/en/docs/overview/_index.md
  test/e2e/config/default/controller_manager_config.yaml
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#4023 [LeaderWorkerSet] Support LeaderReadyStartupPolicy
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/setup.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
Labels: kind/feature, lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#4072 factor out managedBy defaulting logic
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/interface.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4076 refactor: use increment instead of `+= 1`
  .golangci.yaml
  pkg/cache/clusterqueue_test.go
  pkg/cache/resource_node.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/queue/cluster_queue.go
  pkg/scheduler/scheduler_test.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/singlecluster/controller/jobs/rayjob/rayjob_controller_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#2737 KEP: Introduce a new timeout to WaitForPodsReady config
  keps/349-all-or-nothing/README.md
  keps/349-all-or-nothing/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4070 Prevent updating Job status on suspended jobs
  pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_multikueue_adapter.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#4068 Improve logging for TAS to debug rare CI failures
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4087 Automated cherry pick of #4068: Improve logging for TAS to debug rare CI failures
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4089 TAS fix the topology create event logging
  pkg/controller/tas/topology_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4088 Automated cherry pick of #4087: Improve logging for TAS to debug rare CI failures
  pkg/controller/tas/resource_flavor.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4092 Increase the timeout for integration tests
  test/util/constants.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#3897 add argo integration based on pod integration
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/dev/external_frameworks.md
  site/content/en/docs/tasks/run/external_workloads/_index.md
  site/content/en/docs/tasks/run/external_workloads/argo_workflow.md
  site/content/en/docs/tasks/run/external_workloads/flux_miniclusters.md
  site/content/en/docs/tasks/run/external_workloads/wrapped_custom_workload.md
  site/static/_redirects
  site/static/examples/pod-based-workloads/workflow-queue-per-template.yaml
  site/static/examples/pod-based-workloads/workflow-single-queue.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#4099 Add linkTitle for argo workflow doc
  site/content/en/docs/tasks/run/external_workloads/argo_workflow.md
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4100 reference jobset sample rather than inline
  site/content/en/docs/tasks/run/jobsets.md
  site/static/examples/jobs/sample-jobset.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#3881 Add metrics e2e tests
  pkg/util/strings/strings.go
  pkg/util/strings/strings_test.go
  pkg/util/testing/wrappers.go
  test/e2e/config/default/controller_manager_config.yaml
  test/e2e/config/default/manager_e2e_patch.yaml
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/suite_test.go
  test/util/e2e.go
  test/util/util.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4094 Wait for Pods to be deleted in AfterEach.
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/statefulset_test.go
  test/util/util.go
Labels: lgtm, kind/flake, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4083 unit tests for ApplyDefaultForManagedBy
  pkg/controller/jobframework/base_webhook_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4097 Make DominantResourceShare Compatible with Cohorts
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/fair_sharing.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource.go
  pkg/cache/resource_node.go
  pkg/cache/resource_node_test.go
  pkg/cache/resource_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4114 Update workload AdmissionChecks status on AdmissionRequest creation error.
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4117 Automated cherry pick of #4114: Update workload AdmissionChecks status on AdmissionRequest creation error.
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4118 Automated cherry pick of #4114: Update workload AdmissionChecks status on AdmissionRequest creation error.
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes
