Repository kubernetes-sigs/kueue, pull requests merged in 2025-08, with the labels that each got.

#6157 [Docs][zh]Localize jobsets.md
  site/content/zh-CN/docs/tasks/run/multikueue/jobsets.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S, area/localization, language/zh

#6255 [Docs][zh]Localize kubeflow.md
  site/content/zh-CN/docs/tasks/run/multikueue/kubeflow.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6318 Add kueue- prefix for secretName on the Kustomize configuration
  config/components/certmanager/certificate-metrics.yaml
  config/components/certmanager/common_name_transformer.yaml
  config/components/certmanager/kustomization.yaml
  config/components/certmanager/secret_name_transformer.yaml
  config/default/cert_metrics_manager_patch.yaml
  config/default/manager_webhook_patch.yaml
  test/e2e/certmanager/metrics_test.go
  test/e2e/config/certmanager/dev/kustomization.yaml
  test/e2e/config/certmanager/kustomization.yaml
Labels: kind/bug, release-note, lgtm, approved, size/M, kind/cleanup, cncf-cla: yes

#6271 [website] Update MultiKueue Dispatcher API site
  site/content/en/docs/concepts/multikueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#6264 [Docs][zh]Localize multikueue/job.md
  site/content/zh-CN/docs/tasks/run/multikueue/job.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6332 Fix accounting for the evicted_workloads_once_total metric
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/tas/node_failure_controller.go
  pkg/metrics/metrics.go
  pkg/scheduler/preemption/preemption.go
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#6270 FlavorFungibility: update documentation for FlavorFungibilityImplicitPreferenceDefault
  site/content/en/docs/concepts/cluster_queue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5929 [YAML Processor] Generate chart templates for certmanager with yaml processor.
  charts/kueue/templates/certmanager/certificate-metrics.yaml
  charts/kueue/templates/certmanager/certificate.yaml
  hack/processing-plan.yaml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6370 Prepare release v0.13.1
  CHANGELOG/CHANGELOG-0.13.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6372 Update CHANGELOG after v0.12.6
  CHANGELOG/CHANGELOG-0.12.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6304 [Flaky] Fix "should preempt a workload from LQ with higher recent usage"
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/fairsharing/suite_test.go
Labels: kind/bug, size/L, lgtm, kind/flake, release-note-none, approved, cncf-cla: yes

#6371 Update main with the latest v0.13.1
  CHANGELOG/CHANGELOG-0.13.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6369 Cleanup provisioning integration tests.
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6380 [Docs][zh]Localize kueuectl_patch/_index.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6377 [Docs][zh]Localize kueuectl_get_workload.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6378 [Docs][zh]Localize kueuectl_list/_index.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_list/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6353 [Docs][zh]Localize kueuectl_get_localqueue.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6354 [Docs][zh]Localize kueuectl_get_resourceflavor.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6387 Use request context instead of context.TODO().
  cmd/kueueviz/backend/handlers/api_handlers.go
  cmd/kueueviz/backend/handlers/cluster_queues.go
  cmd/kueueviz/backend/handlers/cohorts.go
  cmd/kueueviz/backend/handlers/local_queue_workloads.go
  cmd/kueueviz/backend/handlers/local_queues.go
  cmd/kueueviz/backend/handlers/namespaces.go
  cmd/kueueviz/backend/handlers/resource_flavors.go
  cmd/kueueviz/backend/handlers/websocket_handler.go
  cmd/kueueviz/backend/handlers/workloads.go
  cmd/kueueviz/backend/handlers/workloads_dashboard.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6440 chore: Fix a typo for fungibility
  pkg/features/kube_features.go
  pkg/scheduler/flavorassigner/flavorassigner.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6274 [Docs][zh]Localize leaderworkerset.md
  site/content/zh-CN/docs/tasks/run/leaderworkerset.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6338 [Docs][zh]Localize kueuectl_get_clusterqueue.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6439 [Docs][zh]Localize kueuectl_patch_resourceflavor.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6441 [Docs][zh]Localize kueuectl_patch_workload.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6297 Commonize workload eviction and fix accounting for related metrics
  pkg/controller/core/workload_controller.go
  pkg/controller/tas/node_failure_controller.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6385 Support E2E_RUN_ONLY_ENV for kueueviz e2e tests.
  hack/e2e-kueueviz-local.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6456 Ask for cleanup if E2E_RUN_ONLY_ENV=true.
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  site/content/en/docs/contribution_guidelines/testing.md
  site/content/zh-CN/docs/contribution_guidelines/testing.md
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6464 Automated cherry pick of #6459: Unexport workload functions and rename workload.EvictWorkload -> workload.Evict
  pkg/controller/core/workload_controller.go
  pkg/controller/tas/node_failure_controller.go
  pkg/scheduler/preemption/preemption.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6421 [AFS] Get rid of creating redundant LQs in integration tests
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6468 chore: FlavorQuotas testing wrapper should be built by Obj()
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_node_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#6469 Update the logos links
  README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#6471 Drop the Architecture README section
  README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/S

#6483 Ensure CQ and LQ are active in ProvisioningRequests tests
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6481 Prepare ./hack/releasing/sync-notes.sh.
  hack/releasing/sync-notes.sh
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6494 Prepare ./hack/releasing/wait_for_images.sh.
  hack/releasing/wait_for_images.sh
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6275 [Docs][zh]Localize jobsets.md
  site/content/zh-CN/docs/tasks/run/jobsets.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6524 Automated cherry pick of #6501: Fix Kueue crashing when PodSet count is 0
  pkg/cache/tas_flavor_snapshot.go
  pkg/resources/requests.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#6527 Prepare release v0.12.7
  CHANGELOG/CHANGELOG-0.12.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6529 Add v0.12.7 changelog to the main branch
  CHANGELOG/CHANGELOG-0.12.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#6404 [Docs][zh]Localize appwrappers.md
  site/content/zh-CN/docs/tasks/run/appwrappers.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6502 [Docs][zh]Localize administer_cluster_quotas.md
  site/content/zh-CN/docs/tasks/manage/administer_cluster_quotas.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6545 [Cleanup] Expect delete obj with timeout in MK e2e tests
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6546 [Cleanup] Use wrapper for workload admission
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6492 Add initial documentation for ElastiJobs - batchv1/Job
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/elastic_workload.md
  site/content/en/docs/tasks/run/jobs.md
  site/static/examples/jobs/sample-scalable-job.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#6557 [Cleanup] Separate deploy availability and check no restarts
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6560 Automated cherry pick of #6468: chore: FlavorQuotas testing wrapper should be built by Obj()
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_node_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#6466 MultiKueue testing: allow running tests after: The connection to a worker cluster is unreliable
  test/e2e/multikueue/e2e_test.go
  test/util/e2e.go
Labels: lgtm, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#6555 Self-Nominate gabesaba@ as Full Approver
  OWNERS
  pkg/cache/OWNERS
  pkg/hierarchy/OWNERS
  pkg/resources/OWNERS
  pkg/scheduler/OWNERS
  pkg/util/OWNERS
  test/OWNERS
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#6564 Add Kueue-native Deployment support leveraging WorkloadSlices KEP-77 Graduation
  keps/77-dynamically-sized-jobs/README.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#6533 [Docs][zh]Localize kueuectl_list_workload.md
  site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6592 refactor: remove unused 'ctx' parameter
  pkg/controller/core/localqueue_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#6617 Fix fairsharing reclamation bug
  pkg/cache/fair_sharing.go
  pkg/cache/fair_sharing_test.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6603 fix(kueueviz): use wildcard for CORS allowed origins in development mode
  cmd/kueueviz/backend/README.md
  cmd/kueueviz/backend/middleware/cors.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#6630 fix: wait for workload creation object retention e2e
  test/e2e/customconfigs/objectretentionpolicies_test.go
Labels: lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#6634 Fix cohort link in docs
  site/content/en/docs/concepts/cohort.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#6570 TAS: Filter out Node updates with LastHeartbeatTime changes
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/resource_flavor_test.go
  pkg/util/testingjobs/node/wrappers.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6642 Fix sync-notes.sh.
  hack/releasing/sync-notes.sh
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#6649 Prepare release v0.13.3
  CHANGELOG/CHANGELOG-0.13.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#6652 Update the latest version with v0.13.3
  CHANGELOG/CHANGELOG-0.13.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#6654 Use utiltesting.ContextWithLog().
  pkg/cache/tas_flavor_snapshot_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6644 Add tests for HasLevel.
  pkg/cache/tas_flavor_snapshot_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6656 Add logging to verify target selection for fairsharing
  pkg/scheduler/logging.go
  pkg/scheduler/preemption/preemption.go
  pkg/util/logging/logging.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6669 ensures that Target implements ObjectRefProvider interface at compile time
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#6670 Fix CrashLoopBackOff when using config/alpha-enabled.
  pkg/scheduler/scheduler.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6655 Add unit tests for jobframework/tas.go.
  pkg/controller/jobframework/tas_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6679 Remove skipOnDarwin for TestFSWatchAddRm.
  pkg/controller/admissionchecks/multikueue/fswatch_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6680 Add a full stop at the end of a comment.
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#6694 Take into account Pod observedGeneration in E2E test for v1.34.
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/pod_test.go
  test/util/constants.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6692 Fix ElasticJob integration test bug.
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, release-note-none, approved, size/XS, cncf-cla: yes
