Repository kubernetes-sigs/kueue, pull requests merged in 2025-03, with the labels that each got.

#4438 [Flake] Change image behavior of high-priority-group pod
  test/e2e/singlecluster/pod_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#4450 Automated cherry pick of #4438: [Flake] Change image behavior of high-priority-group pod
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/suite_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4447 Introduce the helper struct for preemptedWorkloads
  pkg/scheduler/preempted_workloads.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4449 Refactor the accounting for preempted workloads in scheduler
  pkg/cache/clusterqueue_snapshot.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4461 Bump github.com/golangci/golangci-lint from 1.63.4 to 1.64.6 in /hack/internal/tools
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4460 Unexport manager fields
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_node_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/cohort_controller_test.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/queue/dumper.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4178 feat: add configuration to kueue-viz backend
  cmd/experimental/kueue-viz/.gitignore
  cmd/experimental/kueue-viz/backend/README.md
  cmd/experimental/kueue-viz/backend/go.mod
  cmd/experimental/kueue-viz/backend/go.sum
  cmd/experimental/kueue-viz/backend/main.go
Labels: release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#4464 Clean up TAS findLevelWithFitDomain loop
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4466 rename local variable in WaitForAppWrapperAvailability
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4463 Bump sigs.k8s.io/controller-tools from 0.17.1 to 0.17.2 in /hack/internal/tools
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4469 Fix flaky deploy ManageJobsWithoutQueue e2e test
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4420 Serialization support for FlavorResource, FlavorResourceSet and FlavorResourceQuantities
  pkg/resources/resource.go
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#4476 Use ReserveQuotaAt instead of ReserveQuota on unit tests
  pkg/scheduler/preemption/preemption_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, size/XL, approved, cncf-cla: yes

#4341 TAS: fix topology assignment for the RayJob's submitter Job
  Makefile-test.mk
  hack/e2e-test.sh
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/tas/rayjob_test.go
  test/e2e/tas/suite_test.go
  test/util/constants.go
  test/util/e2e.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4482 fix construction of activePods in WaitForActivePodsAndTerminate
  test/util/e2e.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4483 Doc: Fix Prometheus Operator installing guide link
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4487 Automated cherry pick of #4484: Allow for one to change namespace for roles for prometheus
  charts/kueue/README.md
  charts/kueue/templates/prometheus/role.yaml
  charts/kueue/values.yaml
Labels: release-note, lgtm, approved, size/XS, cncf-cla: yes

#4490 Automated cherry pick of #4478: [release-0.10] Use ReserveQuotaAt instead of ReserveQuota on unit tests
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#4488 Automated cherry pick of #4484: Allow for one to change namespace for roles for prometheus
  charts/kueue/README.md
  charts/kueue/templates/prometheus/role.yaml
  charts/kueue/values.yaml
Labels: release-note, lgtm, approved, size/XS, cncf-cla: yes

#4452 Automated cherry pick of #4438: [Flake] Change image behavior of high-priority-group pod
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/suite_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4496 ClusterQueueSnapshot.DominantResourceShare - Delete unused return value
  pkg/cache/clusterqueue_snapshot.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4493 Define EntryIterator
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4494 Bump mui/material and mui/icons-material from 5.16.14 to 6.4.6 in /cmd/experimental/kueue-viz/frontend
  cmd/experimental/kueue-viz/frontend/package.json
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4498 Add check to verify RayJob tas pods were deleted
  test/e2e/tas/rayjob_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4504 [Flake] Extend VeryLongTimeout duration to 5 minutes
  test/util/constants.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#4486 add binding metrics port for helm and kustomize
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/values.yaml
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
Labels: kind/bug, lgtm, kind/regression, release-note-none, approved, cncf-cla: yes, size/S

#4418 TAS: support for cohorts and preemptions within them
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#4507 fix arguments to AgnHostImage in AppWrapper TAS test
  test/e2e/tas/appwrapper_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4502 Automated cherry pick of #4341: TAS: fix topology assignment for the RayJob's submitter Job #4498: Add check to verify RayJob tas pods were deleted
  Makefile-deps.mk
  Makefile-test.mk
  hack/e2e-common.sh
  hack/e2e-test.sh
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/rayjob_test.go
  test/e2e/tas/suite_test.go
  test/integration/controller/jobs/raycluster/suite_test.go
  test/integration/controller/jobs/rayjob/suite_test.go
  test/integration/webhook/jobs/suite_test.go
  test/util/constants.go
  test/util/e2e.go
  test/util/util.go
Labels: release-note, lgtm, size/XL, approved, cncf-cla: yes

#4513 [Cleanup] Add listOptions to WaitForActivePodsAndTerminate
  test/e2e/singlecluster/pod_test.go
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4503 Determine candidate ordering for Fair Sharing in Hierarchical Cohorts
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/hierarchy/cohort.go
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#4518 Simply Clearing of FairSharingIterator's DRSValue map
  pkg/scheduler/fair_sharing_iterator.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4517 Improve Scheduling and FairSharingIterator logging
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4521 Fix integration test on release-0.10
  test/integration/controller/jobs/mxjob/mxjob_controller_test.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4165 Do not consider preemption.borrowWithinCohort in FairSharing preemptions
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4416 docs: create RemoveFinalizersWithStrictPatch KEP
  keps/3899-remove-finalizers-with-strict-patch/README.md
  keps/3899-remove-finalizers-with-strict-patch/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#4472 Move Pod labels and annotation to separate package.
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/pod/constants/constants.go
  pkg/controller/jobs/pod/event_handlers.go
  pkg/controller/jobs/pod/indexer.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/tas_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/webhook/jobs/pod_webhook_test.go
  test/integration/singlecluster/webhook/jobs/statefulset_webhook_test.go
  test/util/util.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#4511 Create ResourceFlavor before Topology
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#4526 chore: Avoid to initialize field.ErrorList with an empty slice
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/webhooks/resourceflavor_webhook.go
  pkg/webhooks/workload_webhook.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4522 chore: Avoid empty slice usage in RaJob testings
  pkg/util/testingjobs/rayjob/wrappers.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/tas/rayjob_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4523 Fix 'has malformed LC_DYSYMTAB' warnings for integration testings for MacOS
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4512 ClusterQueueReference; CohortReference
  apis/kueue/v1alpha1/cohort_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  cmd/kueuectl/app/create/create_clusterqueue.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/cohort.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/workload_controller.go
  pkg/hierarchy/clusterqueue.go
  pkg/hierarchy/cohort.go
  pkg/hierarchy/cycle.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/metrics/metrics.go
  pkg/queue/cluster_queue.go
  pkg/queue/cohort.go
  pkg/queue/dumper.go
  pkg/queue/local_queue.go
  pkg/queue/manager.go
  pkg/queue/manager_test.go
  pkg/queue/status_checker.go
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/logging.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/visibility/api/v1beta1/pending_workloads_cq.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/kueuectl/create_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/performance/scheduler/runner/generator/generator.go
  test/performance/scheduler/runner/recorder/recorder.go
  test/util/util.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4528 use 8443 instead of target port
  charts/kueue/values.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4541 TAS: cohorts and preemptions are no longer limitations
  site/content/en/docs/concepts/topology_aware_scheduling.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4524 Add JobUID to preemption condition messages
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  site/content/en/docs/concepts/preemption.md
  test/integration/singlecluster/scheduler/preemption_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#4295 TAS: allow to dump the usage of domains for TAS ResourceFlavors
  pkg/cache/snapshot.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/cache/tas_flavor_snapshot_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#4346 chore: Enable nilerr, nilnesserr
  .golangci.yaml
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/jobs/jobset/jobset_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#4519 TAS: Use TAS implicitly when CQ is TAS-only
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/snapshot.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#4556 TAS: Update KEP with the implicit defaulting of TAS annotations
  keps/2724-topology-aware-scheduling/README.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4547 fix webhook registration when API is available
  pkg/controller/jobframework/setup.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#4404 KEP-4377: Secured Prometheus metrics endpoints
  keps/4377-metrics-tls/README.md
  keps/4377-metrics-tls/kep.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#4563 Move preempted_workloads to preemption package
  pkg/scheduler/preemption/preempted_workloads.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4564 Refactor FairSharing Preemption
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4565 TAS: Rename MostAllocatedFit -> BestFit, LeastAllocatedFit -> MostFreeCapacityFit
  keps/2724-topology-aware-scheduling/kep.yaml
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/features/kube_features.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4515 [Cleanup] make terminating pods not racy
  test/util/e2e.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4577 Update AppWrapper to v1.1.0
  go.mod
  go.sum
  hack/e2e-common.sh
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  vendor/github.com/project-codeflare/appwrapper/api/v1beta2/groupversion_info.go
  vendor/modules.txt
Labels: kind/feature, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#4583 Fix mixed variable names.
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4543 Expose the TopologyName in LocalQueue status
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go
  client-go/applyconfiguration/kueue/v1beta1/topology.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  keps/3122-expose-flavors-in-localqueue-status/README.md
  pkg/cache/cache.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#4584 Upgrade Go version to 1.24
  cmd/experimental/kueue-viz/backend/go.mod
  go.mod
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
  site/go.mod
  site/go.sum
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4589 Do not consider preemption.borrowWithinCohort in FairSharing preemptions (to 0.9)
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4588 Do not consider preemption.borrowWithinCohort in FairSharing preemptions (to 0.10)
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4567 TAS: Add the `kueue.x-k8s.io/podset-unconstrained-topology` annotation
  apis/kueue/v1alpha1/tas_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podsettopologyrequest.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/jobframework/tas.go
  pkg/controller/jobframework/tas_validation.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/features/kube_features.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4576 TAS: Add TAS profiles and the LeastFreeCapacityFit algorithm
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/features/kube_features.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4592 TAS: KEP: Remove implicit unconstrained default
  keps/2724-topology-aware-scheduling/README.md
  keps/2724-topology-aware-scheduling/kep.yaml
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4595 Always use FairSharing preemption logic when FS enabled
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4593 TAS: change implied default to unconstrained, remove the `TASImplicitDefaultUnconstrained` feature gate
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/features/kube_features.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4385 add ability to give tls certificates to metrics server
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/certmanager/certificatemetrics.yaml
  charts/kueue/templates/manager/manager.yaml
  charts/kueue/templates/prometheus/monitor.yaml
  charts/kueue/values.yaml
  cmd/kueue/main.go
  config/components/certmanager/certificate-metrics.yaml
  config/components/certmanager/kustomization.yaml
  config/components/prometheus/kustomization.yaml
  config/components/prometheus/monitor_tls_patch.yaml
  config/default/cert_metrics_manager_patch.yaml
  config/default/kustomization.yaml
  site/content/en/docs/reference/kueue-config.v1beta1.md
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#4562 Optimize kueue-viz frontend build: Remove react-script and add .dockerignore
  cmd/experimental/kueue-viz/frontend/.dockerignore
  cmd/experimental/kueue-viz/frontend/.env
  cmd/experimental/kueue-viz/frontend/Dockerfile
  cmd/experimental/kueue-viz/frontend/index.html
  cmd/experimental/kueue-viz/frontend/package.json
  cmd/experimental/kueue-viz/frontend/public/env.js
  cmd/experimental/kueue-viz/frontend/src/App.jsx
  cmd/experimental/kueue-viz/frontend/src/ClusterQueueDetail.jsx
  cmd/experimental/kueue-viz/frontend/src/ClusterQueues.jsx
  cmd/experimental/kueue-viz/frontend/src/CohortDetail.jsx
  cmd/experimental/kueue-viz/frontend/src/Cohorts.jsx
  cmd/experimental/kueue-viz/frontend/src/Dashboard.jsx
  cmd/experimental/kueue-viz/frontend/src/FlavorTable.jsx
  cmd/experimental/kueue-viz/frontend/src/LocalQueueDetail.jsx
  cmd/experimental/kueue-viz/frontend/src/LocalQueues.jsx
  cmd/experimental/kueue-viz/frontend/src/Navbar.jsx
  cmd/experimental/kueue-viz/frontend/src/ResourceFlavorDetail.jsx
  cmd/experimental/kueue-viz/frontend/src/ResourceFlavors.jsx
  cmd/experimental/kueue-viz/frontend/src/WorkloadDetail.jsx
  cmd/experimental/kueue-viz/frontend/src/Workloads.jsx
  cmd/experimental/kueue-viz/frontend/src/WorkloadsList.jsx
  cmd/experimental/kueue-viz/frontend/src/env.js
  cmd/experimental/kueue-viz/frontend/src/index.jsx
  cmd/experimental/kueue-viz/frontend/start.sh
  cmd/experimental/kueue-viz/frontend/vite.config.js
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4600 Fix typo, memoizing -> memorizing.
  pkg/hierarchy/cycle.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4602 Refactor and Introduce Types to FairSharingStrategy
  pkg/scheduler/fairsharing/strategy.go
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4552 Add development docs regarding testing
  site/content/en/docs/contribution_guidelines/_index.md
  site/content/en/docs/contribution_guidelines/testing.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#4601 Fix comment prefixes.
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/jobframework/webhook/builder.go
  pkg/hierarchy/manager.go
  pkg/util/testingjobs/appwrapper/wrappers.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/tfjob/wrappers_tfjob.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4603 [FairSharing] Add Workload Usage to Snapshot
  pkg/cache/clusterqueue_snapshot.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4607 Move FairSharing package to Preemption/FairSharing
  pkg/scheduler/preemption/fairsharing/strategy.go
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4605 Add link to stress tool website in docs
  site/content/en/docs/contribution_guidelines/testing.md
Labels: lgtm, release-note-none, approved, needs-ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#4616 [release-0.10] Fix unintended write Operation for TAS SinglePodRequests
  pkg/cache/tas_flavor_snapshot.go
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4611 Wait for all Pods deleted in AfterEach block.
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/appwrapper_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/kueuectl_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/pod_group_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4617 Fix Admits workloads respecting fair share test.
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#4622 e2e testing: Log wait time per operator
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4621 TAS: use exit fast images wherever possible (cleanup)
  test/e2e/tas/appwrapper_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4628 chore: Use reconcile batch period constants
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/controller/tas/topology_ungater.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4627 Use RequestAndLimit on e2e tests.
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/deployment/wrappers.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/util/testingjobs/jobset/wrappers.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/pod/wrappers.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/appwrapper_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/e2e/tas/appwrapper_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pod_group_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/rayjob_test.go
  test/e2e/tas/statefulset_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4585 Add TEST_LOG_LEVEL env variable to control logging verbosity.
  Makefile-test.mk
  test/e2e/customconfigs/suite_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/e2e/tas/suite_test.go
  test/integration/framework/framework.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4625 Use TypedControllerManagedBy in localqueue controller
  pkg/controller/core/localqueue_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4624 Consolidate object update channel source into one in clusterqueue controller
  pkg/controller/core/clusterqueue_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4630 Use TypedControllerManagedBy in workload controller
  pkg/controller/core/workload_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4631 Use TypedControllerManagedBy in the admissioncheck controller
  pkg/controller/core/admissioncheck_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4632 Use TypedControllerManagedBy in the cohort controller
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/cohort_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4633 Use TypedControllerManageBy in the resourceflavor controller
  pkg/controller/core/resourceflavor_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4636 TAS: KEP update to add perf test to Beta requirements
  keps/2724-topology-aware-scheduling/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#4637 Make HasCycle Stateless
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/cohort.go
  pkg/cache/resource_node.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
  pkg/hierarchy/cycle.go
  pkg/hierarchy/manager.go
  pkg/hierarchy/manager_test.go
  pkg/queue/cohort.go
  pkg/queue/manager.go
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4561 Cohort Fair Sharing Status and Metrics.
  apis/kueue/v1alpha1/cohort_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/fairsharing_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  keps/79-hierarchical-cohorts/README.md
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/resource_node.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/cohort_controller_test.go
  pkg/controller/core/core.go
  pkg/metrics/metrics.go
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/content/en/docs/reference/metrics.md
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4652 chore: remove unreferenced struct member
  pkg/controller/tas/topology_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4653 TAS: Fix TopologyUngator LeaderElection trigger
  pkg/controller/tas/topology_ungater.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#4649 Consistently Capitalize Fair Sharing - Docs
  CHANGELOG/CHANGELOG-0.7.md
  README.md
  keps/1714-fair-sharing/README.md
  keps/1714-fair-sharing/kep.yaml
  keps/79-hierarchical-cohorts/README.md
  site/content/en/docs/concepts/_index.md
  site/content/en/docs/concepts/cluster_queue.md
  site/content/en/docs/concepts/preemption.md
  site/content/en/docs/overview/_index.md
  site/content/en/docs/reference/metrics.md
  site/content/en/docs/tasks/manage/administer_cluster_quotas.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#4648 Consistently Capitalize Fair Sharing - api/pkg
  apis/config/v1beta1/configuration_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/fairsharing_types.go
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  pkg/metrics/metrics.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: release-note, lgtm, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#4586 [Cleanup] Filter termination of pods in tests by job name
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/pod_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4660 [Flake] Add TerminationGracePeriod when applicable for tests
  pkg/util/testingjobs/deployment/wrappers.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/tas/leaderworkerset_test.go
  test/e2e/tas/statefulset_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#4620 [Flaky] Revisit RayJob TAS e2e tests to not count submitter job pod
  test/e2e/tas/rayjob_test.go
Labels: lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#4668 Automated cherry pick of #4660: [Flake] Add TerminationGracePeriod when applicable for tests
  pkg/util/testingjobs/deployment/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/tas/statefulset_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4658 Resource Node Unchanged During Preemption
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4670 Replace []cmp.Option with cmp.Options
  cmd/importer/pod/import_test.go
  pkg/cache/snapshot_test.go
  pkg/config/config_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/localqueue_controller_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/appwrapper/appwrapper_controller_test.go
  pkg/controller/jobs/appwrapper/appwrapper_multikueue_adapter_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_multikueue_adapter_test.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  pkg/hierarchy/manager_test.go
  pkg/queue/cluster_queue_test.go
  pkg/queue/manager_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/admissionchecks_test.go
  test/e2e/singlecluster/visibility_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4671 Use TypedControllerManagedby in topology ungator
  pkg/controller/tas/topology_ungater.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4672 Use TypedControllerManagedby in topology controller
  pkg/controller/tas/topology_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4673 Use TypedControllerManagedby in TAS ResourceFlavor controller
  pkg/controller/tas/resource_flavor.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4675 [Cleanup] Add TODO note to fix Kuberay operator namespace
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4677 [Feature] Integrate support of Kuberay ManagedBy
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/e2e/multikueue/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4680 Publish helm charts to kueue sub-directory
  Makefile
  hack/push-chart.sh
Labels: release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#4661 add comments to agnhost behavior
  test/util/constants.go
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#4686 [MultiKueue] Update Kuberay run documentation
  site/content/en/docs/tasks/run/multikueue/kuberay.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4689 Prepare release v0.10.3
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4691 Add v0.9.5 to CHANGELOG
  CHANGELOG/CHANGELOG-0.9.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4693 Update main to v0.10.3
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/content/en/docs/installation/_index.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes

#4598 document tls metrics
  charts/kueue/README.md
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/manage/productization/_index.md
  site/content/en/docs/tasks/manage/productization/cert_manager.md
  site/content/en/docs/tasks/manage/productization/prometheus.md
  site/go.sum
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#4696 add nits for prometheus section as follow up for review
  site/content/en/docs/tasks/manage/productization/prometheus.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4695 Refactor Fair Sharing Integration Tests
  pkg/util/testing/wrappers.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4698 Prepare the 0.11.0 release
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  config/components/manager/kustomization.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4707 Adjust main after 0.11 release
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4699 Update the release steps post 0.11.0
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4712 Adjust setting the appVersion for charts in makefile script
  Makefile
  charts/kueue/Chart.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4716 Align the prepare-release-branch script for 0.10
  Makefile
  charts/kueue/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4711 Fix workload priority for LeaderWorkerSet.
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  test/e2e/singlecluster/leaderworkerset_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4728 Update AppWrapper to v1.1.1
  go.mod
  go.sum
  vendor/github.com/project-codeflare/appwrapper/pkg/utils/utils.go
  vendor/modules.txt
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#4730 Prepare v0.11.1
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4735 Add sanity e2e test for WorkloadPriorityClass on StatefulSet.
  pkg/util/testingjobs/statefulset/wrappers.go
  test/e2e/singlecluster/statefulset_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4732 Upgrade Kind version to v0.27.0
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4596 e2e test for kueue-viz using cypress
  .gitignore
  Makefile-test.mk
  cmd/experimental/kueue-viz/frontend/cypress.config.js
  cmd/experimental/kueue-viz/frontend/cypress/e2e/app.cy.js
  cmd/experimental/kueue-viz/frontend/cypress/support/commands.js
  cmd/experimental/kueue-viz/frontend/cypress/support/e2e.js
  cmd/experimental/kueue-viz/frontend/package.json
  cmd/experimental/kueue-viz/frontend/src/ResourceFlavorDetail.jsx
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-frontend.sh
  hack/e2e-kueueviz-local.sh
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4736 Update main after v0.11.1
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4700 Adapt Kubeflow integration documentations with new Trainer brand
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/manage/setup_multikueue.md
  site/content/en/docs/tasks/run/kubeflow/_index.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/content/en/docs/tasks/run/multikueue/kubeflow.md
  site/content/en/docs/tasks/run/multikueue/mpijob.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4714 Doc: Replace Kuberay with KubeRay
  site/content/en/docs/tasks/run/multikueue/kuberay.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4702 [FSxHC] Add Integration Test
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4740 Fix push-char for kueue-viz images
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4721 [Cleanup] Provide a function that creates namespace from wrapper
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4748 Align kueue-viz tags to `main` instead if `main-latest`
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/kueue-viz/backend-deployment.yaml
  charts/kueue/templates/kueue-viz/frontend-deployment.yaml
  charts/kueue/values.yaml
  config/components/kueue-viz/backend-deployment.yaml
  config/components/kueue-viz/frontend-deployment.yaml
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4756 Use util.SetupLogger() on certmanager suite.
  test/e2e/certmanager/suite_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4754 Use testing.TB.Context() instead of context.Background()
  cmd/importer/pod/check_test.go
  cmd/importer/pod/import_test.go
  cmd/kueuectl/app/create/create_resourceflavor_test.go
  cmd/kueuectl/app/delete/delete_workload_test.go
  pkg/cache/cache_test.go
  pkg/cache/resource_node_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
  pkg/controller/admissionchecks/multikueue/fswatch_test.go
  pkg/controller/admissionchecks/multikueue/indexer_test.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler_test.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/admissionchecks/provisioning/indexer_test.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/cohort_controller_test.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobframework/setup_test.go
  pkg/controller/jobframework/webhook/defaulter_test.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/queue/cluster_queue_test.go
  pkg/queue/manager_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/admissioncheck/admissioncheck_test.go
  pkg/util/parallelize/parallelize_test.go
  pkg/util/priority/priority_test.go
  pkg/util/routine/error_channel_test.go
  pkg/util/testing/context.go
  pkg/util/wait/backoff_test.go
  pkg/visibility/api/v1beta1/pending_workloads_cq_test.go
  pkg/visibility/api/v1beta1/pending_workloads_lq_test.go
  pkg/workload/workload_test.go
  test/e2e/certmanager/suite_test.go
  test/e2e/customconfigs/suite_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/suite_test.go
  test/e2e/tas/suite_test.go
  test/integration/framework/framework.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4757 Update testing docs.
  site/content/en/docs/contribution_guidelines/testing.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4758 Ignore cypress screenshots.
  cmd/experimental/kueue-viz/frontend/.gitignore
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4708 Add FairsharingStatus API documentation to Cohort and ClusterQueue
  apis/kueue/v1alpha1/cohort_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/fairsharing_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4750 feat: Output MultiKueue's Event to workload
  pkg/controller/admissionchecks/multikueue/controllers.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#4765 Add License prefix for KueueViz sh files.
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-frontend.sh
  hack/e2e-kueueviz-local.sh
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4766 [Flake] Do not manipulate RayCluster suspend field
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/multikueue_test.go
Labels: lgtm, kind/flake, release-note-none, approved, cncf-cla: yes, size/S

#4752 Improve KueueViz documentation in preparation for release
  Makefile
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/README.md
  cmd/kueueviz/assets/kueueviz.png
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, kind/dashboard

#4773 Fix post-kueue-push-images.
  cloudbuild.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4751 [Flake] Use agnhost `test-webserver` instead of `pause`
  test/util/constants.go
Labels: lgtm, kind/flake, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4785 [Flake] Customconfigs Increase timeout waiting for unsuspended to escape flakiness
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#4783 Cleaner and more detailed error message for kueueviz frontend
  cmd/kueueviz/frontend/src/App.css
  cmd/kueueviz/frontend/src/ClusterQueueDetail.jsx
  cmd/kueueviz/frontend/src/ClusterQueues.jsx
  cmd/kueueviz/frontend/src/CohortDetail.jsx
  cmd/kueueviz/frontend/src/Cohorts.jsx
  cmd/kueueviz/frontend/src/Dashboard.jsx
  cmd/kueueviz/frontend/src/ErrorMessage.jsx
  cmd/kueueviz/frontend/src/LocalQueueDetail.jsx
  cmd/kueueviz/frontend/src/LocalQueues.jsx
  cmd/kueueviz/frontend/src/ResourceFlavorDetail.jsx
  cmd/kueueviz/frontend/src/ResourceFlavors.jsx
  cmd/kueueviz/frontend/src/WorkloadDetail.jsx
  cmd/kueueviz/frontend/src/Workloads.jsx
  cmd/kueueviz/frontend/src/WorkloadsList.jsx
  cmd/kueueviz/frontend/src/useWebSocket.js
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, kind/dashboard

#4787 Upgrade controller-runtime to v0.20.x.
  go.mod
  go.sum
  pkg/controller/jobs/pod/pod_controller_test.go
  vendor/golang.org/x/exp/maps/maps.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/.gomodcheck.yaml
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/name.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_mapped.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_owner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/kind.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/server/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4784 Use WithCustomDefaulter instead of WithLosslessDefaulter.
  go.mod
  pkg/controller/jobframework/base_webhook.go
  pkg/controller/jobframework/webhook/defaulter.go
  pkg/controller/jobframework/webhook/defaulter_test.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/job/job_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/mpijob/mpijob_webhook.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4793 Stop supporting k8s v1.29.
  Makefile-test.mk
  README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes
