Repository kubernetes-sigs/kueue, pull requests merged in 2025-02, with the labels that each got.

#4095 Increase log level for Kubernetes components.
  hack/kind-cluster.yaml
  hack/multikueue/manager-cluster.kind.yaml
  hack/multikueue/worker-cluster.kind.yaml
  hack/tas-kind-cluster.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4125 Automated cherry pick of #4095: Increase log level for Kubernetes components.
  hack/kind-cluster.yaml
  hack/multikueue/manager-cluster.kind.yaml
  hack/multikueue/worker-cluster.kind.yaml
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4108 cleanup scheduler.go
  pkg/scheduler/scheduler.go
  pkg/workload/resources.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#4130 TAS: Fix JobSet validation.
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  test/integration/singlecluster/webhook/jobs/jobset_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4086 Create PodTemplate before ProvisioningRequest
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/util/testing/wrappers.go
Labels: kind/bug, release-note, lgtm, size/XL, approved, cncf-cla: yes

#3775 Replace `time.Now()` with `clock.Clock.Now()` in pkg/pod
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#3898 Document Tekton Pipeline support with pod integration
  site/content/en/docs/tasks/run/external_workloads/_index.md
  site/content/en/docs/tasks/run/external_workloads/tektoncd.md
  site/static/examples/pod-based-workloads/tekton-hello-task.yaml
  site/static/examples/pod-based-workloads/tekton-pipeline-run.yaml
  site/static/examples/pod-based-workloads/tekton-pipeline.yaml
  site/static/examples/pod-based-workloads/tekton-sleep-task.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#4119 chore: enable nolintlint to detect unused //nolint
  .golangci.yaml
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes, size/S

#4149 Remove unused functions
  pkg/controller/core/clusterqueue_controller.go
  pkg/util/kubeversion/kubeversion.go
  pkg/util/pod/pod.go
  pkg/util/testing/condition_matchers.go
  pkg/util/testing/core.go
  pkg/util/testing/util.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4148 chore: Clean up workload resources lib
  pkg/workload/resources.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4081 Allow to change mutable PodSpec fields.
  pkg/controller/jobframework/validation.go
  pkg/controller/jobframework/validation_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/pod/pod.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4156 Automated cherry pick of #4130: TAS: Fix JobSet validation.
  pkg/controller/jobs/jobset/jobset_webhook.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  test/integration/webhook/jobs/jobset_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4103 Deployment e2e tests for MultiKueue
  test/e2e/multikueue/e2e_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#4158 chore: Use multiKueue intead of multikueue for struct and variable name
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_multikueue_adapter.go
  pkg/controller/jobs/pod/pod_multikueue_adapter_test.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4121 statefulset should have same namespace selector as pod and deployment
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/kustomization.yaml
  hack/update-helm.sh
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4159 Check deleted metrics form the test ns
  test/e2e/singlecluster/metrics_test.go
Labels: lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#4082 Fix problems with enabling cert manager with Kueue
  config/components/crd/kustomization.yaml
  config/components/crd/patches/cainjection_in_cohorts.yaml
  config/default/kustomization.yaml
  config/default/mutating_webhookcainjection_patch.yaml
  config/default/validating_webhookcainjection_patch.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4163 properly configure appwrapper webhooks
  charts/kueue/templates/webhook/webhook.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  test/integration/singlecluster/webhook/jobs/appwrapper_webhook_test.go
  test/integration/singlecluster/webhook/jobs/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4166 Graduate WorkloadResourceRequestsSummary to Stable
  keps/2937-resource-transformer/kep.yaml
  pkg/features/kube_features.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
  test/integration/singlecluster/scheduler/workload_controller_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#4172 Introduce preemption context to reduce passing of parameters
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4175 chore: Avoid unnecessary slice initialization
  pkg/controller/admissionchecks/multikueue/workload.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4176 MultiKueue: Implement suspended Job status propagation UTs
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
  pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
  pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go
  pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4179 KueueCtl: Use stable node label in help description
  cmd/kueuectl/app/create/create_resourceflavor.go
  cmd/kueuectl/app/create/create_resourceflavor_test.go
  site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_resourceflavor.md
  test/integration/singlecluster/kueuectl/create_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4177 Introduce PodRequests calculation helper of the corev1helpers
  pkg/cache/tas_flavor.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/workload/workload.go
  vendor/k8s.io/component-helpers/resource/OWNERS
  vendor/k8s.io/component-helpers/resource/helpers.go
  vendor/modules.txt
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#4182 chore: Rename JobSet Wrapper Deepcopy with Clone
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go
  pkg/util/testingjobs/jobset/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4185 ProvReq: avoid to truncate AC conditon message
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: kind/bug, release-note, lgtm, approved, size/XS, cncf-cla: yes

#4184 Utilize isPodTerminated
  cmd/importer/util/util.go
  pkg/cache/tas_flavor.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/util/pod/pod.go
  pkg/util/pod/pod_test.go
  pkg/util/testingjobs/pod/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4186 chore: Use Ray aarch64 image only when test executed platform is arm64
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4189 Automated cherry pick of #4185: ProvReq: avoid to truncate AC conditon message
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: release-note, lgtm, approved, size/XS, cncf-cla: yes

#4116 [Feature] Update MultiKueue to support Kubeflow Jobs ManagedBy
  hack/e2e-common.sh
  hack/multikueue-e2e-test.sh
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_multikueue_adapter.go
  pkg/util/testingjobs/paddlejob/wrappers.go
  pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
  pkg/util/testingjobs/tfjob/wrappers_tfjob.go
  pkg/util/testingjobs/xgboostjob/wrappers.go
  test/e2e/config/multikueue/kustomization.yaml
  test/e2e/config/multikueue/patch_crds.yaml
  test/e2e/config/multikueue/patch_deployment.yaml
  test/e2e/config/multikueue/worker/kustomization.yaml
  test/e2e/config/multikueue/worker/patch_crds.yaml
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/integration/multikueue/multikueue_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#4131 Improve error messages when ProvisioningRequest CRD is missing or unsupported
  cmd/kueue/main.go
  pkg/controller/admissionchecks/provisioning/indexer.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#4187 chore: Propagate testutil errors to the top level
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4191 Add missing external types to apply configurations
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go
  client-go/applyconfiguration/kueue/v1beta1/podset.go
  client-go/applyconfiguration/kueue/v1beta1/podsetupdate.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  hack/update-codegen.sh
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#4190 Truncate admission check error message.
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: kind/bug, release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#4194 Automated cherry pick of #4190: Truncate admission check error message.
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: kind/bug, release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#4195 Automated cherry pick of #4190: Truncate admission check error message.
  pkg/controller/admissionchecks/provisioning/controller.go
Labels: kind/bug, release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#4150 Finalize Pods if StatefulSet is not found.
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  test/e2e/singlecluster/statefulset_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4112 Add e2e tests for manageJobsWithoutQueueName
  Makefile-test.mk
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/customconfigs/suite_test.go
  test/util/constants.go
  test/util/e2e.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4201 Automated cherry pick of #4191: Add missing external types to apply configurations
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go
  client-go/applyconfiguration/kueue/v1beta1/podset.go
  client-go/applyconfiguration/kueue/v1beta1/podsetupdate.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  hack/update-codegen.sh
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#4199 Add unit test for TAS to show it works with partial admission
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4202 Automated cherry pick of #4191: Add missing external types to apply configurations
  client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go
  client-go/applyconfiguration/kueue/v1beta1/podset.go
  client-go/applyconfiguration/kueue/v1beta1/podsetupdate.go
  client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
  hack/update-codegen.sh
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#4204 TAS: Improve error message for TAS workloads when no flavor assigned
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#4213 drop manager auth proxy patch from kustomize defaults.
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4219 Implement LocalQueueDefaulting UTs for owner is managed by Kueue
  pkg/controller/jobs/job/job_webhook_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4206 Automated cherry pick of #4150: Finalize Pods if StatefulSet is not found.
  charts/kueue/templates/rbac/role.yaml
  config/components/rbac/role.yaml
  pkg/controller/jobs/statefulset/statefulset_controller.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  test/e2e/singlecluster/statefulset_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4220 Clean up enabled integrations every UT cases
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4214 Perform container building in parallel
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4203 Automated cherry pick of #4150: Finalize Pods if StatefulSet is not found.
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
  test/e2e/singlecluster/statefulset_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4222 Fix post container building commands
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4170 Using builtin methods of slice and map
  pkg/cache/clusterqueue.go
  pkg/cache/snapshot.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/jobframework/validation.go
  pkg/util/maps/maps.go
  pkg/util/slices/slices.go
  pkg/util/slices/slices_test.go
  pkg/util/testing/metrics/metrics.go
  pkg/workload/workload.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4223 Revert #4214 #4222: Make post container buildings as sequentially
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4225 chore: Increase machine size to 'E2_HIGHCPU_32' for post container image buildings
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4226 chore: Drop concurrency (-j=3) from cloudbuild
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4216 Stabilizing workload ValidateResources
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/resources.go
  pkg/workload/resources_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4217 Use compatible controller name with Prometheus
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/controller/tas/topology_ungater.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#4227 Automated cherry pick of #4217: Use compatible controller name with Prometheus
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_ungater.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#4229 Automated cherry pick of #4217: Use compatible controller name with Prometheus
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/controller/tas/topology_ungater.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#4235 Optimize StatefulSet reconciler.
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4245 Automated cherry pick of #4216: Stabilizing workload ValidateResources
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/resources.go
  pkg/workload/resources_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#4246 Automated cherry pick of #4216: Stabilizing workload ValidateResources
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/resources.go
  pkg/workload/resources_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#4248 TAS: simplify domain sorting
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4200 Refactor computation of TAS assignments
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/resources/requests.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4234 add feature gates table for graduated or deprecated features
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4174 implement TAS support in AppWrapper integration
  Makefile-test.mk
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  site/content/en/docs/overview/_index.md
  test/e2e/tas/appwrapper_test.go
  test/e2e/tas/suite_test.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4250 Extend e2e tests for scaling the LWS when LeaderReadyStartupPolicy.
  test/e2e/singlecluster/leaderworkerset_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#4253 Sync Job-integrated features table.
  site/content/en/docs/overview/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4146 TAS: Support LeaderWorkerSet
  Makefile-test.mk
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  site/content/en/docs/overview/_index.md
  test/e2e/tas/leaderworkerset_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4254 [MultiKueue] Update Kubeflow Jobs run documentation
  site/content/en/docs/tasks/run/multikueue/kubeflow.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4228 Add BestFit algorithm to TAS
  keps/2724-topology-aware-scheduling/README.md
  keps/2724-topology-aware-scheduling/kep.yaml
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/features/kube_features.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#4259 Doc: mention the supported ResourceFlavor nodeTaints effect
  site/content/en/docs/concepts/resource_flavor.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4260 Don't run 'test-e2e-customconfigs' Makefile target as part of 'run-test-e2e' Makefile target
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4272 TAS: Remove unused argumentes from WorkloadsTopologyRequests()
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4274 chore: Enable logger for tas_cash UTs
  pkg/cache/tas_cache_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4207 Improve output messages in case of failed e2e tests for metrics
  pkg/util/testing/metrics_matchers.go
  test/e2e/singlecluster/metrics_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4269 chore: Fix concurrency logging info in JobFramework Pod reconciler
  pkg/controller/jobs/pod/pod_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4268 chore: Use LimitRange wrappers during UTs
  pkg/util/limitrange/limitrange_test.go
  pkg/util/testing/wrappers.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4267 Stabilizing workload.ValidateLimitRange
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/workload/resources.go
  pkg/workload/resources_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4283 Add documentation for LeaderWorkerSet.
  site/content/en/docs/tasks/_index.md
  site/content/en/docs/tasks/run/leaderworkerset.md
  site/static/examples/serving-workloads/sample-leaderworkerset.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4291 Automated cherry pick of #4267: Stabilizing workload.ValidateLimitRange
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/limitrange/limitrange.go
  pkg/util/limitrange/limitrange_test.go
  pkg/workload/resources.go
  pkg/workload/resources_test.go
  test/integration/scheduler/scheduler_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#4293 TAS: Remove non-contributed usage calculation
  pkg/cache/tas_flavor_snapshot.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4271 TAS: Fix incorrect topology assignments under the situations where topology has insufficient allocatable Pods count
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#4251 Generalize handling of parent jobs in ReconcileGenericJob
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testingjobs/appwrapper/wrappers.go
  pkg/util/testingjobs/mpijob/wrappers_mpijob.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4284 WaitForPodsReady cleanup
  pkg/controller/core/workload_controller.go
Labels: kind/feature, lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4287 Simplify logic of WaitForPodsReady countdown
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
Labels: kind/feature, release-note, lgtm, approved, size/XS, cncf-cla: yes

#4288 Add FairSharing config to Cohort
  apis/kueue/v1alpha1/cohort_types.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/fairsharing_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  pkg/util/testing/wrappers.go
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/cohort_webhook.go
  pkg/webhooks/common.go
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4304 Make FairSharing optional in ClusterQueue
  apis/kueue/v1beta1/clusterqueue_types.go
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, kind/documentation, cncf-cla: yes

#4303 fix(docs): Change the What's next link in the Multikueue documentation from a Kueue link to a Multikueueue link
  site/content/en/docs/concepts/multikueue.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4306 chore: Remove unused constants
  apis/kueue/v1beta1/workload_types.go
  pkg/visibility/api/v1beta1/pending_workloads_cq_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4308 Clarify the comment for versioning of HELM charts in Kueue
  charts/kueue/Chart.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4309 docs: update pod integration name in documentation
  site/content/en/docs/tasks/run/deployment.md
  site/content/en/docs/tasks/run/external_workloads/argo_workflow.md
  site/content/en/docs/tasks/run/external_workloads/tektoncd.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/run/statefulset.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#4312 Publish helm charts to kueue repository
  Makefile
  hack/push-chart.sh
Labels: release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#4292 docs: add user examples for multikueue pods and deployments
  site/content/en/docs/concepts/multikueue.md
  site/content/en/docs/tasks/run/multikueue/deployment.md
  site/content/en/docs/tasks/run/multikueue/plain_pods.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes

#4171 TAS: support preemption within ClusterQueue
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler_test.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#4315 chore: Rename request with topologyRequest
  pkg/cache/tas_cache_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4321 Automated cherry pick of #4309: docs: update pod integration name in documentation
  site/content/en/docs/tasks/run/deployment.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/run/statefulset.md
Labels: lgtm, release-note-none, approved, needs-ok-to-test, size/XS, cncf-cla: yes

#4264 e2e test for parent/ancestor jobs with manageJobsWithoutQueueName
  Makefile-test.mk
  pkg/util/testingjobs/jobset/wrappers.go
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/customconfigs/suite_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4300 limit traversal of ancestor links in getAncestorJobManagedByKueue
  pkg/controller/jobframework/events.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4326 Use consistent naming for prebuilt workload across the codebase
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/util/testingjobs/pod/wrappers.go
  site/content/en/docs/reference/labels-and-annotations.md
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4256 Deprecate integrations.podOptions
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  charts/kueue/templates/webhook/webhook.yaml
  charts/kueue/values.yaml
  cmd/kueue/main.go
  config/components/manager/controller_manager_config.yaml
  hack/update-helm.sh
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md
  site/content/en/docs/tasks/run/plain_pods.md
  site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/webhook/jobs/pod_webhook_test.go
  test/integration/singlecluster/webhook/jobs/statefulset_webhook_test.go
Labels: release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#4299 Pod: Add e2e tests for the manageJobsWithoutQueueName
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4328 Automated cherry pick of #4271: TAS: Fix incorrect topology assignments under the situations where topology has insufficient allocatable Pods count
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/workload.go
  test/integration/controller/jobs/job/job_controller_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/integration/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/controller/jobs/pod/pod_controller_test.go
  test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/tas/tas_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#4145 [Cleanup] Replace using gcr.io sleep with agnhost in tests
  hack/e2e-common.sh
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/appwrapper_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/metrics_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/e2e/tas/appwrapper_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/leaderworkerset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/statefulset_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/util/constants.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4208 Validate prebuilt workload for Pod groups.
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  site/content/en/docs/reference/labels-and-annotations.md
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#4302 Extend the WaitForPodsReady API with `.recoveryTimeout` field
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults_test.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#4347 Revert "Publish helm charts to kueue repository"
  Makefile
  hack/push-chart.sh
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4313 Define FairShare Score for Cohorts; Generalize to Hierarchical Case
  pkg/cache/clusterqueue.go
  pkg/cache/cohort.go
  pkg/cache/cohort_snapshot.go
  pkg/cache/fair_sharing.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_node.go
  pkg/cache/resource_node_test.go
  pkg/cache/snapshot.go
  pkg/cache/snapshot_test.go
Labels: kind/feature, lgtm, release-note-none, size/XL, approved, cncf-cla: yes

#4351 Doc: Add Helm installation guides
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#4353 Update release process with promoting Helm chart
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4358 chore: Rename CreateNodes with CreateNodesWithStatus
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4361 chore: Use PodSet wrapper during UTs
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook_test.go
  test/integration/singlecluster/webhook/core/workload_test.go
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4362 chore: Use core ResourceName typed instead of string in GetGreaterKeys()
  pkg/scheduler/scheduler_test.go
  pkg/util/limitrange/limitrange_test.go
  pkg/util/resource/resource.go
  pkg/util/resource/resource_test.go
  pkg/workload/resources_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4357 chore: Consolidated all DeleteAllXXXJobsInNamespace() processings into deleteAllObjectsInNamespace()
  test/e2e/singlecluster/jobset_test.go
  test/e2e/tas/jobset_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4365 chore: Remove redundant type parameters for sets
  pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/util/expectations/store.go
  test/e2e/singlecluster/pod_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4363 chore: Rename podSetFlavor with psAssignment
  pkg/cache/cache_test.go
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4356 chore: Commonize duplicated expectJobUnsuspendedWithNodeSelectors()
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/tas_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4375 chore: Use plural for variables typed []PodSetAssignment
  pkg/cache/cache_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4379 chore: Use constants default PodSet name
  cmd/importer/pod/import_test.go
  pkg/cache/cache_test.go
  pkg/cache/snapshot_test.go
  pkg/cache/tas_cache_test.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/queue/cluster_queue_test.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook_test.go
  pkg/workload/workload_test.go
  test/e2e/singlecluster/e2e_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/integration/singlecluster/scheduler/workload_controller_test.go
  test/integration/singlecluster/webhook/core/workload_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4380 Bump github.com/project-codeflare/appwrapper from 1.0.4 to 1.0.6
  go.mod
  go.sum
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  vendor/github.com/project-codeflare/appwrapper/api/v1beta2/appwrapper_types.go
  vendor/github.com/project-codeflare/appwrapper/api/v1beta2/zz_generated.deepcopy.go
  vendor/github.com/project-codeflare/appwrapper/pkg/utils/utils.go
  vendor/modules.txt
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4383 Set namespace for leader election role/rolebinding
  charts/kueue/templates/rbac/leader_election_role.yaml
  charts/kueue/templates/rbac/leader_election_role_binding.yaml
  config/components/rbac/leader_election_role.yaml
  config/components/rbac/leader_election_role_binding.yaml
Labels: kind/bug, lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#4338 AppWrapper TAS: full support for PodSetTopologyRequest
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/e2e/tas/appwrapper_test.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4389 Use condition matcher instead of apimeta.FindStatusCondition().
  pkg/util/testing/condition_matchers.go
  test/integration/multikueue/multikueue_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4395 Prepare release v0.10.2
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4397 Prepare release v0.9.4
  CHANGELOG/CHANGELOG-0.9.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4399 Update main to v0.10.2
  CHANGELOG/CHANGELOG-0.10.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4400 Add v0.9.4 to CHANGELOG
  CHANGELOG/CHANGELOG-0.9.md
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4335 feat: Add a column to multikueue indicating if it is connected to worker cluster
  apis/kueue/v1beta1/multikueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#4391 Clean up Reconcile() logs.
  pkg/controller/admissionchecks/multikueue/admissioncheck.go
  pkg/controller/admissionchecks/multikueue/multikueuecluster.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/cohort_controller.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/statefulset/statefulset_reconciler.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_ungater.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4407 Fix inaccurate By message in appwrapper multikueue test case
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4408 docs: fix typo, nods -> nodes
  site/content/en/docs/concepts/topology_aware_scheduling.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#4388 Fix LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy test.
  test/e2e/singlecluster/leaderworkerset_test.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#4258 Add RF API comments for evaluated nodeTaints effect
  apis/kueue/v1beta1/resourceflavor_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4311 Commonize the code for checking if workload is managed by Kueue.
  pkg/controller/jobframework/defaults.go
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4343 Deploy: Add e2e tests for the manageJobsWithoutQueueName
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4410 Document kueueViz charts and adds params for backend and frontend images
  charts/kueue/README.md
  charts/kueue/templates/kueue-viz/backend-deployment.yaml
  charts/kueue/templates/kueue-viz/frontend-deployment.yaml
  hack/update-helm.sh
Labels: release-note, lgtm, approved, size/M, cncf-cla: yes

#4301 WaitForPodsReady.recoveryTimeout implementation
  apis/kueue/v1beta1/workload_types.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/workload/workload.go
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go
  test/integration/singlecluster/controller/jobs/rayjob/rayjob_controller_test.go
  test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/singlecluster/scheduler/podsready/scheduler_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#4419 Update KEP with new PodsReady reasons
  keps/349-all-or-nothing/README.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#4354 Automated cherry pick of #4145: [Cleanup] Replace using gcr.io sleep with agnhost in tests
  hack/e2e-common.sh
  hack/e2e-test.sh
  hack/multikueue-e2e-test.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/util/constants.go
  test/util/e2e.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4366 Automated cherry pick of #4145: [Cleanup] Replace using gcr.io sleep with agnhost in tests
  hack/e2e-common.sh
  test/e2e/multikueue/e2e_test.go
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/deployment_test.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/e2e/singlecluster/jobset_test.go
  test/e2e/singlecluster/pod_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/tas_test.go
  test/e2e/singlecluster/visibility_test.go
  test/e2e/tas/job_test.go
  test/e2e/tas/jobset_test.go
  test/e2e/tas/mpijob_test.go
  test/e2e/tas/pytorch_test.go
  test/e2e/tas/statefulset_test.go
  test/integration/controller/jobs/jobset/jobset_controller_test.go
  test/util/constants.go
  test/util/e2e.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4422 Cleanup: remove redundant helpers for scaling requests
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4423 Use SinglePodRequests internally for TopologyDomainRequests
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/tas_flavor.go
  pkg/resources/requests.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4424 [Fix] Bring back e2e test cases where image was updated from old to new
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/statefulset_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#4426 Automated cherry pick of #4424: [Fix] Bring back e2e test cases where image was updated from old to new
  test/e2e/singlecluster/statefulset_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4427 TAS: introduce the workload Usage struct
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/workload/usage.go
  pkg/workload/workload.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4412 Use ManagedByKueueLabelKey from pkg/constants.
  cmd/importer/pod/import.go
  cmd/importer/pod/import_test.go
  pkg/constants/constants.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/pod/pod_webhook.go
  pkg/controller/jobs/pod/pod_webhook_test.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
  test/integration/multikueue/multikueue_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/importer/importer_test.go
  test/integration/singlecluster/webhook/jobs/pod_webhook_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#4441 Fix preemption with TAS failure in the case of fulfilled pods count limit on Nodes
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testingjobs/node/wrappers.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#4431 StatefulSet: Add e2e tests for the manageJobsWithoutQueueName
  test/e2e/customconfigs/skipjobswithoutqueuename_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#4417 Introduce PodSetReference type for better static code analysis
  apis/kueue/v1beta1/constants.go
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podset.go
  client-go/applyconfiguration/kueue/v1beta1/podsetassignment.go
  client-go/applyconfiguration/kueue/v1beta1/podsetrequest.go
  client-go/applyconfiguration/kueue/v1beta1/podsetupdate.go
  client-go/applyconfiguration/kueue/v1beta1/reclaimablepod.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/provisioning.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/jobset/jobset_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/mpijob/mpijob_controller_test.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller_test.go
  pkg/controller/tas/topology_ungater.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/podset/podset.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/kubeflow/kubeflowjob.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/singlecluster/webhook/core/workload_test.go
Labels: lgtm, size/XL, release-note-action-required, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#4440 Cleanup getAssignments wrt calling partial admission
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S
