Repository kubernetes-sigs/kueue, pull requests merged in 2025-05, with the labels that each got.

#4704 Add ResourceFlavor specificatios for coupling of nodeTaints and tolerations to documentation
  apis/kueue/v1beta1/resourceflavor_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  site/content/en/docs/concepts/resource_flavor.md
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5142 test/e2e: fix certmanager installation
  config/components/crd/kustomization.yaml
  hack/e2e-common.sh
  test/e2e/config/certmanager/cert_metrics_manager_patch.yaml
  test/e2e/config/certmanager/image_pull_policy.yaml
  test/e2e/config/certmanager/kustomization.yaml
  test/e2e/config/certmanager/mutating_webhookcainjection_patch.yaml
  test/e2e/config/certmanager/patches/rolebinding_transformer.yaml
  test/e2e/config/certmanager/patches/secret-deletion.yaml
  test/e2e/config/certmanager/validating_webhookcainjection_patch.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#4917 [Cleanup] Use ray project mini for tests
  Makefile
  Makefile-test.mk
  hack/e2e-common.sh
  hack/internal/test-images/ray/Dockerfile
  pkg/util/testing/defaults.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#5154 Automated cherry pick of #4917: [Cleanup] Use ray project mini for tests
  Makefile
  Makefile-test.mk
  hack/e2e-common.sh
  hack/internal/test-images/ray/Dockerfile
  pkg/util/testing/defaults.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#5153 Automated cherry pick of #4917: Add ray-project-mini image Dockerfile
  Makefile
  Makefile-test.mk
  hack/e2e-common.sh
  hack/internal/test-images/ray/Dockerfile
  pkg/util/testing/defaults.go
  pkg/util/testingjobs/raycluster/wrappers.go
  pkg/util/testingjobs/rayjob/wrappers.go
  test/util/e2e.go
Labels: size/L, lgtm, release-note-none, approved, cncf-cla: yes

#5162 Cache - Small Cleanup
  pkg/cache/snapshot.go
  pkg/cache/tas_flavor.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5165 Export kind logs in the CustomConfig e2e tests before each restart
  test/util/e2e.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#4614 [Feature] [Tool] Script to download logs/artifacts from the CI job.
  .gitignore
  hack/get_build_logs.sh
Labels: kind/feature, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#5163 Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.
  test/e2e/singlecluster/deployment_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#5168 Automated cherry pick of #5163: Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.
  test/e2e/singlecluster/deployment_test.go
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#4718 [Feature] Add sanity singlecluster e2e tests for KubeRay
  Makefile-test.mk
  test/e2e/singlecluster/kuberay_test.go
Labels: kind/feature, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#5073 Fix RayJob webhook validation
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#5171 [Tests] Reclaim Nominal Quota with Zero Weight
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5179 cherry pick of #5073: Fix RayJob webhook validation
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#5180 cherry-pick of 5179: Fix RayJob webhook validation
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Labels: release-note, lgtm, approved, cncf-cla: yes, size/S

#5170 [Cleanup] Drop architecture conditions for Ray image env
  Makefile
  hack/e2e-common.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5185 Update changelog about corrupted 0.11.x (x<=2)
  CHANGELOG/CHANGELOG-0.11.md
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#5188 [Flake] Extend timeout for RayCluster MultiKueue e2e tests
  test/e2e/multikueue/e2e_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5183 Deflake ProvReq integration test by adding 100ms sleep to avoid data race
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/feature, lgtm, kind/failing-test, release-note-none, approved, size/XS, cncf-cla: yes

#4687 Introduce FS at admission time
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  apis/kueue/v1alpha1/zz_generated.deepcopy.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/fairsharing_types.go
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  client-go/applyconfiguration/kueue/v1beta1/admissionfairsharingstatus.go
  client-go/applyconfiguration/kueue/v1beta1/admissionscope.go
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuespec.go
  client-go/applyconfiguration/kueue/v1beta1/fairsharingstatus.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuespec.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuestatus.go
  client-go/applyconfiguration/utils.go
  cmd/kueue/main.go
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/localqueue.go
  pkg/controller/core/core.go
  pkg/controller/core/localqueue_controller.go
  pkg/controller/core/localqueue_controller_test.go
  pkg/features/kube_features.go
  pkg/queue/cluster_queue.go
  pkg/queue/cluster_queue_test.go
  pkg/queue/manager.go
  pkg/resources/resource.go
  pkg/util/resource/resource.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/static/examples/admission-fs/admission-fair-sharing-setup.yaml
  site/static/examples/admission-fs/lq-a-simple-job.yaml
  site/static/examples/admission-fs/lq-b-simple-job.yaml
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
  test/integration/singlecluster/scheduler/fairsharing/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#5195 [Flake] MK integration test: Wait for cq and lq to become ready before the test execution.
  test/integration/multikueue/jobs_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5196 [Cleanup] Correct ExpectClusterQueuesToBeActive for worker2Cq in mk integration
  test/integration/multikueue/jobs_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5199 Bump github.com/google/docsy from v0.10.0 to v0.11.0
  site/go.mod
  site/go.sum
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5201 Automated cherry pick of #5195: [Flake] MK integration test: Wait for cq and lq to become ready before the test execution. #5196: [Cleanup] Correct ExpectClusterQueuesToBeActive for worker2Cq in mk integration
  test/integration/multikueue/jobs_test.go
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5193 build cleanup
  Dockerfile
  Makefile
  cloudbuild.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5194 Include child modules in golangci-lint.
  Makefile
  cmd/kueueviz/backend/handlers/cluster_queues.go
  cmd/kueueviz/backend/handlers/handlers.go
  cmd/kueueviz/backend/handlers/local_queues.go
  cmd/kueueviz/backend/handlers/resource_flavors.go
  cmd/kueueviz/backend/handlers/websocket_handler.go
  cmd/kueueviz/backend/handlers/workloads_dashboard.go
  cmd/kueueviz/backend/main.go
  hack/internal/tools/ginkgo-top/ginkgo-top.go
  hack/internal/tools/pinversion.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#2742 KEP 1618: Optional garbage collection of finished Workloads
  keps/1618-optional-gc-of-workloads/README.md
  keps/1618-optional-gc-of-workloads/kep.yaml
Labels: kind/feature, size/L, lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes

#5205 dockerfile: drop redundant GOOS=linux and let buildx template the go env
  Dockerfile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5206 split gitignore and dockerignore, dockerignore a few MB of source files
  .dockerignore
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5138 scheduler: Fix nil ClusterQueue handling
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, cncf-cla: yes, size/S

#5208 Follow up on scheduler panic fix to improve logging
  pkg/scheduler/scheduler.go
Labels: kind/bug, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5136 [Feature] Admission scheduling time metrics
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/metrics/metrics.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  site/content/en/docs/reference/metrics.md
  test/e2e/customconfigs/waitforpodsready_test.go
  test/e2e/singlecluster/metrics_test.go
  test/util/e2e.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5219 Run sync-dependabot workflow only with ok-to-test label.
  .github/workflows/sync-dependabot.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5222 Fix the message produced by integration tests by using proper offset
  test/util/util.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5223 Drop unnecessary use of SetWorkloadsAdmissionCheck in tests
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5211 Update KEP-1282 to support WaitForPodsReady metrics for eviction by reason
  keps/1282-pods-ready-requeue-strategy/README.md
  keps/1282-pods-ready-requeue-strategy/kep.yaml
Labels: lgtm, release-note-none, approved, size/M, kind/documentation, cncf-cla: yes

#5204 Support extending PodSetUpdates from ProvisioningRequestDetails
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestconfigspec.go
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestpodsetupdates.go
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestpodsetupdatesnodeselector.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: kind/feature, release-note, size/L, lgtm, approved, kind/api-change, cncf-cla: yes

#5210 Add GIT_TAG and GIT_COMMIT args on Dockerfile.
  .dockerignore
  Dockerfile
  Makefile
  Makefile-test.mk
  pkg/version/version.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5231 Do not distinguish null and zero in DeletionTimestamp
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_multikueue_adapter.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5234 Drop unnecessary omitempty for ProvisioningRequestConfig fields
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
Labels: lgtm, release-note-none, approved, kind/api-change, kind/cleanup, size/XS, cncf-cla: yes

#5063 Mutating webhook with reinvocation policy
  charts/kueue/README.md
  charts/kueue/templates/webhook/manifests.yaml
  charts/kueue/values.yaml
  hack/processing-plan.yaml
Labels: kind/feature, release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#5197 Update Workload priority based on update of the `kueue.x-k8s.io/priority-class` label
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/deployment/deployment_webhook_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook_test.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook_test.go
  pkg/util/testingjobs/leaderworkerset/wrappers.go
  test/e2e/singlecluster/e2e_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#5239 [Site] Add 'kueue.x-k8s.io/podset' label to the site
  site/content/en/docs/reference/labels-and-annotations.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5241 Do not allow removal of workload priority
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
  test/e2e/singlecluster/e2e_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#5245 Move kueueviz e2e tests to test/e2e directory
  Makefile-test.mk
  hack/e2e-kueueviz-backend.sh
  hack/e2e-kueueviz-frontend.sh
  hack/e2e-kueueviz-local.sh
  test/e2e/kueueviz/cypress.config.js
  test/e2e/kueueviz/cypress/e2e/app.cy.js
  test/e2e/kueueviz/cypress/screenshots/app.cy.js/Kueue Dashboard -- should navigate to cluster-queue and verify local queues (failed).png
  test/e2e/kueueviz/cypress/screenshots/app.cy.js/Kueue Dashboard -- should navigate to cluster-queue unused-cluster-queue (failed).png
  test/e2e/kueueviz/cypress/screenshots/app.cy.js/Kueue Dashboard -- should navigate to resource-flavors and verify table content (failed).png
  test/e2e/kueueviz/cypress/screenshots/app.cy.js/Kueue Dashboard -- should verify cohort link and navigate to cohorts page (failed).png
  test/e2e/kueueviz/cypress/support/commands.js
  test/e2e/kueueviz/cypress/support/e2e.js
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5052 TAS + ProvisioningRequest
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/podsetassignment.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/snapshot.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/controller/core/workload_controller.go
  pkg/queue/manager.go
  pkg/queue/second_pass_queue.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/ptr/ptrs.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook.go
  pkg/webhooks/workload_webhook_test.go
  pkg/workload/admissionchecks.go
  pkg/workload/admissionchecks_test.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/tas/suite_test.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, kind/api-change, cncf-cla: yes

#5247 Use new kueueviz icons
  cmd/kueueviz/frontend/public/favicon.ico
  cmd/kueueviz/frontend/public/kueueviz.png
Labels: release-note, lgtm, approved, kind/cleanup, size/XS, cncf-cla: yes

#5248 Self-nominate akram as reviewer for kueueviz code and tests
  cmd/kueueviz/OWNERS
  test/e2e/kueueviz/OWNERS
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#4613 Support JAX in Kueue using training-operator 1.9
  Makefile-test.mk
  apis/config/v1beta1/configuration_types.go
  charts/kueue/templates/rbac/jaxjob_editor_role.yaml
  charts/kueue/templates/rbac/jaxjob_viewer_role.yaml
  charts/kueue/templates/rbac/role.yaml
  charts/kueue/templates/webhook/manifests.yaml
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
  config/components/rbac/jaxjob_editor_role.yaml
  config/components/rbac/jaxjob_viewer_role.yaml
  config/components/rbac/kustomization.yaml
  config/components/rbac/role.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/kubeflow/jobs/jaxjob/jaxjob_controller.go
  pkg/controller/jobs/kubeflow/jobs/jaxjob/jaxjob_controller_test.go
  pkg/controller/jobs/kubeflow/jobs/jaxjob/jaxjob_multikueue_adapter.go
  pkg/controller/jobs/kubeflow/jobs/jaxjob/jaxjob_multikueue_adapter_test.go
  pkg/controller/jobs/kubeflow/jobs/jobs.go
  pkg/util/testingjobs/jaxjob/wrappers.go
  site/content/en/docs/overview/_index.md
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/tasks/run/jobsets.md
  site/content/en/docs/tasks/run/kubeflow/_index.md
  site/content/en/docs/tasks/run/kubeflow/jaxjobs.md
  site/content/en/docs/tasks/run/kubeflow/mpijobs.md
  site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
  site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
  site/content/en/docs/tasks/run/kubeflow/tfjobs.md
  site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
  site/static/examples/jobs/sample-jaxjob.yaml
  test/e2e/config/default/controller_manager_config.yaml
  test/e2e/config/multikueue/patch_deployment.yaml
  test/e2e/multikueue/suite_test.go
  test/e2e/singlecluster/jaxjob_test.go
  test/e2e/singlecluster/leaderworkerset_test.go
  test/e2e/singlecluster/statefulset_test.go
  test/e2e/singlecluster/suite_test.go
  test/e2e/tas/leaderworkerset_test.go
  test/e2e/tas/statefulset_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/singlecluster/controller/jobs/jaxjob/jaxjob_controller_test.go
  test/integration/singlecluster/controller/jobs/jaxjob/suite_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#5251 Doc: Fix the outdated deployment queue-name label section
  site/content/en/docs/tasks/run/deployment.md
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5255 test/fix-failing-failed-workload-retention-test
  test/e2e/customconfigs/objectretentionpolicies_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5252 Fix Kueue ownership traversal resulting in permission errors
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  test/e2e/singlecluster/e2e_test.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, kind/regression, approved, cncf-cla: yes

#5263 Automated cherry pick of #5252: Fix Kueue ownership traversal resulting in permission errors
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  test/e2e/singlecluster/e2e_test.go
  test/util/util.go
Labels: kind/bug, release-note, size/L, lgtm, kind/regression, approved, cncf-cla: yes

#5264 KEP-973: Mutable PriorityClassName for suspended Workloads
  keps/973-workload-priority/README.md
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5256 TAS/Controllers - Small Cleanup
  pkg/controller/jobframework/tas.go
  pkg/controller/jobframework/tas_validation.go
  pkg/controller/jobs/appwrapper/appwrapper_controller.go
  pkg/controller/jobs/job/job_controller.go
  pkg/controller/jobs/jobset/jobset_controller.go
  pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
  pkg/controller/jobs/mpijob/mpijob_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/raycluster/raycluster_controller.go
  pkg/controller/jobs/rayjob/rayjob_controller.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5270 Cleanup functions in the integration manager
  pkg/controller/jobframework/integrationmanager.go
  pkg/controller/jobframework/integrationmanager_test.go
  pkg/controller/jobframework/reconciler.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5268 Follow-up: Clean up tests for updating the Workload priority label.
  test/e2e/singlecluster/e2e_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5277 Specify resource requests and limits for KueueViz containers
  charts/kueue/templates/kueueviz/backend-deployment.yaml
  charts/kueue/templates/kueueviz/frontend-deployment.yaml
  config/components/kueueviz/backend-deployment.yaml
  config/components/kueueviz/frontend-deployment.yaml
Labels: kind/bug, lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5279 Fix tagging of the images for KueueViz
  Makefile
  config/components/kueueviz/backend-deployment.yaml
  config/components/kueueviz/frontend-deployment.yaml
  config/components/kueueviz/kustomization.yaml
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#5280 Fix tagging of release candidate images for helm
  hack/push-chart.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5259 [Feature] Create a metric to track the number of workloads evicted due to unique reasons
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/schedulingstats.go
  client-go/applyconfiguration/kueue/v1beta1/workloadschedulingstatsevicition.go
  client-go/applyconfiguration/kueue/v1beta1/workloadstatus.go
  client-go/applyconfiguration/utils.go
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/metrics/metrics.go
  pkg/scheduler/preemption/preemption.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  site/content/en/docs/reference/metrics.md
  test/e2e/customconfigs/waitforpodsready_test.go
  test/e2e/singlecluster/metrics_test.go
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/scheduler/podsready/scheduler_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#5293 Improve TAS example
  site/static/examples/tas/sample-queues.yaml
Labels: lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes, size/S

#5300 Cleanup addOrUpdateWorkload in cache
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5306 Fix tagging for helm charts
  hack/push-chart.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5307 Fix formatting of KueueViz config yamls
  config/components/kueueviz/frontend-deployment.yaml
  config/components/kueueviz/kustomization.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5290 [Feature] Allow to merge equivalent/identical PodSets
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  client-go/applyconfiguration/kueue/v1beta1/provisioningrequestconfigspec.go
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  keps/1136-provisioning-request-support/README.md
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/controller/admissionchecks/provisioning/controller_test.go
  pkg/util/testing/wrappers.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
Labels: kind/feature, release-note, lgtm, size/XL, approved, cncf-cla: yes

#5316 Fix typo in the new API field WorkloadSchedulingStatsEvicition
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  client-go/applyconfiguration/kueue/v1beta1/schedulingstats.go
  client-go/applyconfiguration/kueue/v1beta1/workloadschedulingstatseviction.go
  client-go/applyconfiguration/utils.go
  keps/1282-pods-ready-requeue-strategy/README.md
  pkg/controller/core/workload_controller_test.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/e2e/customconfigs/waitforpodsready_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#5320 test: waitforpodsready e2e move curl-pod to test cases
  test/e2e/customconfigs/waitforpodsready_test.go
Labels: lgtm, kind/flake, release-note-none, approved, size/M, cncf-cla: yes

#5317 Extract EvictWorkload to Function
  pkg/controller/tas/node_failure_controller.go
  pkg/controller/tas/node_failure_controller_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5324 Use logger inside cache
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/localqueue_controller_test.go
  pkg/controller/core/workload_controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5326 Use logger inside cache 2.0
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/jobframework/base_webhook_test.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5287 [TAS] Replace failed node in faulty PodSet TopologyAssignment
  pkg/cache/clusterqueue_snapshot.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
  pkg/cache/tas_flavor_snapshot_test.go
  pkg/controller/core/workload_controller.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/webhooks/workload_webhook.go
  pkg/workload/workload.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#5325 Fix assumedUsage calculation in TAS
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor_snapshot.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5276 TAS: account for TAS usage after reboot
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5330 drop workload state from kueueviz as its always unknown
  cmd/kueueviz/frontend/src/LocalQueueDetail.jsx
  cmd/kueueviz/frontend/src/WorkloadDetail.jsx
  cmd/kueueviz/frontend/src/Workloads.jsx
  cmd/kueueviz/frontend/src/WorkloadsList.jsx
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5333 Use logger in cache (cherry-pick to release-0.10)
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/resource_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/admissioncheck_controller.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/resourceflavor_controller.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/jobset/jobset_webhook_test.go
  pkg/controller/jobs/mpijob/mpijob_webhook_test.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: lgtm, release-note-none, size/XL, approved, kind/cleanup, cncf-cla: yes

#5335 TAS: account for TAS usage after reboot (cherry-pick to 0.10)
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/tas/resource_flavor.go
  test/integration/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5334 TAS: account for TAS usage after reboot (cherry-pick to 0.11)
  pkg/cache/cache.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#5309 TAS: refactor the tasCache access and fix initialization issues
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_test.go
  pkg/cache/tas_cache.go
  pkg/cache/tas_cache_test.go
  pkg/cache/tas_flavor.go
  pkg/controller/tas/resource_flavor.go
  pkg/controller/tas/topology_controller.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, kind/cleanup, cncf-cla: yes

#5323 Fix missing namespace selector on webhook manifest
  charts/kueue/templates/webhook/manifests.yaml
  hack/processing-plan.yaml
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#5327 Allow to observe panics during integration tests
  Makefile-test.mk
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, cncf-cla: yes

#5356 Prepare release v0.12.0
  CHANGELOG/CHANGELOG-0.12.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  config/components/manager/kustomization.yaml
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5354 Prepare v0.11.5
  CHANGELOG/CHANGELOG-0.11.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5364 Automated cherry pick of #5362: Update main after v0.11.5
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#5367 Update main after v0.12.0
  CHANGELOG/CHANGELOG-0.12.md
  Makefile
  README.md
  SECURITY-INSIGHTS.yaml
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  site/hugo.toml
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#5372 Add commented exemplary configuration to Kueue manifest
  charts/kueue/values.yaml
  config/components/manager/controller_manager_config.yaml
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5378 Remove CronJob in AfterEach instead of DeferCleanup.
  test/e2e/singlecluster/e2e_test.go
Labels: kind/bug, lgtm, kind/failing-test, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#5380 Revert "Merge the FlowSchema and PriorityLevelConfiguration v1 manifests into the installation manifests (#5043)"
  Makefile
  charts/kueue/README.md
  charts/kueue/templates/visibility-apf/flowschema.yaml
  charts/kueue/templates/visibility-apf/prioritylevelconfigurations.yaml
  charts/kueue/values.yaml
  config/components/visibility-apf/flowschema.yaml
  config/components/visibility-apf/kustomization.yaml
  config/components/visibility-apf/prioritylevelconfigurations.yaml
  config/components/visibility/kustomization.yaml
  config/visibility-apf/kustomization.yaml
  hack/processing-plan.yaml
  site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
  test/e2e/config/default/kustomization.yaml
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#5388 Configure Dependabot to automatically bump the Cypress image tag
  .github/dependabot.yml
  Makefile-test.mk
  hack/cypress/Dockerfile
  hack/e2e-kueueviz-backend.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#5278 Fix restoring of the image in artifacts goal
  Makefile
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5408 Automated cherry pick of #5278: Fix restoring of the image in artifacts goal
  Makefile
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#5412 Add generate-code target.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5422 Modernize and lint-fix
  cmd/importer/util/util.go
  pkg/cache/clusterqueue.go
  pkg/cache/clusterqueue_snapshot.go
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/tas/topology_ungater.go
  pkg/metrics/metrics_test.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/util/heap/heap_test.go
  pkg/util/maps/maps_test.go
  pkg/util/testing/wrappers.go
  pkg/util/testingjobs/node/wrappers.go
  pkg/util/testingjobs/pod/wrappers.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
  test/integration/singlecluster/webhook/core/clusterqueue_test.go
  test/integration/singlecluster/webhook/core/resourceflavor_test.go
  test/performance/scheduler/runner/generator/generator.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#5427 [Cleanup] Reword tas_test comments
  test/integration/singlecluster/tas/tas_test.go
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S
