Repository kubernetes-sigs/kueue, pull requests merged in 2025-09, with the labels that each got.

#6700 [Cleanup] Move FindAdmissionCheck to admissioncheck pkg
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/provisioning/controller.go
  pkg/util/admissioncheck/admissioncheck.go
  pkg/workload/admissionchecks.go
  pkg/workload/admissionchecks_test.go
  test/e2e/multikueue/e2e_test.go
  test/integration/multikueue/dispatcher_test.go
  test/integration/multikueue/enabled_integration_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/no_gc_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
  test/util/util.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6696 Extract iteration over findFlavorForPodSetResource to a helper
  pkg/scheduler/flavorassigner/flavorassigner.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#6631 Drop the QueueVisibility feature
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  pkg/controller/core/clusterqueue_controller.go
  pkg/controller/core/clusterqueue_controller_test.go
  pkg/controller/core/core.go
  pkg/features/kube_features.go
  pkg/features/kube_features_test.go
  site/content/en/docs/installation/_index.md
  site/content/en/docs/reference/components-tools/feature-gate-removed.md
  site/content/en/docs/reference/kueue.v1beta1.md
  site/content/zh-CN/docs/installation/_index.md
  test/integration/singlecluster/controller/core/clusterqueue_controller_test.go
Labels: lgtm, size/XL, release-note-action-required, approved, kind/cleanup, ok-to-test, kind/deprecation, cncf-cla: yes

#6715 fix: parameter passing error
  pkg/controller/jobs/deployment/deployment_webhook.go
  pkg/controller/jobs/statefulset/statefulset_webhook.go
Labels: kind/bug, release-note, lgtm, approved, ok-to-test, size/XS, cncf-cla: yes

#6721 Use RequeueAfter instead of Requeue.
  pkg/controller/jobframework/reconciler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6662 Support in-tree RayAutoscaler for Elastic RayCluster objects
  keps/77-dynamically-sized-jobs/README.md
  pkg/controller/jobs/raycluster/raycluster_webhook.go
  pkg/controller/jobs/raycluster/raycluster_webhook_test.go
  pkg/controller/jobs/rayjob/rayjob_webhook.go
  pkg/util/testingjobs/raycluster/wrappers.go
  site/content/en/docs/concepts/elastic_workload.md
  site/content/en/docs/tasks/run/rayclusters.md
  test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#6725 Use BASE_BUILDER_IMAGE.
  Makefile
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6727 Automated cherry pick of #6722: Bump gotest.tools/gotestsum from v1.12.2 to v1.12.3.
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#6728 Automated cherry pick of #6722: Bump gotest.tools/gotestsum from v1.12.2 to v1.12.3.
  hack/internal/tools/go.mod
  hack/internal/tools/go.sum
Labels: lgtm, release-note-none, approved, size/M, cncf-cla: yes

#6734 (docs): fix minor typos in the documentation
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  site/content/en/docs/installation/_index.md
Labels: lgtm, release-note-none, approved, ok-to-test, cncf-cla: yes, size/S

#6755 Add info logging to config.waitForPodsReady when enable is set to false and rest fields are set
  pkg/config/validation.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#6761 Bump testing-library/cypress.
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#6762 Bump the all group in /cmd/kueueviz/frontend with 3 updates
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6764 Order candidates for FS preemption using less function used to sort workloads
  pkg/scheduler/preemption/common/ordering.go
  pkg/scheduler/preemption/fairsharing/ordering.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6775 Improve base_webhook_test.go ValidateUpdate unit-test coverage.
  pkg/controller/jobframework/base_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6588 Prepare ci_pull.sh.
  .github/ISSUE_TEMPLATE/NEW_RELEASE.md
  hack/releasing/ci_pull.sh
  hack/releasing/common.sh
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6781 Automated cherry pick of #6328: AFS: Increase logging for Admission Fair Sharing
  pkg/cache/snapshot.go
  pkg/controller/core/localqueue_controller.go
  pkg/scheduler/preemption/classical/candidate_generator.go
  pkg/scheduler/preemption/classical/hierarchical_preemption.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_test.go
Labels: lgtm, release-note-none, approved, cncf-cla: yes, size/S

#6782 update FS comment
  pkg/cache/scheduler/fair_sharing.go
Labels: lgtm, release-note-none, approved, size/XS, kind/documentation, cncf-cla: yes

#6401 [Docs][zh]Localize setup_wait_for_pods_ready.md
  site/content/zh-CN/docs/tasks/manage/setup_wait_for_pods_ready.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6822 Rename failedNode to unhealthyNode.
  pkg/controller/tas/node_failure_controller.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/workload/workload.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6828 TAS: don't rely on TAS label for Pod integration
  pkg/controller/jobs/pod/pod_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6827 Interrupt wait_for_images.sh if gcloud is not installed.
  hack/releasing/wait_for_images.sh
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6850 Improve logs in nodeFailureReconciler.
  pkg/controller/tas/node_failure_controller.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6849 [Doc] Add documentation about TAS fast hot swap
  site/content/en/docs/concepts/topology_aware_scheduling.md
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#6858 Automated cherry pick of #6544: Reduce verbosity scheduler unit tests #6815: Follow-up: Refactor assignment-related wrappers
  cmd/importer/pod/import_test.go
  pkg/cache/cache_test.go
  pkg/cache/fair_sharing_test.go
  pkg/cache/snapshot_test.go
  pkg/controller/core/workload_controller_test.go
  pkg/controller/jobs/job/job_controller_test.go
  pkg/controller/jobs/pod/pod_controller_test.go
  pkg/controller/jobs/raycluster/raycluster_controller_test.go
  pkg/controller/tas/node_failure_controller_test.go
  pkg/controller/tas/topology_ungater_test.go
  pkg/queue/manager_test.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler_test.go
  pkg/util/testing/wrappers.go
  pkg/webhooks/workload_webhook_test.go
  pkg/workload/workload_test.go
  test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
  test/integration/singlecluster/controller/core/clusterqueue_controller_test.go
  test/integration/singlecluster/controller/core/localqueue_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/integration/singlecluster/webhook/core/workload_test.go
Labels: lgtm, size/XXL, release-note-none, approved, cncf-cla: yes

#6871 (cleanup): remove redundant type arguments
  pkg/cache/hierarchy/manager_test.go
  pkg/cache/queue/cohort.go
  pkg/cache/queue/manager.go
Labels: lgtm, release-note-none, approved, kind/cleanup, ok-to-test, size/XS, cncf-cla: yes

#6873 Add workload and job UIDs to log
  pkg/scheduler/preemption/preemption.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#5873 Add support for DRA devices in kueue workloads
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/rbac/role.yaml
  cmd/kueue/main.go
  config/components/rbac/role.yaml
  pkg/cache/queue/manager.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/dra/claims.go
  pkg/dra/claims_test.go
  pkg/dra/mapper.go
  pkg/dra/mapper_test.go
  pkg/features/kube_features.go
  pkg/util/testing/wrappers.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/framework/framework.go
  test/integration/singlecluster/controller/dra/dra_test.go
  test/integration/singlecluster/controller/dra/suite_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#6881 Automated cherry pick of #6553 upstream website 1758095044
  site/content/en/docs/admission-check-controllers/_index.md
  site/content/en/docs/concepts/admission.md
  site/content/en/docs/concepts/admission_check/_index.md
  site/content/en/docs/concepts/admission_check/multikueue.md
  site/content/en/docs/concepts/admission_check/provisioning_request.md
Labels: size/L, lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes

#6876 Add workload_priority_class label for kueue_evicted_workloads_once_total metric.
  pkg/metrics/metrics.go
  pkg/workload/workload.go
  site/content/en/docs/reference/metrics.md
  site/content/zh-CN/docs/reference/metrics.md
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/scheduler/podsready/scheduler_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
  test/integration/singlecluster/scheduler/scheduler_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, approved, size/M, cncf-cla: yes

#6872 Refine IsActive logic to ignore Pods stuck terminating in pod-integration pod-groups
  pkg/controller/jobs/pod/pod_controller.go
  pkg/controller/jobs/pod/pod_controller_test.go
Labels: release-note, size/L, lgtm, approved, cncf-cla: yes

#6885 Add workload_priority_class label for kueue_admission_wait_time_seconds metric.
  pkg/metrics/metrics.go
  site/content/en/docs/reference/metrics.md
  site/content/zh-CN/docs/reference/metrics.md
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#6909 increase the wait tieme for the trainer deployment
  hack/e2e-common.sh
Labels: kind/bug, lgtm, release-note-none, approved, size/XS, cncf-cla: yes

#6890 TAS: Graduate Hot Swap feature gates.
  pkg/controller/tas/node_failure_controller_test.go
  pkg/features/kube_features.go
  pkg/scheduler/scheduler_test.go
  site/content/en/docs/concepts/topology_aware_scheduling.md
  site/content/en/docs/installation/_index.md
  test/e2e/config/default/controller_manager_config.yaml
  test/e2e/config/default/values.yaml
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#6887 Add workload_priority_class label for kueue_quota_reserved_wait_time_seconds metric.
  pkg/metrics/metrics.go
  site/content/en/docs/reference/metrics.md
  site/content/zh-CN/docs/reference/metrics.md
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, approved, cncf-cla: yes, size/S

#6918 fix: ensure webhook configurations use the correct resource name
  pkg/util/cert/cert.go
  pkg/util/cert/cert_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#6760 feat(multikueue): Add support for external generic jobs
  apis/config/v1beta1/configuration_types.go
  apis/config/v1beta1/zz_generated.deepcopy.go
  cmd/kueue/main.go
  pkg/controller/jobs/generic/config.go
  pkg/controller/jobs/generic/config_test.go
  pkg/controller/jobs/generic/generic_multikueue_adapter.go
  pkg/controller/jobs/generic/generic_multikueue_adapter_test.go
  pkg/features/kube_features.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  site/content/en/docs/tasks/run/multikueue/external-frameworks.md
  test/integration/multikueue/external_job_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#6921 Cleanup after graduation TAS to beta.
  apis/kueue/v1beta1/localqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  pkg/config/validation_test.go
  pkg/scheduler/scheduler_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/e2e/config/default/controller_manager_config.yaml
  test/e2e/config/default/values.yaml
  test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
  test/integration/singlecluster/controller/jobs/jaxjob/jaxjob_controller_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go
  test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go
  test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
  test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
  test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go
  test/integration/singlecluster/tas/tas_test.go
  test/integration/singlecluster/webhook/jobs/jobset_webhook_test.go
  test/integration/singlecluster/webhook/jobs/paddlejob_webhook_test.go
  test/integration/singlecluster/webhook/jobs/pytorchjob_webhook_test.go
  test/integration/singlecluster/webhook/jobs/tfjob_webhook_test.go
  test/integration/singlecluster/webhook/jobs/xgboostjob_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6927 Automated cherry pick of #6914: [TAS] Fix empty hot swap replacement for slices
  pkg/cache/tas_flavor_snapshot.go
  pkg/scheduler/scheduler_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#6925 [Fair Sharing] Fix Rounding Bug
  pkg/cache/scheduler/cache.go
  pkg/cache/scheduler/clusterqueue_snapshot.go
  pkg/cache/scheduler/cohort_snapshot.go
  pkg/cache/scheduler/fair_sharing.go
  pkg/cache/scheduler/fair_sharing_test.go
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/preemption/fairsharing/least_common_ancestor.go
  pkg/scheduler/preemption/fairsharing/ordering.go
  pkg/scheduler/preemption/fairsharing/strategy.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/scheduler_test.go
  test/e2e/singlecluster/fair_sharing_test.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6906 Implement more flexible limitations on the number of Flavors per ClusterQueue
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  pkg/webhooks/clusterqueue_webhook.go
  pkg/webhooks/clusterqueue_webhook_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/webhook/core/clusterqueue_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: kind/feature, release-note, size/L, lgtm, approved, ok-to-test, cncf-cla: yes

#6961 Cleanup after rename workload_priority_class label to priority_class.
  pkg/metrics/metrics.go
  test/util/util.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#6963 Fix fair sharing flake due to data race after calling AsFloat64Slow
  pkg/cache/scheduler/fair_sharing.go
Labels: kind/bug, lgtm, kind/flake, release-note-none, approved, size/XS, cncf-cla: yes

#6978 [Cleanup] Remove QueueVisibility config validation code
  apis/config/v1beta1/defaults.go
  apis/config/v1beta1/defaults_test.go
  pkg/config/config_test.go
  pkg/config/validation.go
  pkg/config/validation_test.go
  test/integration/singlecluster/kueuectl/suite_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6944 Add priority_class label for optional metrics (if waitForPodsReady is enabled)
  pkg/controller/jobframework/reconciler.go
  pkg/metrics/metrics.go
  site/content/en/docs/reference/metrics.md
  test/e2e/customconfigs/waitforpodsready_test.go
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, size/L, lgtm, approved, cncf-cla: yes

#6976 [Docs][zh]Localize tasks/manage/setup_multikueue
  site/content/zh-CN/docs/tasks/manage/setup_multikueue.md
Labels: lgtm, release-note-none, approved, size/M, ok-to-test, kind/documentation, cncf-cla: yes, area/localization, language/zh

#6990 [release-0.13] import cache as schdcache in ./pkg/scheduler
  pkg/scheduler/fair_sharing_iterator.go
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  pkg/scheduler/flavorassigner/tas_flavorassigner.go
  pkg/scheduler/logging.go
  pkg/scheduler/preemption/classical/candidate_generator.go
  pkg/scheduler/preemption/classical/hierarchical_preemption.go
  pkg/scheduler/preemption/fairsharing/least_common_ancestor.go
  pkg/scheduler/preemption/fairsharing/ordering.go
  pkg/scheduler/preemption/fairsharing/target.go
  pkg/scheduler/preemption/policy.go
  pkg/scheduler/preemption/preemption.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/scheduler/preemption/preemption_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6973 BugFix: scale-up workload stuck pending not triggering preemption.
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#6928 [docs][minor][Admission fair sharing] Update section titles for better English usage
  site/content/en/docs/concepts/admission_fair_sharing.md
Labels: lgtm, release-note-none, approved, ok-to-test, size/XS, kind/documentation, cncf-cla: yes

#6949 fix cases where DRA resources are skipping workload reconcile on their way to scheduler queue
  pkg/cache/queue/manager.go
  pkg/controller/core/core.go
  pkg/controller/core/workload_controller.go
  pkg/controller/core/workload_controller_test.go
  pkg/dra/mapper.go
  pkg/workload/workload.go
  test/integration/singlecluster/controller/dra/dra_test.go
  test/integration/singlecluster/controller/dra/suite_test.go
Labels: kind/bug, size/L, lgtm, release-note-none, approved, cncf-cla: yes

#7009 fix logging for dra code
  pkg/cache/queue/manager.go
  pkg/controller/core/workload_controller.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#7013 [release-0.13] Cherry-pick 🍒 Fix Scale-up workload stuck pending not triggering preemption.
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/flavorassigner/flavorassigner_test.go
  test/integration/singlecluster/scheduler/preemption_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#7018 Remove unnecessary DeepCopy() on evictWorkloadAfterFailedTASReplacement.
  pkg/scheduler/scheduler.go
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#6902 Add priority_class to kueue_local_queue_admission_checks_wait_time_seconds
  pkg/controller/core/workload_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/scheduler/scheduler.go
  site/content/en/docs/reference/metrics.md
  site/content/zh-CN/docs/reference/metrics.md
  test/integration/singlecluster/controller/jobs/job/job_controller_test.go
  test/util/util.go
Labels: kind/feature, release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#7019 Add options to PatchAdmissionStatus().
  cmd/importer/pod/import.go
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/tas/node_failure_controller.go
  pkg/controller/workloaddispatcher/incrementaldispatcher.go
  pkg/scheduler/scheduler.go
  pkg/workload/workload.go
  pkg/workload/workload_test.go
  test/integration/multikueue/dispatcher_test.go
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/scheduler/podsready/scheduler_test.go
  test/integration/singlecluster/webhook/core/workload_test.go
  test/performance/scheduler/runner/controller/controller.go
  test/util/util.go
  test/util/util_scheduling.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#7006 refactor(multikueue): Rewrite external frameworks adapter
  apis/config/v1beta1/configuration_types.go
  cmd/kueue/main.go
  pkg/config/validation.go
  pkg/controller/admissionchecks/multikueue/externalframeworks/adapter.go
  pkg/controller/admissionchecks/multikueue/externalframeworks/adapter_test.go
  pkg/controller/admissionchecks/multikueue/externalframeworks/config.go
  pkg/controller/admissionchecks/multikueue/externalframeworks/config_test.go
  site/content/en/docs/reference/kueue-config.v1beta1.md
  test/integration/multikueue/external_job_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, ok-to-test, cncf-cla: yes

#6995 Optimize performance of controllers by skipping Reconcile if the object didn't change
  cmd/importer/pod/import.go
  pkg/controller/core/workload_controller.go
  pkg/controller/jobframework/reconciler.go
  pkg/scheduler/scheduler.go
  pkg/workload/admissionchecks.go
  pkg/workload/workload.go
  test/integration/multikueue/dispatcher_test.go
  test/integration/singlecluster/controller/core/workload_controller_test.go
  test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
  test/integration/singlecluster/scheduler/podsready/scheduler_test.go
  test/integration/singlecluster/webhook/core/workload_test.go
  test/performance/scheduler/runner/controller/controller.go
  test/util/util.go
  test/util/util_scheduling.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#6899 Add priority_class to kueue_local_queue_admission_wait_time_seconds
  pkg/metrics/metrics.go
  site/content/en/docs/reference/metrics.md
  site/content/zh-CN/docs/reference/metrics.md
  test/integration/singlecluster/controller/core/localqueue_controller_test.go
  test/util/util.go
Labels: release-note, lgtm, approved, ok-to-test, cncf-cla: yes, size/S

#6708 Validate `kueue.x-k8s.io/podset-group-name` annotation value
  pkg/controller/jobframework/tas_validation.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
Labels: kind/feature, lgtm, release-note-action-required, approved, size/M, ok-to-test, cncf-cla: yes

#6898 Add priority_class label for kueue_local_queue_evicted_workloads_total metric.
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/workload/workload.go
  site/content/en/docs/reference/metrics.md
  site/content/zh-CN/docs/reference/metrics.md
  test/integration/singlecluster/scheduler/preemption_test.go
  test/util/util.go
Labels: release-note, lgtm, approved, size/M, ok-to-test, cncf-cla: yes

#6445 Introduce multi-Kueue support for ElasticJobs, with specific support for `batch/v1.Job` workloads when ElasticJob functionality is enabled.
  apis/kueue/v1beta1/workload_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  pkg/controller/admissionchecks/multikueue/workload.go
  pkg/controller/admissionchecks/multikueue/workload_test.go
  pkg/controller/jobframework/reconciler.go
  pkg/controller/jobframework/reconciler_test.go
  pkg/controller/jobframework/validation.go
  pkg/controller/jobframework/validation_test.go
  pkg/controller/jobs/job/job_multikueue_adapter.go
  pkg/controller/jobs/job/job_multikueue_adapter_test.go
  pkg/scheduler/scheduler.go
  pkg/util/testingjobs/job/wrappers.go
  pkg/workload/workload.go
  pkg/workloadslicing/workloadslicing.go
  pkg/workloadslicing/workloadslicing_test.go
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/multikueue/jobs_test.go
Labels: kind/feature, release-note, lgtm, size/XXL, approved, cncf-cla: yes

#7042 [release-0.13] Cherry Pick #7024, #7040
  pkg/scheduler/flavorassigner/flavorassigner.go
  pkg/scheduler/scheduler_test.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, size/L, lgtm, approved, cncf-cla: yes

#7055 Use TrainingRuntimes in integration tests
  pkg/util/testingjobs/trainjob/wrappers.go
  test/integration/singlecluster/controller/jobs/trainjob/trainjob_controller_test.go
  test/util/util.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, cncf-cla: yes

#7056 Bump Kubeflow Trainer to v2.0.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, release-note-none, approved, kind/cleanup, size/XS, cncf-cla: yes

#7017 add kal linter
  .golangci-kal.yml
  Makefile
  Makefile-deps.mk
  apis/kueue/v1beta1/admissioncheck_types.go
  apis/kueue/v1beta1/clusterqueue_types.go
  apis/kueue/v1beta1/cohort_types.go
  apis/kueue/v1beta1/fairsharing_types.go
  apis/kueue/v1beta1/localqueue_types.go
  apis/kueue/v1beta1/multikueue_types.go
  apis/kueue/v1beta1/provisioningrequestconfig_types.go
  apis/kueue/v1beta1/resourceflavor_types.go
  apis/kueue/v1beta1/topology_types.go
  apis/kueue/v1beta1/workload_types.go
  apis/kueue/v1beta1/workloadpriorityclass_types.go
  apis/kueue/v1beta1/zz_generated.deepcopy.go
  charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
  client-go/applyconfiguration/kueue/v1beta1/clusterqueuestatus.go
  client-go/applyconfiguration/kueue/v1beta1/localqueuestatus.go
  client-go/applyconfiguration/kueue/v1beta1/workloadstatus.go
  config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
  config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
  config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
  config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
  config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
  hack/kal-linter/.custom-gcl.yaml
  site/content/en/docs/reference/kueue.v1beta1.md
Labels: lgtm, size/XXL, release-note-none, approved, kind/cleanup, cncf-cla: yes

#7064 Fix limit for ClusterQueue Resources, FlavorReservation and FlavorUsage
  apis/kueue/v1beta1/clusterqueue_types.go
  charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
  charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
  config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
  config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
  site/content/en/docs/reference/kueue.v1beta1.md
  test/integration/singlecluster/webhook/core/clusterqueue_test.go
  test/integration/singlecluster/webhook/core/cohort_test.go
Labels: kind/bug, lgtm, release-note-none, approved, size/M, ok-to-test, cncf-cla: yes

#7039 [TAS] fix typos
  keps/2724-topology-aware-scheduling/README.md
Labels: lgtm, release-note-none, approved, ok-to-test, kind/documentation, cncf-cla: yes, size/S

#7074 Bump sigs.k8s.io/jobset from 0.9.0 to 0.10.1.
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/openapi_generated.go
  vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2/failurepolicyrule.go
  vendor/sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2/jobset.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, cncf-cla: yes

#7070 Cleanup validation of `PodSet` simultaneous grouping and slicing in TAS
  pkg/controller/jobframework/tas_validation.go
  pkg/controller/jobs/job/job_webhook_test.go
  pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
Labels: lgtm, release-note-none, approved, size/M, kind/cleanup, ok-to-test, cncf-cla: yes

#7077 Fix SimulateWorkloadRemoval bug
  pkg/cache/scheduler/clusterqueue_snapshot.go
  pkg/cache/scheduler/snapshot.go
  pkg/scheduler/preemption/preemption_oracle.go
  pkg/scheduler/scheduler.go
  test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M, cncf-cla: yes

#7080 Update the documentation after TAS graduates to beta.
  site/content/en/docs/reference/kueue-alpha.v1alpha1.md
  site/content/zh-CN/docs/reference/kueue-alpha.v1alpha1.md
  site/static/examples/tas/sample-gpu-queues.yaml
  site/static/examples/tas/sample-queues.yaml
Labels: size/L, lgtm, release-note-none, approved, kind/documentation, cncf-cla: yes

#6690 Upgrade Go version to 1.25
  Dockerfile
  cmd/kueueviz/backend/go.mod
  go.mod
  hack/internal/tools/go.mod
  site/go.mod
Labels: lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes, size/S

#7081 Extract Trainjob from the Kubeflow directory
  charts/kueue/templates/webhook/manifests.yaml
  config/components/webhook/manifests.yaml
  pkg/controller/jobs/jobs.go
  pkg/controller/jobs/trainjob/trainjob_controller.go
  pkg/controller/jobs/trainjob/trainjob_controller_test.go
  pkg/controller/jobs/trainjob/trainjob_multikueue_adapter.go
  pkg/controller/jobs/trainjob/trainjob_multikueue_adapter_test.go
  pkg/controller/jobs/trainjob/trainjob_webhook.go
  pkg/controller/jobs/trainjob/trainjob_webhook_test.go
  test/e2e/multikueue/e2e_test.go
  test/e2e/singlecluster/trainjob_test.go
  test/integration/multikueue/jobs_test.go
  test/integration/multikueue/suite_test.go
  test/integration/singlecluster/controller/jobs/trainjob/suite_test.go
  test/integration/singlecluster/controller/jobs/trainjob/trainjob_controller_test.go
  test/integration/singlecluster/webhook/jobs/trainjob_webhook_test.go
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, cncf-cla: yes

#7091 Prepare release v0.14
  CHANGELOG/CHANGELOG-0.14.md
  Makefile
  README.md
  charts/kueue/Chart.yaml
  charts/kueue/README.md
  charts/kueue/README.md.gotmpl
  charts/kueue/values.yaml
  cmd/kueueviz/INSTALL.md
  cmd/kueueviz/frontend/package-lock.json
  cmd/kueueviz/frontend/package.json
  site/hugo.toml
  test/e2e/kueueviz/package-lock.json
  test/e2e/kueueviz/package.json
Labels: size/L, lgtm, release-note-none, approved, kind/cleanup, kind/documentation, cncf-cla: yes

#7090 Update changelog after v0.12.10
  CHANGELOG/CHANGELOG-0.12.md
Labels: lgtm, release-note-none, approved, kind/cleanup, kind/documentation, cncf-cla: yes, size/S
